<br>

> **관련 정보**

- page.title: {{ page.title }}
- page.url: {{ page.url }}
- page.id: {{ page.id }}
- page.name: {{ page.name }}
- page.path: {{ page.path }}

| {% if page.url != "/fn/fn_low_per" %} [저PER](/fn/fn_low_per) {% else %} 저PER {% endif %} | {% if page.url != "/fn/fn_high_per" %} [고PER](/fn/fn_high_per) {% else %} 고PER {% endif %} | {% if page.url != "/fn/fn_low_pbr" %} [저PBR](/fn/fn_low_pbr) {% else %} 저PBR {% endif %} | {% if page.url != "/fn/fn_high_pbr" %} [고PBR](/fn/fn_high_pbr) {% else %} 고PBR {% endif %} | {% if page.url != "/fn/fn_high_divr" %} [고배당](/fn/fn_high_div) {% else %} 고배당 {% endif %} |
| :-: | :-: | :-: | :-: | :-: |
| [![저PER 상위 10%](/fn/images/fn_low_per_table5.png)](/fn/fn_low_per/) | [![고PER 상위 10%](/fn/images/fn_high_per_table5.png)](/fn/fn_high_per/) | [![저PBR 상위 10%](/fn/images/fn_low_pbr_table5.png)](/fn/fn_low_pbr/) | [![고PBR 상위 10%](/fn/images/fn_high_pbr_table5.png)](/fn/fn_high_pbr/) | [![고배당 상위 10%](/fn/images/fn_high_div_table5.png)](/fn/fn_high_div/) | 


| [저PER](/fn/fn_low_per/) | [고PER](/fn/fn_high_per/) | [저PBR](/fn/fn_low_pbr/) | [고PBR](/fn/fn_high_pbr/) | [고배당](/fn/fn_high_div/) |
| :-: | :-: | :-: | :-: | :-: |
| [![저PER 상위 10%](/fn/images/fn_low_per_table5.png)](/fn/fn_low_per/) | [![고PER 상위 10%](/fn/images/fn_high_per_table5.png)](/fn/fn_high_per/) | [![저PBR 상위 10%](/fn/images/fn_low_pbr_table5.png)](/fn/fn_low_pbr/) | [![고PBR 상위 10%](/fn/images/fn_high_pbr_table5.png)](/fn/fn_high_pbr/) | [![고배당 상위 10%](/fn/images/fn_high_div_table5.png)](/fn/fn_high_div/) | 
