<br>

> **관련 정보**

| [저PER](/fn/fn_low_per/) | [고PER](/fn/fn_high_per/) | [저PBR](/fn/fn_low_pbr/) | [고PBR](/fn/fn_high_pbr/) | [고배당](/fn/fn_high_div/) |
| :-: | :-: | :-: | :-: | :-: |
| [![저PER 상위 10%](/fn/images/fn_low_per_table5.png)](/fn/fn_low_per/) | [![고PER 상위 10%](/fn/images/fn_high_per_table5.png)](/fn/fn_high_per/) | [![저PBR 상위 10%](/fn/images/fn_low_pbr_table5.png)](/fn/fn_low_pbr/) | [![고PBR 상위 10%](/fn/images/fn_high_pbr_table5.png)](/fn/fn_high_pbr/) | [![고배당 상위 10%](/fn/images/fn_high_div_table5.png)](/fn/fn_high_div/) | 
