| **종목** | **배율** | **1년** | **<small>변동성비용</small>** | **<small>금융비용</small>** | **<small>전체비용</small>** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| KODEX 200 | 기초 | <span style="color: tomato">12.6<small>%</small></span> | - | - | - |
| [KODEX 2x](/122630/) | 2<small>배</small> | <span style="color: tomato">18.4<small>%</small></span> | 2.4<small>%</small> | 4.2<small>%</small> | 6.5<small>%</small> |
| [TIGER 2xF](/267770/) | 2<small>배</small> | <span style="color: tomato">19.2<small>%</small></span> | 2.4<small>%</small> | 3.6<small>%</small> | 5.9<small>%</small> |
| [KODEX -1x](/114800/) | -1<small>배</small> | <span style="color: cornflowerblue">-8.7<small>%</small></span> | 2.4<small>%</small> | -5.3<small>%</small> | -2.8<small>%</small> |
| [KODEX -2x](/252670/) | -2<small>배</small> | <span style="color: cornflowerblue">-21.5<small>%</small></span> | 7.0<small>%</small> | -7.0<small>%</small> | 0.5<small>%</small> |