| **종목** | **배율** | **1년** | **<small>변동성비용</small>** | **<small>금융비용</small>** | **<small>전체비용</small>** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| KODEX 200 | 기초 | <span style="color: tomato">13.9<small>%</small></span> | - | - | - |
| [KODEX 2x](/122630/) | 2<small>배</small> | <span style="color: tomato">19.7<small>%</small></span> | 2.7<small>%</small> | 5.2<small>%</small> | 7.7<small>%</small> |
| [TIGER 2xF](/267770/) | 2<small>배</small> | <span style="color: tomato">20.4<small>%</small></span> | 2.7<small>%</small> | 4.6<small>%</small> | 7.2<small>%</small> |
| [KODEX -1x](/114800/) | -1<small>배</small> | <span style="color: cornflowerblue">-9.5<small>%</small></span> | 2.7<small>%</small> | -5.9<small>%</small> | -3.1<small>%</small> |
| [KODEX -2x](/252670/) | -2<small>배</small> | <span style="color: cornflowerblue">-23.1<small>%</small></span> | 8.0<small>%</small> | -8.5<small>%</small> | 0.2<small>%</small> |