| **종목** | **배율** | **1년** | **<small>변동성비용</small>** | **<small>금융비용</small>** | **<small>전체비용</small>** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| KODEX 200 | 기초 | <span style="color: tomato">11.3<small>%</small></span> | - | - | - |
| [KODEX 2x](/122630/) | 2<small>배</small> | <span style="color: tomato">14.2<small>%</small></span> | 2.7<small>%</small> | 5.2<small>%</small> | 7.7<small>%</small> |
| [TIGER 2xF](/267770/) | 2<small>배</small> | <span style="color: tomato">14.6<small>%</small></span> | 2.7<small>%</small> | 4.9<small>%</small> | 7.4<small>%</small> |
| [KODEX -1x](/114800/) | -1<small>배</small> | <span style="color: cornflowerblue">-7.5<small>%</small></span> | 2.7<small>%</small> | -5.8<small>%</small> | -2.9<small>%</small> |
| [KODEX -2x](/252670/) | -2<small>배</small> | <span style="color: cornflowerblue">-19.5<small>%</small></span> | 7.9<small>%</small> | -8.3<small>%</small> | 0.3<small>%</small> |