| **종목** | **배율** | **1년** | **<small>변동성비용</small>** | **<small>금융비용</small>** | **<small>전체비용</small>** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| KODEX 150 | 기초 | <span style="color: tomato">2.0<small>%</small></span> | - | - | - |
| [KODEX 150 2x](/233740/) | 2<small>배</small> | <span style="color: cornflowerblue">-5.9<small>%</small></span> | 8.6<small>%</small> | 1.1<small>%</small> | 9.6<small>%</small> |
| [KBSTAR 150 2xF](/278240/) | 2<small>배</small> | <span style="color: cornflowerblue">-1.2<small>%</small></span> | 8.6<small>%</small> | -3.9<small>%</small> | 5.1<small>%</small> |
| [KODEX 150 -1x](/251340/) | -1<small>배</small> | <span style="color: cornflowerblue">-10.1<small>%</small></span> | 9.0<small>%</small> | -0.7<small>%</small> | 8.4<small>%</small> |
| [삼성 150 -2x](/530107/) | -2<small>배</small> | <span style="color: cornflowerblue">-31.9<small>%</small></span> | 25.3<small>%</small> | 5.2<small>%</small> | 29.2<small>%</small> |
| [미래 150 -2x](/520057/) | -2<small>배</small> | <span style="color: cornflowerblue">-31.7<small>%</small></span> | 25.3<small>%</small> | 4.9<small>%</small> | 29.0<small>%</small> |