| **종목** | **배율** | **1년** | **<small>변동성비용</small>** | **<small>금융비용</small>** | **<small>전체비용</small>** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| KODEX 150 | 기초 | <span style="color: tomato">19.6<small>%</small></span> | - | - | - |
| [KODEX 150 2x](/233740/) | 2<small>배</small> | <span style="color: tomato">26.4<small>%</small></span> | 9.0<small>%</small> | 2.9<small>%</small> | 11.6<small>%</small> |
| [KBSTAR 150 2xF](/278240/) | 2<small>배</small> | <span style="color: tomato">28.8<small>%</small></span> | 9.0<small>%</small> | 1.2<small>%</small> | 10.0<small>%</small> |
| [KODEX 150 -1x](/251340/) | -1<small>배</small> | <span style="color: cornflowerblue">-22.3<small>%</small></span> | 9.4<small>%</small> | -2.5<small>%</small> | 7.1<small>%</small> |
| [삼성 150 -2x](/530107/) | -2<small>배</small> | <span style="color: cornflowerblue">-49.5<small>%</small></span> | 26.2<small>%</small> | 2.0<small>%</small> | 27.7<small>%</small> |
| [미래 150 -2x](/520057/) | -2<small>배</small> | <span style="color: cornflowerblue">-49.4<small>%</small></span> | 26.2<small>%</small> | 1.9<small>%</small> | 27.6<small>%</small> |