| **종목** | **배율** | **1년** | **<small>변동성비용</small>** | **<small>금융비용</small>** | **<small>전체비용</small>** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| KODEX 150 | 기초 | <span style="color: tomato">2.2<small>%</small></span> | - | - | - |
| [KODEX 150 2x](/233740/) | 2<small>배</small> | <span style="color: cornflowerblue">-5.5<small>%</small></span> | 8.3<small>%</small> | 1.3<small>%</small> | 9.5<small>%</small> |
| [KBSTAR 150 2xF](/278240/) | 2<small>배</small> | <span style="color: cornflowerblue">-0.6<small>%</small></span> | 8.3<small>%</small> | -3.8<small>%</small> | 4.8<small>%</small> |
| [KODEX 150 -1x](/251340/) | -1<small>배</small> | <span style="color: cornflowerblue">-9.9<small>%</small></span> | 8.7<small>%</small> | -0.8<small>%</small> | 8.0<small>%</small> |
| [삼성 150 -2x](/530107/) | -2<small>배</small> | <span style="color: cornflowerblue">-31.2<small>%</small></span> | 24.5<small>%</small> | 5.0<small>%</small> | 28.3<small>%</small> |
| [미래 150 -2x](/520057/) | -2<small>배</small> | <span style="color: cornflowerblue">-31.0<small>%</small></span> | 24.5<small>%</small> | 4.6<small>%</small> | 28.0<small>%</small> |