| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| KODEX 200 | 기초 | <span style="color: tomato">10.1<small>%</small></span> | - | - | - |
| [KODEX 2x](/122630/) | 2<small>배</small> | <span style="color: tomato">13.2<small>%</small></span> | 2.4<small>%</small> | 4.3<small>%</small> | 6.6<small>%</small> |
| [TIGER 2xF](/267770/) | 2<small>배</small> | <span style="color: tomato">14.0<small>%</small></span> | 2.4<small>%</small> | 3.7<small>%</small> | 6.0<small>%</small> |
| [KODEX -1x](/114800/) | -1<small>배</small> | <span style="color: cornflowerblue">-6.8<small>%</small></span> | 2.4<small>%</small> | -5.2<small>%</small> | -2.7<small>%</small> |
| [KODEX -2x](/252670/) | -2<small>배</small> | <span style="color: cornflowerblue">-17.7<small>%</small></span> | 7.1<small>%</small> | -7.3<small>%</small> | 0.3<small>%</small> |