| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| KODEX USD | 기초 | <span style="color: tomato">9.0<small>%</small></span> | - | - | - |
| [KODEX USD 2x](/261250/) | 2<small>배</small> | <span style="color: tomato">13.8<small>%</small></span> | 0.9<small>%</small> | 3.4<small>%</small> | 4.2<small>%</small> |
| [KODEX USD -1x](/261270/) | -1<small>배</small> | <span style="color: cornflowerblue">-4.5<small>%</small></span> | 0.9<small>%</small> | -5.0<small>%</small> | -4.1<small>%</small> |
| [KODEX USD -2x](/261260/) | -2<small>배</small> | <span style="color: cornflowerblue">-12.3<small>%</small></span> | 2.7<small>%</small> | -7.1<small>%</small> | -4.2<small>%</small> |