| **종목** | **배율** | **1년** | **<small>변동성비용</small>** | **<small>금융비용</small>** | **<small>전체비용</small>** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| KODEX USD | 기초 | <span style="color: tomato">7.8<small>%</small></span> | - | - | - |
| [KODEX USD 2x](/261250/) | 2<small>배</small> | <span style="color: tomato">11.1<small>%</small></span> | 0.8<small>%</small> | 3.6<small>%</small> | 4.4<small>%</small> |
| [KODEX USD -1x](/261270/) | -1<small>배</small> | <span style="color: cornflowerblue">-2.9<small>%</small></span> | 0.8<small>%</small> | -5.4<small>%</small> | -4.6<small>%</small> |
| [KODEX USD -2x](/261260/) | -2<small>배</small> | <span style="color: cornflowerblue">-9.3<small>%</small></span> | 2.2<small>%</small> | -7.7<small>%</small> | -5.3<small>%</small> |