| **종목** | **배율** | **CAGR** | **<small>변동성비용</small>** | **<small>금융비용</small>** | **<small>전체비용</small>** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| KODEX KRX300 | | <span style="color: tomato">9.8<small>%</small></span> | - | - | - |
| [KODEX KRX300레버리지](/306950/) | 2<small>x</small> | <span style="color: tomato">11.5<small>%</small></span> | 4.3<small>%</small> | 3.4<small>%</small> | 7.6<small>%</small> |