| **종목** | **배율** | **CAGR** | **<small>변동성비용</small>** | **<small>금융비용</small>** | **<small>전체비용</small>** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| KODEX 2차전지산업 | | <span style="color: cornflowerblue">-37.3<small>%</small></span> | - | - | - |
| [KODEX 2차전지산업레버리지](/462330/) | 2<small>x</small> | <span style="color: cornflowerblue">-69.3<small>%</small></span> | 17.5<small>%</small> | 5.5<small>%</small> | 22.1<small>%</small> |