| **종목** | **배율** | **CAGR** | **<small>변동성비용</small>** | **<small>금융비용</small>** | **<small>전체비용</small>** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| KODEX 2차전지산업 | | <span style="color: cornflowerblue">-19.8<small>%</small></span><sup><small>11개월</small></sup> | - | - | - |
| [KODEX 2차전지산업레버리지](/462330/) | 2<small>x</small> | <span style="color: cornflowerblue">-50.4<small>%</small></span><sup><small>11개월</small></sup> | 17.2<small>%</small> | 6.8<small>%</small> | 22.8<small>%</small> |