| **종목** | **배율** | **CAGR** | **<small>변동성비용</small>** | **<small>금융비용</small>** | **<small>전체비용</small>** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| TIGER 2차전지TOP10 | | <span style="color: cornflowerblue">-24.2<small>%</small></span> | - | - | - |
| [TIGER 2차전지TOP10레버리지](/412570/) | 2<small>x</small> | <span style="color: cornflowerblue">-56.6<small>%</small></span> | 20.7<small>%</small> | 4.6<small>%</small> | 24.4<small>%</small> |