| **종목** | **배율** | **CAGR** | **<small>변동성비용</small>** | **<small>금융비용</small>** | **<small>전체비용</small>** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| RISE 2차전지TOP10 | | <span style="color: cornflowerblue">-41.3<small>%</small></span><sup><small>10개월</small></sup> | - | - | - |
| [RISE 2차전지TOP10인버스(합성)](/465350/) | -1<small>x</small> | <span style="color: tomato">40.7<small>%</small></span><sup><small>10개월</small></sup> | 23.0<small>%</small> | -8.4<small>%</small> | 16.5<small>%</small> |