| **종목** | **배율** | **CAGR** | **<small>변동성비용</small>** | **<small>금융비용</small>** | **<small>전체비용</small>** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| RISE 2차전지TOP10 | | <span style="color: cornflowerblue">-26.7<small>%</small></span> | - | - | - |
| [RISE 2차전지TOP10인버스(합성)](/465350/) | -1<small>x</small> | <span style="color: tomato">9.7<small>%</small></span> | 23.5<small>%</small> | -5.2<small>%</small> | 19.6<small>%</small> |