| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| KODEX 150 | 기초 | <span style="color: tomato">19.1<small>%</small></span> | - | - | - |
| [KODEX 150 2x](/233740/) | 2<small>배</small> | <span style="color: tomato">25.3<small>%</small></span> | 9.2<small>%</small> | 2.6<small>%</small> | 11.6<small>%</small> |
| [KBSTAR 150 2xF](/278240/) | 2<small>배</small> | <span style="color: tomato">27.2<small>%</small></span> | 9.2<small>%</small> | 1.1<small>%</small> | 10.3<small>%</small> |
| [KODEX 150 -1x](/251340/) | -1<small>배</small> | <span style="color: cornflowerblue">-22.4<small>%</small></span> | 9.7<small>%</small> | -2.3<small>%</small> | 7.6<small>%</small> |
| [삼성 150 -2x](/530107/) | -2<small>배</small> | <span style="color: cornflowerblue">-49.7<small>%</small></span> | 27.0<small>%</small> | 2.4<small>%</small> | 28.7<small>%</small> |
| [미래 150 -2x](/520057/) | -2<small>배</small> | <span style="color: cornflowerblue">-51.1<small>%</small></span> | 26.9<small>%</small> | 2.0<small>%</small> | 28.4<small>%</small> |