| **종목** | **배율** | **1년** | **<small>변동성비용</small>** | **<small>금융비용</small>** | **<small>전체비용</small>** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| AAPL | 기초 | <span style="color: tomato">4.1<small>%</small></span> | - | - | - |
| [AAPU](/aapu/) | 1.5<small>배</small> | <span style="color: cornflowerblue">-2.5<small>%</small></span> | 1.4<small>%</small> | 6.9<small>%</small> | 8.2<small>%</small> |
| [AAP2.L](/aap2/) | 2<small>배</small> | <span style="color: cornflowerblue">-1.8<small>%</small></span> | 3.7<small>%</small> | 7.3<small>%</small> | 10.7<small>%</small> |
| [AAP3.L](/aap3/) | 3<small>배</small> | <span style="color: cornflowerblue">-10.8<small>%</small></span> | 10.7<small>%</small> | 13.5<small>%</small> | 22.7<small>%</small> |
| [AAPD](/aapd/) | -1<small>배</small> | <span style="color: tomato">0.5<small>%</small></span> | 3.6<small>%</small> | -8.5<small>%</small> | -4.6<small>%</small> |
| [AAPS.L](/aaps/) | -3<small>배</small> | <span style="color: cornflowerblue">-21.5<small>%</small></span> | 20.0<small>%</small> | -13.3<small>%</small> | 9.4<small>%</small> |