| **종목** | **배율** | **1년** | **<small>변동성비용</small>** | **<small>금융비용</small>** | **<small>전체비용</small>** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| AAPL | 기초 | <span style="color: tomato">24.5<small>%</small></span> | - | - | - |
| [AAPU](/aapu/) | 1.5<small>배</small> | <span style="color: tomato">28.6<small>%</small></span> | 1.4<small>%</small> | 6.1<small>%</small> | 7.4<small>%</small> |
| [AAP2.L](/aap2/) | 2<small>배</small> | <span style="color: tomato">34.0<small>%</small></span> | 3.7<small>%</small> | 8.7<small>%</small> | 12.1<small>%</small> |
| [AAP3.L](/aap3/) | 3<small>배</small> | <span style="color: tomato">49.5<small>%</small></span> | 10.6<small>%</small> | 13.3<small>%</small> | 22.5<small>%</small> |
| [AAPD](/aapd/) | -1<small>배</small> | <span style="color: cornflowerblue">-16.1<small>%</small></span> | 3.6<small>%</small> | -8.3<small>%</small> | -4.4<small>%</small> |
| [AAPS.L](/aaps/) | -3<small>배</small> | <span style="color: cornflowerblue">-51.1<small>%</small></span> | 20.2<small>%</small> | -15.4<small>%</small> | 7.9<small>%</small> |