| **종목** | **배율** | **CAGR** | **<small>변동성비용</small>** | **<small>금융비용</small>** | **<small>전체비용</small>** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| AAPL | | <span style="color: tomato">26.9<small>%</small></span> | - | - | - |
| [AAP2.L](/aap2/) | 2<small>x</small> | <span style="color: tomato">40.3<small>%</small></span> | 4.7<small>%</small> | 8.7<small>%</small> | 13.0<small>%</small> |
| [AAPU](/aapu/) | 2<small>x</small> | <span style="color: tomato">185.6<small>%</small></span><sup><small>4개월</small></sup> | 2.8<small>%</small> | 4.4<small>%</small> | 7.1<small>%</small> |
| [AAP3.L](/aap3/) | 3<small>x</small> | <span style="color: tomato">50.0<small>%</small></span> | 13.3<small>%</small> | 15.5<small>%</small> | 26.7<small>%</small> |
| [AAPD](/aapd/) | -1<small>x</small> | <span style="color: cornflowerblue">-18.5<small>%</small></span> | 4.7<small>%</small> | -8.6<small>%</small> | -3.5<small>%</small> |
| [AAPS.L](/aaps/) | -3<small>x</small> | <span style="color: cornflowerblue">-58.1<small>%</small></span> | 25.7<small>%</small> | -15.4<small>%</small> | 14.2<small>%</small> |