| **종목** | **배율** | **1년** | **<small>변동성비용</small>** | **<small>금융비용</small>** | **<small>전체비용</small>** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| DIA | 기초 | <span style="color: tomato">16.1<small>%</small></span> | - | - | - |
| [DDM](/ddm/) | 2<small>배</small> | <span style="color: tomato">24.6<small>%</small></span> | 0.9<small>%</small> | 6.6<small>%</small> | 7.4<small>%</small> |
| [UDOW](/udow/) | 3<small>배</small> | <span style="color: tomato">33.9<small>%</small></span> | 2.8<small>%</small> | 11.8<small>%</small> | 14.3<small>%</small> |
| [DOG](/dog/) | -1<small>배</small> | <span style="color: cornflowerblue">-6.3<small>%</small></span> | 0.9<small>%</small> | -9.8<small>%</small> | -8.8<small>%</small> |
| [DXD](/dxd/) | -2<small>배</small> | <span style="color: cornflowerblue">-17.5<small>%</small></span> | 2.8<small>%</small> | -14.3<small>%</small> | -11.1<small>%</small> |
| [SDOW](/sdow/) | -3<small>배</small> | <span style="color: cornflowerblue">-27.0<small>%</small></span> | 5.5<small>%</small> | -20.8<small>%</small> | -14.1<small>%</small> |