| **종목** | **배율** | **1년** | **<small>변동성비용</small>** | **<small>금융비용</small>** | **<small>전체비용</small>** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| DIA | 기초 | <span style="color: tomato">22.7<small>%</small></span> | - | - | - |
| [DDM](/ddm/) | 2<small>배</small> | <span style="color: tomato">39.2<small>%</small></span> | 1.0<small>%</small> | 6.6<small>%</small> | 7.5<small>%</small> |
| [UDOW](/udow/) | 3<small>배</small> | <span style="color: tomato">57.7<small>%</small></span> | 2.9<small>%</small> | 12.0<small>%</small> | 14.6<small>%</small> |
| [DOG](/dog/) | -1<small>배</small> | <span style="color: cornflowerblue">-11.6<small>%</small></span> | 1.0<small>%</small> | -9.6<small>%</small> | -8.5<small>%</small> |
| [DXD](/dxd/) | -2<small>배</small> | <span style="color: cornflowerblue">-26.5<small>%</small></span> | 3.0<small>%</small> | -14.0<small>%</small> | -10.6<small>%</small> |
| [SDOW](/sdow/) | -3<small>배</small> | <span style="color: cornflowerblue">-38.4<small>%</small></span> | 5.9<small>%</small> | -20.8<small>%</small> | -13.7<small>%</small> |