| **종목** | **배율** | **1년** | **<small>변동성비용</small>** | **<small>금융비용</small>** | **<small>전체비용</small>** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| DIA | 기초 | <span style="color: tomato">24.9<small>%</small></span> | - | - | - |
| [DDM](/ddm/) | 2<small>배</small> | <span style="color: tomato">43.5<small>%</small></span> | 1.0<small>%</small> | 7.0<small>%</small> | 8.0<small>%</small> |
| [UDOW](/udow/) | 3<small>배</small> | <span style="color: tomato">65.7<small>%</small></span> | 3.0<small>%</small> | 12.3<small>%</small> | 14.9<small>%</small> |
| [DOG](/dog/) | -1<small>배</small> | <span style="color: cornflowerblue">-14.0<small>%</small></span> | 1.0<small>%</small> | -8.5<small>%</small> | -7.4<small>%</small> |
| [DXD](/dxd/) | -2<small>배</small> | <span style="color: cornflowerblue">-29.6<small>%</small></span> | 3.0<small>%</small> | -13.2<small>%</small> | -9.7<small>%</small> |
| [SDOW](/sdow/) | -3<small>배</small> | <span style="color: cornflowerblue">-42.5<small>%</small></span> | 6.0<small>%</small> | -19.2<small>%</small> | -12.1<small>%</small> |