| **종목** | **배율** | **1년** | **<small>변동성비용</small>** | **<small>금융비용</small>** | **<small>전체비용</small>** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| EWJ | 기초 | <span style="color: tomato">15.3<small>%</small></span> | - | - | - |
| [EZJ](/ezj/) | 2<small>배</small> | <span style="color: tomato">19.6<small>%</small></span> | 2.2<small>%</small> | 8.0<small>%</small> | 10.0<small>%</small> |
| [EWV](/ewv/) | -2<small>배</small> | <span style="color: cornflowerblue">-22.0<small>%</small></span> | 6.5<small>%</small> | -10.9<small>%</small> | -3.7<small>%</small> |