| **종목** | **배율** | **CAGR** | **<small>변동성비용</small>** | **<small>금융비용</small>** | **<small>전체비용</small>** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| EWJ | | <span style="color: tomato">17.6<small>%</small></span> | - | - | - |
| [EZJ](/ezj/) | 2<small>x</small> | <span style="color: tomato">23.7<small>%</small></span> | 3.1<small>%</small> | 7.8<small>%</small> | 10.6<small>%</small> |
| [EWV](/ewv/) | -2<small>x</small> | <span style="color: cornflowerblue">-26.3<small>%</small></span> | 8.9<small>%</small> | -11.9<small>%</small> | -1.9<small>%</small> |