| **종목** | **배율** | **1년** | **<small>변동성비용</small>** | **<small>금융비용</small>** | **<small>전체비용</small>** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| EWJ | 기초 | <span style="color: tomato">13.0<small>%</small></span> | - | - | - |
| [EZJ](/ezj/) | 2<small>배</small> | <span style="color: tomato">15.2<small>%</small></span> | 2.0<small>%</small> | 8.0<small>%</small> | 9.8<small>%</small> |
| [EWV](/ewv/) | -2<small>배</small> | <span style="color: cornflowerblue">-18.4<small>%</small></span> | 5.9<small>%</small> | -10.7<small>%</small> | -4.2<small>%</small> |