| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| EWJ | 기초 | <span style="color: tomato">17.8<small>%</small></span> | - | - | - |
| [EZJ](/ezj/) | 2<small>배</small> | <span style="color: tomato">26.2<small>%</small></span> | 2.1<small>%</small> | 7.0<small>%</small> | 9.0<small>%</small> |
| [EWV](/ewv/) | -2<small>배</small> | <span style="color: cornflowerblue">-25.1<small>%</small></span> | 6.3<small>%</small> | -10.8<small>%</small> | -3.8<small>%</small> |