| **종목** | **배율** | **CAGR** | **<small>변동성비용</small>** | **<small>금융비용</small>** | **<small>전체비용</small>** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| FNGS | | <span style="color: tomato">60.5<small>%</small></span> | - | - | - |
| [FNGO](/fngo/) | 2<small>x</small> | <span style="color: tomato">129.1<small>%</small></span> | 6.0<small>%</small> | 5.4<small>%</small> | 11.1<small>%</small> |
| [FNGG](/fngg/) | 2<small>x</small> | <span style="color: tomato">128.8<small>%</small></span> | 6.0<small>%</small> | 5.5<small>%</small> | 11.2<small>%</small> |
| [FNGU](/fngu/) | 3<small>x</small> | <span style="color: tomato">209.7<small>%</small></span> | 17.1<small>%</small> | 9.7<small>%</small> | 25.1<small>%</small> |
| [FNGZ](/fngz/) | -2<small>x</small> | <span style="color: cornflowerblue">-44.8<small>%</small></span> | 17.1<small>%</small> | 2.8<small>%</small> | 19.4<small>%</small> |
| [FNGD](/fngd/) | -3<small>x</small> | <span style="color: cornflowerblue">-80.4<small>%</small></span> | 31.1<small>%</small> | -17.9<small>%</small> | 18.7<small>%</small> |