| **종목** | **배율** | **CAGR** | **<small>변동성비용</small>** | **<small>금융비용</small>** | **<small>전체비용</small>** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| FNGS | | <span style="color: tomato">42.6<small>%</small></span> | - | - | - |
| [FNGO](/fngo/) | 2<small>x</small> | <span style="color: tomato">79.9<small>%</small></span> | 6.2<small>%</small> | 5.7<small>%</small> | 11.5<small>%</small> |
| [FNGG](/fngg/) | 2<small>x</small> | <span style="color: tomato">80.1<small>%</small></span> | 6.2<small>%</small> | 5.6<small>%</small> | 11.4<small>%</small> |
| [FNGU](/fngu/) | 3<small>x</small> | <span style="color: tomato">114.4<small>%</small></span> | 17.4<small>%</small> | 10.5<small>%</small> | 26.1<small>%</small> |
| [FNGZ](/fngz/) | -2<small>x</small> | <span style="color: cornflowerblue">-44.8<small>%</small></span> | 17.1<small>%</small> | 2.8<small>%</small> | 19.4<small>%</small> |
| [FNGD](/fngd/) | -3<small>x</small> | <span style="color: cornflowerblue">-72.0<small>%</small></span> | 31.5<small>%</small> | -18.4<small>%</small> | 18.9<small>%</small> |