| **종목** | **배율** | **CAGR** | **<small>변동성비용</small>** | **<small>금융비용</small>** | **<small>전체비용</small>** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| FNGS | | <span style="color: tomato">55.6<small>%</small></span> | - | - | - |
| [FNGO](/fngo/) | 2<small>x</small> | <span style="color: tomato">115.4<small>%</small></span> | 6.1<small>%</small> | 5.2<small>%</small> | 11.0<small>%</small> |
| [FNGG](/fngg/) | 2<small>x</small> | <span style="color: tomato">115.7<small>%</small></span> | 6.1<small>%</small> | 5.1<small>%</small> | 10.9<small>%</small> |
| [FNGU](/fngu/) | 3<small>x</small> | <span style="color: tomato">181.6<small>%</small></span> | 17.3<small>%</small> | 9.7<small>%</small> | 25.3<small>%</small> |
| [FNGZ](/fngz/) | -2<small>x</small> | <span style="color: cornflowerblue">-44.8<small>%</small></span> | 17.1<small>%</small> | 2.8<small>%</small> | 19.4<small>%</small> |
| [FNGD](/fngd/) | -3<small>x</small> | <span style="color: cornflowerblue">-78.6<small>%</small></span> | 31.4<small>%</small> | -17.7<small>%</small> | 19.3<small>%</small> |