| **종목** | **배율** | **CAGR** | **<small>변동성비용</small>** | **<small>금융비용</small>** | **<small>전체비용</small>** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| FXI | | <span style="color: tomato">6.6<small>%</small></span> | - | - | - |
| [XPP](/xpp/) | 2<small>x</small> | <span style="color: cornflowerblue">-2.3<small>%</small></span> | 6.0<small>%</small> | 8.6<small>%</small> | 14.0<small>%</small> |
| [YINN](/yinn/) | 3<small>x</small> | <span style="color: cornflowerblue">-11.8<small>%</small></span> | 16.8<small>%</small> | 12.4<small>%</small> | 27.2<small>%</small> |
| [YXI](/yxi/) | -1<small>x</small> | <span style="color: cornflowerblue">-5.3<small>%</small></span> | 6.0<small>%</small> | -7.4<small>%</small> | -1.0<small>%</small> |
| [FXP](/fxp/) | -2<small>x</small> | <span style="color: cornflowerblue">-19.3<small>%</small></span> | 17.1<small>%</small> | -10.6<small>%</small> | 8.3<small>%</small> |
| [YANG](/yang/) | -3<small>x</small> | <span style="color: cornflowerblue">-30.7<small>%</small></span> | 31.4<small>%</small> | -22.5<small>%</small> | 16.0<small>%</small> |