| **종목** | **배율** | **CAGR** | **<small>변동성비용</small>** | **<small>금융비용</small>** | **<small>전체비용</small>** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| FXI | | <span style="color: tomato">20.1<small>%</small></span> | - | - | - |
| [XPP](/xpp/) | 2<small>x</small> | <span style="color: tomato">19.4<small>%</small></span> | 9.2<small>%</small> | 8.8<small>%</small> | 17.2<small>%</small> |
| [YINN](/yinn/) | 3<small>x</small> | <span style="color: tomato">14.3<small>%</small></span> | 25.0<small>%</small> | 12.0<small>%</small> | 34.0<small>%</small> |
| [YXI](/yxi/) | -1<small>x</small> | <span style="color: cornflowerblue">-18.9<small>%</small></span> | 9.3<small>%</small> | -7.4<small>%</small> | 2.6<small>%</small> |
| [FXP](/fxp/) | -2<small>x</small> | <span style="color: cornflowerblue">-42.9<small>%</small></span> | 25.7<small>%</small> | -10.8<small>%</small> | 17.7<small>%</small> |
| [YANG](/yang/) | -3<small>x</small> | <span style="color: cornflowerblue">-61.9<small>%</small></span> | 45.4<small>%</small> | -20.8<small>%</small> | 34.0<small>%</small> |