| **종목** | **배율** | **1년** | **<small>변동성비용</small>** | **<small>금융비용</small>** | **<small>전체비용</small>** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| INDA | 기초 | <span style="color: tomato">29.3<small>%</small></span> | - | - | - |
| [INDL](/indl/) | 2<small>배</small> | <span style="color: tomato">52.8<small>%</small></span> | 1.8<small>%</small> | 6.9<small>%</small> | 8.6<small>%</small> |