| **종목** | **배율** | **1년** | **<small>변동성비용</small>** | **<small>금융비용</small>** | **<small>전체비용</small>** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| IWM | 기초 | <span style="color: tomato">16.8<small>%</small></span> | - | - | - |
| [UWM](/uwm/) | 2<small>배</small> | <span style="color: tomato">23.0<small>%</small></span> | 3.7<small>%</small> | 6.3<small>%</small> | 9.8<small>%</small> |
| [TNA](/tna/) | 3<small>배</small> | <span style="color: tomato">25.8<small>%</small></span> | 10.7<small>%</small> | 11.4<small>%</small> | 20.9<small>%</small> |
| [RWM](/rwm/) | -1<small>배</small> | <span style="color: cornflowerblue">-9.7<small>%</small></span> | 3.8<small>%</small> | -9.5<small>%</small> | -5.4<small>%</small> |
| [TWM](/twm/) | -2<small>배</small> | <span style="color: cornflowerblue">-25.9<small>%</small></span> | 10.9<small>%</small> | -13.4<small>%</small> | -1.0<small>%</small> |
| [TZA](/tza/) | -3<small>배</small> | <span style="color: cornflowerblue">-40.1<small>%</small></span> | 20.8<small>%</small> | -20.4<small>%</small> | 4.6<small>%</small> |