| **종목** | **배율** | **CAGR** | **<small>변동성비용</small>** | **<small>금융비용</small>** | **<small>전체비용</small>** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| IWM | | <span style="color: tomato">14.6<small>%</small></span> | - | - | - |
| [UWM](/uwm/) | 2<small>x</small> | <span style="color: tomato">17.3<small>%</small></span> | 4.4<small>%</small> | 6.5<small>%</small> | 10.6<small>%</small> |
| [TNA](/tna/) | 3<small>x</small> | <span style="color: tomato">15.8<small>%</small></span> | 12.6<small>%</small> | 11.8<small>%</small> | 23.0<small>%</small> |
| [RWM](/rwm/) | -1<small>x</small> | <span style="color: cornflowerblue">-8.5<small>%</small></span> | 4.4<small>%</small> | -9.7<small>%</small> | -4.8<small>%</small> |
| [TWM](/twm/) | -2<small>x</small> | <span style="color: cornflowerblue">-24.1<small>%</small></span> | 12.8<small>%</small> | -14.1<small>%</small> | 0.5<small>%</small> |
| [TZA](/tza/) | -3<small>x</small> | <span style="color: cornflowerblue">-38.6<small>%</small></span> | 24.0<small>%</small> | -21.5<small>%</small> | 7.6<small>%</small> |