| **종목** | **배율** | **CAGR** | **<small>변동성비용</small>** | **<small>금융비용</small>** | **<small>전체비용</small>** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| IWM | | <span style="color: tomato">5.4<small>%</small></span> | - | - | - |
| [UWM](/uwm/) | 2<small>x</small> | <span style="color: cornflowerblue">-0.5<small>%</small></span> | 4.1<small>%</small> | 6.5<small>%</small> | 10.4<small>%</small> |
| [TNA](/tna/) | 3<small>x</small> | <span style="color: cornflowerblue">-9.2<small>%</small></span> | 11.9<small>%</small> | 11.9<small>%</small> | 22.5<small>%</small> |
| [RWM](/rwm/) | -1<small>x</small> | <span style="color: cornflowerblue">-0.2<small>%</small></span> | 4.2<small>%</small> | -9.8<small>%</small> | -5.2<small>%</small> |
| [TWM](/twm/) | -2<small>x</small> | <span style="color: cornflowerblue">-9.6<small>%</small></span> | 12.0<small>%</small> | -14.1<small>%</small> | -0.4<small>%</small> |
| [TZA](/tza/) | -3<small>x</small> | <span style="color: cornflowerblue">-19.7<small>%</small></span> | 22.7<small>%</small> | -21.4<small>%</small> | 6.1<small>%</small> |