| **종목** | **배율** | **CAGR** | **<small>변동성비용</small>** | **<small>금융비용</small>** | **<small>전체비용</small>** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| KWEB | | <span style="color: tomato">43.7<small>%</small></span> | - | - | - |
| [CWEB](/cweb/) | 2<small>x</small> | <span style="color: tomato">70.2<small>%</small></span> | 11.4<small>%</small> | 6.9<small>%</small> | 17.5<small>%</small> |