| **종목** | **배율** | **1년** | **<small>변동성비용</small>** | **<small>금융비용</small>** | **<small>전체비용</small>** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| KWEB | 기초 | <span style="color: tomato">3.5<small>%</small></span> | - | - | - |
| [CWEB](/cweb/) | 2<small>배</small> | <span style="color: cornflowerblue">-10.7<small>%</small></span> | 10.3<small>%</small> | 7.1<small>%</small> | 16.6<small>%</small> |