| **종목** | **배율** | **1년** | **<small>변동성비용</small>** | **<small>금융비용</small>** | **<small>전체비용</small>** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| KWEB | 기초 | <span style="color: cornflowerblue">-11.7<small>%</small></span> | - | - | - |
| [CWEB](/cweb/) | 2<small>배</small> | <span style="color: cornflowerblue">-36.5<small>%</small></span> | 12.3<small>%</small> | 7.2<small>%</small> | 18.6<small>%</small> |