| **종목** | **배율** | **CAGR** | **<small>변동성비용</small>** | **<small>금융비용</small>** | **<small>전체비용</small>** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| MAGS | | <span style="color: tomato">33.6<small>%</small></span><sup><small>6개월</small></sup> | - | - | - |
| [MAGX](/magx/) | 2<small>x</small> | <span style="color: tomato">51.5<small>%</small></span><sup><small>6개월</small></sup> | 3.4<small>%</small> | 4.5<small>%</small> | 7.8<small>%</small> |
| [MAGQ](/magq/) | -1<small>x</small> | -<sup><small>1개월</small></sup> | 1.5<small>%</small> | -2.0<small>%</small> | -0.4<small>%</small> |