| **종목** | **배율** | **CAGR** | **<small>변동성비용</small>** | **<small>금융비용</small>** | **<small>전체비용</small>** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| MAGS | | <span style="color: tomato">16.2<small>%</small></span><sup><small>4개월</small></sup> | - | - | - |
| [MAGX](/magx/) | 2<small>x</small> | <span style="color: tomato">14.5<small>%</small></span><sup><small>4개월</small></sup> | 3.0<small>%</small> | 4.1<small>%</small> | 7.0<small>%</small> |
| [MAGQ](/magq/) | -1<small>x</small> | -<sup><small>1개월</small></sup> | 1.1<small>%</small> | -1.3<small>%</small> | -0.2<small>%</small> |