| **종목** | **배율** | **1년** | **<small>변동성비용</small>** | **<small>금융비용</small>** | **<small>전체비용</small>** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| NVDA | 기초 | <span style="color: tomato">233.1<small>%</small></span> | - | - | - |
| [NVDL](/nvdl/) | 2<small>배</small> | <span style="color: tomato">468.8<small>%</small></span> | 17.2<small>%</small> | 37.9<small>%</small> | 48.6<small>%</small> |
| [NVDD](/nvdd/) | -1<small>배</small> | <span style="color: cornflowerblue">-68.4<small>%</small></span> | 5.0<small>%</small> | -3.6<small>%</small> | 1.6<small>%</small> |
| [NVDS](/nvds/) | -1.25<small>배</small> | <span style="color: cornflowerblue">-96.5<small>%</small></span> | 27.0<small>%</small> | 78.0<small>%</small> | 83.9<small>%</small> |
| [NVD](/nvd/) | -2<small>배</small> | <span style="color: cornflowerblue">-82.5<small>%</small></span> | 15.5<small>%</small> | -22.0<small>%</small> | -3.1<small>%</small> |