| **종목** | **배율** | **1년** | **<small>변동성비용</small>** | **<small>금융비용</small>** | **<small>전체비용</small>** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| NVDA | 기초 | <span style="color: tomato">194.8<small>%</small></span> | - | - | - |
| [NVDL](/nvdl/) | 2<small>배</small> | <span style="color: tomato">1186.4<small>%</small></span> | 17.2<small>%</small> | -78.6<small>%</small> | -47.9<small>%</small> |
| [3LNV.L](/3lnv/) | 3<small>배</small> | <span style="color: tomato">1052.0<small>%</small></span> | 43.0<small>%</small> | 20.9<small>%</small> | 54.9<small>%</small> |
| [NVDD](/nvdd/) | -1<small>배</small> | <span style="color: cornflowerblue">-75.6<small>%</small></span> | 14.4<small>%</small> | -6.4<small>%</small> | 8.9<small>%</small> |
| [NVD](/nvd/) | -2<small>배</small> | <span style="color: cornflowerblue">-93.4<small>%</small></span> | 39.3<small>%</small> | -24.7<small>%</small> | 24.3<small>%</small> |
| [3SNV.L](/3snv/) | -3<small>배</small> | <span style="color: cornflowerblue">-98.7<small>%</small></span> | 72.5<small>%</small> | -25.3<small>%</small> | 65.6<small>%</small> |