| **종목** | **배율** | **CAGR** | **<small>변동성비용</small>** | **<small>금융비용</small>** | **<small>전체비용</small>** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| NVDA | | <span style="color: tomato">121.8<small>%</small></span> | - | - | - |
| [NVDL](/nvdl/) | 2<small>x</small> | <span style="color: tomato">213.0<small>%</small></span> | 21.1<small>%</small> | 19.2<small>%</small> | 36.3<small>%</small> |
| [3LNV.L](/3lnv/) | 3<small>x</small> | <span style="color: tomato">490.2<small>%</small></span> | 50.8<small>%</small> | -10.1<small>%</small> | 45.8<small>%</small> |
| [NVDD](/nvdd/) | -1<small>x</small> | <span style="color: cornflowerblue">-65.2<small>%</small></span><sup><small>10개월</small></sup> | 20.2<small>%</small> | -7.7<small>%</small> | 14.1<small>%</small> |
| [NVD](/nvd/) | -2<small>x</small> | <span style="color: cornflowerblue">-88.2<small>%</small></span> | 51.0<small>%</small> | -28.0<small>%</small> | 37.3<small>%</small> |
| [3SNV.L](/3snv/) | -3<small>x</small> | <span style="color: cornflowerblue">-97.9<small>%</small></span> | 79.8<small>%</small> | -12.4<small>%</small> | 77.2<small>%</small> |