| **종목** | **배율** | **1년** | **<small>변동성비용</small>** | **<small>금융비용</small>** | **<small>전체비용</small>** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| NVDA | 기초 | <span style="color: tomato">230.4<small>%</small></span> | - | - | - |
| [NVDL](/nvdl/) | 2<small>배</small> | <span style="color: tomato">461.0<small>%</small></span> | 17.0<small>%</small> | 38.1<small>%</small> | 48.6<small>%</small> |
| [NVDD](/nvdd/) | -1<small>배</small> | <span style="color: cornflowerblue">-67.8<small>%</small></span> | 5.1<small>%</small> | -3.7<small>%</small> | 1.5<small>%</small> |
| [NVDS](/nvds/) | -1.25<small>배</small> | <span style="color: cornflowerblue">-96.4<small>%</small></span> | 26.6<small>%</small> | 78.0<small>%</small> | 83.8<small>%</small> |
| [NVD](/nvd/) | -2<small>배</small> | <span style="color: cornflowerblue">-82.1<small>%</small></span> | 15.8<small>%</small> | -22.4<small>%</small> | -3.1<small>%</small> |