| **종목** | **배율** | **CAGR** | **<small>변동성비용</small>** | **<small>금융비용</small>** | **<small>전체비용</small>** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| QQQ | | <span style="color: tomato">25.8<small>%</small></span> | - | - | - |
| [QLD](/qld/) | 2<small>x</small> | <span style="color: tomato">43.8<small>%</small></span> | 3.0<small>%</small> | 6.4<small>%</small> | 9.1<small>%</small> |
| [TQQQ](/tqqq/) | 3<small>x</small> | <span style="color: tomato">59.8<small>%</small></span> | 8.6<small>%</small> | 12.1<small>%</small> | 19.7<small>%</small> |
| [QQQ5.L](/qqq5/) | 5<small>x</small> | <span style="color: tomato">56.0<small>%</small></span> | 25.9<small>%</small> | 24.5<small>%</small> | 44.0<small>%</small> |
| [PSQ](/psq/) | -1<small>x</small> | <span style="color: cornflowerblue">-15.5<small>%</small></span> | 3.0<small>%</small> | -9.5<small>%</small> | -6.3<small>%</small> |
| [QID](/qid/) | -2<small>x</small> | <span style="color: cornflowerblue">-34.0<small>%</small></span> | 8.6<small>%</small> | -14.4<small>%</small> | -4.5<small>%</small> |
| [SQQQ](/sqqq/) | -3<small>x</small> | <span style="color: cornflowerblue">-49.1<small>%</small></span> | 16.5<small>%</small> | -21.4<small>%</small> | -1.4<small>%</small> |