| **종목** | **배율** | **1년** | **<small>변동성비용</small>** | **<small>금융비용</small>** | **<small>전체비용</small>** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| QQQ | 기초 | <span style="color: tomato">34.4<small>%</small></span> | - | - | - |
| [QLD](/qld/) | 2<small>배</small> | <span style="color: tomato">64.9<small>%</small></span> | 2.6<small>%</small> | 6.2<small>%</small> | 8.7<small>%</small> |
| [TQQQ](/tqqq/) | 3<small>배</small> | <span style="color: tomato">97.9<small>%</small></span> | 7.6<small>%</small> | 11.8<small>%</small> | 18.5<small>%</small> |
| [QQQ5.L](/qqq5/) | 5<small>배</small> | <span style="color: tomato">164.5<small>%</small></span> | 23.2<small>%</small> | 21.5<small>%</small> | 39.7<small>%</small> |
| [PSQ](/psq/) | -1<small>배</small> | <span style="color: cornflowerblue">-23.8<small>%</small></span> | 2.6<small>%</small> | -5.1<small>%</small> | -2.4<small>%</small> |
| [QID](/qid/) | -2<small>배</small> | <span style="color: cornflowerblue">-43.8<small>%</small></span> | 7.6<small>%</small> | -9.9<small>%</small> | -1.5<small>%</small> |
| [SQQQ](/sqqq/) | -3<small>배</small> | <span style="color: cornflowerblue">-57.7<small>%</small></span> | 14.7<small>%</small> | -20.4<small>%</small> | -2.6<small>%</small> |