| **종목** | **배율** | **CAGR** | **<small>변동성비용</small>** | **<small>금융비용</small>** | **<small>전체비용</small>** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| QQQ | | <span style="color: tomato">37.9<small>%</small></span> | - | - | - |
| [QLD](/qld/) | 2<small>x</small> | <span style="color: tomato">72.4<small>%</small></span> | 3.0<small>%</small> | 6.6<small>%</small> | 9.4<small>%</small> |
| [TQQQ](/tqqq/) | 3<small>x</small> | <span style="color: tomato">110.7<small>%</small></span> | 8.9<small>%</small> | 12.0<small>%</small> | 19.8<small>%</small> |
| [QQQ5.L](/qqq5/) | 5<small>x</small> | <span style="color: tomato">171.6<small>%</small></span> | 26.6<small>%</small> | 26.0<small>%</small> | 45.7<small>%</small> |
| [PSQ](/psq/) | -1<small>x</small> | <span style="color: cornflowerblue">-23.0<small>%</small></span> | 3.0<small>%</small> | -9.6<small>%</small> | -6.3<small>%</small> |
| [QID](/qid/) | -2<small>x</small> | <span style="color: cornflowerblue">-45.0<small>%</small></span> | 8.8<small>%</small> | -14.8<small>%</small> | -4.6<small>%</small> |
| [SQQQ](/sqqq/) | -3<small>x</small> | <span style="color: cornflowerblue">-61.5<small>%</small></span> | 16.9<small>%</small> | -21.6<small>%</small> | -1.0<small>%</small> |