| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| DIA | 기초 | <span style="color: tomato">15.6<small>%</small></span> | - | - | - |
| [DDM](/ddm/) | 2<small>배</small> | <span style="color: tomato">23.4<small>%</small></span> | 1.2<small>%</small> | 6.5<small>%</small> | 7.6<small>%</small> |
| [UDOW](/udow/) | 3<small>배</small> | <span style="color: tomato">31.3<small>%</small></span> | 3.4<small>%</small> | 11.9<small>%</small> | 14.9<small>%</small> |
| [DOG](/dog/) | -1<small>배</small> | <span style="color: cornflowerblue">-6.4<small>%</small></span> | 1.2<small>%</small> | -9.5<small>%</small> | -8.2<small>%</small> |
| [DXD](/dxd/) | -2<small>배</small> | <span style="color: cornflowerblue">-17.7<small>%</small></span> | 3.5<small>%</small> | -13.9<small>%</small> | -9.9<small>%</small> |
| [SDOW](/sdow/) | -3<small>배</small> | <span style="color: cornflowerblue">-27.2<small>%</small></span> | 6.8<small>%</small> | -20.6<small>%</small> | -12.4<small>%</small> |