| **종목** | **배율** | **1년** | **<small>변동성비용</small>** | **<small>금융비용</small>** | **<small>전체비용</small>** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| SOXQ | 기초 | <span style="color: tomato">54.7<small>%</small></span> | - | - | - |
| [SOXL](/soxl/) | 3<small>배</small> | <span style="color: tomato">160.5<small>%</small></span> | 20.2<small>%</small> | 11.8<small>%</small> | 29.6<small>%</small> |
| [SOXS](/soxs/) | -3<small>배</small> | <span style="color: cornflowerblue">-79.7<small>%</small></span> | 37.7<small>%</small> | -20.6<small>%</small> | 24.9<small>%</small> |