| **종목** | **배율** | **1년** | **<small>변동성비용</small>** | **<small>금융비용</small>** | **<small>전체비용</small>** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| SOXQ | 기초 | <span style="color: tomato">56.6<small>%</small></span> | - | - | - |
| [SOXL](/soxl/) | 3<small>배</small> | <span style="color: tomato">172.1<small>%</small></span> | 20.2<small>%</small> | 11.1<small>%</small> | 29.1<small>%</small> |
| [SOXS](/soxs/) | -3<small>배</small> | <span style="color: cornflowerblue">-80.6<small>%</small></span> | 37.7<small>%</small> | -19.5<small>%</small> | 25.5<small>%</small> |