| **종목** | **배율** | **1년** | **<small>변동성비용</small>** | **<small>금융비용</small>** | **<small>전체비용</small>** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| SOXQ | 기초 | <span style="color: tomato">60.2<small>%</small></span> | - | - | - |
| [SOXL](/soxl/) | 3<small>배</small> | <span style="color: tomato">177.9<small>%</small></span> | 21.8<small>%</small> | 13.4<small>%</small> | 32.3<small>%</small> |
| [SOXS](/soxs/) | -3<small>배</small> | <span style="color: cornflowerblue">-82.6<small>%</small></span> | 40.0<small>%</small> | -19.7<small>%</small> | 28.2<small>%</small> |