| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| SOXQ | 기초 | <span style="color: tomato">50.9<small>%</small></span> | - | - | - |
| [SOXL](/soxl/) | 3<small>배</small> | <span style="color: tomato">140.8<small>%</small></span> | 20.0<small>%</small> | 12.2<small>%</small> | 29.8<small>%</small> |
| [SOXS](/soxs/) | -3<small>배</small> | <span style="color: cornflowerblue">-77.6<small>%</small></span> | 37.4<small>%</small> | -23.1<small>%</small> | 22.9<small>%</small> |