| **종목** | **배율** | **CAGR** | **<small>변동성비용</small>** | **<small>금융비용</small>** | **<small>전체비용</small>** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| SPY | | <span style="color: tomato">35.3<small>%</small></span> | - | - | - |
| [SSO](/sso/) | 2<small>x</small> | <span style="color: tomato">68.3<small>%</small></span> | 1.6<small>%</small> | 6.6<small>%</small> | 8.0<small>%</small> |
| [SPXL](/spxl/) | 3<small>x</small> | <span style="color: tomato">107.9<small>%</small></span> | 4.6<small>%</small> | 12.0<small>%</small> | 16.0<small>%</small> |
| [SPYU](/spyu/) | 4<small>x</small> | <span style="color: tomato">117.8<small>%</small></span><sup><small>10개월</small></sup> | 7.7<small>%</small> | 23.9<small>%</small> | 29.8<small>%</small> |
| [SH](/sh/) | -1<small>x</small> | <span style="color: cornflowerblue">-20.0<small>%</small></span> | 1.6<small>%</small> | -10.0<small>%</small> | -8.3<small>%</small> |
| [SDS](/sds/) | -2<small>x</small> | <span style="color: cornflowerblue">-39.7<small>%</small></span> | 4.6<small>%</small> | -15.7<small>%</small> | -10.4<small>%</small> |
| [SPXU](/spxu/) | -3<small>x</small> | <span style="color: cornflowerblue">-55.3<small>%</small></span> | 9.0<small>%</small> | -21.6<small>%</small> | -10.6<small>%</small> |