| **종목** | **배율** | **1년** | **<small>변동성비용</small>** | **<small>금융비용</small>** | **<small>전체비용</small>** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| SPY | 기초 | <span style="color: tomato">24.2<small>%</small></span> | - | - | - |
| [SSO](/sso/) | 2<small>배</small> | <span style="color: tomato">42.1<small>%</small></span> | 1.5<small>%</small> | 6.5<small>%</small> | 7.9<small>%</small> |
| [SPXL](/spxl/) | 3<small>배</small> | <span style="color: tomato">61.8<small>%</small></span> | 4.5<small>%</small> | 11.6<small>%</small> | 15.6<small>%</small> |
| [SH](/sh/) | -1<small>배</small> | <span style="color: cornflowerblue">-13.1<small>%</small></span> | 1.5<small>%</small> | -9.6<small>%</small> | -7.9<small>%</small> |
| [SDS](/sds/) | -2<small>배</small> | <span style="color: cornflowerblue">-28.7<small>%</small></span> | 4.5<small>%</small> | -15.2<small>%</small> | -10.0<small>%</small> |
| [SPXU](/spxu/) | -3<small>배</small> | <span style="color: cornflowerblue">-42.3<small>%</small></span> | 8.9<small>%</small> | -21.3<small>%</small> | -10.5<small>%</small> |