| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| QQQ | 기초 | <span style="color: tomato">44.1<small>%</small></span> | - | - | - |
| [QLD](/qld/) | 2<small>배</small> | <span style="color: tomato">89.4<small>%</small></span> | 2.7<small>%</small> | 6.3<small>%</small> | 8.8<small>%</small> |
| [TQQQ](/tqqq/) | 3<small>배</small> | <span style="color: tomato">143.5<small>%</small></span> | 7.9<small>%</small> | 11.6<small>%</small> | 18.6<small>%</small> |
| [QQQ5.L](/qqq5/) | 5<small>배</small> | <span style="color: tomato">277.0<small>%</small></span> | 24.3<small>%</small> | 19.8<small>%</small> | 39.3<small>%</small> |
| [PSQ](/psq/) | -1<small>배</small> | <span style="color: cornflowerblue">-26.4<small>%</small></span> | 2.7<small>%</small> | -9.0<small>%</small> | -6.0<small>%</small> |
| [QID](/qid/) | -2<small>배</small> | <span style="color: cornflowerblue">-49.8<small>%</small></span> | 8.0<small>%</small> | -13.2<small>%</small> | -4.2<small>%</small> |
| [SQQQ](/sqqq/) | -3<small>배</small> | <span style="color: cornflowerblue">-66.1<small>%</small></span> | 15.4<small>%</small> | -19.9<small>%</small> | -1.4<small>%</small> |