| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| XLK | 기초 | <span style="color: tomato">45.9<small>%</small></span> | - | - | - |
| [ROM](/rom/) | 2<small>배</small> | <span style="color: tomato">97.8<small>%</small></span> | 3.1<small>%</small> | 4.0<small>%</small> | 7.0<small>%</small> |
| [TECL](/tecl/) | 3<small>배</small> | <span style="color: tomato">148.8<small>%</small></span> | 9.1<small>%</small> | 11.8<small>%</small> | 19.8<small>%</small> |
| [REW](/rew/) | -2<small>배</small> | <span style="color: cornflowerblue">-53.7<small>%</small></span> | 9.2<small>%</small> | -8.4<small>%</small> | 1.6<small>%</small> |
| [TECS](/tecs/) | -3<small>배</small> | <span style="color: cornflowerblue">-68.1<small>%</small></span> | 17.6<small>%</small> | -20.2<small>%</small> | 0.9<small>%</small> |