| **종목** | **배율** | **1년** | **<small>변동성비용</small>** | **<small>금융비용</small>** | **<small>전체비용</small>** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| TLT | 기초 | <span style="color: cornflowerblue">-7.1<small>%</small></span> | - | - | - |
| [TMF](/tmf/) | 3<small>배</small> | <span style="color: cornflowerblue">-36.5<small>%</small></span> | 9.3<small>%</small> | 12.7<small>%</small> | 20.9<small>%</small> |
| [TBF](/tbf/) | -1<small>배</small> | <span style="color: tomato">13.4<small>%</small></span> | 3.2<small>%</small> | -8.9<small>%</small> | -5.4<small>%</small> |
| [TBT](/tbt/) | -2<small>배</small> | <span style="color: tomato">20.3<small>%</small></span> | 9.3<small>%</small> | -14.6<small>%</small> | -3.9<small>%</small> |
| [TMV](/tmv/) | -3<small>배</small> | <span style="color: tomato">32.2<small>%</small></span> | 17.8<small>%</small> | -29.1<small>%</small> | -6.1<small>%</small> |