| **종목** | **배율** | **CAGR** | **<small>변동성비용</small>** | **<small>금융비용</small>** | **<small>전체비용</small>** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| TLT | | <span style="color: tomato">0.6<small>%</small></span> | - | - | - |
| [TMF](/tmf/) | 3<small>x</small> | <span style="color: cornflowerblue">-16.7<small>%</small></span> | 8.1<small>%</small> | 11.1<small>%</small> | 18.4<small>%</small> |
| [TBF](/tbf/) | -1<small>x</small> | <span style="color: tomato">5.1<small>%</small></span> | 2.8<small>%</small> | -8.8<small>%</small> | -5.8<small>%</small> |
| [TBT](/tbt/) | -2<small>x</small> | <span style="color: tomato">3.6<small>%</small></span> | 8.1<small>%</small> | -14.2<small>%</small> | -4.9<small>%</small> |
| [TMV](/tmv/) | -3<small>x</small> | <span style="color: tomato">0.3<small>%</small></span> | 15.6<small>%</small> | -21.1<small>%</small> | -2.2<small>%</small> |