| **종목** | **배율** | **1년** | **<small>변동성비용</small>** | **<small>금융비용</small>** | **<small>전체비용</small>** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| TLT | 기초 | <span style="color: cornflowerblue">-11.2<small>%</small></span> | - | - | - |
| [TMF](/tmf/) | 3<small>배</small> | <span style="color: cornflowerblue">-42.5<small>%</small></span> | 8.2<small>%</small> | 10.7<small>%</small> | 18.0<small>%</small> |
| [TBF](/tbf/) | -1<small>배</small> | <span style="color: tomato">19.4<small>%</small></span> | 2.8<small>%</small> | -9.1<small>%</small> | -6.1<small>%</small> |
| [TBT](/tbt/) | -2<small>배</small> | <span style="color: tomato">33.0<small>%</small></span> | 8.2<small>%</small> | -14.3<small>%</small> | -5.0<small>%</small> |
| [TMV](/tmv/) | -3<small>배</small> | <span style="color: tomato">44.8<small>%</small></span> | 15.6<small>%</small> | -20.4<small>%</small> | -1.5<small>%</small> |