| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| TLT | 기초 | <span style="color: cornflowerblue">-6.7<small>%</small></span> | - | - | - |
| [TMF](/tmf/) | 3<small>배</small> | <span style="color: cornflowerblue">-35.6<small>%</small></span> | 9.3<small>%</small> | 12.5<small>%</small> | 20.6<small>%</small> |
| [TBF](/tbf/) | -1<small>배</small> | <span style="color: tomato">13.0<small>%</small></span> | 3.2<small>%</small> | -8.8<small>%</small> | -5.4<small>%</small> |
| [TBT](/tbt/) | -2<small>배</small> | <span style="color: tomato">19.4<small>%</small></span> | 9.3<small>%</small> | -14.6<small>%</small> | -3.9<small>%</small> |
| [TMV](/tmv/) | -3<small>배</small> | <span style="color: tomato">30.6<small>%</small></span> | 17.7<small>%</small> | -28.9<small>%</small> | -6.0<small>%</small> |