| **종목** | **배율** | **CAGR** | **<small>변동성비용</small>** | **<small>금융비용</small>** | **<small>전체비용</small>** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| TSLA | | <span style="color: tomato">19.6<small>%</small></span><sup><small>10개월</small></sup> | - | - | - |
| [TSLT](/tslt/) | 2<small>x</small> | <span style="color: cornflowerblue">-8.7<small>%</small></span><sup><small>10개월</small></sup> | 24.4<small>%</small> | 13.2<small>%</small> | 34.4<small>%</small> |
| [TSLL](/tsll/) | 2<small>x</small> | <span style="color: tomato">204.3<small>%</small></span><sup><small>6개월</small></sup> | 17.2<small>%</small> | 5.7<small>%</small> | 21.9<small>%</small> |
| [TSL3.L](/tsl3/) | 3<small>x</small> | <span style="color: cornflowerblue">-57.4<small>%</small></span> | 60.1<small>%</small> | 16.1<small>%</small> | 66.5<small>%</small> |
| [TSLS](/tsls/) | -1<small>x</small> | <span style="color: cornflowerblue">-25.9<small>%</small></span> | 25.8<small>%</small> | -8.1<small>%</small> | 19.8<small>%</small> |