| **종목** | **배율** | **1년** | **<small>변동성비용</small>** | **<small>금융비용</small>** | **<small>전체비용</small>** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| TSLA | 기초 | <span style="color: cornflowerblue">-2.0<small>%</small></span> | - | - | - |
| [TSLL](/tsll/) | 1.5<small>배</small> | <span style="color: cornflowerblue">-21.1<small>%</small></span> | 9.3<small>%</small> | 10.3<small>%</small> | 18.7<small>%</small> |
| [TSL3.L](/tsl3/) | 3<small>배</small> | <span style="color: cornflowerblue">-64.0<small>%</small></span> | 54.9<small>%</small> | 15.5<small>%</small> | 61.9<small>%</small> |
| [TSLS](/tsls/) | -1<small>배</small> | <span style="color: cornflowerblue">-15.2<small>%</small></span> | 23.3<small>%</small> | -8.3<small>%</small> | 16.9<small>%</small> |