| **종목** | **배율** | **1년** | **<small>변동성비용</small>** | **<small>금융비용</small>** | **<small>전체비용</small>** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| TSLA | 기초 | <span style="color: cornflowerblue">-9.8<small>%</small></span> | - | - | - |
| [TSLL](/tsll/) | 1.5<small>배</small> | <span style="color: cornflowerblue">-27.1<small>%</small></span> | 8.6<small>%</small> | 6.7<small>%</small> | 14.8<small>%</small> |
| [TSLT](/tslt/) | 2<small>배</small> | <span style="color: cornflowerblue">-65.2<small>%</small></span> | 6.2<small>%</small> | 4.1<small>%</small> | 10.0<small>%</small> |
| [TSL3.L](/tsl3/) | 3<small>배</small> | <span style="color: cornflowerblue">-71.9<small>%</small></span> | 52.4<small>%</small> | 19.4<small>%</small> | 61.7<small>%</small> |
| [TSLS](/tsls/) | -1<small>배</small> | <span style="color: cornflowerblue">-5.5<small>%</small></span> | 21.1<small>%</small> | -8.0<small>%</small> | 14.8<small>%</small> |