| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| TSLA | 기초 | <span style="color: cornflowerblue">-3.4<small>%</small></span> | - | - | - |
| [TSLL](/tsll/) | 1.5<small>배</small> | <span style="color: cornflowerblue">-19.2<small>%</small></span> | 8.8<small>%</small> | 6.8<small>%</small> | 14.9<small>%</small> |
| [TSLT](/tslt/) | 2<small>배</small> | <span style="color: cornflowerblue">-66.4<small>%</small></span> | 6.1<small>%</small> | 4.1<small>%</small> | 9.9<small>%</small> |
| [TSL3.L](/tsl3/) | 3<small>배</small> | <span style="color: cornflowerblue">-62.1<small>%</small></span> | 52.7<small>%</small> | 10.9<small>%</small> | 57.9<small>%</small> |
| [TSLS](/tsls/) | -1<small>배</small> | <span style="color: cornflowerblue">-12.3<small>%</small></span> | 21.4<small>%</small> | -8.0<small>%</small> | 15.2<small>%</small> |