| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| IWM | 기초 | <span style="color: tomato">7.0<small>%</small></span> | - | - | - |
| [TNA](/tna/) | 3<small>배</small> | <span style="color: cornflowerblue">-3.6<small>%</small></span> | 11.1<small>%</small> | 11.3<small>%</small> | 21.2<small>%</small> |
| [TZA](/tza/) | -3<small>배</small> | <span style="color: cornflowerblue">-22.8<small>%</small></span> | 21.4<small>%</small> | -20.2<small>%</small> | 5.5<small>%</small> |