| **종목** | **배율** | **CAGR** | **<small>변동성비용</small>** | **<small>금융비용</small>** | **<small>전체비용</small>** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| VIXY | | <span style="color: cornflowerblue">-39.6<small>%</small></span> | - | - | - |
| [UVXY](/uvxy/) | 1.5<small>x</small> | <span style="color: cornflowerblue">-62.1<small>%</small></span> | 17.9<small>%</small> | 1.9<small>%</small> | 19.4<small>%</small> |
| [UVIX](/uvix/) | 2<small>x</small> | <span style="color: cornflowerblue">-82.2<small>%</small></span> | 40.6<small>%</small> | 17.9<small>%</small> | 51.2<small>%</small> |
| [SVXY](/svxy/) | -0.5<small>x</small> | <span style="color: tomato">8.2<small>%</small></span> | 20.0<small>%</small> | -5.1<small>%</small> | 15.9<small>%</small> |
| [SVIX](/svix/) | -1<small>x</small> | <span style="color: cornflowerblue">-15.7<small>%</small></span> | 47.1<small>%</small> | 3.8<small>%</small> | 49.1<small>%</small> |