| **종목** | **배율** | **CAGR** | **<small>변동성비용</small>** | **<small>금융비용</small>** | **<small>전체비용</small>** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| VIXY | | <span style="color: cornflowerblue">-50.5<small>%</small></span> | - | - | - |
| [UVXY](/uvxy/) | 1.5<small>x</small> | <span style="color: cornflowerblue">-71.7<small>%</small></span> | 17.0<small>%</small> | 2.0<small>%</small> | 18.6<small>%</small> |
| [UVIX](/uvix/) | 2<small>x</small> | <span style="color: cornflowerblue">-87.8<small>%</small></span> | 38.8<small>%</small> | 18.2<small>%</small> | 50.0<small>%</small> |
| [SVXY](/svxy/) | -0.5<small>x</small> | <span style="color: tomato">20.8<small>%</small></span> | 19.1<small>%</small> | -5.1<small>%</small> | 15.0<small>%</small> |
| [SVIX](/svix/) | -1<small>x</small> | <span style="color: tomato">6.0<small>%</small></span> | 45.5<small>%</small> | 3.8<small>%</small> | 47.5<small>%</small> |