| **종목** | **배율** | **CAGR** | **<small>변동성비용</small>** | **<small>금융비용</small>** | **<small>전체비용</small>** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| VIXY | | <span style="color: cornflowerblue">-39.1<small>%</small></span> | - | - | - |
| [UVXY](/uvxy/) | 1.5<small>x</small> | <span style="color: cornflowerblue">-61.6<small>%</small></span> | 17.8<small>%</small> | 1.7<small>%</small> | 19.2<small>%</small> |
| [UVIX](/uvix/) | 2<small>x</small> | <span style="color: cornflowerblue">-82.0<small>%</small></span> | 40.5<small>%</small> | 18.4<small>%</small> | 51.5<small>%</small> |
| [SVXY](/svxy/) | -0.5<small>x</small> | <span style="color: tomato">7.6<small>%</small></span> | 19.9<small>%</small> | -5.0<small>%</small> | 16.0<small>%</small> |
| [SVIX](/svix/) | -1<small>x</small> | <span style="color: cornflowerblue">-16.3<small>%</small></span> | 47.0<small>%</small> | 3.5<small>%</small> | 48.9<small>%</small> |