| **종목** | **배율** | **1년** | **<small>변동성비용</small>** | **<small>금융비용</small>** | **<small>전체비용</small>** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| XBI | 기초 | <span style="color: tomato">4.0<small>%</small></span> | - | - | - |
| [LABU](/labu/) | 3<small>배</small> | <span style="color: cornflowerblue">-21.4<small>%</small></span> | 20.6<small>%</small> | 12.1<small>%</small> | 30.2<small>%</small> |
| [LABD](/labd/) | -3<small>배</small> | <span style="color: cornflowerblue">-34.9<small>%</small></span> | 37.5<small>%</small> | -17.1<small>%</small> | 26.8<small>%</small> |