| **종목** | **배율** | **CAGR** | **<small>변동성비용</small>** | **<small>금융비용</small>** | **<small>전체비용</small>** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| XBI | | <span style="color: tomato">37.6<small>%</small></span> | - | - | - |
| [LABU](/labu/) | 3<small>x</small> | <span style="color: tomato">77.7<small>%</small></span> | 21.4<small>%</small> | 13.2<small>%</small> | 31.7<small>%</small> |
| [LABD](/labd/) | -3<small>x</small> | <span style="color: cornflowerblue">-72.4<small>%</small></span> | 38.8<small>%</small> | -17.4<small>%</small> | 28.2<small>%</small> |