| **종목** | **배율** | **1년** | **<small>변동성비용</small>** | **<small>금융비용</small>** | **<small>전체비용</small>** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| XBI | 기초 | <span style="color: tomato">22.6<small>%</small></span> | - | - | - |
| [LABU](/labu/) | 3<small>배</small> | <span style="color: tomato">27.2<small>%</small></span> | 21.9<small>%</small> | 11.5<small>%</small> | 30.9<small>%</small> |
| [LABD](/labd/) | -3<small>배</small> | <span style="color: cornflowerblue">-62.0<small>%</small></span> | 39.9<small>%</small> | -16.5<small>%</small> | 29.9<small>%</small> |