| **종목** | **배율** | **1년** | **<small>변동성비용</small>** | **<small>금융비용</small>** | **<small>전체비용</small>** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| XLK | 기초 | <span style="color: tomato">32.8<small>%</small></span> | - | - | - |
| [ROM](/rom/) | 2<small>배</small> | <span style="color: tomato">58.8<small>%</small></span> | 3.1<small>%</small> | 7.0<small>%</small> | 10.0<small>%</small> |
| [TECL](/tecl/) | 3<small>배</small> | <span style="color: tomato">86.9<small>%</small></span> | 9.1<small>%</small> | 12.2<small>%</small> | 20.2<small>%</small> |
| [REW](/rew/) | -2<small>배</small> | <span style="color: cornflowerblue">-43.2<small>%</small></span> | 9.2<small>%</small> | -10.4<small>%</small> | -0.2<small>%</small> |
| [TECS](/tecs/) | -3<small>배</small> | <span style="color: cornflowerblue">-57.4<small>%</small></span> | 17.7<small>%</small> | -21.2<small>%</small> | 0.2<small>%</small> |