| **종목** | **배율** | **1년** | **<small>변동성비용</small>** | **<small>금융비용</small>** | **<small>전체비용</small>** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| XLK | 기초 | <span style="color: tomato">33.1<small>%</small></span> | - | - | - |
| [ROM](/rom/) | 2<small>배</small> | <span style="color: tomato">60.1<small>%</small></span> | 3.0<small>%</small> | 6.8<small>%</small> | 9.6<small>%</small> |
| [TECL](/tecl/) | 3<small>배</small> | <span style="color: tomato">88.9<small>%</small></span> | 8.8<small>%</small> | 12.2<small>%</small> | 19.9<small>%</small> |
| [REW](/rew/) | -2<small>배</small> | <span style="color: cornflowerblue">-42.1<small>%</small></span> | 8.8<small>%</small> | -12.4<small>%</small> | -2.5<small>%</small> |
| [TECS](/tecs/) | -3<small>배</small> | <span style="color: cornflowerblue">-57.2<small>%</small></span> | 16.9<small>%</small> | -21.5<small>%</small> | -1.0<small>%</small> |