| **종목** | **배율** | **1년** | **<small>변동성비용</small>** | **<small>금융비용</small>** | **<small>전체비용</small>** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| XLK | 기초 | <span style="color: tomato">34.3<small>%</small></span> | - | - | - |
| [ROM](/rom/) | 2<small>배</small> | <span style="color: tomato">62.5<small>%</small></span> | 3.1<small>%</small> | 7.0<small>%</small> | 9.9<small>%</small> |
| [TECL](/tecl/) | 3<small>배</small> | <span style="color: tomato">94.1<small>%</small></span> | 9.0<small>%</small> | 11.9<small>%</small> | 19.9<small>%</small> |
| [REW](/rew/) | -2<small>배</small> | <span style="color: cornflowerblue">-44.7<small>%</small></span> | 9.1<small>%</small> | -9.7<small>%</small> | 0.4<small>%</small> |
| [TECS](/tecs/) | -3<small>배</small> | <span style="color: cornflowerblue">-58.8<small>%</small></span> | 17.5<small>%</small> | -21.0<small>%</small> | 0.1<small>%</small> |