| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| FXI | 기초 | <span style="color: cornflowerblue">-23.6<small>%</small></span> | - | - | - |
| [XPP](/xpp/) | 2<small>배</small> | <span style="color: cornflowerblue">-50.5<small>%</small></span> | 7.5<small>%</small> | 8.3<small>%</small> | 15.2<small>%</small> |
| [YINN](/yinn/) | 3<small>배</small> | <span style="color: cornflowerblue">-69.1<small>%</small></span> | 20.9<small>%</small> | 12.3<small>%</small> | 30.6<small>%</small> |
| [YXI](/yxi/) | -1<small>배</small> | <span style="color: tomato">29.3<small>%</small></span> | 7.6<small>%</small> | -6.9<small>%</small> | 1.2<small>%</small> |
| [FXP](/fxp/) | -2<small>배</small> | <span style="color: tomato">48.6<small>%</small></span> | 21.1<small>%</small> | -10.0<small>%</small> | 13.2<small>%</small> |
| [YANG](/yang/) | -3<small>배</small> | <span style="color: tomato">67.9<small>%</small></span> | 38.0<small>%</small> | -20.8<small>%</small> | 25.0<small>%</small> |