> **KOSPI**<a id="KOSPI"></a>

| 전체 업종 | 전체 종목 |
| :---: | :---: |
| [![KOSPI 전체 업종별 시가총액 비중](images/kospi_all_all_업종.png)](kospi_all_all_업종/) | [![KOSPI 전체 종목별 시가총액 비중](images/kospi_all_all_종목.png)](kospi_all_all_종목/) |
| 전기전자 <small>(41.2%)</small> | 기타금융 <small>(10.0%)</small> |
| [![KOSPI 전기전자 업종 종목별 시가총액 비중](images/kospi_업종_전기전자_종목.png)](kospi_업종_전기전자_종목/) | [![KOSPI 기타금융 업종 종목별 시가총액 비중](images/kospi_업종_기타금융_종목.png)](kospi_업종_기타금융_종목/) |
| 운수장비 <small>(9.6%)</small> | 서비스업 <small>(7.0%)</small> |
| [![KOSPI 운수장비 업종 종목별 시가총액 비중](images/kospi_업종_운수장비_종목.png)](kospi_업종_운수장비_종목/) | [![KOSPI 서비스업 업종 종목별 시가총액 비중](images/kospi_업종_서비스업_종목.png)](kospi_업종_서비스업_종목/) |
| 화학 <small>(6.7%)</small> | 의약품 <small>(5.3%)</small> |
| [![KOSPI 화학 업종 종목별 시가총액 비중](images/kospi_업종_화학_종목.png)](kospi_업종_화학_종목/) | [![KOSPI 의약품 업종 종목별 시가총액 비중](images/kospi_업종_의약품_종목.png)](kospi_업종_의약품_종목/) |
| 유통업 <small>(3.1%)</small> | 철강금속 <small>(2.7%)</small> |
| [![KOSPI 유통업 업종 종목별 시가총액 비중](images/kospi_업종_유통업_종목.png)](kospi_업종_유통업_종목/) | [![KOSPI 철강금속 업종 종목별 시가총액 비중](images/kospi_업종_철강금속_종목.png)](kospi_업종_철강금속_종목/) |
| 기계 <small>(2.7%)</small> | 보험 <small>(2.4%)</small> |
| [![KOSPI 기계 업종 종목별 시가총액 비중](images/kospi_업종_기계_종목.png)](kospi_업종_기계_종목/) | [![KOSPI 보험 업종 종목별 시가총액 비중](images/kospi_업종_보험_종목.png)](kospi_업종_보험_종목/) |
| 운수창고업 <small>(1.8%)</small> | 음식료품 <small>(1.4%)</small> |
| [![KOSPI 운수창고업 업종 종목별 시가총액 비중](images/kospi_업종_운수창고업_종목.png)](kospi_업종_운수창고업_종목/) | [![KOSPI 음식료품 업종 종목별 시가총액 비중](images/kospi_업종_음식료품_종목.png)](kospi_업종_음식료품_종목/) |
| 통신업 <small>(1.1%)</small> | 증권 <small>(1.0%)</small> |
| [![KOSPI 통신업 업종 종목별 시가총액 비중](images/kospi_업종_통신업_종목.png)](kospi_업종_통신업_종목/) | [![KOSPI 증권 업종 종목별 시가총액 비중](images/kospi_업종_증권_종목.png)](kospi_업종_증권_종목/) |
| 은행 <small>(0.9%)</small> | 전기가스업 <small>(0.9%)</small> |
| [![KOSPI 은행 업종 종목별 시가총액 비중](images/kospi_업종_은행_종목.png)](kospi_업종_은행_종목/) | [![KOSPI 전기가스업 업종 종목별 시가총액 비중](images/kospi_업종_전기가스업_종목.png)](kospi_업종_전기가스업_종목/) |
| 건설업 <small>(0.6%)</small> | 기타제조업 <small>(0.6%)</small> |
| [![KOSPI 건설업 업종 종목별 시가총액 비중](images/kospi_업종_건설업_종목.png)](kospi_업종_건설업_종목/) | [![KOSPI 기타제조업 업종 종목별 시가총액 비중](images/kospi_업종_기타제조업_종목.png)](kospi_업종_기타제조업_종목/) |
| 비금속광물 <small>(0.4%)</small> | 섬유의복 <small>(0.3%)</small> |
| [![KOSPI 비금속광물 업종 종목별 시가총액 비중](images/kospi_업종_비금속광물_종목.png)](kospi_업종_비금속광물_종목/) | [![KOSPI 섬유의복 업종 종목별 시가총액 비중](images/kospi_업종_섬유의복_종목.png)](kospi_업종_섬유의복_종목/) |
| 의료정밀 <small>(0.2%)</small> | 종이목재 <small>(0.1%)</small> |
| [![KOSPI 의료정밀 업종 종목별 시가총액 비중](images/kospi_업종_의료정밀_종목.png)](kospi_업종_의료정밀_종목/) | [![KOSPI 종이목재 업종 종목별 시가총액 비중](images/kospi_업종_종이목재_종목.png)](kospi_업종_종이목재_종목/) |
| 농업임업및어업 <small>(0.0%)</small> |  |
| [![KOSPI 농업임업및어업 업종 종목별 시가총액 비중](images/kospi_업종_농업임업및어업_종목.png)](kospi_업종_농업임업및어업_종목/) |  |


> **KOSDAQ**<a id="KOSDAQ"></a>

| 전체 업종 | 전체 종목 |
| :---: | :---: |
| [![KOSDAQ 전체 업종별 시가총액 비중](images/kosdaq_all_all_업종.png)](kosdaq_all_all_업종/) | [![KOSDAQ 전체 종목별 시가총액 비중](images/kosdaq_all_all_종목.png)](kosdaq_all_all_종목/) |
| 반도체 <small>(14.6%)</small> | 제약 <small>(13.0%)</small> |
| [![KOSDAQ 반도체 업종 종목별 시가총액 비중](images/kosdaq_업종_반도체_종목.png)](kosdaq_업종_반도체_종목/) | [![KOSDAQ 제약 업종 종목별 시가총액 비중](images/kosdaq_업종_제약_종목.png)](kosdaq_업종_제약_종목/) |
| 기타서비스 <small>(9.9%)</small> | 일반전기전자 <small>(8.5%)</small> |
| [![KOSDAQ 기타서비스 업종 종목별 시가총액 비중](images/kosdaq_업종_기타서비스_종목.png)](kosdaq_업종_기타서비스_종목/) | [![KOSDAQ 일반전기전자 업종 종목별 시가총액 비중](images/kosdaq_업종_일반전기전자_종목.png)](kosdaq_업종_일반전기전자_종목/) |
| 화학 <small>(6.9%)</small> | 기계장비 <small>(6.4%)</small> |
| [![KOSDAQ 화학 업종 종목별 시가총액 비중](images/kosdaq_업종_화학_종목.png)](kosdaq_업종_화학_종목/) | [![KOSDAQ 기계장비 업종 종목별 시가총액 비중](images/kosdaq_업종_기계장비_종목.png)](kosdaq_업종_기계장비_종목/) |
| IT부품 <small>(5.0%)</small> | 금융 <small>(4.9%)</small> |
| [![KOSDAQ IT부품 업종 종목별 시가총액 비중](images/kosdaq_업종_IT부품_종목.png)](kosdaq_업종_IT부품_종목/) | [![KOSDAQ 금융 업종 종목별 시가총액 비중](images/kosdaq_업종_금융_종목.png)](kosdaq_업종_금융_종목/) |
| 소프트웨어 <small>(4.5%)</small> | 의료정밀기기 <small>(4.3%)</small> |
| [![KOSDAQ 소프트웨어 업종 종목별 시가총액 비중](images/kosdaq_업종_소프트웨어_종목.png)](kosdaq_업종_소프트웨어_종목/) | [![KOSDAQ 의료정밀기기 업종 종목별 시가총액 비중](images/kosdaq_업종_의료정밀기기_종목.png)](kosdaq_업종_의료정밀기기_종목/) |
| 디지털컨텐츠 <small>(3.4%)</small> | 유통 <small>(3.2%)</small> |
| [![KOSDAQ 디지털컨텐츠 업종 종목별 시가총액 비중](images/kosdaq_업종_디지털컨텐츠_종목.png)](kosdaq_업종_디지털컨텐츠_종목/) | [![KOSDAQ 유통 업종 종목별 시가총액 비중](images/kosdaq_업종_유통_종목.png)](kosdaq_업종_유통_종목/) |
| 오락문화 <small>(2.0%)</small> | 금속 <small>(2.0%)</small> |
| [![KOSDAQ 오락문화 업종 종목별 시가총액 비중](images/kosdaq_업종_오락문화_종목.png)](kosdaq_업종_오락문화_종목/) | [![KOSDAQ 금속 업종 종목별 시가총액 비중](images/kosdaq_업종_금속_종목.png)](kosdaq_업종_금속_종목/) |
| 운송장비부품 <small>(1.9%)</small> | 통신장비 <small>(1.8%)</small> |
| [![KOSDAQ 운송장비부품 업종 종목별 시가총액 비중](images/kosdaq_업종_운송장비부품_종목.png)](kosdaq_업종_운송장비부품_종목/) | [![KOSDAQ 통신장비 업종 종목별 시가총액 비중](images/kosdaq_업종_통신장비_종목.png)](kosdaq_업종_통신장비_종목/) |
| 음식료담배 <small>(1.2%)</small> | 건설 <small>(0.8%)</small> |
| [![KOSDAQ 음식료담배 업종 종목별 시가총액 비중](images/kosdaq_업종_음식료담배_종목.png)](kosdaq_업종_음식료담배_종목/) | [![KOSDAQ 건설 업종 종목별 시가총액 비중](images/kosdaq_업종_건설_종목.png)](kosdaq_업종_건설_종목/) |
| 인터넷 <small>(0.8%)</small> | 방송서비스 <small>(0.7%)</small> |
| [![KOSDAQ 인터넷 업종 종목별 시가총액 비중](images/kosdaq_업종_인터넷_종목.png)](kosdaq_업종_인터넷_종목/) | [![KOSDAQ 방송서비스 업종 종목별 시가총액 비중](images/kosdaq_업종_방송서비스_종목.png)](kosdaq_업종_방송서비스_종목/) |
| 비금속 <small>(0.6%)</small> | 종이목재 <small>(0.5%)</small> |
| [![KOSDAQ 비금속 업종 종목별 시가총액 비중](images/kosdaq_업종_비금속_종목.png)](kosdaq_업종_비금속_종목/) | [![KOSDAQ 종이목재 업종 종목별 시가총액 비중](images/kosdaq_업종_종이목재_종목.png)](kosdaq_업종_종이목재_종목/) |
| 정보기기 <small>(0.5%)</small> | 출판매체복제 <small>(0.5%)</small> |
| [![KOSDAQ 정보기기 업종 종목별 시가총액 비중](images/kosdaq_업종_정보기기_종목.png)](kosdaq_업종_정보기기_종목/) | [![KOSDAQ 출판매체복제 업종 종목별 시가총액 비중](images/kosdaq_업종_출판매체복제_종목.png)](kosdaq_업종_출판매체복제_종목/) |
| 섬유의류 <small>(0.5%)</small> | 컴퓨터서비스 <small>(0.4%)</small> |
| [![KOSDAQ 섬유의류 업종 종목별 시가총액 비중](images/kosdaq_업종_섬유의류_종목.png)](kosdaq_업종_섬유의류_종목/) | [![KOSDAQ 컴퓨터서비스 업종 종목별 시가총액 비중](images/kosdaq_업종_컴퓨터서비스_종목.png)](kosdaq_업종_컴퓨터서비스_종목/) |
| 기타제조 <small>(0.3%)</small> | 통신서비스 <small>(0.3%)</small> |
| [![KOSDAQ 기타제조 업종 종목별 시가총액 비중](images/kosdaq_업종_기타제조_종목.png)](kosdaq_업종_기타제조_종목/) | [![KOSDAQ 통신서비스 업종 종목별 시가총액 비중](images/kosdaq_업종_통신서비스_종목.png)](kosdaq_업종_통신서비스_종목/) |
| 숙박음식 <small>(0.2%)</small> | 전기가스수도 <small>(0.1%)</small> |
| [![KOSDAQ 숙박음식 업종 종목별 시가총액 비중](images/kosdaq_업종_숙박음식_종목.png)](kosdaq_업종_숙박음식_종목/) | [![KOSDAQ 전기가스수도 업종 종목별 시가총액 비중](images/kosdaq_업종_전기가스수도_종목.png)](kosdaq_업종_전기가스수도_종목/) |
| 운송 <small>(0.1%)</small> | 농업임업및어업 <small>(0.0%)</small> |
| [![KOSDAQ 운송 업종 종목별 시가총액 비중](images/kosdaq_업종_운송_종목.png)](kosdaq_업종_운송_종목/) | [![KOSDAQ 농업임업및어업 업종 종목별 시가총액 비중](images/kosdaq_업종_농업임업및어업_종목.png)](kosdaq_업종_농업임업및어업_종목/) |