<span style="color:tomato">붉은색</span>으로 표시된 수치는 저PER, 저PBR, 고배당에도 해당[^fn_finance_metric]되는 경우입니다. <span style="color:cornflowerblue">푸른색</span>으로 표시된 수치는 고PER, 고PBR에도 해당되는 경우입니다.

| **종목** | **업종**[^fn_sector_abbr] | **PER** | **PBR** | **DIV** |
| :--- | :--- | --: | --: | --: |
| [레인보우로보틱스](/277810/) | Q:기계장비 | <span style="color:cornflowerblue">481.7</span> | **46.8** | - |
| [금양](/001570/) | P:화학 | - | **42.0** | - |
| [메지온](/140410/) | Q:기타서비스 | - | **37.3** | - |
| [알테오젠](/196170/) | Q:기타서비스 | - | **36.3** | - |
| [에코프로머티](/450080/) | P:전기전자 | <span style="color:cornflowerblue">662.9</span> | **35.9** | - |
| [루닛](/328130/) | Q:소프트웨어 | - | **24.8** | - |
| [HPSP](/403870/) | Q:반도체 | 63.8 | **24.0** | 0.3<small>%</small> |
| [SK바이오팜](/326030/) | P:서비스업 | - | **22.5** | - |
| [보로노이](/310210/) | Q:제약 | - | **18.4** | - |
| [엔켐](/348370/) | Q:화학 | <span style="color:cornflowerblue">225.5</span> | **17.9** | - |
| [에코프로비엠](/247540/) | Q:일반전기전자 | <span style="color:cornflowerblue">86.6</span> | **17.9** | 0.2<small>%</small> |
| [박셀바이오](/323990/) | Q:기타서비스 | - | **16.6** | - |
| [레이크머티리얼즈](/281740/) | Q:화학 | 51.3 | **16.1** | - |
| [HLB](/028300/) | Q:제약 | - | **15.5** | - |
| [현대바이오](/048410/) | Q:화학 | - | **14.8** | - |
| [에이비엘바이오](/298380/) | Q:제약 | <span style="color:cornflowerblue">317.2</span> | **14.6** | - |
| [원텍](/336570/) | Q:의료정밀기기 | 55.5 | **13.5** | - |
| [엠로](/058970/) | Q:소프트웨어 | <span style="color:cornflowerblue">104.5</span> | **13.4** | - |
| [강원에너지](/114190/) | Q:금속 | <span style="color:cornflowerblue">124.2</span> | **13.3** | - |
| [에코프로](/086520/) | Q:금융 | <span style="color:cornflowerblue">416.5</span> | **11.7** | 0.1<small>%</small> |
| [셀트리온제약](/068760/) | Q:제약 | <span style="color:cornflowerblue">160.0</span> | **11.7** | - |
| [제이오](/418550/) | Q:기타서비스 | - | **11.4** | - |
| [한올바이오파마](/009420/) | P:의약품 | <span style="color:cornflowerblue">7260.0</span> | **10.9** | - |
| [에코프로에이치엔](/383310/) | Q:화학 | 28.9 | **10.8** | 1.0<small>%</small> |
| [파크시스템스](/140860/) | Q:의료정밀기기 | 43.6 | **10.2** | 0.2<small>%</small> |
| [TCC스틸](/002710/) | P:철강금속 | 63.4 | **9.7** | 0.1<small>%</small> |
| [대주전자재료](/078600/) | Q:IT부품 | <span style="color:cornflowerblue">1155.2</span> | **9.6** | 0.1<small>%</small> |
| [포스코퓨처엠](/003670/) | P:전기전자 | <span style="color:cornflowerblue">200.1</span> | **9.6** | 0.1<small>%</small> |
| [포스코엠텍](/009520/) | Q:금속 | <span style="color:cornflowerblue">217.7</span> | **9.2** | 0.1<small>%</small> |
| [클래시스](/214150/) | Q:의료정밀기기 | 27.3 | **8.9** | 0.4<small>%</small> |
| [삼천당제약](/000250/) | Q:제약 | <span style="color:cornflowerblue">261.5</span> | **8.8** | - |
| [삼아알미늄](/006110/) | P:철강금속 | <span style="color:cornflowerblue">68.1</span> | **8.5** | 0.2<small>%</small> |
| [JYP Ent.](/035900/) | Q:오락문화 | 37.7 | **8.5** | 0.5<small>%</small> |
| [셀바스AI](/108860/) | Q:소프트웨어 | <span style="color:cornflowerblue">67.8</span> | **8.3** | - |
| [하나투어](/039130/) | P:서비스업 | - | **8.0** | - |