<span style="color:tomato">붉은색</span>으로 표시된 수치는 저PER, 저PBR, 고배당에도 해당[^fn_finance_metric]되는 경우입니다. <span style="color:cornflowerblue">푸른색</span>으로 표시된 수치는 고PER, 고PBR에도 해당되는 경우입니다.

| **종목** | **업종**[^fn_sector_abbr] | **PER** | **PBR** | **DIV** |
| :--- | :--- | --: | --: | --: |
| [한올바이오파마](/009420/) | P:의약품 | **7160.0** | <span style="color:cornflowerblue">10.8</span> | - |
| [대주전자재료](/078600/) | Q:IT부품 | **1349.2** | <span style="color:cornflowerblue">11.2</span> | 0.1<small>%</small> |
| [서진시스템](/178320/) | Q:통신장비 | **579.1** | 1.7 | - |
| [레인보우로보틱스](/277810/) | Q:기계장비 | **503.1** | <span style="color:cornflowerblue">48.9</span> | - |
| [두산퓨얼셀](/336260/) | P:전기전자 | **436.2** | 2.6 | - |
| [삼천당제약](/000250/) | Q:제약 | **435.9** | <span style="color:cornflowerblue">14.7</span> | - |
| [하나마이크론](/067310/) | Q:반도체 | **433.3** | 5.2 | 0.2<small>%</small> |
| [에코프로](/086520/) | Q:금융 | **426.3** | <span style="color:cornflowerblue">12.0</span> | 0.1<small>%</small> |
| [에코프로머티](/450080/) | P:전기전자 | **420.1** | <span style="color:cornflowerblue">22.8</span> | - |
| [에이비엘바이오](/298380/) | Q:제약 | **378.4** | <span style="color:cornflowerblue">17.4</span> | - |
| [하나기술](/299030/) | Q:기계장비 | **280.8** | 5.8 | - |
| [포스코엠텍](/009520/) | Q:금속 | **191.4** | <span style="color:cornflowerblue">8.1</span> | 0.2<small>%</small> |
| [포스코퓨처엠](/003670/) | P:전기전자 | **187.9** | <span style="color:cornflowerblue">9.0</span> | 0.1<small>%</small> |
| [엔켐](/348370/) | Q:화학 | **185.3** | <span style="color:cornflowerblue">14.7</span> | - |
| [하이브](/352820/) | P:서비스업 | **175.9** | 3.3 | - |
| [셀트리온제약](/068760/) | Q:제약 | **160.2** | <span style="color:cornflowerblue">11.7</span> | - |
| [한온시스템](/018880/) | P:기계 | **156.8** | 1.4 | <span style="color:tomato">6.0<small>%</small></span> |
| [RFHIC](/218410/) | Q:일반전기전자 | **152.7** | 1.6 | 0.6<small>%</small> |
| [강원에너지](/114190/) | Q:금속 | **149.6** | <span style="color:cornflowerblue">16.0</span> | - |
| [한전기술](/052690/) | P:서비스업 | **138.3** | 4.6 | 0.4<small>%</small> |
| [넥슨게임즈](/225570/) | Q:디지털컨텐츠 | **128.9** | 3.8 | - |
| [일진하이솔루스](/271940/) | P:운수장비 | **126.5** | 2.8 | - |
| [효성티앤씨](/298020/) | P:화학 | **123.6** | 1.2 | 3.0<small>%</small> |
| [LG에너지솔루션](/373220/) | P:전기전자 | **118.9** | 4.9 | - |
| [코스모화학](/005420/) | P:화학 | **117.0** | 6.4 | - |
| [엘앤씨바이오](/290650/) | Q:제약 | **113.5** | 5.3 | 0.2<small>%</small> |
| [엠로](/058970/) | Q:소프트웨어 | **111.1** | <span style="color:cornflowerblue">14.2</span> | - |
| [카카오페이](/377300/) | P:기타금융 | **93.5** | 2.8 | - |
| [에코프로비엠](/247540/) | Q:일반전기전자 | **90.8** | <span style="color:cornflowerblue">18.7</span> | 0.2<small>%</small> |
| [에스티팜](/237690/) | Q:제약 | **84.8** | 4.5 | 0.6<small>%</small> |
| [효성](/004800/) | P:기타금융 | **75.3** | 0.5 | <span style="color:tomato">7.6<small>%</small></span> |
| [롯데케미칼](/011170/) | P:화학 | **71.8** | <span style="color:tomato">0.3</span> | 2.8<small>%</small> |
| [삼성바이오로직스](/207940/) | P:의약품 | **71.3** | 6.5 | - |
| [나노신소재](/121600/) | Q:화학 | **71.0** | 6.8 | 0.2<small>%</small> |
| [코스맥스](/192820/) | P:화학 | **69.6** | 2.5 | - |