<span style="color:tomato">붉은색</span>으로 표시된 수치는 저PER, 저PBR, 고배당에도 해당[^fn_finance_metric]되는 경우입니다. <span style="color:cornflowerblue">푸른색</span>으로 표시된 수치는 고PER, 고PBR에도 해당되는 경우입니다.

| **종목** | **업종**[^fn_sector_abbr] | **PER** | **PBR** | **DIV** |
| :--- | :--- | --: | --: | --: |
| [한올바이오파마](/009420/) | P:의약품 | **6420.0** | <span style="color:cornflowerblue">9.7</span> | - |
| [대주전자재료](/078600/) | Q:IT부품 | **1329.8** | <span style="color:cornflowerblue">11.1</span> | 0.1<small>%</small> |
| [서진시스템](/178320/) | Q:통신장비 | **539.5** | 1.6 | - |
| [레인보우로보틱스](/277810/) | Q:기계장비 | **476.1** | <span style="color:cornflowerblue">46.3</span> | - |
| [하나마이크론](/067310/) | Q:반도체 | **411.4** | 4.9 | 0.2<small>%</small> |
| [두산퓨얼셀](/336260/) | P:전기전자 | **401.1** | 2.4 | - |
| [삼천당제약](/000250/) | Q:제약 | **387.6** | <span style="color:cornflowerblue">13.0</span> | - |
| [에코프로머티](/450080/) | P:전기전자 | **368.4** | <span style="color:cornflowerblue">19.9</span> | - |
| [에코프로](/086520/) | Q:금융 | **361.3** | <span style="color:cornflowerblue">10.2</span> | 0.1<small>%</small> |
| [에이비엘바이오](/298380/) | Q:제약 | **335.1** | <span style="color:cornflowerblue">15.4</span> | - |
| [하나기술](/299030/) | Q:기계장비 | **244.7** | 5.1 | - |
| [엔켐](/348370/) | Q:화학 | **211.1** | <span style="color:cornflowerblue">16.7</span> | - |
| [하이브](/352820/) | P:서비스업 | **182.2** | 3.4 | - |
| [포스코엠텍](/009520/) | Q:금속 | **172.8** | 7.3 | 0.2<small>%</small> |
| [포스코퓨처엠](/003670/) | P:전기전자 | **166.0** | <span style="color:cornflowerblue">7.9</span> | 0.1<small>%</small> |
| [셀트리온제약](/068760/) | Q:제약 | **142.8** | <span style="color:cornflowerblue">10.4</span> | - |
| [RFHIC](/218410/) | Q:일반전기전자 | **141.7** | 1.4 | 0.7<small>%</small> |
| [효성티앤씨](/298020/) | P:화학 | **128.8** | 1.2 | 2.9<small>%</small> |
| [한온시스템](/018880/) | P:기계 | **128.4** | 1.2 | <span style="color:tomato">7.4<small>%</small></span> |
| [강원에너지](/114190/) | Q:금속 | **119.2** | <span style="color:cornflowerblue">12.7</span> | - |
| [넥슨게임즈](/225570/) | Q:디지털컨텐츠 | **118.8** | 3.5 | - |
| [한전기술](/052690/) | P:서비스업 | **116.1** | 3.8 | 0.5<small>%</small> |
| [LG에너지솔루션](/373220/) | P:전기전자 | **111.0** | 4.6 | - |
| [일진하이솔루스](/271940/) | P:운수장비 | **109.8** | 2.5 | - |
| [엠로](/058970/) | Q:소프트웨어 | **105.0** | <span style="color:cornflowerblue">13.4</span> | - |
| [엘앤씨바이오](/290650/) | Q:제약 | **102.5** | 4.8 | 0.2<small>%</small> |
| [코스모화학](/005420/) | P:화학 | **92.1** | 5.0 | - |
| [에스티팜](/237690/) | Q:제약 | **85.9** | 4.6 | 0.6<small>%</small> |
| [카카오페이](/377300/) | P:기타금융 | **81.6** | 2.4 | - |
| [에코프로비엠](/247540/) | Q:일반전기전자 | **79.0** | <span style="color:cornflowerblue">16.3</span> | 0.2<small>%</small> |
| [대한전선](/001440/) | P:전기전자 | **77.7** | 2.0 | - |
| [아모레퍼시픽](/090430/) | P:화학 | **73.3** | 1.7 | 0.5<small>%</small> |
| [원텍](/336570/) | Q:의료정밀기기 | **73.2** | <span style="color:cornflowerblue">17.8</span> | - |
| [코스맥스](/192820/) | P:화학 | **73.2** | 2.6 | - |
| [효성](/004800/) | P:기타금융 | **72.5** | 0.4 | <span style="color:tomato">7.9<small>%</small></span> |