<span style="color:tomato">붉은색</span>으로 표시된 수치는 저PER, 저PBR, 고배당에도 해당[^fn_finance_metric]되는 경우입니다. <span style="color:cornflowerblue">푸른색</span>으로 표시된 수치는 고PER, 고PBR에도 해당되는 경우입니다.

| **종목** | **업종**[^fn_sector_abbr] | **PER** | **PBR** | **DIV** |
| :--- | :--- | --: | --: | --: |
| [한올바이오파마](/009420/) | P:의약품 | **7520.0** | <span style="color:cornflowerblue">11.3</span> | - |
| [대주전자재료](/078600/) | Q:IT부품 | **1392.5** | <span style="color:cornflowerblue">11.6</span> | 0.1<small>%</small> |
| [서진시스템](/178320/) | Q:통신장비 | **537.2** | 1.6 | - |
| [레인보우로보틱스](/277810/) | Q:기계장비 | **534.0** | <span style="color:cornflowerblue">51.9</span> | - |
| [에코프로머티](/450080/) | P:전기전자 | **517.4** | <span style="color:cornflowerblue">28.0</span> | - |
| [에코프로](/086520/) | Q:금융 | **427.0** | <span style="color:cornflowerblue">12.0</span> | 0.1<small>%</small> |
| [두산퓨얼셀](/336260/) | P:전기전자 | **415.1** | 2.4 | - |
| [하나마이크론](/067310/) | Q:반도체 | **406.8** | 4.9 | 0.2<small>%</small> |
| [에이비엘바이오](/298380/) | Q:제약 | **386.6** | <span style="color:cornflowerblue">17.8</span> | - |
| [삼천당제약](/000250/) | Q:제약 | **332.1** | <span style="color:cornflowerblue">11.2</span> | - |
| [하나기술](/299030/) | Q:기계장비 | **298.6** | 6.2 | - |
| [포스코퓨처엠](/003670/) | P:전기전자 | **210.5** | <span style="color:cornflowerblue">10.1</span> | 0.1<small>%</small> |
| [포스코엠텍](/009520/) | Q:금속 | **207.3** | <span style="color:cornflowerblue">8.7</span> | 0.1<small>%</small> |
| [셀트리온제약](/068760/) | Q:제약 | **177.7** | <span style="color:cornflowerblue">12.9</span> | - |
| [엔켐](/348370/) | Q:화학 | **161.7** | <span style="color:cornflowerblue">12.8</span> | - |
| [강원에너지](/114190/) | Q:금속 | **156.8** | <span style="color:cornflowerblue">16.7</span> | - |
| [하이브](/352820/) | P:서비스업 | **152.3** | 2.9 | - |
| [한온시스템](/018880/) | P:기계 | **147.1** | 1.3 | <span style="color:tomato">6.4<small>%</small></span> |
| [한전기술](/052690/) | P:서비스업 | **141.9** | 4.7 | 0.4<small>%</small> |
| [RFHIC](/218410/) | Q:일반전기전자 | **141.9** | 1.4 | 0.7<small>%</small> |
| [넥슨게임즈](/225570/) | Q:디지털컨텐츠 | **125.8** | 3.7 | - |
| [일진하이솔루스](/271940/) | P:운수장비 | **122.4** | 2.7 | - |
| [LG에너지솔루션](/373220/) | P:전기전자 | **121.9** | 5.0 | - |
| [코스모화학](/005420/) | P:화학 | **115.8** | 6.3 | - |
| [엘앤씨바이오](/290650/) | Q:제약 | **114.2** | 5.3 | 0.2<small>%</small> |
| [효성티앤씨](/298020/) | P:화학 | **107.2** | 1.0 | 3.5<small>%</small> |
| [엠로](/058970/) | Q:소프트웨어 | **100.5** | <span style="color:cornflowerblue">12.9</span> | - |
| [카카오페이](/377300/) | P:기타금융 | **94.6** | 2.8 | - |
| [에코프로비엠](/247540/) | Q:일반전기전자 | **94.2** | <span style="color:cornflowerblue">19.4</span> | 0.2<small>%</small> |
| [에스티팜](/237690/) | Q:제약 | **93.1** | 5.0 | 0.6<small>%</small> |
| [나노신소재](/121600/) | Q:화학 | **80.3** | 7.8 | 0.2<small>%</small> |
| [씨아이에스](/222080/) | Q:기계장비 | **75.3** | 6.4 | - |
| [삼성바이오로직스](/207940/) | P:의약품 | **74.1** | 6.7 | - |
| [커넥트웨이브](/119860/) | Q:인터넷 | **73.1** | 1.1 | - |
| [효성](/004800/) | P:기타금융 | **72.9** | 0.5 | <span style="color:tomato">7.8<small>%</small></span> |