<span style="color:tomato">붉은색</span>으로 표시된 수치는 저PER, 저PBR, 고배당에도 해당[^fn_finance_metric]되는 경우입니다. <span style="color:cornflowerblue">푸른색</span>으로 표시된 수치는 고PER, 고PBR에도 해당되는 경우입니다.

| **종목** | **업종**[^fn_sector_abbr] | **PER** | **PBR** | **DIV** |
| :--- | :--- | --: | --: | --: |
| [레인보우로보틱스](/277810/) | Q:기계장비 | <span style="color:cornflowerblue">490.7</span> | **47.7** | - |
| [금양](/001570/) | P:화학 | - | **38.4** | - |
| [에코프로머티](/450080/) | P:전기전자 | <span style="color:cornflowerblue">680.3</span> | **36.9** | - |
| [메지온](/140410/) | Q:기타서비스 | - | **35.5** | - |
| [알테오젠](/196170/) | Q:기타서비스 | - | **30.1** | - |
| [HPSP](/403870/) | Q:반도체 | <span style="color:cornflowerblue">68.1</span> | **25.6** | 0.2<small>%</small> |
| [루닛](/328130/) | Q:소프트웨어 | - | **21.4** | - |
| [SK바이오팜](/326030/) | P:서비스업 | - | **21.3** | - |
| [에코프로비엠](/247540/) | Q:일반전기전자 | <span style="color:cornflowerblue">84.5</span> | **17.4** | 0.2<small>%</small> |
| [박셀바이오](/323990/) | Q:기타서비스 | - | **16.1** | - |
| [보로노이](/310210/) | Q:제약 | - | **16.1** | - |
| [엔켐](/348370/) | Q:화학 | <span style="color:cornflowerblue">194.2</span> | **15.4** | - |
| [현대바이오](/048410/) | Q:화학 | - | **14.6** | - |
| [레이크머티리얼즈](/281740/) | Q:화학 | 45.3 | **14.2** | - |
| [에이비엘바이오](/298380/) | Q:제약 | <span style="color:cornflowerblue">305.2</span> | **14.1** | - |
| [HLB](/028300/) | Q:제약 | - | **14.0** | - |
| [엠로](/058970/) | Q:소프트웨어 | <span style="color:cornflowerblue">104.2</span> | **13.3** | - |
| [원텍](/336570/) | Q:의료정밀기기 | 53.2 | **12.9** | - |
| [에코프로](/086520/) | Q:금융 | <span style="color:cornflowerblue">434.7</span> | **12.2** | 0.1<small>%</small> |
| [셀트리온제약](/068760/) | Q:제약 | <span style="color:cornflowerblue">166.4</span> | **12.1** | - |
| [강원에너지](/114190/) | Q:금속 | <span style="color:cornflowerblue">106.4</span> | **11.4** | - |
| [에코프로에이치엔](/383310/) | Q:화학 | 29.1 | **10.8** | 1.0<small>%</small> |
| [한올바이오파마](/009420/) | P:의약품 | <span style="color:cornflowerblue">6990.0</span> | **10.5** | - |
| [파크시스템스](/140860/) | Q:의료정밀기기 | 44.1 | **10.3** | 0.2<small>%</small> |
| [제이오](/418550/) | Q:기타서비스 | - | **9.3** | - |
| [포스코퓨처엠](/003670/) | P:전기전자 | <span style="color:cornflowerblue">187.0</span> | **8.9** | 0.1<small>%</small> |
| [포스코엠텍](/009520/) | Q:금속 | <span style="color:cornflowerblue">211.6</span> | **8.9** | 0.1<small>%</small> |
| [삼천당제약](/000250/) | Q:제약 | <span style="color:cornflowerblue">264.9</span> | **8.9** | - |
| [대주전자재료](/078600/) | Q:IT부품 | <span style="color:cornflowerblue">1052.2</span> | **8.8** | 0.1<small>%</small> |
| [JYP Ent.](/035900/) | Q:오락문화 | 37.8 | **8.5** | 0.5<small>%</small> |
| [클래시스](/214150/) | Q:의료정밀기기 | 25.8 | **8.4** | 0.4<small>%</small> |
| [네이처셀](/007390/) | Q:제약 | - | **8.2** | - |
| [셀바스AI](/108860/) | Q:소프트웨어 | <span style="color:cornflowerblue">66.0</span> | **8.1** | - |
| [하나투어](/039130/) | P:서비스업 | - | **7.8** | - |
| [제이시스메디칼](/287410/) | Q:의료정밀기기 | 21.9 | **7.5** | - |