<span style="color:tomato">붉은색</span>으로 표시된 수치는 저PER, 저PBR, 고배당에도 해당[^fn_finance_metric]되는 경우입니다. <span style="color:cornflowerblue">푸른색</span>으로 표시된 수치는 고PER, 고PBR에도 해당되는 경우입니다.

| **종목** | **업종**[^fn_sector_abbr] | **PER** | **PBR** | **DIV** |
| :--- | :--- | --: | --: | --: |
| [하나투어](/039130/) | P:서비스업 | 15.9 | 4.4 | **10.4**<small>%</small> |
| [현대엘리베이](/017800/) | P:기계 | <span style="color:tomato">5.1</span> | 1.2 | **9.2**<small>%</small> |
| [한샘](/009240/) | P:유통업 | - | 2.8 | **7.9**<small>%</small> |
| [한온시스템](/018880/) | P:기계 | 43.3 | 0.9 | **7.6**<small>%</small> |
| [티이엠씨](/425040/) | Q:화학 | 8.7 | 1.1 | **7.5**<small>%</small> |
| [기업은행](/024110/) | P:은행 | <span style="color:tomato">4.5</span> | <span style="color:tomato">0.4</span> | **7.0**<small>%</small> |
| [골프존](/215000/) | Q:출판매체복제 | <span style="color:tomato">5.2</span> | 1.0 | **6.6**<small>%</small> |
| [DGB금융지주](/139130/) | P:기타금융 | <span style="color:tomato">3.8</span> | <span style="color:tomato">0.2</span> | **6.6**<small>%</small> |
| [LG유플러스](/032640/) | P:통신업 | 6.8 | 0.5 | **6.6**<small>%</small> |
| [우리금융지주](/316140/) | P:기타금융 | <span style="color:tomato">4.9</span> | <span style="color:tomato">0.4</span> | **6.3**<small>%</small> |
| [컴투스](/078340/) | Q:출판매체복제 | 12.1 | 0.4 | **6.3**<small>%</small> |
| [현대해상](/001450/) | P:보험 | <span style="color:tomato">4.4</span> | 0.4 | **6.2**<small>%</small> |
| [SK텔레콤](/017670/) | P:통신업 | 11.7 | 1.1 | **6.1**<small>%</small> |
| [제일기획](/030000/) | P:서비스업 | 9.9 | 1.4 | **6.0**<small>%</small> |
| [롯데지주](/004990/) | P:기타금융 | - | <span style="color:tomato">0.3</span> | **6.0**<small>%</small> |
| [롯데쇼핑](/023530/) | P:유통업 | 11.0 | <span style="color:tomato">0.2</span> | **6.0**<small>%</small> |
| [세아베스틸지주](/001430/) | P:철강금속 | 5.7 | <span style="color:tomato">0.4</span> | **5.9**<small>%</small> |
| [삼성카드](/029780/) | P:기타금융 | 7.5 | 0.6 | **5.8**<small>%</small> |
| [효성](/004800/) | P:기타금융 | <span style="color:cornflowerblue">17333.3</span> | <span style="color:tomato">0.4</span> | **5.8**<small>%</small> |
| [하나금융지주](/086790/) | P:기타금융 | <span style="color:tomato">5.2</span> | 0.4 | **5.7**<small>%</small> |
| [한일시멘트](/300720/) | P:비금속광물 | <span style="color:tomato">5.7</span> | 0.6 | **5.7**<small>%</small> |
| [NH투자증권](/005940/) | P:증권 | 8.9 | 0.7 | **5.7**<small>%</small> |
| [GS](/078930/) | P:기타금융 | <span style="color:tomato">3.3</span> | <span style="color:tomato">0.3</span> | **5.5**<small>%</small> |
| [JB금융지주](/175330/) | P:기타금융 | <span style="color:tomato">5.3</span> | 0.6 | **5.5**<small>%</small> |
| [기아](/000270/) | P:운수장비 | <span style="color:tomato">4.7</span> | 0.9 | **5.4**<small>%</small> |
| [강원랜드](/035250/) | P:서비스업 | 10.3 | 0.9 | **5.4**<small>%</small> |
| [TKG휴켐스](/069260/) | P:화학 | <span style="color:tomato">5.3</span> | 0.9 | **5.3**<small>%</small> |
| [BNK금융지주](/138930/) | P:기타금융 | <span style="color:tomato">5.1</span> | <span style="color:tomato">0.3</span> | **5.3**<small>%</small> |
| [현대글로비스](/086280/) | P:운수창고업 | 8.5 | 1.2 | **5.2**<small>%</small> |
| [한전KPS](/051600/) | P:건설업 | 11.5 | 1.5 | **5.2**<small>%</small> |
| [한화생명](/088350/) | P:보험 | <span style="color:tomato">3.1</span> | <span style="color:tomato">0.2</span> | **5.0**<small>%</small> |
| [KT&G](/033780/) | P:기타제조업 | 13.7 | 1.3 | **4.8**<small>%</small> |
| [삼성증권](/016360/) | P:증권 | 7.5 | 0.6 | **4.8**<small>%</small> |
| [오리온홀딩스](/001800/) | P:기타금융 | 11.1 | 0.4 | **4.7**<small>%</small> |