<span style="color:tomato">붉은색</span>으로 표시된 수치는 저PER, 저PBR, 고배당에도 해당[^fn_finance_metric]되는 경우입니다. <span style="color:cornflowerblue">푸른색</span>으로 표시된 수치는 고PER, 고PBR에도 해당되는 경우입니다.

| **종목** | **업종**[^fn_sector_abbr] | **PER** | **PBR** | **DIV** |
| :--- | :--- | --: | --: | --: |
| [레인보우로보틱스](/277810/) | Q:기계장비 | <span style="color:cornflowerblue">489.0</span> | **47.5** | - |
| [에코프로머티](/450080/) | P:전기전자 | <span style="color:cornflowerblue">712.6</span> | **38.6** | - |
| [금양](/001570/) | P:화학 | - | **37.9** | - |
| [메지온](/140410/) | Q:기타서비스 | - | **35.4** | - |
| [알테오젠](/196170/) | Q:기타서비스 | - | **30.0** | - |
| [HPSP](/403870/) | Q:반도체 | <span style="color:cornflowerblue">65.6</span> | **24.6** | 0.2<small>%</small> |
| [루닛](/328130/) | Q:소프트웨어 | - | **21.8** | - |
| [SK바이오팜](/326030/) | P:서비스업 | - | **21.5** | - |
| [에코프로비엠](/247540/) | Q:일반전기전자 | <span style="color:cornflowerblue">83.3</span> | **17.2** | 0.2<small>%</small> |
| [보로노이](/310210/) | Q:제약 | - | **16.8** | - |
| [박셀바이오](/323990/) | Q:기타서비스 | - | **16.1** | - |
| [엔켐](/348370/) | Q:화학 | <span style="color:cornflowerblue">188.5</span> | **15.0** | - |
| [HLB](/028300/) | Q:제약 | - | **14.8** | - |
| [현대바이오](/048410/) | Q:화학 | - | **14.7** | - |
| [에이비엘바이오](/298380/) | Q:제약 | <span style="color:cornflowerblue">307.5</span> | **14.2** | - |
| [레이크머티리얼즈](/281740/) | Q:화학 | 43.7 | **13.7** | - |
| [엠로](/058970/) | Q:소프트웨어 | <span style="color:cornflowerblue">105.0</span> | **13.4** | - |
| [원텍](/336570/) | Q:의료정밀기기 | 51.8 | **12.6** | - |
| [에코프로](/086520/) | Q:금융 | <span style="color:cornflowerblue">443.8</span> | **12.5** | 0.1<small>%</small> |
| [셀트리온제약](/068760/) | Q:제약 | <span style="color:cornflowerblue">166.4</span> | **12.1** | - |
| [에코프로에이치엔](/383310/) | Q:화학 | 28.7 | **10.7** | 1.0<small>%</small> |
| [한올바이오파마](/009420/) | P:의약품 | <span style="color:cornflowerblue">7040.0</span> | **10.6** | - |
| [강원에너지](/114190/) | Q:금속 | <span style="color:cornflowerblue">98.9</span> | **10.6** | - |
| [파크시스템스](/140860/) | Q:의료정밀기기 | 43.3 | **10.2** | 0.2<small>%</small> |
| [포스코엠텍](/009520/) | Q:금속 | <span style="color:cornflowerblue">211.6</span> | **8.9** | 0.1<small>%</small> |
| [삼천당제약](/000250/) | Q:제약 | <span style="color:cornflowerblue">259.6</span> | **8.7** | - |
| [대주전자재료](/078600/) | Q:IT부품 | <span style="color:cornflowerblue">1043.3</span> | **8.7** | 0.1<small>%</small> |
| [포스코퓨처엠](/003670/) | P:전기전자 | <span style="color:cornflowerblue">180.8</span> | **8.7** | 0.1<small>%</small> |
| [제이오](/418550/) | Q:기타서비스 | - | **8.6** | - |
| [JYP Ent.](/035900/) | Q:오락문화 | 36.5 | **8.2** | 0.5<small>%</small> |
| [네이처셀](/007390/) | Q:제약 | - | **8.2** | - |
| [셀바스AI](/108860/) | Q:소프트웨어 | <span style="color:cornflowerblue">65.7</span> | **8.1** | - |
| [클래시스](/214150/) | Q:의료정밀기기 | 24.6 | **8.1** | 0.4<small>%</small> |
| [하나투어](/039130/) | P:서비스업 | - | **7.9** | - |
| [제이시스메디칼](/287410/) | Q:의료정밀기기 | 21.8 | **7.4** | - |