<span style="color:tomato">붉은색</span>으로 표시된 수치는 저PER, 저PBR, 고배당에도 해당[^fn_finance_metric]되는 경우입니다. <span style="color:cornflowerblue">푸른색</span>으로 표시된 수치는 고PER, 고PBR에도 해당되는 경우입니다.

| **종목** | **업종**[^fn_sector_abbr] | **PER** | **PBR** | **DIV** |
| :--- | :--- | --: | --: | --: |
| [LX인터내셔널](/001120/) | P:유통업 | <span style="color:tomato">1.9</span> | <span style="color:tomato">0.4</span> | **11.0**<small>%</small> |
| [GS건설](/006360/) | P:건설업 | <span style="color:tomato">3.9</span> | <span style="color:tomato">0.3</span> | **8.3**<small>%</small> |
| [BNK금융지주](/138930/) | P:기타금융 | <span style="color:tomato">3.2</span> | <span style="color:tomato">0.2</span> | **8.2**<small>%</small> |
| [에스디바이오센서](/137310/) | P:의료정밀 | <span style="color:tomato">1.4</span> | <span style="color:tomato">0.4</span> | **8.0**<small>%</small> |
| [우리금융지주](/316140/) | P:기타금융 | <span style="color:tomato">3.5</span> | <span style="color:tomato">0.4</span> | **7.7**<small>%</small> |
| [효성](/004800/) | P:기타금융 | <span style="color:cornflowerblue">75.6</span> | <span style="color:tomato">0.5</span> | **7.6**<small>%</small> |
| [S-Oil](/010950/) | P:화학 | <span style="color:tomato">4.2</span> | 1.0 | **7.3**<small>%</small> |
| [롯데정밀화학](/004000/) | P:화학 | 8.4 | 0.5 | **7.3**<small>%</small> |
| [DGB금융지주](/139130/) | P:기타금융 | <span style="color:tomato">4.0</span> | <span style="color:tomato">0.3</span> | **7.3**<small>%</small> |
| [기업은행](/024110/) | P:은행 | <span style="color:tomato">4.2</span> | <span style="color:tomato">0.4</span> | **6.8**<small>%</small> |
| [HMM](/011200/) | P:운수창고업 | <span style="color:tomato">0.9</span> | <span style="color:tomato">0.4</span> | **6.7**<small>%</small> |
| [HD현대](/267250/) | P:기타금융 | <span style="color:tomato">3.5</span> | 0.7 | **6.6**<small>%</small> |
| [삼성카드](/029780/) | P:기타금융 | 6.7 | 0.5 | **6.4**<small>%</small> |
| [LG유플러스](/032640/) | P:통신업 | 6.6 | 0.5 | **6.4**<small>%</small> |
| [SK텔레콤](/017670/) | P:통신업 | 12.6 | 1.0 | **6.4**<small>%</small> |
| [쌍용C&E](/003410/) | P:비금속광물 | 27.4 | 2.2 | **6.3**<small>%</small> |
| [제일기획](/030000/) | P:서비스업 | 9.6 | 1.5 | **6.3**<small>%</small> |
| [JB금융지주](/175330/) | P:기타금융 | 4.5 | 0.6 | **6.1**<small>%</small> |
| [현대해상](/001450/) | P:보험 | 4.6 | 0.6 | **6.0**<small>%</small> |
| [NH투자증권](/005940/) | P:증권 | 13.6 | 0.6 | **5.9**<small>%</small> |
| [한온시스템](/018880/) | P:기계 | <span style="color:cornflowerblue">162.6</span> | 1.5 | **5.8**<small>%</small> |
| [골프존](/215000/) | Q:소프트웨어 | <span style="color:tomato">4.2</span> | 1.3 | **5.8**<small>%</small> |
| [코웰패션](/033290/) | Q:유통 | <span style="color:tomato">4.5</span> | 0.6 | **5.8**<small>%</small> |
| [하나금융지주](/086790/) | P:기타금융 | 5.1 | 0.5 | **5.6**<small>%</small> |
| [KT&G](/033780/) | P:기타제조업 | 10.9 | 1.2 | **5.4**<small>%</small> |
| [GS](/078930/) | P:기타금융 | <span style="color:tomato">2.2</span> | <span style="color:tomato">0.4</span> | **5.1**<small>%</small> |
| [KT](/030200/) | P:통신업 | 7.4 | 0.6 | **5.1**<small>%</small> |
| [TKG휴켐스](/069260/) | P:화학 | 9.3 | 1.0 | **5.0**<small>%</small> |
| [롯데지주](/004990/) | P:기타금융 | 12.6 | <span style="color:tomato">0.3</span> | **5.0**<small>%</small> |
| [SK이노베이션](/096770/) | P:화학 | 6.4 | 0.5 | **5.0**<small>%</small> |
| [세아베스틸지주](/001430/) | P:철강금속 | 9.4 | <span style="color:tomato">0.5</span> | **5.0**<small>%</small> |
| [오리온홀딩스](/001800/) | P:기타금융 | 8.5 | <span style="color:tomato">0.4</span> | **4.8**<small>%</small> |
| [한일시멘트](/300720/) | P:비금속광물 | 10.7 | 0.6 | **4.8**<small>%</small> |
| [하이트진로](/000080/) | P:음식료품 | 16.0 | 1.2 | **4.8**<small>%</small> |
| [신한지주](/055550/) | P:기타금융 | 5.2 | 0.5 | **4.7**<small>%</small> |