<span style="color:tomato">붉은색</span>으로 표시된 수치는 저PER, 저PBR, 고배당에도 해당[^fn_finance_metric]되는 경우입니다. <span style="color:cornflowerblue">푸른색</span>으로 표시된 수치는 고PER, 고PBR에도 해당되는 경우입니다.

| **종목** | **업종**[^fn_sector_abbr] | **PER** | **PBR** | **DIV** |
| :--- | :--- | --: | --: | --: |
| [이마트](/139480/) | P:유통업 | - | **0.1** | 3.4<small>%</small> |
| [한화생명](/088350/) | P:보험 | <span style="color:tomato">2.8</span> | **0.2** | <span style="color:tomato">5.5<small>%</small></span> |
| [영풍](/000670/) | P:철강금속 | - | **0.2** | 2.8<small>%</small> |
| [롯데쇼핑](/023530/) | P:유통업 | 11.1 | **0.2** | <span style="color:tomato">5.9<small>%</small></span> |
| [현대제철](/004020/) | P:철강금속 | 8.2 | **0.2** | 3.5<small>%</small> |
| [하림지주](/003380/) | Q:금융 | 15.9 | **0.2** | 2.0<small>%</small> |
| [DGB금융지주](/139130/) | P:기타금융 | <span style="color:tomato">3.6</span> | **0.2** | <span style="color:tomato">7.0<small>%</small></span> |
| [한화](/000880/) | P:화학 | 6.8 | **0.2** | 2.8<small>%</small> |
| [현대백화점](/069960/) | P:유통업 | - | **0.2** | 2.6<small>%</small> |
| [BNK금융지주](/138930/) | P:기타금융 | <span style="color:tomato">4.2</span> | **0.2** | <span style="color:tomato">6.3<small>%</small></span> |
| [롯데지주](/004990/) | P:기타금융 | - | **0.3** | <span style="color:tomato">6.0<small>%</small></span> |
| [GS건설](/006360/) | P:건설업 | - | **0.3** | - |
| [GS](/078930/) | P:기타금융 | <span style="color:tomato">3.1</span> | **0.3** | <span style="color:tomato">5.8<small>%</small></span> |
| [DL이앤씨](/375500/) | P:건설업 | 7.5 | **0.3** | 1.4<small>%</small> |
| [롯데케미칼](/011170/) | P:화학 | - | **0.3** | 3.1<small>%</small> |
| [DL](/000210/) | P:화학 | - | **0.3** | 1.8<small>%</small> |
| [우리금융지주](/316140/) | P:기타금융 | <span style="color:tomato">4.3</span> | **0.3** | <span style="color:tomato">7.2<small>%</small></span> |
| [기업은행](/024110/) | P:은행 | <span style="color:tomato">4.2</span> | **0.3** | <span style="color:tomato">7.4<small>%</small></span> |
| [삼성생명](/032830/) | P:보험 | 7.8 | **0.3** | 4.5<small>%</small> |
| [한국전력](/015760/) | P:전기가스업 | - | **0.3** | - |
| [KG스틸](/016380/) | P:철강금속 | <span style="color:tomato">2.8</span> | **0.3** | 3.0<small>%</small> |
| [한국앤컴퍼니](/000240/) | P:기타금융 | 7.6 | **0.3** | 4.7<small>%</small> |
| [신세계](/004170/) | P:유통업 | 6.7 | **0.3** | 2.5<small>%</small> |
| [다우데이타](/032190/) | Q:유통 | 6.9 | **0.4** | 2.2<small>%</small> |
| [대우건설](/047040/) | P:건설업 | <span style="color:tomato">2.9</span> | **0.4** | - |
| [미래에셋증권](/006800/) | P:증권 | 13.3 | **0.4** | 2.1<small>%</small> |
| [세아베스틸지주](/001430/) | P:철강금속 | 5.9 | **0.4** | <span style="color:tomato">5.7<small>%</small></span> |
| [컴투스](/078340/) | Q:디지털컨텐츠 | 11.2 | **0.4** | <span style="color:tomato">6.8<small>%</small></span> |
| [KCC](/002380/) | P:화학 | 9.7 | **0.4** | 2.9<small>%</small> |
| [영원무역홀딩스](/009970/) | P:기타금융 | <span style="color:tomato">2.5</span> | **0.4** | 4.9<small>%</small> |
| [현대해상](/001450/) | P:보험 | <span style="color:tomato">4.2</span> | **0.4** | <span style="color:tomato">6.4<small>%</small></span> |
| [오리온홀딩스](/001800/) | P:기타금융 | 10.8 | **0.4** | 4.9<small>%</small> |
| [코오롱인더](/120110/) | P:화학 | 30.6 | **0.4** | 3.3<small>%</small> |
| [하나금융지주](/086790/) | P:기타금융 | <span style="color:tomato">5.2</span> | **0.4** | <span style="color:tomato">5.7<small>%</small></span> |
| [현대위아](/011210/) | P:운수장비 | 16.5 | **0.4** | 1.5<small>%</small> |