<span style="color:tomato">붉은색</span>으로 표시된 수치는 저PER, 저PBR, 고배당에도 해당[^fn_finance_metric]되는 경우입니다. <span style="color:cornflowerblue">푸른색</span>으로 표시된 수치는 고PER, 고PBR에도 해당되는 경우입니다.

| **종목** | **업종**[^fn_sector_abbr] | **PER** | **PBR** | **DIV** |
| :--- | :--- | --: | --: | --: |
| [이마트](/139480/) | P:유통업 | <span style="color:tomato">1.6</span> | **0.1** | 3.3<small>%</small> |
| [영풍](/000670/) | P:철강금속 | <span style="color:tomato">2.0</span> | **0.2** | 2.4<small>%</small> |
| [롯데쇼핑](/023530/) | P:유통업 | - | **0.2** | <span style="color:tomato">4.9<small>%</small></span> |
| [한국가스공사](/036460/) | P:전기가스업 | <span style="color:tomato">1.5</span> | **0.2** | - |
| [하림지주](/003380/) | Q:금융 | <span style="color:tomato">2.3</span> | **0.2** | 1.9<small>%</small> |
| [현대제철](/004020/) | P:철강금속 | <span style="color:tomato">4.1</span> | **0.2** | 3.2<small>%</small> |
| [현대백화점](/069960/) | P:유통업 | 7.6 | **0.2** | 2.6<small>%</small> |
| [GS건설](/006360/) | P:건설업 | <span style="color:tomato">3.6</span> | **0.2** | <span style="color:tomato">9.0<small>%</small></span> |
| [BNK금융지주](/138930/) | P:기타금융 | <span style="color:tomato">3.2</span> | **0.2** | <span style="color:tomato">8.2<small>%</small></span> |
| [롯데지주](/004990/) | P:기타금융 | 10.8 | **0.3** | <span style="color:tomato">5.8<small>%</small></span> |
| [DGB금융지주](/139130/) | P:기타금융 | <span style="color:tomato">3.6</span> | **0.3** | <span style="color:tomato">8.0<small>%</small></span> |
| [DL](/000210/) | P:화학 | 19.3 | **0.3** | 1.9<small>%</small> |
| [롯데케미칼](/011170/) | P:화학 | 62.8 | **0.3** | 3.2<small>%</small> |
| [한화생명](/088350/) | P:보험 | <span style="color:tomato">3.1</span> | **0.3** | - |
| [DL이앤씨](/375500/) | P:건설업 | <span style="color:tomato">3.4</span> | **0.3** | 3.0<small>%</small> |
| [GS](/078930/) | P:기타금융 | <span style="color:tomato">2.0</span> | **0.3** | <span style="color:tomato">5.6<small>%</small></span> |
| [한국전력](/015760/) | P:전기가스업 | - | **0.3** | - |
| [KCC](/002380/) | P:화학 | 51.7 | **0.3** | 3.4<small>%</small> |
| [우리금융지주](/316140/) | P:기타금융 | <span style="color:tomato">3.2</span> | **0.3** | <span style="color:tomato">8.3<small>%</small></span> |
| [미래에셋증권](/006800/) | P:증권 | 7.4 | **0.3** | 2.6<small>%</small> |
| [기업은행](/024110/) | P:은행 | <span style="color:tomato">3.9</span> | **0.3** | <span style="color:tomato">7.5<small>%</small></span> |
| [에스디바이오센서](/137310/) | P:의료정밀 | <span style="color:tomato">1.2</span> | **0.4** | <span style="color:tomato">9.2<small>%</small></span> |
| [코오롱인더](/120110/) | P:화학 | 5.9 | **0.4** | 3.7<small>%</small> |
| [HMM](/011200/) | P:운수창고업 | <span style="color:tomato">0.8</span> | **0.4** | <span style="color:tomato">7.8<small>%</small></span> |
| [신세계](/004170/) | P:유통업 | <span style="color:tomato">3.9</span> | **0.4** | 2.3<small>%</small> |
| [한화](/000880/) | P:화학 | <span style="color:tomato">1.9</span> | **0.4** | 2.8<small>%</small> |
| [다우데이타](/032190/) | Q:유통 | <span style="color:tomato">2.2</span> | **0.4** | 2.6<small>%</small> |
| [오리온홀딩스](/001800/) | P:기타금융 | 8.2 | **0.4** | <span style="color:tomato">5.0<small>%</small></span> |
| [LG디스플레이](/034220/) | P:전기전자 | - | **0.4** | - |
| [한국앤컴퍼니](/000240/) | P:기타금융 | 9.1 | **0.4** | 4.1<small>%</small> |
| [컴투스](/078340/) | Q:디지털컨텐츠 | 13.6 | **0.4** | 3.4<small>%</small> |
| [대우건설](/047040/) | P:건설업 | <span style="color:tomato">3.0</span> | **0.4** | - |
| [세아베스틸지주](/001430/) | P:철강금속 | 8.4 | **0.4** | <span style="color:tomato">5.6<small>%</small></span> |
| [KG스틸](/016380/) | P:철강금속 | <span style="color:tomato">1.3</span> | **0.4** | 2.2<small>%</small> |
| [LX인터내셔널](/001120/) | P:유통업 | <span style="color:tomato">1.9</span> | **0.4** | <span style="color:tomato">11.3<small>%</small></span> |