<span style="color:tomato">붉은색</span>으로 표시된 수치는 저PER, 저PBR, 고배당에도 해당[^fn_finance_metric]되는 경우입니다. <span style="color:cornflowerblue">푸른색</span>으로 표시된 수치는 고PER, 고PBR에도 해당되는 경우입니다.

| **종목** | **업종**[^fn_sector_abbr] | **PER** | **PBR** | **DIV** |
| :--- | :--- | --: | --: | --: |
| [OCI홀딩스](/010060/) | P:기타금융 | **2.7** | 0.5 | 3.3<small>%</small> |
| [영원무역홀딩스](/009970/) | P:기타금융 | **2.8** | <span style="color:tomato">0.4</span> | 4.4<small>%</small> |
| [KG스틸](/016380/) | P:철강금속 | **3.0** | <span style="color:tomato">0.4</span> | 2.9<small>%</small> |
| [대우건설](/047040/) | P:건설업 | **3.0** | <span style="color:tomato">0.4</span> | - |
| [GS](/078930/) | P:기타금융 | **3.3** | <span style="color:tomato">0.3</span> | <span style="color:tomato">5.6<small>%</small></span> |
| [영원무역](/111770/) | P:유통업 | **3.3** | 0.5 | 3.4<small>%</small> |
| [한화생명](/088350/) | P:보험 | **3.3** | <span style="color:tomato">0.2</span> | 4.8<small>%</small> |
| [서부T&D](/006730/) | Q:숙박음식 | **3.6** | 0.6 | 0.7<small>%</small> |
| [DB손해보험](/005830/) | P:보험 | **3.9** | 0.7 | 4.8<small>%</small> |
| [DGB금융지주](/139130/) | P:기타금융 | **3.9** | <span style="color:tomato">0.2</span> | <span style="color:tomato">6.4<small>%</small></span> |
| [KG이니시스](/035600/) | Q:소프트웨어 | **4.1** | 0.7 | 3.6<small>%</small> |
| [더네이쳐홀딩스](/298540/) | Q:섬유의류 | **4.4** | 0.7 | 2.7<small>%</small> |
| [성우하이텍](/015750/) | Q:운송장비부품 | **4.4** | 0.6 | 1.6<small>%</small> |
| [기업은행](/024110/) | P:은행 | **4.4** | <span style="color:tomato">0.3</span> | <span style="color:tomato">7.0<small>%</small></span> |
| [에스엘](/005850/) | P:운수장비 | **4.5** | 0.8 | 2.8<small>%</small> |
| [우리금융지주](/316140/) | P:기타금융 | **4.5** | <span style="color:tomato">0.3</span> | <span style="color:tomato">6.8<small>%</small></span> |
| [현대해상](/001450/) | P:보험 | **4.5** | <span style="color:tomato">0.5</span> | <span style="color:tomato">6.0<small>%</small></span> |
| [BNK금융지주](/138930/) | P:기타금융 | **4.5** | <span style="color:tomato">0.3</span> | <span style="color:tomato">5.9<small>%</small></span> |
| [JB금융지주](/175330/) | P:기타금융 | **4.6** | 0.5 | <span style="color:tomato">6.4<small>%</small></span> |
| [현대엘리베이](/017800/) | P:기계 | **4.8** | 1.2 | <span style="color:tomato">9.7<small>%</small></span> |
| [아이에스동서](/010780/) | P:비금속광물 | **5.0** | 0.5 | <span style="color:tomato">5.6<small>%</small></span> |
| [대웅](/003090/) | P:의약품 | **5.1** | 0.8 | 0.5<small>%</small> |
| [명신산업](/009900/) | P:운수장비 | **5.2** | 1.5 | 0.7<small>%</small> |
| [기아](/000270/) | P:운수장비 | **5.2** | 1.0 | <span style="color:tomato">4.9<small>%</small></span> |
| [우리기술투자](/041190/) | Q:금융 | **5.3** | 1.2 | - |
| [현대차](/005380/) | P:운수장비 | **5.4** | 0.7 | 4.6<small>%</small> |
| [매일유업](/267980/) | Q:음식료담배 | **5.4** | 0.6 | 2.9<small>%</small> |
| [아난티](/025980/) | Q:숙박음식 | **5.5** | 0.9 | - |
| [하나금융지주](/086790/) | P:기타금융 | **5.6** | 0.5 | <span style="color:tomato">5.3<small>%</small></span> |
| [TKG휴켐스](/069260/) | P:화학 | **5.6** | 0.9 | <span style="color:tomato">5.1<small>%</small></span> |
| [한일시멘트](/300720/) | P:비금속광물 | **5.8** | 0.6 | <span style="color:tomato">5.7<small>%</small></span> |
| [한국금융지주](/071050/) | P:기타금융 | **5.9** | 0.5 | 3.7<small>%</small> |
| [신한지주](/055550/) | P:기타금융 | **6.0** | 0.5 | 4.4<small>%</small> |
| [골프존](/215000/) | Q:소프트웨어 | **6.0** | 1.1 | <span style="color:tomato">5.8<small>%</small></span> |
| [현대모비스](/012330/) | P:운수장비 | **6.0** | 0.5 | 2.0<small>%</small> |