| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [삼성전자우](/005935-vs-005930/) | <span style="color: tomato">14.0<small>%</small></span> | 35.7<small>%</small> | 0.39 | -71.9<small>%</small> | -18.1<small>%</small> |
| 삼성전자 | <span style="color: tomato">11.8<small>%</small></span> | 34.3<small>%</small> | 0.35 | -64.8<small>%</small> | -17.7<small>%</small> |