| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [삼성전자우](/005935-vs-005930/) | <span style="color: tomato">15.2<small>%</small></span> | 35.5<small>%</small> | 0.43 | -71.9<small>%</small> | -18.2<small>%</small> |
| 삼성전자 | <span style="color: tomato">12.0<small>%</small></span> | 34.2<small>%</small> | 0.35 | -64.8<small>%</small> | -17.7<small>%</small> |