| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KOSEF KRX100](/100910-vs-292190/) | <span style="color: tomato">4.0<small>%</small></span> | 18.7<small>%</small> | 0.21 | -35.6<small>%</small> | -13.8<small>%</small> |
| KODEX KRX300 | <span style="color: tomato">4.7<small>%</small></span> | 19.1<small>%</small> | 0.24 | -36.8<small>%</small> | -12.8<small>%</small> |