| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KOSEF KRX100](/100910-vs-292190/) | <span style="color: tomato">4.5<small>%</small></span> | 18.8<small>%</small> | 0.24 | -35.6<small>%</small> | -13.9<small>%</small> |
| KODEX KRX300 | <span style="color: tomato">5.3<small>%</small></span> | 19.2<small>%</small> | 0.27 | -36.8<small>%</small> | -13.0<small>%</small> |