| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KOSEF 고배당](/104530-vs-161510/) | <span style="color: tomato">7.1<small>%</small></span> | 16.0<small>%</small> | 0.44 | -49.3<small>%</small> | -8.9<small>%</small> |
| ARIRANG 고배당주 | <span style="color: tomato">5.9<small>%</small></span> | 16.2<small>%</small> | 0.37 | -51.5<small>%</small> | -8.3<small>%</small> |