| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KOSEF 고배당](/104530-vs-161510/) | <span style="color: tomato">7.2<small>%</small></span> | 15.9<small>%</small> | 0.45 | -49.3<small>%</small> | -9.0<small>%</small> |
| ARIRANG 고배당주 | <span style="color: tomato">6.2<small>%</small></span> | 16.1<small>%</small> | 0.38 | -51.5<small>%</small> | -8.4<small>%</small> |