| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KOSEF 고배당](/104530-vs-161510/) | <span style="color: tomato">7.8<small>%</small></span> | 16.1<small>%</small> | 0.49 | -49.3<small>%</small> | -8.8<small>%</small> |
| ARIRANG 고배당주 | <span style="color: tomato">6.7<small>%</small></span> | 16.2<small>%</small> | 0.41 | -51.6<small>%</small> | -8.3<small>%</small> |