| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PLUS 코스피50](/122090-vs-069500/) | <span style="color: tomato">5.4<small>%</small></span> | 18.3<small>%</small> | 0.30 | -36.6<small>%</small> | -12.5<small>%</small> |
| KODEX 200 | <span style="color: tomato">5.4<small>%</small></span> | 17.0<small>%</small> | 0.32 | -38.1<small>%</small> | -11.5<small>%</small> |