| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국나스닥100](/133690-vs-379810/) | <span style="color: tomato">14.3<small>%</small></span> | 20.1<small>%</small> | 0.71 | -31.0<small>%</small> | -8.1<small>%</small> |
| KODEX 미국나스닥100TR | <span style="color: tomato">14.7<small>%</small></span> | 20.0<small>%</small> | 0.73 | -31.0<small>%</small> | -8.1<small>%</small> |