| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국나스닥100](/133690-vs-161510/) | <span style="color: tomato">18.8<small>%</small></span> | 18.5<small>%</small> | 1.02 | -31.0<small>%</small> | -4.8<small>%</small> |
| PLUS 고배당주 | <span style="color: tomato">6.9<small>%</small></span> | 16.3<small>%</small> | 0.42 | -51.6<small>%</small> | -8.2<small>%</small> |