| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국나스닥100](/133690-vs-161510/) | <span style="color: tomato">20.7<small>%</small></span> | 18.4<small>%</small> | 1.13 | -31.0<small>%</small> | -4.8<small>%</small> |
| ARIRANG 고배당주 | <span style="color: tomato">7.3<small>%</small></span> | 16.2<small>%</small> | 0.45 | -51.6<small>%</small> | -8.2<small>%</small> |