| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국나스닥100](/133690-vs-379810/) | <span style="color: tomato">17.8<small>%</small></span> | 20.3<small>%</small> | 0.87 | -31.0<small>%</small> | -8.1<small>%</small> |
| KODEX 미국나스닥100TR | <span style="color: tomato">17.9<small>%</small></span> | 20.2<small>%</small> | 0.88 | -31.0<small>%</small> | -8.1<small>%</small> |