| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국S&P500선물(H)](/143850-vs-360750/) | <span style="color: tomato">11.5<small>%</small></span> | 17.5<small>%</small> | 0.66 | -25.7<small>%</small> | -8.0<small>%</small> |
| TIGER 미국S&P500 | <span style="color: tomato">17.9<small>%</small></span> | 14.9<small>%</small> | 1.20 | -16.7<small>%</small> | -3.9<small>%</small> |