| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국S&P500선물(H)](/143850-vs-360750/) | <span style="color: tomato">10.5<small>%</small></span> | 17.7<small>%</small> | 0.59 | -25.7<small>%</small> | -8.4<small>%</small> |
| TIGER 미국S&P500 | <span style="color: tomato">16.6<small>%</small></span> | 15.1<small>%</small> | 1.10 | -16.7<small>%</small> | -4.1<small>%</small> |