| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국S&P500선물(H)](/143850-vs-360750/) | <span style="color: tomato">11.8<small>%</small></span> | 17.6<small>%</small> | 0.67 | -25.7<small>%</small> | -8.2<small>%</small> |
| TIGER 미국S&P500 | <span style="color: tomato">18.1<small>%</small></span> | 15.0<small>%</small> | 1.21 | -16.7<small>%</small> | -4.0<small>%</small> |