| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 모멘텀](/147970-vs-069500/) | <span style="color: tomato">3.7<small>%</small></span> | 17.2<small>%</small> | 0.21 | -53.8<small>%</small> | -11.9<small>%</small> |
| KODEX 200 | <span style="color: tomato">4.6<small>%</small></span> | 16.4<small>%</small> | 0.28 | -38.1<small>%</small> | -9.9<small>%</small> |