| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 모멘텀](/147970-vs-069500/) | <span style="color: tomato">5.1<small>%</small></span> | 17.3<small>%</small> | 0.29 | -53.8<small>%</small> | -11.6<small>%</small> |
| KODEX 200 | <span style="color: tomato">5.0<small>%</small></span> | 16.4<small>%</small> | 0.31 | -38.1<small>%</small> | -9.9<small>%</small> |