| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [1482.T](/1482-vs-ief/) | <span style="color: cornflowerblue">-2.8<small>%</small></span> | 7.6<small>%</small> | -0.37 | -31.4<small>%</small> | -11.9<small>%</small> |
| IEF | <span style="color: cornflowerblue">-0.0<small>%</small></span> | 7.0<small>%</small> | -0.01 | -23.9<small>%</small> | -7.6<small>%</small> |