| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ARIRANG 고배당주](/161510-vs-069500/) | <span style="color: tomato">6.7<small>%</small></span> | 16.1<small>%</small> | 0.41 | -51.5<small>%</small> | -8.4<small>%</small> |
| KODEX 200 | <span style="color: tomato">5.0<small>%</small></span> | 16.1<small>%</small> | 0.31 | -38.1<small>%</small> | -10.1<small>%</small> |