| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [170350](/170350-vs-069500/) | <span style="color: tomato">8.0<small>%</small></span> | 16.3<small>%</small> | 0.49 | -46.5<small>%</small> | -9.6<small>%</small> |
| KODEX 200 | <span style="color: tomato">7.9<small>%</small></span> | 15.9<small>%</small> | 0.49 | -38.1<small>%</small> | -7.7<small>%</small> |