| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 로우볼](/174350-vs-069500/) | <span style="color: tomato">4.4<small>%</small></span> | 13.9<small>%</small> | 0.31 | -49.6<small>%</small> | -8.8<small>%</small> |
| KODEX 200 | <span style="color: tomato">6.2<small>%</small></span> | 16.3<small>%</small> | 0.38 | -38.1<small>%</small> | -10.5<small>%</small> |