| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [파워 고배당저변동성](/192720-vs-161510/) | <span style="color: tomato">5.9<small>%</small></span> | 15.5<small>%</small> | 0.38 | -49.8<small>%</small> | -8.2<small>%</small> |
| ARIRANG 고배당주 | <span style="color: tomato">7.4<small>%</small></span> | 16.8<small>%</small> | 0.44 | -51.6<small>%</small> | -8.7<small>%</small> |