| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 유로스탁스50(합성 H)](/195930-vs-379790/) | <span style="color: tomato">6.2<small>%</small></span> | 19.1<small>%</small> | 0.32 | -24.2<small>%</small> | -5.7<small>%</small> |
| RISE 유로스탁스50(H) | <span style="color: tomato">7.4<small>%</small></span> | 18.6<small>%</small> | 0.40 | -23.7<small>%</small> | -5.5<small>%</small> |