| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 유로스탁스50(합성 H)](/195930-vs-379790/) | <span style="color: tomato">5.3<small>%</small></span> | 19.1<small>%</small> | 0.28 | -24.2<small>%</small> | -5.7<small>%</small> |
| RISE 유로스탁스50(H) | <span style="color: tomato">6.8<small>%</small></span> | 18.5<small>%</small> | 0.37 | -23.7<small>%</small> | -5.5<small>%</small> |