| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KOSEF 인도Nifty50(합성)](/200250-vs-453810/) | <span style="color: tomato">28.2<small>%</small></span> | 13.1<small>%</small> | 2.15 | -6.3<small>%</small> | -1.4<small>%</small> |
| KODEX 인도Nifty50 | <span style="color: tomato">29.3<small>%</small></span> | 13.8<small>%</small> | 2.13 | -6.3<small>%</small> | -1.3<small>%</small> |