| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KOSEF 인도Nifty50(합성)](/200250-vs-453810/) | <span style="color: tomato">26.9<small>%</small></span> | 13.0<small>%</small> | 2.06 | -6.3<small>%</small> | -1.5<small>%</small> |
| KODEX 인도Nifty50 | <span style="color: tomato">27.9<small>%</small></span> | 13.7<small>%</small> | 2.04 | -6.3<small>%</small> | -1.4<small>%</small> |