| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KOSEF 인도Nifty50(합성)](/200250-vs-453810/) | <span style="color: tomato">29.3<small>%</small></span> | 11.5<small>%</small> | 2.54 | -6.2<small>%</small> | -1.4<small>%</small> |
| KODEX 인도Nifty50 | <span style="color: tomato">30.7<small>%</small></span> | 12.1<small>%</small> | 2.53 | -6.3<small>%</small> | -1.4<small>%</small> |