| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 코스피고배당](/210780-vs-161510/) | <span style="color: tomato">6.5<small>%</small></span> | 15.1<small>%</small> | 0.43 | -48.0<small>%</small> | -9.4<small>%</small> |
| ARIRANG 고배당주 | <span style="color: tomato">6.4<small>%</small></span> | 17.2<small>%</small> | 0.37 | -51.5<small>%</small> | -9.1<small>%</small> |