| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 배당성장](/211560-vs-069500/) | <span style="color: tomato">7.2<small>%</small></span> | 16.6<small>%</small> | 0.43 | -50.4<small>%</small> | -11.3<small>%</small> |
| KODEX 200 | <span style="color: tomato">7.4<small>%</small></span> | 16.8<small>%</small> | 0.44 | -38.1<small>%</small> | -11.3<small>%</small> |