| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 배당성장](/211560-vs-069500/) | <span style="color: tomato">6.8<small>%</small></span> | 16.6<small>%</small> | 0.41 | -50.4<small>%</small> | -11.2<small>%</small> |
| KODEX 200 | <span style="color: tomato">6.5<small>%</small></span> | 16.9<small>%</small> | 0.38 | -38.1<small>%</small> | -11.2<small>%</small> |