| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 배당성장](/211560-vs-069500/) | <span style="color: tomato">5.7<small>%</small></span> | 16.7<small>%</small> | 0.34 | -50.4<small>%</small> | -11.5<small>%</small> |
| KODEX 200 | <span style="color: tomato">6.2<small>%</small></span> | 16.9<small>%</small> | 0.37 | -38.1<small>%</small> | -11.3<small>%</small> |