| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 미국S&P500선물(H)](/219480-vs-143850/) | <span style="color: tomato">9.9<small>%</small></span> | 21.7<small>%</small> | 0.45 | -34.8<small>%</small> | -7.9<small>%</small> |
| TIGER 미국S&P500선물(H) | <span style="color: tomato">9.8<small>%</small></span> | 17.5<small>%</small> | 0.56 | -35.0<small>%</small> | -5.6<small>%</small> |