| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 미국S&P500선물(H)](/219480-vs-143850/) | <span style="color: tomato">10.2<small>%</small></span> | 21.6<small>%</small> | 0.47 | -34.8<small>%</small> | -7.8<small>%</small> |
| TIGER 미국S&P500선물(H) | <span style="color: tomato">10.1<small>%</small></span> | 17.4<small>%</small> | 0.58 | -35.0<small>%</small> | -5.5<small>%</small> |