| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국S&P500레버리지(합성 H)](/225040-vs-sso/) | <span style="color: tomato">17.3<small>%</small></span> | 34.2<small>%</small> | 0.51 | -58.8<small>%</small> | -12.6<small>%</small> |
| SSO | <span style="color: tomato">20.3<small>%</small></span> | 37.0<small>%</small> | 0.55 | -59.3<small>%</small> | -11.2<small>%</small> |