| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국S&P500레버리지(합성 H)](/225040-vs-sso/) | <span style="color: tomato">16.1<small>%</small></span> | 34.3<small>%</small> | 0.47 | -58.8<small>%</small> | -12.5<small>%</small> |
| SSO | <span style="color: tomato">19.5<small>%</small></span> | 37.0<small>%</small> | 0.53 | -59.3<small>%</small> | -11.1<small>%</small> |