| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 200 중소형](/226980-vs-069500/) | <span style="color: tomato">3.5<small>%</small></span> | 19.9<small>%</small> | 0.18 | -56.6<small>%</small> | -15.3<small>%</small> |
| KODEX 200 | <span style="color: tomato">8.2<small>%</small></span> | 17.2<small>%</small> | 0.48 | -38.1<small>%</small> | -11.0<small>%</small> |