| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 200 중소형](/226980-vs-069500/) | <span style="color: tomato">1.9<small>%</small></span> | 20.2<small>%</small> | 0.10 | -56.6<small>%</small> | -15.2<small>%</small> |
| KODEX 200 | <span style="color: tomato">6.4<small>%</small></span> | 17.5<small>%</small> | 0.37 | -38.1<small>%</small> | -10.9<small>%</small> |