| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 200 중소형](/226980-vs-069500/) | <span style="color: tomato">2.4<small>%</small></span> | 20.0<small>%</small> | 0.12 | -56.6<small>%</small> | -15.4<small>%</small> |
| KODEX 200 | <span style="color: tomato">7.5<small>%</small></span> | 17.2<small>%</small> | 0.44 | -38.1<small>%</small> | -11.0<small>%</small> |