| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 우량가치](/227570-vs-069500/) | <span style="color: tomato">3.7<small>%</small></span> | 17.1<small>%</small> | 0.21 | -56.3<small>%</small> | -12.8<small>%</small> |
| KODEX 200 | <span style="color: tomato">7.7<small>%</small></span> | 17.2<small>%</small> | 0.45 | -38.1<small>%</small> | -11.0<small>%</small> |