| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ACE 일본Nikkei225(H)](/238720-vs-1329/) | <span style="color: tomato">11.0<small>%</small></span> | 19.8<small>%</small> | 0.56 | -32.1<small>%</small> | -6.0<small>%</small> |
| 1329.T | <span style="color: tomato">11.5<small>%</small></span> | 19.4<small>%</small> | 0.59 | -31.2<small>%</small> | -5.7<small>%</small> |