| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 모멘텀Plus](/244620-vs-069500/) | <span style="color: tomato">3.4<small>%</small></span> | 21.8<small>%</small> | 0.15 | -49.9<small>%</small> | -13.9<small>%</small> |
| KODEX 200 | <span style="color: tomato">6.8<small>%</small></span> | 17.8<small>%</small> | 0.38 | -38.1<small>%</small> | -11.6<small>%</small> |