| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [RISE 차이나HSCEI(H)](/250730-vs-2828/) | <span style="color: tomato">17.2<small>%</small></span> | 21.1<small>%</small> | 0.82 | -14.8<small>%</small> | -6.7<small>%</small> |
| 2828.HK | <span style="color: tomato">18.8<small>%</small></span> | 21.2<small>%</small> | 0.88 | -14.0<small>%</small> | -6.5<small>%</small> |