| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [RISE 차이나HSCEI(H)](/250730-vs-2828/) | <span style="color: tomato">12.5<small>%</small></span> | 21.8<small>%</small> | 0.58 | -14.8<small>%</small> | -6.4<small>%</small> |
| 2828.HK | <span style="color: tomato">12.3<small>%</small></span> | 21.8<small>%</small> | 0.56 | -14.0<small>%</small> | -6.3<small>%</small> |