| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [RISE 차이나HSCEI(H)](/250730-vs-2828/) | <span style="color: tomato">56.9<small>%</small></span> | 28.5<small>%</small> | 1.99 | -14.8<small>%</small> | -6.8<small>%</small> |
| 2828.HK | <span style="color: tomato">54.6<small>%</small></span> | 32.2<small>%</small> | 1.70 | -14.2<small>%</small> | -6.7<small>%</small> |