| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ARIRANG 고배당저변동50](/251590-vs-161510/) | <span style="color: tomato">6.8<small>%</small></span> | 14.1<small>%</small> | 0.48 | -48.8<small>%</small> | -8.5<small>%</small> |
| ARIRANG 고배당주 | <span style="color: tomato">7.7<small>%</small></span> | 17.7<small>%</small> | 0.43 | -51.6<small>%</small> | -9.8<small>%</small> |