| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ARIRANG 고배당저변동50](/251590-vs-161510/) | <span style="color: tomato">6.6<small>%</small></span> | 14.2<small>%</small> | 0.46 | -48.7<small>%</small> | -8.6<small>%</small> |
| ARIRANG 고배당주 | <span style="color: tomato">7.8<small>%</small></span> | 17.6<small>%</small> | 0.44 | -51.5<small>%</small> | -9.9<small>%</small> |