| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 200동일가중](/252650-vs-069500/) | <span style="color: tomato">3.6<small>%</small></span> | 17.5<small>%</small> | 0.20 | -52.2<small>%</small> | -14.3<small>%</small> |
| KODEX 200 | <span style="color: tomato">7.3<small>%</small></span> | 17.7<small>%</small> | 0.41 | -38.1<small>%</small> | -12.1<small>%</small> |