| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KBSTAR 모멘텀밸류](/252720-vs-069500/) | <span style="color: tomato">8.9<small>%</small></span> | 18.9<small>%</small> | 0.47 | -48.5<small>%</small> | -12.1<small>%</small> |
| KODEX 200 | <span style="color: tomato">7.5<small>%</small></span> | 17.7<small>%</small> | 0.42 | -38.1<small>%</small> | -12.2<small>%</small> |