| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 우선주](/261140-vs-069500/) | <span style="color: tomato">6.9<small>%</small></span> | 18.2<small>%</small> | 0.38 | -40.5<small>%</small> | -15.8<small>%</small> |
| KODEX 200 | <span style="color: tomato">6.8<small>%</small></span> | 17.9<small>%</small> | 0.38 | -38.1<small>%</small> | -12.6<small>%</small> |