| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 우선주](/261140-vs-069500/) | <span style="color: tomato">7.5<small>%</small></span> | 18.3<small>%</small> | 0.41 | -40.5<small>%</small> | -15.9<small>%</small> |
| KODEX 200 | <span style="color: tomato">7.1<small>%</small></span> | 18.0<small>%</small> | 0.40 | -38.1<small>%</small> | -12.6<small>%</small> |