| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [2621.T](/2621-vs-tlt/) | <span style="color: cornflowerblue">-14.9<small>%</small></span> | 16.0<small>%</small> | -0.93 | -51.7<small>%</small> | -28.6<small>%</small> |
| TLT | <span style="color: cornflowerblue">-10.9<small>%</small></span> | 17.3<small>%</small> | -0.63 | -45.5<small>%</small> | -24.5<small>%</small> |