| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [2621.T](/2621-vs-tlt/) | <span style="color: cornflowerblue">-15.0<small>%</small></span> | 16.1<small>%</small> | -0.93 | -51.7<small>%</small> | -28.3<small>%</small> |
| TLT | <span style="color: cornflowerblue">-11.2<small>%</small></span> | 17.4<small>%</small> | -0.64 | -45.5<small>%</small> | -24.4<small>%</small> |