| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [2621.T](/2621-vs-tlt/) | <span style="color: cornflowerblue">-15.9<small>%</small></span> | 16.2<small>%</small> | -0.98 | -51.7<small>%</small> | -27.8<small>%</small> |
| TLT | <span style="color: cornflowerblue">-12.4<small>%</small></span> | 17.5<small>%</small> | -0.71 | -45.5<small>%</small> | -24.0<small>%</small> |