| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KBSTAR 고배당](/266160-vs-161510/) | <span style="color: tomato">8.7<small>%</small></span> | 17.4<small>%</small> | 0.50 | -43.4<small>%</small> | -8.9<small>%</small> |
| ARIRANG 고배당주 | <span style="color: tomato">7.4<small>%</small></span> | 18.2<small>%</small> | 0.41 | -51.5<small>%</small> | -10.7<small>%</small> |