| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KBSTAR 고배당](/266160-vs-161510/) | <span style="color: tomato">8.4<small>%</small></span> | 17.4<small>%</small> | 0.48 | -43.4<small>%</small> | -8.8<small>%</small> |
| ARIRANG 고배당주 | <span style="color: tomato">7.1<small>%</small></span> | 18.2<small>%</small> | 0.39 | -51.6<small>%</small> | -10.6<small>%</small> |