| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KBSTAR 고배당](/266160-vs-161510/) | <span style="color: tomato">8.4<small>%</small></span> | 17.3<small>%</small> | 0.49 | -43.4<small>%</small> | -8.9<small>%</small> |
| ARIRANG 고배당주 | <span style="color: tomato">7.2<small>%</small></span> | 18.1<small>%</small> | 0.39 | -51.5<small>%</small> | -10.8<small>%</small> |