| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX S&P글로벌인프라(합성)](/269420-vs-269530/) | <span style="color: tomato">6.6<small>%</small></span> | 15.8<small>%</small> | 0.42 | -38.4<small>%</small> | -8.1<small>%</small> |
| ARIRANG S&P글로벌인프라 | <span style="color: tomato">7.4<small>%</small></span> | 17.8<small>%</small> | 0.42 | -40.0<small>%</small> | -7.8<small>%</small> |