| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ARIRANG 미국S&P500(H)](/269540-vs-143850/) | <span style="color: tomato">11.7<small>%</small></span> | 18.4<small>%</small> | 0.64 | -35.3<small>%</small> | -5.8<small>%</small> |
| TIGER 미국S&P500선물(H) | <span style="color: tomato">10.6<small>%</small></span> | 18.2<small>%</small> | 0.58 | -35.0<small>%</small> | -6.4<small>%</small> |