| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PLUS 미국S&P500(H)](/269540-vs-448290/) | <span style="color: tomato">16.4<small>%</small></span> | 13.8<small>%</small> | 1.19 | -9.7<small>%</small> | -2.0<small>%</small> |
| TIGER 미국S&P500TR(H) | <span style="color: tomato">15.8<small>%</small></span> | 13.9<small>%</small> | 1.14 | -10.1<small>%</small> | -2.1<small>%</small> |