| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ARIRANG 미국S&P500(H)](/269540-vs-spy/) | <span style="color: tomato">12.3<small>%</small></span> | 18.4<small>%</small> | 0.67 | -35.2<small>%</small> | -5.7<small>%</small> |
| SPY | <span style="color: tomato">14.1<small>%</small></span> | 19.4<small>%</small> | 0.73 | -33.7<small>%</small> | -5.3<small>%</small> |