| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ARIRANG 미국S&P500(H)](/269540-vs-spy/) | <span style="color: tomato">12.1<small>%</small></span> | 18.5<small>%</small> | 0.65 | -35.2<small>%</small> | -5.8<small>%</small> |
| SPY | <span style="color: tomato">14.0<small>%</small></span> | 19.5<small>%</small> | 0.72 | -33.7<small>%</small> | -5.4<small>%</small> |