| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KBSTAR KQ고배당](/270800-vs-161510/) | <span style="color: tomato">5.9<small>%</small></span> | 22.2<small>%</small> | 0.27 | -47.9<small>%</small> | -16.5<small>%</small> |
| ARIRANG 고배당주 | <span style="color: tomato">5.5<small>%</small></span> | 18.3<small>%</small> | 0.30 | -51.5<small>%</small> | -11.1<small>%</small> |