| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [RISE KQ고배당](/270800-vs-161510/) | <span style="color: tomato">3.4<small>%</small></span> | 22.2<small>%</small> | 0.16 | -48.0<small>%</small> | -17.0<small>%</small> |
| PLUS 고배당주 | <span style="color: tomato">7.5<small>%</small></span> | 18.5<small>%</small> | 0.41 | -51.6<small>%</small> | -10.6<small>%</small> |