| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ACE 스마트모멘텀](/272220-vs-069500/) | <span style="color: tomato">5.8<small>%</small></span> | 18.1<small>%</small> | 0.32 | -37.6<small>%</small> | -13.9<small>%</small> |
| KODEX 200 | <span style="color: tomato">5.6<small>%</small></span> | 18.4<small>%</small> | 0.31 | -38.1<small>%</small> | -13.4<small>%</small> |