| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX MSCI모멘텀](/275280-vs-069500/) | <span style="color: tomato">4.6<small>%</small></span> | 20.5<small>%</small> | 0.22 | -43.8<small>%</small> | -16.0<small>%</small> |
| KODEX 200 | <span style="color: tomato">4.3<small>%</small></span> | 18.4<small>%</small> | 0.24 | -38.1<small>%</small> | -13.3<small>%</small> |