| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX MSCI모멘텀](/275280-vs-069500/) | <span style="color: tomato">4.1<small>%</small></span> | 20.9<small>%</small> | 0.20 | -43.8<small>%</small> | -16.0<small>%</small> |
| KODEX 200 | <span style="color: tomato">3.6<small>%</small></span> | 18.8<small>%</small> | 0.19 | -38.1<small>%</small> | -13.3<small>%</small> |