| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX MSCI모멘텀](/275280-vs-069500/) | <span style="color: tomato">6.1<small>%</small></span> | 20.3<small>%</small> | 0.30 | -43.8<small>%</small> | -16.1<small>%</small> |
| KODEX 200 | <span style="color: tomato">5.1<small>%</small></span> | 18.4<small>%</small> | 0.28 | -38.1<small>%</small> | -13.4<small>%</small> |