| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 미국S&P500배당귀족커버드콜(합성 H)](/276970-vs-161510/) | <span style="color: tomato">3.1<small>%</small></span> | 14.2<small>%</small> | 0.22 | -32.5<small>%</small> | -5.5<small>%</small> |
| ARIRANG 고배당주 | <span style="color: tomato">6.2<small>%</small></span> | 18.4<small>%</small> | 0.34 | -51.6<small>%</small> | -10.8<small>%</small> |