| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 코스피중형주](/277650-vs-226490/) | <span style="color: tomato">3.7<small>%</small></span> | 18.7<small>%</small> | 0.20 | -53.1<small>%</small> | -15.8<small>%</small> |
| KODEX 코스피 | <span style="color: tomato">4.5<small>%</small></span> | 17.5<small>%</small> | 0.25 | -41.3<small>%</small> | -13.7<small>%</small> |