| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 코스피대형주](/277640-vs-069500/) | <span style="color: tomato">5.0<small>%</small></span> | 18.1<small>%</small> | 0.28 | -38.4<small>%</small> | -13.6<small>%</small> |
| KODEX 200 | <span style="color: tomato">5.3<small>%</small></span> | 18.6<small>%</small> | 0.28 | -38.1<small>%</small> | -13.7<small>%</small> |