| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 코스피중형주](/277650-vs-226490/) | <span style="color: tomato">2.6<small>%</small></span> | 19.0<small>%</small> | 0.14 | -53.1<small>%</small> | -15.9<small>%</small> |
| KODEX 코스피 | <span style="color: tomato">4.2<small>%</small></span> | 17.6<small>%</small> | 0.24 | -41.3<small>%</small> | -13.8<small>%</small> |