| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [RISE 코스닥150선물레버리지](/278240-vs-233740/) | <span style="color: cornflowerblue">-1.7<small>%</small></span> | 64.6<small>%</small> | -0.03 | -85.9<small>%</small> | -52.9<small>%</small> |
| KODEX 코스닥150레버리지 | <span style="color: cornflowerblue">-3.8<small>%</small></span> | 57.2<small>%</small> | -0.07 | -86.0<small>%</small> | -54.8<small>%</small> |