| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KBSTAR 코스닥150선물레버리지](/278240-vs-233740/) | <span style="color: tomato">2.6<small>%</small></span> | 64.9<small>%</small> | 0.04 | -85.9<small>%</small> | -52.7<small>%</small> |
| KODEX 코스닥150레버리지 | <span style="color: tomato">0.2<small>%</small></span> | 57.4<small>%</small> | 0.00 | -86.0<small>%</small> | -54.3<small>%</small> |