| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 200TR](/278530-vs-069500/) | <span style="color: tomato">3.8<small>%</small></span> | 18.9<small>%</small> | 0.20 | -38.1<small>%</small> | -13.9<small>%</small> |
| KODEX 200 | <span style="color: tomato">3.7<small>%</small></span> | 19.1<small>%</small> | 0.19 | -38.1<small>%</small> | -13.9<small>%</small> |