| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 고배당](/279530-vs-161510/) | <span style="color: tomato">5.1<small>%</small></span> | 14.8<small>%</small> | 0.35 | -49.2<small>%</small> | -10.4<small>%</small> |
| PLUS 고배당주 | <span style="color: tomato">7.3<small>%</small></span> | 18.7<small>%</small> | 0.39 | -51.6<small>%</small> | -10.8<small>%</small> |