| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 최소변동성](/279540-vs-069500/) | <span style="color: tomato">2.9<small>%</small></span> | 16.1<small>%</small> | 0.18 | -39.2<small>%</small> | -11.4<small>%</small> |
| KODEX 200 | <span style="color: tomato">3.4<small>%</small></span> | 18.7<small>%</small> | 0.18 | -38.1<small>%</small> | -14.0<small>%</small> |