| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 고배당](/279530-vs-161510/) | <span style="color: tomato">4.9<small>%</small></span> | 14.6<small>%</small> | 0.33 | -49.2<small>%</small> | -10.5<small>%</small> |
| ARIRANG 고배당주 | <span style="color: tomato">6.7<small>%</small></span> | 18.5<small>%</small> | 0.36 | -51.6<small>%</small> | -10.9<small>%</small> |