| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 최소변동성](/279540-vs-292190/) | <span style="color: tomato">2.9<small>%</small></span> | 16.2<small>%</small> | 0.18 | -35.2<small>%</small> | -9.9<small>%</small> |
| KODEX KRX300 | <span style="color: tomato">4.4<small>%</small></span> | 19.2<small>%</small> | 0.23 | -36.8<small>%</small> | -13.2<small>%</small> |