| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 고배당](/279530-vs-161510/) | <span style="color: tomato">4.6<small>%</small></span> | 14.8<small>%</small> | 0.31 | -49.2<small>%</small> | -10.9<small>%</small> |
| ARIRANG 고배당주 | <span style="color: tomato">5.2<small>%</small></span> | 18.6<small>%</small> | 0.28 | -51.5<small>%</small> | -11.4<small>%</small> |