| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KBSTAR 중소형고배당](/281990-vs-161510/) | <span style="color: tomato">2.4<small>%</small></span> | 19.0<small>%</small> | 0.13 | -52.0<small>%</small> | -13.7<small>%</small> |
| ARIRANG 고배당주 | <span style="color: tomato">4.1<small>%</small></span> | 18.6<small>%</small> | 0.22 | -51.5<small>%</small> | -11.4<small>%</small> |