| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KBSTAR 중소형고배당](/281990-vs-161510/) | <span style="color: tomato">3.2<small>%</small></span> | 18.7<small>%</small> | 0.17 | -52.0<small>%</small> | -13.6<small>%</small> |
| ARIRANG 고배당주 | <span style="color: tomato">6.7<small>%</small></span> | 18.6<small>%</small> | 0.36 | -51.6<small>%</small> | -11.0<small>%</small> |