| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [RISE 중소형고배당](/281990-vs-161510/) | <span style="color: tomato">2.5<small>%</small></span> | 18.8<small>%</small> | 0.13 | -52.0<small>%</small> | -13.5<small>%</small> |
| PLUS 고배당주 | <span style="color: tomato">7.0<small>%</small></span> | 18.7<small>%</small> | 0.37 | -51.6<small>%</small> | -10.8<small>%</small> |