| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 200미국채혼합](/284430-vs-292190/) | <span style="color: tomato">4.2<small>%</small></span> | 6.9<small>%</small> | 0.61 | -17.0<small>%</small> | -4.7<small>%</small> |
| KODEX KRX300 | <span style="color: tomato">4.7<small>%</small></span> | 19.2<small>%</small> | 0.24 | -36.8<small>%</small> | -13.1<small>%</small> |