| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 200미국채혼합](/284430-vs-069500/) | <span style="color: tomato">3.9<small>%</small></span> | 6.9<small>%</small> | 0.57 | -17.0<small>%</small> | -5.0<small>%</small> |
| KODEX 200 | <span style="color: tomato">4.6<small>%</small></span> | 18.8<small>%</small> | 0.25 | -38.1<small>%</small> | -14.0<small>%</small> |