| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 200커버드콜ATM](/289480-vs-166400/) | <span style="color: tomato">2.4<small>%</small></span> | 13.7<small>%</small> | 0.18 | -31.4<small>%</small> | -9.4<small>%</small> |
| TIGER 200커버드콜5%OTM | <span style="color: tomato">2.1<small>%</small></span> | 16.0<small>%</small> | 0.13 | -35.2<small>%</small> | -13.8<small>%</small> |