| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 200커버드콜ATM](/289480-vs-069500/) | <span style="color: tomato">2.4<small>%</small></span> | 13.7<small>%</small> | 0.17 | -31.4<small>%</small> | -9.5<small>%</small> |
| KODEX 200 | <span style="color: tomato">5.7<small>%</small></span> | 18.9<small>%</small> | 0.30 | -35.6<small>%</small> | -13.0<small>%</small> |