| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 200커버드콜ATM](/289480-vs-069500/) | <span style="color: tomato">2.2<small>%</small></span> | 13.6<small>%</small> | 0.16 | -31.4<small>%</small> | -9.4<small>%</small> |
| KODEX 200 | <span style="color: tomato">6.0<small>%</small></span> | 18.8<small>%</small> | 0.32 | -35.6<small>%</small> | -12.9<small>%</small> |