| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KBSTAR 200고배당커버드콜ATM](/290080-vs-210780/) | <span style="color: cornflowerblue">-0.0<small>%</small></span> | 15.3<small>%</small> | -0.00 | -45.3<small>%</small> | -14.2<small>%</small> |
| TIGER 코스피고배당 | <span style="color: tomato">6.6<small>%</small></span> | 16.8<small>%</small> | 0.39 | -44.3<small>%</small> | -9.4<small>%</small> |