| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX KRX300](/292190-vs-069500/) | <span style="color: tomato">4.7<small>%</small></span> | 19.3<small>%</small> | 0.24 | -36.8<small>%</small> | -13.1<small>%</small> |
| KODEX 200 | <span style="color: tomato">4.8<small>%</small></span> | 19.0<small>%</small> | 0.26 | -35.6<small>%</small> | -13.3<small>%</small> |