| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER TOP10](/292150-vs-069500/) | <span style="color: tomato">6.3<small>%</small></span> | 21.3<small>%</small> | 0.29 | -39.7<small>%</small> | -15.9<small>%</small> |
| KODEX 200 | <span style="color: tomato">5.1<small>%</small></span> | 18.8<small>%</small> | 0.27 | -35.6<small>%</small> | -13.2<small>%</small> |