| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER TOP10](/292150-vs-292190/) | <span style="color: tomato">6.4<small>%</small></span> | 21.4<small>%</small> | 0.30 | -39.7<small>%</small> | -16.0<small>%</small> |
| KODEX KRX300 | <span style="color: tomato">4.8<small>%</small></span> | 19.2<small>%</small> | 0.25 | -36.8<small>%</small> | -13.0<small>%</small> |