| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER TOP10](/292150-vs-292190/) | <span style="color: tomato">5.4<small>%</small></span> | 21.5<small>%</small> | 0.25 | -39.7<small>%</small> | -15.9<small>%</small> |
| KODEX KRX300 | <span style="color: tomato">4.3<small>%</small></span> | 19.3<small>%</small> | 0.22 | -36.8<small>%</small> | -13.1<small>%</small> |