| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER TOP10](/292150-vs-069500/) | <span style="color: tomato">6.0<small>%</small></span> | 21.4<small>%</small> | 0.28 | -39.7<small>%</small> | -15.9<small>%</small> |
| KODEX 200 | <span style="color: tomato">5.0<small>%</small></span> | 19.0<small>%</small> | 0.27 | -35.6<small>%</small> | -13.4<small>%</small> |