| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER TOP10](/292150-vs-292190/) | <span style="color: tomato">3.6<small>%</small></span> | 21.8<small>%</small> | 0.16 | -39.7<small>%</small> | -15.9<small>%</small> |
| KODEX KRX300 | <span style="color: tomato">2.9<small>%</small></span> | 19.6<small>%</small> | 0.15 | -36.8<small>%</small> | -12.8<small>%</small> |