| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 중소형가치](/292140-vs-069500/) | <span style="color: tomato">8.4<small>%</small></span> | 22.4<small>%</small> | 0.37 | -52.0<small>%</small> | -14.2<small>%</small> |
| KODEX 200 | <span style="color: tomato">12.7<small>%</small></span> | 20.9<small>%</small> | 0.61 | -35.6<small>%</small> | -9.0<small>%</small> |