| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX KRX300](/292190-vs-069500/) | <span style="color: tomato">3.7<small>%</small></span> | 19.6<small>%</small> | 0.19 | -36.8<small>%</small> | -12.8<small>%</small> |
| KODEX 200 | <span style="color: tomato">3.8<small>%</small></span> | 19.3<small>%</small> | 0.20 | -35.6<small>%</small> | -13.1<small>%</small> |