| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX KRX300](/292190-vs-069500/) | <span style="color: tomato">5.5<small>%</small></span> | 19.1<small>%</small> | 0.29 | -36.8<small>%</small> | -12.9<small>%</small> |
| KODEX 200 | <span style="color: tomato">5.6<small>%</small></span> | 18.8<small>%</small> | 0.30 | -35.6<small>%</small> | -13.1<small>%</small> |