| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER TOP10](/292150-vs-069500/) | <span style="color: tomato">5.3<small>%</small></span> | 21.4<small>%</small> | 0.25 | -39.7<small>%</small> | -16.0<small>%</small> |
| KODEX 200 | <span style="color: tomato">4.3<small>%</small></span> | 18.9<small>%</small> | 0.23 | -35.6<small>%</small> | -13.3<small>%</small> |