| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER MSCI Korea TR](/310970-vs-069500/) | <span style="color: tomato">7.5<small>%</small></span> | 19.4<small>%</small> | 0.39 | -35.1<small>%</small> | -12.6<small>%</small> |
| KODEX 200 | <span style="color: tomato">7.7<small>%</small></span> | 19.4<small>%</small> | 0.40 | -34.6<small>%</small> | -12.1<small>%</small> |