| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER MSCI Korea TR](/310970-vs-292190/) | <span style="color: tomato">7.9<small>%</small></span> | 19.4<small>%</small> | 0.41 | -35.1<small>%</small> | -12.5<small>%</small> |
| KODEX KRX300 | <span style="color: tomato">7.7<small>%</small></span> | 19.7<small>%</small> | 0.39 | -34.9<small>%</small> | -11.5<small>%</small> |