| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER MSCI Korea TR](/310970-vs-292190/) | <span style="color: tomato">8.6<small>%</small></span> | 19.4<small>%</small> | 0.44 | -35.1<small>%</small> | -12.6<small>%</small> |
| KODEX KRX300 | <span style="color: tomato">8.5<small>%</small></span> | 19.8<small>%</small> | 0.43 | -34.9<small>%</small> | -11.7<small>%</small> |