| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 미국빅테크10(H)](/314250-vs-472160/) | <span style="color: tomato">49.2<small>%</small></span> | 28.2<small>%</small> | 1.74 | -22.1<small>%</small> | -3.5<small>%</small> |
| TIGER 미국테크TOP10 INDXX(H) | <span style="color: tomato">48.7<small>%</small></span> | 27.2<small>%</small> | 1.79 | -22.5<small>%</small> | -3.3<small>%</small> |