| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 미국빅테크10(H)](/314250-vs-381170/) | <span style="color: tomato">12.0<small>%</small></span> | 29.6<small>%</small> | 0.40 | -49.7<small>%</small> | -16.3<small>%</small> |
| TIGER 미국테크TOP10 INDXX | <span style="color: tomato">22.9<small>%</small></span> | 24.6<small>%</small> | 0.93 | -40.6<small>%</small> | -10.0<small>%</small> |