| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 미국빅테크10(H)](/314250-vs-381170/) | <span style="color: tomato">9.7<small>%</small></span> | 29.7<small>%</small> | 0.33 | -49.7<small>%</small> | -16.5<small>%</small> |
| TIGER 미국테크TOP10 INDXX | <span style="color: tomato">20.4<small>%</small></span> | 24.6<small>%</small> | 0.83 | -40.6<small>%</small> | -10.0<small>%</small> |