| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [RISE 대형고배당10TR](/315960-vs-161510/) | <span style="color: tomato">13.6<small>%</small></span> | 23.1<small>%</small> | 0.59 | -36.6<small>%</small> | -9.5<small>%</small> |
| PLUS 고배당주 | <span style="color: tomato">10.4<small>%</small></span> | 19.6<small>%</small> | 0.53 | -47.4<small>%</small> | -8.4<small>%</small> |