| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [RISE 대형고배당10TR](/315960-vs-069500/) | <span style="color: tomato">12.5<small>%</small></span> | 23.1<small>%</small> | 0.54 | -36.6<small>%</small> | -9.5<small>%</small> |
| KODEX 200 | <span style="color: tomato">7.1<small>%</small></span> | 19.9<small>%</small> | 0.36 | -34.6<small>%</small> | -12.2<small>%</small> |