| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KBSTAR 대형고배당10TR](/315960-vs-161510/) | <span style="color: tomato">13.9<small>%</small></span> | 22.6<small>%</small> | 0.61 | -36.6<small>%</small> | -10.0<small>%</small> |
| ARIRANG 고배당주 | <span style="color: tomato">7.8<small>%</small></span> | 19.6<small>%</small> | 0.40 | -47.4<small>%</small> | -8.9<small>%</small> |