| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KBSTAR 대형고배당10TR](/315960-vs-292150/) | <span style="color: tomato">14.1<small>%</small></span> | 22.6<small>%</small> | 0.62 | -36.6<small>%</small> | -9.8<small>%</small> |
| TIGER TOP10 | <span style="color: tomato">10.3<small>%</small></span> | 22.0<small>%</small> | 0.47 | -39.7<small>%</small> | -15.1<small>%</small> |