| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KBSTAR 대형고배당10TR](/315960-vs-069500/) | <span style="color: tomato">13.2<small>%</small></span> | 22.6<small>%</small> | 0.58 | -36.6<small>%</small> | -10.1<small>%</small> |
| KODEX 200 | <span style="color: tomato">7.3<small>%</small></span> | 19.7<small>%</small> | 0.37 | -34.6<small>%</small> | -12.4<small>%</small> |