| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KBSTAR KRX300미국달러선물혼합](/319870-vs-292190/) | <span style="color: tomato">12.7<small>%</small></span> | 17.2<small>%</small> | 0.74 | -28.3<small>%</small> | -6.6<small>%</small> |
| KODEX KRX300 | <span style="color: tomato">7.7<small>%</small></span> | 20.1<small>%</small> | 0.38 | -34.9<small>%</small> | -12.3<small>%</small> |