| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KBSTAR KRX300미국달러선물혼합](/319870-vs-292190/) | <span style="color: tomato">13.5<small>%</small></span> | 17.1<small>%</small> | 0.79 | -28.3<small>%</small> | -6.5<small>%</small> |
| KODEX KRX300 | <span style="color: tomato">8.2<small>%</small></span> | 20.1<small>%</small> | 0.41 | -34.9<small>%</small> | -12.2<small>%</small> |