| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KBSTAR KRX300미국달러선물혼합](/319870-vs-138230/) | <span style="color: tomato">12.7<small>%</small></span> | 17.2<small>%</small> | 0.74 | -28.3<small>%</small> | -6.6<small>%</small> |
| KOSEF 미국달러선물 | <span style="color: tomato">5.6<small>%</small></span> | 8.8<small>%</small> | 0.64 | -15.6<small>%</small> | -5.8<small>%</small> |