| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KBSTAR KRX300미국달러선물혼합](/319870-vs-292190/) | <span style="color: tomato">13.1<small>%</small></span> | 17.1<small>%</small> | 0.76 | -28.3<small>%</small> | -6.6<small>%</small> |
| KODEX KRX300 | <span style="color: tomato">7.8<small>%</small></span> | 20.1<small>%</small> | 0.39 | -34.9<small>%</small> | -12.3<small>%</small> |