| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [HANARO 고배당](/322410-vs-161510/) | <span style="color: tomato">10.3<small>%</small></span> | 18.2<small>%</small> | 0.57 | -44.3<small>%</small> | -7.0<small>%</small> |
| ARIRANG 고배당주 | <span style="color: tomato">7.4<small>%</small></span> | 19.9<small>%</small> | 0.37 | -46.7<small>%</small> | -8.8<small>%</small> |