| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [HANARO 고배당](/322410-vs-161510/) | <span style="color: tomato">9.9<small>%</small></span> | 17.9<small>%</small> | 0.55 | -44.4<small>%</small> | -6.8<small>%</small> |
| PLUS 고배당주 | <span style="color: tomato">9.2<small>%</small></span> | 19.8<small>%</small> | 0.47 | -46.8<small>%</small> | -8.4<small>%</small> |