| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [HANARO 고배당](/322410-vs-161510/) | <span style="color: tomato">8.2<small>%</small></span> | 18.2<small>%</small> | 0.45 | -44.4<small>%</small> | -6.8<small>%</small> |
| PLUS 고배당주 | <span style="color: tomato">8.0<small>%</small></span> | 20.0<small>%</small> | 0.40 | -46.8<small>%</small> | -8.4<small>%</small> |