| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ARIRANG KS밸류가중TR](/333970-vs-069500/) | <span style="color: tomato">10.8<small>%</small></span> | 20.4<small>%</small> | 0.53 | -39.4<small>%</small> | -9.7<small>%</small> |
| KODEX 200 | <span style="color: tomato">9.9<small>%</small></span> | 20.2<small>%</small> | 0.49 | -34.6<small>%</small> | -13.1<small>%</small> |