| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PLUS KS로우사이즈가중TR](/333950-vs-292190/) | <span style="color: tomato">8.5<small>%</small></span> | 21.0<small>%</small> | 0.41 | -39.7<small>%</small> | -11.0<small>%</small> |
| KODEX KRX300 | <span style="color: tomato">8.5<small>%</small></span> | 21.0<small>%</small> | 0.40 | -34.9<small>%</small> | -12.4<small>%</small> |