| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PLUS KS밸류가중TR](/333970-vs-292190/) | <span style="color: tomato">10.5<small>%</small></span> | 20.2<small>%</small> | 0.52 | -39.4<small>%</small> | -9.5<small>%</small> |
| KODEX KRX300 | <span style="color: tomato">10.0<small>%</small></span> | 20.5<small>%</small> | 0.49 | -34.9<small>%</small> | -12.4<small>%</small> |