| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ARIRANG KS모멘텀가중TR](/333960-vs-292190/) | <span style="color: tomato">9.9<small>%</small></span> | 20.6<small>%</small> | 0.48 | -35.0<small>%</small> | -13.6<small>%</small> |
| KODEX KRX300 | <span style="color: tomato">10.6<small>%</small></span> | 20.5<small>%</small> | 0.52 | -34.9<small>%</small> | -12.4<small>%</small> |