| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PLUS KS모멘텀가중TR](/333960-vs-069500/) | <span style="color: tomato">9.5<small>%</small></span> | 20.7<small>%</small> | 0.46 | -35.0<small>%</small> | -13.6<small>%</small> |
| KODEX 200 | <span style="color: tomato">10.1<small>%</small></span> | 20.1<small>%</small> | 0.51 | -34.6<small>%</small> | -13.0<small>%</small> |