| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ARIRANG KS로우사이즈가중TR](/333950-vs-069500/) | <span style="color: tomato">11.5<small>%</small></span> | 20.4<small>%</small> | 0.56 | -39.7<small>%</small> | -11.1<small>%</small> |
| KODEX 200 | <span style="color: tomato">10.4<small>%</small></span> | 20.2<small>%</small> | 0.52 | -34.6<small>%</small> | -13.1<small>%</small> |