| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ARIRANG KS로우볼가중TR](/333940-vs-292190/) | <span style="color: tomato">7.3<small>%</small></span> | 18.3<small>%</small> | 0.40 | -37.7<small>%</small> | -10.4<small>%</small> |
| KODEX KRX300 | <span style="color: tomato">10.5<small>%</small></span> | 20.6<small>%</small> | 0.51 | -34.9<small>%</small> | -12.5<small>%</small> |