| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PLUS KS로우사이즈가중TR](/333950-vs-069500/) | <span style="color: tomato">8.6<small>%</small></span> | 20.9<small>%</small> | 0.41 | -39.7<small>%</small> | -11.2<small>%</small> |
| KODEX 200 | <span style="color: tomato">8.3<small>%</small></span> | 20.6<small>%</small> | 0.40 | -34.6<small>%</small> | -13.0<small>%</small> |