| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ARIRANG KS밸류가중TR](/333970-vs-292190/) | <span style="color: tomato">10.8<small>%</small></span> | 20.4<small>%</small> | 0.53 | -39.4<small>%</small> | -9.7<small>%</small> |
| KODEX KRX300 | <span style="color: tomato">10.2<small>%</small></span> | 20.6<small>%</small> | 0.49 | -34.9<small>%</small> | -12.6<small>%</small> |