| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PLUS KS로우볼가중TR](/333940-vs-292190/) | <span style="color: tomato">6.1<small>%</small></span> | 18.7<small>%</small> | 0.32 | -37.7<small>%</small> | -10.2<small>%</small> |
| KODEX KRX300 | <span style="color: tomato">8.5<small>%</small></span> | 21.0<small>%</small> | 0.40 | -34.9<small>%</small> | -12.4<small>%</small> |