| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PLUS KS퀄리티가중TR](/333980-vs-069500/) | <span style="color: tomato">8.6<small>%</small></span> | 19.0<small>%</small> | 0.45 | -32.2<small>%</small> | -11.2<small>%</small> |
| KODEX 200 | <span style="color: tomato">9.8<small>%</small></span> | 20.1<small>%</small> | 0.49 | -34.6<small>%</small> | -13.0<small>%</small> |