| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PLUS KS밸류가중TR](/333970-vs-069500/) | <span style="color: tomato">10.2<small>%</small></span> | 20.2<small>%</small> | 0.50 | -39.4<small>%</small> | -9.5<small>%</small> |
| KODEX 200 | <span style="color: tomato">9.6<small>%</small></span> | 20.1<small>%</small> | 0.48 | -34.6<small>%</small> | -13.0<small>%</small> |