| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ARIRANG KS퀄리티가중TR](/333980-vs-292190/) | <span style="color: tomato">9.3<small>%</small></span> | 19.1<small>%</small> | 0.49 | -32.2<small>%</small> | -11.3<small>%</small> |
| KODEX KRX300 | <span style="color: tomato">10.9<small>%</small></span> | 20.5<small>%</small> | 0.53 | -34.9<small>%</small> | -12.5<small>%</small> |