| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PLUS KS퀄리티가중TR](/333980-vs-292190/) | <span style="color: tomato">7.2<small>%</small></span> | 19.5<small>%</small> | 0.37 | -32.2<small>%</small> | -11.2<small>%</small> |
| KODEX KRX300 | <span style="color: tomato">8.5<small>%</small></span> | 21.0<small>%</small> | 0.40 | -34.9<small>%</small> | -12.4<small>%</small> |