| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PLUS KS모멘텀가중TR](/333960-vs-069500/) | <span style="color: tomato">7.3<small>%</small></span> | 21.3<small>%</small> | 0.34 | -35.0<small>%</small> | -13.6<small>%</small> |
| KODEX 200 | <span style="color: tomato">8.0<small>%</small></span> | 20.6<small>%</small> | 0.39 | -34.6<small>%</small> | -13.0<small>%</small> |