| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ARIRANG KS로우볼가중TR](/333940-vs-069500/) | <span style="color: tomato">7.7<small>%</small></span> | 18.3<small>%</small> | 0.42 | -37.7<small>%</small> | -10.3<small>%</small> |
| KODEX 200 | <span style="color: tomato">10.9<small>%</small></span> | 20.1<small>%</small> | 0.54 | -34.6<small>%</small> | -13.0<small>%</small> |