| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ARIRANG KS로우볼가중TR](/333940-vs-069500/) | <span style="color: tomato">6.9<small>%</small></span> | 18.3<small>%</small> | 0.38 | -37.7<small>%</small> | -10.5<small>%</small> |
| KODEX 200 | <span style="color: tomato">10.1<small>%</small></span> | 20.2<small>%</small> | 0.50 | -34.6<small>%</small> | -13.1<small>%</small> |