| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 코스피대형주](/337140-vs-226490/) | <span style="color: tomato">8.4<small>%</small></span> | 19.7<small>%</small> | 0.43 | -34.6<small>%</small> | -13.0<small>%</small> |
| KODEX 코스피 | <span style="color: tomato">8.3<small>%</small></span> | 19.2<small>%</small> | 0.43 | -35.4<small>%</small> | -13.0<small>%</small> |