| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 코스피대형주](/337140-vs-226490/) | <span style="color: tomato">9.2<small>%</small></span> | 19.7<small>%</small> | 0.47 | -34.6<small>%</small> | -12.9<small>%</small> |
| KODEX 코스피 | <span style="color: tomato">8.9<small>%</small></span> | 19.1<small>%</small> | 0.46 | -35.4<small>%</small> | -12.9<small>%</small> |