| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 코스피대형주](/337140-vs-226490/) | <span style="color: tomato">6.2<small>%</small></span> | 20.2<small>%</small> | 0.31 | -34.6<small>%</small> | -12.9<small>%</small> |
| KODEX 코스피 | <span style="color: tomato">5.9<small>%</small></span> | 19.6<small>%</small> | 0.30 | -35.4<small>%</small> | -12.9<small>%</small> |