| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER CD금리투자KIS(합성)](/357870-vs-273130/) | <span style="color: tomato">2.2<small>%</small></span> | 0.2<small>%</small> | 9.68 | -0.1<small>%</small> | -0.0<small>%</small> |
| KODEX 종합채권(AA-이상)액티브 | <span style="color: tomato">0.4<small>%</small></span> | 3.7<small>%</small> | 0.11 | -13.2<small>%</small> | -4.1<small>%</small> |