| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 코스닥150롱코스피200숏선물](/360150-vs-069500/) | <span style="color: cornflowerblue">-0.3<small>%</small></span> | 19.8<small>%</small> | -0.01 | -27.9<small>%</small> | -15.5<small>%</small> |
| KODEX 200 | <span style="color: tomato">7.8<small>%</small></span> | 17.4<small>%</small> | 0.45 | -34.3<small>%</small> | -14.7<small>%</small> |