| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 코스닥150롱코스피200숏선물](/360150-vs-360140/) | <span style="color: cornflowerblue">-0.7<small>%</small></span> | 19.8<small>%</small> | -0.04 | -27.9<small>%</small> | -15.5<small>%</small> |
| KODEX 200롱코스닥150숏선물 | <span style="color: cornflowerblue">-2.8<small>%</small></span> | 19.6<small>%</small> | -0.14 | -38.1<small>%</small> | -17.2<small>%</small> |