| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 200롱코스닥150숏선물](/360140-vs-229200/) | <span style="color: cornflowerblue">-3.0<small>%</small></span> | 19.6<small>%</small> | -0.15 | -38.1<small>%</small> | -17.3<small>%</small> |
| KODEX 코스닥150 | <span style="color: tomato">2.0<small>%</small></span> | 27.9<small>%</small> | 0.07 | -39.3<small>%</small> | -14.3<small>%</small> |