| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 코스닥150롱코스피200숏선물](/360150-vs-360140/) | <span style="color: tomato">0.6<small>%</small></span> | 19.8<small>%</small> | 0.03 | -27.9<small>%</small> | -15.6<small>%</small> |
| KODEX 200롱코스닥150숏선물 | <span style="color: cornflowerblue">-4.2<small>%</small></span> | 19.7<small>%</small> | -0.21 | -38.1<small>%</small> | -16.9<small>%</small> |