| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 코스닥150롱코스피200숏선물](/360150-vs-229200/) | <span style="color: tomato">0.7<small>%</small></span> | 19.8<small>%</small> | 0.04 | -27.9<small>%</small> | -15.6<small>%</small> |
| KODEX 코스닥150 | <span style="color: tomato">2.9<small>%</small></span> | 28.0<small>%</small> | 0.10 | -39.3<small>%</small> | -14.4<small>%</small> |