| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 200롱코스닥150숏선물](/360140-vs-229200/) | <span style="color: cornflowerblue">-2.4<small>%</small></span> | 19.5<small>%</small> | -0.12 | -38.1<small>%</small> | -17.5<small>%</small> |
| KODEX 코스닥150 | <span style="color: tomato">3.5<small>%</small></span> | 27.7<small>%</small> | 0.13 | -39.3<small>%</small> | -14.3<small>%</small> |