| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 200롱코스닥150숏선물](/360140-vs-069500/) | <span style="color: cornflowerblue">-3.6<small>%</small></span> | 19.7<small>%</small> | -0.18 | -38.1<small>%</small> | -16.8<small>%</small> |
| KODEX 200 | <span style="color: tomato">6.3<small>%</small></span> | 17.4<small>%</small> | 0.36 | -34.3<small>%</small> | -14.9<small>%</small> |