| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 코스닥150롱코스피200숏선물](/360150-vs-069500/) | <span style="color: tomato">0.9<small>%</small></span> | 19.8<small>%</small> | 0.04 | -27.9<small>%</small> | -15.6<small>%</small> |
| KODEX 200 | <span style="color: tomato">6.3<small>%</small></span> | 17.4<small>%</small> | 0.36 | -34.3<small>%</small> | -14.9<small>%</small> |