| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 코스닥150롱코스피200숏선물](/360150-vs-229200/) | <span style="color: cornflowerblue">-0.1<small>%</small></span> | 19.8<small>%</small> | -0.00 | -27.9<small>%</small> | -15.5<small>%</small> |
| KODEX 코스닥150 | <span style="color: tomato">1.8<small>%</small></span> | 27.9<small>%</small> | 0.07 | -39.3<small>%</small> | -14.3<small>%</small> |