| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ACE 미국S&P500](/360200-vs-360750/) | <span style="color: tomato">18.3<small>%</small></span> | 14.9<small>%</small> | 1.23 | -16.7<small>%</small> | -3.9<small>%</small> |
| TIGER 미국S&P500 | <span style="color: tomato">18.2<small>%</small></span> | 14.9<small>%</small> | 1.22 | -16.7<small>%</small> | -3.9<small>%</small> |