| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ACE 미국S&P500](/360200-vs-360750/) | <span style="color: tomato">17.7<small>%</small></span> | 14.8<small>%</small> | 1.20 | -16.7<small>%</small> | -3.7<small>%</small> |
| TIGER 미국S&P500 | <span style="color: tomato">17.5<small>%</small></span> | 14.8<small>%</small> | 1.18 | -16.7<small>%</small> | -3.7<small>%</small> |