| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ACE 미국S&P500](/360200-vs-379800/) | <span style="color: tomato">17.6<small>%</small></span> | 14.4<small>%</small> | 1.22 | -16.7<small>%</small> | -3.7<small>%</small> |
| KODEX 미국S&P500TR | <span style="color: tomato">17.6<small>%</small></span> | 14.3<small>%</small> | 1.23 | -16.7<small>%</small> | -3.6<small>%</small> |