| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ACE 미국S&P500](/360200-vs-360750/) | <span style="color: tomato">19.7<small>%</small></span> | 14.6<small>%</small> | 1.35 | -16.7<small>%</small> | -3.7<small>%</small> |
| TIGER 미국S&P500 | <span style="color: tomato">19.5<small>%</small></span> | 14.7<small>%</small> | 1.33 | -16.7<small>%</small> | -3.7<small>%</small> |