| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국S&P500](/360750-vs-379800/) | <span style="color: tomato">15.5<small>%</small></span> | 14.7<small>%</small> | 1.05 | -16.7<small>%</small> | -3.8<small>%</small> |
| KODEX 미국S&P500TR | <span style="color: tomato">15.6<small>%</small></span> | 14.6<small>%</small> | 1.07 | -16.7<small>%</small> | -3.7<small>%</small> |