| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국S&P500](/360750-vs-161510/) | <span style="color: tomato">19.5<small>%</small></span> | 14.7<small>%</small> | 1.33 | -16.7<small>%</small> | -3.7<small>%</small> |
| ARIRANG 고배당주 | <span style="color: tomato">20.9<small>%</small></span> | 16.6<small>%</small> | 1.26 | -18.0<small>%</small> | -4.5<small>%</small> |