| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국S&P500](/360750-vs-161510/) | <span style="color: tomato">17.4<small>%</small></span> | 14.8<small>%</small> | 1.17 | -16.7<small>%</small> | -3.7<small>%</small> |
| PLUS 고배당주 | <span style="color: tomato">21.3<small>%</small></span> | 16.9<small>%</small> | 1.26 | -18.0<small>%</small> | -4.4<small>%</small> |