| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ACE 미국나스닥100](/367380-vs-133690/) | <span style="color: tomato">24.3<small>%</small></span> | 19.8<small>%</small> | 1.22 | -30.9<small>%</small> | -7.4<small>%</small> |
| TIGER 미국나스닥100 | <span style="color: tomato">24.3<small>%</small></span> | 19.9<small>%</small> | 1.22 | -31.0<small>%</small> | -7.4<small>%</small> |