| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ACE 미국나스닥100](/367380-vs-379810/) | <span style="color: tomato">18.2<small>%</small></span> | 19.6<small>%</small> | 0.93 | -30.9<small>%</small> | -8.1<small>%</small> |
| KODEX 미국나스닥100TR | <span style="color: tomato">18.3<small>%</small></span> | 19.6<small>%</small> | 0.93 | -31.0<small>%</small> | -8.1<small>%</small> |