| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ACE 미국나스닥100](/367380-vs-133690/) | <span style="color: tomato">22.7<small>%</small></span> | 20.2<small>%</small> | 1.13 | -30.9<small>%</small> | -7.8<small>%</small> |
| TIGER 미국나스닥100 | <span style="color: tomato">22.8<small>%</small></span> | 20.2<small>%</small> | 1.13 | -31.0<small>%</small> | -7.8<small>%</small> |