| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ACE 미국나스닥100](/367380-vs-379810/) | <span style="color: tomato">14.6<small>%</small></span> | 20.0<small>%</small> | 0.73 | -30.9<small>%</small> | -8.1<small>%</small> |
| KODEX 미국나스닥100TR | <span style="color: tomato">14.7<small>%</small></span> | 20.0<small>%</small> | 0.73 | -31.0<small>%</small> | -8.1<small>%</small> |