| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ACE 미국나스닥100](/367380-vs-379810/) | <span style="color: tomato">17.5<small>%</small></span> | 20.2<small>%</small> | 0.86 | -30.9<small>%</small> | -8.1<small>%</small> |
| KODEX 미국나스닥100TR | <span style="color: tomato">17.5<small>%</small></span> | 20.2<small>%</small> | 0.87 | -31.0<small>%</small> | -8.2<small>%</small> |