| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [RISE 미국나스닥100](/368590-vs-379810/) | <span style="color: tomato">17.9<small>%</small></span> | 19.8<small>%</small> | 0.91 | -31.0<small>%</small> | -8.1<small>%</small> |
| KODEX 미국나스닥100TR | <span style="color: tomato">18.0<small>%</small></span> | 19.7<small>%</small> | 0.91 | -31.0<small>%</small> | -8.1<small>%</small> |