| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KBSTAR 미국나스닥100](/368590-vs-133690/) | <span style="color: tomato">18.4<small>%</small></span> | 20.2<small>%</small> | 0.91 | -31.0<small>%</small> | -8.1<small>%</small> |
| TIGER 미국나스닥100 | <span style="color: tomato">18.5<small>%</small></span> | 20.2<small>%</small> | 0.92 | -31.0<small>%</small> | -8.1<small>%</small> |