| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [RISE 미국나스닥100](/368590-vs-133690/) | <span style="color: tomato">20.3<small>%</small></span> | 19.8<small>%</small> | 1.02 | -31.0<small>%</small> | -7.4<small>%</small> |
| TIGER 미국나스닥100 | <span style="color: tomato">20.4<small>%</small></span> | 19.8<small>%</small> | 1.03 | -31.0<small>%</small> | -7.4<small>%</small> |