| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [RISE 미국나스닥100](/368590-vs-379810/) | <span style="color: tomato">16.5<small>%</small></span> | 20.3<small>%</small> | 0.81 | -31.0<small>%</small> | -8.1<small>%</small> |
| KODEX 미국나스닥100TR | <span style="color: tomato">16.6<small>%</small></span> | 20.2<small>%</small> | 0.82 | -31.0<small>%</small> | -8.1<small>%</small> |