| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KBSTAR 미국나스닥100](/368590-vs-133690/) | <span style="color: tomato">19.0<small>%</small></span> | 20.1<small>%</small> | 0.95 | -31.0<small>%</small> | -7.8<small>%</small> |
| TIGER 미국나스닥100 | <span style="color: tomato">19.1<small>%</small></span> | 20.0<small>%</small> | 0.96 | -31.0<small>%</small> | -7.8<small>%</small> |