| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KBSTAR 미국S&P500](/379780-vs-360750/) | <span style="color: tomato">15.9<small>%</small></span> | 14.9<small>%</small> | 1.07 | -16.8<small>%</small> | -4.0<small>%</small> |
| TIGER 미국S&P500 | <span style="color: tomato">16.1<small>%</small></span> | 14.8<small>%</small> | 1.09 | -16.7<small>%</small> | -4.0<small>%</small> |