| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KBSTAR 미국S&P500](/379780-vs-360750/) | <span style="color: tomato">18.5<small>%</small></span> | 14.5<small>%</small> | 1.28 | -16.8<small>%</small> | -3.8<small>%</small> |
| TIGER 미국S&P500 | <span style="color: tomato">18.8<small>%</small></span> | 14.5<small>%</small> | 1.30 | -16.7<small>%</small> | -3.7<small>%</small> |