| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KBSTAR 미국S&P500](/379780-vs-360750/) | <span style="color: tomato">14.8<small>%</small></span> | 15.0<small>%</small> | 0.98 | -16.8<small>%</small> | -4.2<small>%</small> |
| TIGER 미국S&P500 | <span style="color: tomato">15.0<small>%</small></span> | 15.0<small>%</small> | 1.00 | -16.7<small>%</small> | -4.2<small>%</small> |