| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 미국S&P500TR](/379800-vs-360750/) | <span style="color: tomato">16.9<small>%</small></span> | 14.5<small>%</small> | 1.17 | -16.7<small>%</small> | -3.8<small>%</small> |
| TIGER 미국S&P500 | <span style="color: tomato">16.8<small>%</small></span> | 14.7<small>%</small> | 1.14 | -16.7<small>%</small> | -3.9<small>%</small> |