| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 미국나스닥100TR](/379810-vs-133690/) | <span style="color: tomato">19.7<small>%</small></span> | 19.7<small>%</small> | 1.00 | -31.0<small>%</small> | -8.3<small>%</small> |
| TIGER 미국나스닥100 | <span style="color: tomato">19.5<small>%</small></span> | 19.8<small>%</small> | 0.99 | -31.0<small>%</small> | -8.3<small>%</small> |