| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 미국나스닥100TR](/379810-vs-133690/) | <span style="color: tomato">16.7<small>%</small></span> | 20.2<small>%</small> | 0.83 | -31.0<small>%</small> | -9.0<small>%</small> |
| TIGER 미국나스닥100 | <span style="color: tomato">16.5<small>%</small></span> | 20.2<small>%</small> | 0.82 | -31.0<small>%</small> | -9.0<small>%</small> |