| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 미국나스닥100TR](/379810-vs-133690/) | <span style="color: tomato">17.0<small>%</small></span> | 20.0<small>%</small> | 0.85 | -31.0<small>%</small> | -8.7<small>%</small> |
| TIGER 미국나스닥100 | <span style="color: tomato">16.8<small>%</small></span> | 20.0<small>%</small> | 0.84 | -31.0<small>%</small> | -8.7<small>%</small> |