| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 미국S&P500TR](/379800-vs-360750/) | <span style="color: tomato">15.7<small>%</small></span> | 14.8<small>%</small> | 1.06 | -16.7<small>%</small> | -4.1<small>%</small> |
| TIGER 미국S&P500 | <span style="color: tomato">15.5<small>%</small></span> | 15.0<small>%</small> | 1.03 | -16.7<small>%</small> | -4.1<small>%</small> |