| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIMEFOLIO Kstock액티브](/385720-vs-069500/) | <span style="color: cornflowerblue">-1.5<small>%</small></span> | 17.3<small>%</small> | -0.08 | -31.0<small>%</small> | -15.4<small>%</small> |
| KODEX 200 | <span style="color: cornflowerblue">-2.3<small>%</small></span> | 16.8<small>%</small> | -0.13 | -34.3<small>%</small> | -18.3<small>%</small> |