| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIMEFOLIO 코스피액티브](/385720-vs-069500/) | <span style="color: tomato">0.8<small>%</small></span> | 17.3<small>%</small> | 0.04 | -31.0<small>%</small> | -14.6<small>%</small> |
| KODEX 200 | <span style="color: cornflowerblue">-1.1<small>%</small></span> | 16.7<small>%</small> | -0.06 | -34.3<small>%</small> | -17.4<small>%</small> |