| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIMEFOLIO 코스피액티브](/385720-vs-069500/) | <span style="color: tomato">1.4<small>%</small></span> | 17.3<small>%</small> | 0.08 | -31.0<small>%</small> | -14.7<small>%</small> |
| KODEX 200 | <span style="color: cornflowerblue">-0.4<small>%</small></span> | 16.7<small>%</small> | -0.03 | -34.3<small>%</small> | -17.4<small>%</small> |