| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX Fn Top10동일가중](/395170-vs-292150/) | <span style="color: cornflowerblue">-7.1<small>%</small></span> | 21.4<small>%</small> | -0.33 | -33.7<small>%</small> | -21.0<small>%</small> |
| TIGER TOP10 | <span style="color: cornflowerblue">-6.6<small>%</small></span> | 20.1<small>%</small> | -0.33 | -37.9<small>%</small> | -22.7<small>%</small> |