| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX Fn Top10동일가중](/395170-vs-292150/) | <span style="color: cornflowerblue">-6.7<small>%</small></span> | 21.2<small>%</small> | -0.31 | -33.7<small>%</small> | -20.9<small>%</small> |
| TIGER TOP10 | <span style="color: cornflowerblue">-4.8<small>%</small></span> | 20.3<small>%</small> | -0.23 | -37.9<small>%</small> | -22.3<small>%</small> |