| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ACE 미국배당다우존스](/402970-vs-458730/) | <span style="color: tomato">18.7<small>%</small></span> | 11.0<small>%</small> | 1.71 | -7.8<small>%</small> | -1.8<small>%</small> |
| TIGER 미국배당다우존스 | <span style="color: tomato">18.7<small>%</small></span> | 11.4<small>%</small> | 1.64 | -7.7<small>%</small> | -1.9<small>%</small> |