| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 미국나스닥100레버리지(합성 H)](/409820-vs-qld/) | <span style="color: tomato">3.7<small>%</small></span> | 49.0<small>%</small> | 0.07 | -63.2<small>%</small> | -32.9<small>%</small> |
| QLD | <span style="color: tomato">5.8<small>%</small></span> | 48.7<small>%</small> | 0.12 | -63.4<small>%</small> | -32.5<small>%</small> |