| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 미국나스닥100레버리지(합성 H)](/409820-vs-qld/) | <span style="color: tomato">7.0<small>%</small></span> | 49.0<small>%</small> | 0.14 | -63.2<small>%</small> | -33.0<small>%</small> |
| QLD | <span style="color: tomato">8.3<small>%</small></span> | 48.7<small>%</small> | 0.17 | -63.4<small>%</small> | -32.7<small>%</small> |