| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 미국나스닥100레버리지(합성 H)](/409820-vs-qld/) | <span style="color: cornflowerblue">-1.3<small>%</small></span> | 50.1<small>%</small> | -0.03 | -63.2<small>%</small> | -32.5<small>%</small> |
| QLD | <span style="color: tomato">0.2<small>%</small></span> | 49.1<small>%</small> | 0.00 | -63.4<small>%</small> | -32.2<small>%</small> |