| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SOL 200 Top10](/411540-vs-292150/) | <span style="color: cornflowerblue">-5.1<small>%</small></span> | 21.1<small>%</small> | -0.24 | -28.5<small>%</small> | -15.7<small>%</small> |
| TIGER TOP10 | <span style="color: cornflowerblue">-2.4<small>%</small></span> | 20.5<small>%</small> | -0.12 | -31.7<small>%</small> | -17.2<small>%</small> |