| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SOL 200 Top10](/411540-vs-292150/) | <span style="color: cornflowerblue">-5.0<small>%</small></span> | 21.0<small>%</small> | -0.24 | -28.5<small>%</small> | -15.5<small>%</small> |
| TIGER TOP10 | <span style="color: cornflowerblue">-2.3<small>%</small></span> | 20.6<small>%</small> | -0.11 | -31.7<small>%</small> | -16.6<small>%</small> |