| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SOL 200 Top10](/411540-vs-395170/) | <span style="color: cornflowerblue">-3.0<small>%</small></span> | 20.9<small>%</small> | -0.15 | -29.1<small>%</small> | -15.9<small>%</small> |
| KODEX Fn Top10동일가중 | <span style="color: cornflowerblue">-3.0<small>%</small></span> | 21.2<small>%</small> | -0.14 | -27.4<small>%</small> | -15.3<small>%</small> |