| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SOL 200 Top10](/411540-vs-395170/) | <span style="color: cornflowerblue">-5.1<small>%</small></span> | 21.0<small>%</small> | -0.24 | -28.5<small>%</small> | -15.5<small>%</small> |
| KODEX Fn Top10동일가중 | <span style="color: cornflowerblue">-5.2<small>%</small></span> | 21.4<small>%</small> | -0.24 | -26.8<small>%</small> | -14.8<small>%</small> |