| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SOL 200 Top10](/411540-vs-395170/) | <span style="color: cornflowerblue">-5.4<small>%</small></span> | 21.1<small>%</small> | -0.26 | -28.5<small>%</small> | -15.7<small>%</small> |
| KODEX Fn Top10동일가중 | <span style="color: cornflowerblue">-5.6<small>%</small></span> | 21.6<small>%</small> | -0.26 | -26.8<small>%</small> | -14.9<small>%</small> |