| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 차이나과창판STAR50(합성)](/414780-vs-416090/) | <span style="color: cornflowerblue">-18.6<small>%</small></span> | 24.5<small>%</small> | -0.76 | -51.3<small>%</small> | -29.6<small>%</small> |
| ACE 중국과창판STAR50 | <span style="color: cornflowerblue">-19.4<small>%</small></span> | 25.2<small>%</small> | -0.77 | -53.8<small>%</small> | -31.9<small>%</small> |