| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 차이나과창판STAR50(합성)](/414780-vs-416090/) | <span style="color: cornflowerblue">-19.3<small>%</small></span> | 24.3<small>%</small> | -0.79 | -50.5<small>%</small> | -27.5<small>%</small> |
| ACE 중국과창판STAR50 | <span style="color: cornflowerblue">-21.4<small>%</small></span> | 24.4<small>%</small> | -0.88 | -53.0<small>%</small> | -29.7<small>%</small> |