| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 차이나과창판STAR50(합성)](/414780-vs-416090/) | <span style="color: cornflowerblue">-21.6<small>%</small></span> | 24.3<small>%</small> | -0.89 | -50.5<small>%</small> | -28.9<small>%</small> |
| ACE 중국과창판STAR50 | <span style="color: cornflowerblue">-23.0<small>%</small></span> | 24.3<small>%</small> | -0.95 | -53.0<small>%</small> | -31.1<small>%</small> |