| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX KOFR금리액티브(합성)](/423160-vs-273130/) | <span style="color: tomato">3.3<small>%</small></span> | 0.1<small>%</small> | 24.98 | -0.0<small>%</small> | -0.0<small>%</small> |
| KODEX 종합채권(AA-이상)액티브 | <span style="color: tomato">3.8<small>%</small></span> | 4.5<small>%</small> | 0.85 | -6.9<small>%</small> | -1.3<small>%</small> |