| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIMEFOLIO 미국나스닥100액티브](/426030-vs-133690/) | <span style="color: tomato">29.1<small>%</small></span> | 24.4<small>%</small> | 1.19 | -24.6<small>%</small> | -5.6<small>%</small> |
| TIGER 미국나스닥100 | <span style="color: tomato">21.9<small>%</small></span> | 20.3<small>%</small> | 1.08 | -23.8<small>%</small> | -4.8<small>%</small> |