| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIMEFOLIO 미국나스닥100액티브](/426030-vs-133690/) | <span style="color: tomato">42.1<small>%</small></span> | 22.8<small>%</small> | 1.84 | -24.6<small>%</small> | -5.7<small>%</small> |
| TIGER 미국나스닥100 | <span style="color: tomato">29.1<small>%</small></span> | 19.7<small>%</small> | 1.48 | -23.8<small>%</small> | -5.1<small>%</small> |