| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIMEFOLIO 미국S&P500액티브](/426020-vs-360750/) | <span style="color: tomato">32.7<small>%</small></span> | 18.2<small>%</small> | 1.80 | -18.2<small>%</small> | -4.2<small>%</small> |
| TIGER 미국S&P500 | <span style="color: tomato">19.3<small>%</small></span> | 14.8<small>%</small> | 1.30 | -15.2<small>%</small> | -3.5<small>%</small> |