| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIMEFOLIO 미국S&P500액티브](/426020-vs-360750/) | <span style="color: tomato">26.5<small>%</small></span> | 18.6<small>%</small> | 1.42 | -18.2<small>%</small> | -4.1<small>%</small> |
| TIGER 미국S&P500 | <span style="color: tomato">17.8<small>%</small></span> | 14.7<small>%</small> | 1.21 | -15.2<small>%</small> | -3.3<small>%</small> |