| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIMEFOLIO 미국S&P500액티브](/426020-vs-360750/) | <span style="color: tomato">25.1<small>%</small></span> | 18.5<small>%</small> | 1.35 | -18.2<small>%</small> | -4.0<small>%</small> |
| TIGER 미국S&P500 | <span style="color: tomato">16.8<small>%</small></span> | 14.7<small>%</small> | 1.14 | -15.2<small>%</small> | -3.3<small>%</small> |