| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIMEFOLIO 미국나스닥100액티브](/426030-vs-133690/) | <span style="color: tomato">42.2<small>%</small></span> | 23.6<small>%</small> | 1.79 | -24.6<small>%</small> | -5.5<small>%</small> |
| TIGER 미국나스닥100 | <span style="color: tomato">28.7<small>%</small></span> | 19.5<small>%</small> | 1.48 | -23.8<small>%</small> | -4.8<small>%</small> |