| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국S&P500배당귀족](/429000-vs-161510/) | <span style="color: tomato">8.0<small>%</small></span> | 13.7<small>%</small> | 0.58 | -11.5<small>%</small> | -3.7<small>%</small> |
| ARIRANG 고배당주 | <span style="color: tomato">15.0<small>%</small></span> | 16.0<small>%</small> | 0.94 | -17.2<small>%</small> | -5.6<small>%</small> |