| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PLUS 미국S&P500](/429760-vs-360750/) | <span style="color: tomato">20.0<small>%</small></span> | 14.7<small>%</small> | 1.36 | -16.2<small>%</small> | -3.6<small>%</small> |
| TIGER 미국S&P500 | <span style="color: tomato">21.1<small>%</small></span> | 14.7<small>%</small> | 1.44 | -15.2<small>%</small> | -3.3<small>%</small> |