| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PLUS 미국S&P500](/429760-vs-360750/) | <span style="color: tomato">19.2<small>%</small></span> | 14.4<small>%</small> | 1.34 | -16.2<small>%</small> | -3.6<small>%</small> |
| TIGER 미국S&P500 | <span style="color: tomato">20.4<small>%</small></span> | 14.2<small>%</small> | 1.43 | -15.2<small>%</small> | -3.3<small>%</small> |