| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PLUS 미국S&P500](/429760-vs-379800/) | <span style="color: tomato">19.6<small>%</small></span> | 14.4<small>%</small> | 1.36 | -16.2<small>%</small> | -3.6<small>%</small> |
| KODEX 미국S&P500TR | <span style="color: tomato">21.0<small>%</small></span> | 14.0<small>%</small> | 1.50 | -15.0<small>%</small> | -3.2<small>%</small> |