| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [HANARO 미국S&P500](/432840-vs-379800/) | <span style="color: tomato">18.6<small>%</small></span> | 15.9<small>%</small> | 1.17 | -15.1<small>%</small> | -3.3<small>%</small> |
| KODEX 미국S&P500TR | <span style="color: tomato">19.6<small>%</small></span> | 14.4<small>%</small> | 1.37 | -15.0<small>%</small> | -3.3<small>%</small> |