| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [HANARO 미국S&P500](/432840-vs-360750/) | <span style="color: tomato">17.7<small>%</small></span> | 16.1<small>%</small> | 1.10 | -15.1<small>%</small> | -3.3<small>%</small> |
| TIGER 미국S&P500 | <span style="color: tomato">18.5<small>%</small></span> | 14.7<small>%</small> | 1.26 | -15.2<small>%</small> | -3.4<small>%</small> |