| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [HANARO 미국S&P500](/432840-vs-360750/) | <span style="color: tomato">17.8<small>%</small></span> | 15.9<small>%</small> | 1.12 | -15.1<small>%</small> | -3.3<small>%</small> |
| TIGER 미국S&P500 | <span style="color: tomato">18.9<small>%</small></span> | 14.3<small>%</small> | 1.32 | -15.2<small>%</small> | -3.3<small>%</small> |