| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [HANARO 미국S&P500](/432840-vs-360750/) | <span style="color: tomato">17.0<small>%</small></span> | 16.0<small>%</small> | 1.06 | -15.1<small>%</small> | -3.3<small>%</small> |
| TIGER 미국S&P500 | <span style="color: tomato">17.6<small>%</small></span> | 14.6<small>%</small> | 1.20 | -15.2<small>%</small> | -3.3<small>%</small> |