| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [HANARO 미국S&P500](/432840-vs-379800/) | <span style="color: tomato">17.7<small>%</small></span> | 16.1<small>%</small> | 1.10 | -15.1<small>%</small> | -3.3<small>%</small> |
| KODEX 미국S&P500TR | <span style="color: tomato">18.8<small>%</small></span> | 14.4<small>%</small> | 1.30 | -15.0<small>%</small> | -3.3<small>%</small> |