| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SOL 미국S&P500](/433330-vs-379800/) | <span style="color: tomato">23.1<small>%</small></span> | 14.2<small>%</small> | 1.63 | -15.1<small>%</small> | -3.3<small>%</small> |
| KODEX 미국S&P500TR | <span style="color: tomato">24.0<small>%</small></span> | 14.2<small>%</small> | 1.69 | -15.0<small>%</small> | -3.1<small>%</small> |