| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SOL 미국S&P500](/433330-vs-360750/) | <span style="color: tomato">21.7<small>%</small></span> | 14.2<small>%</small> | 1.53 | -15.1<small>%</small> | -3.3<small>%</small> |
| TIGER 미국S&P500 | <span style="color: tomato">22.2<small>%</small></span> | 14.4<small>%</small> | 1.54 | -15.2<small>%</small> | -3.2<small>%</small> |