| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SOL 미국S&P500](/433330-vs-360750/) | <span style="color: tomato">24.7<small>%</small></span> | 14.4<small>%</small> | 1.71 | -15.1<small>%</small> | -3.6<small>%</small> |
| TIGER 미국S&P500 | <span style="color: tomato">25.3<small>%</small></span> | 14.7<small>%</small> | 1.73 | -15.2<small>%</small> | -3.6<small>%</small> |