| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SOL 미국S&P500](/433330-vs-360750/) | <span style="color: tomato">22.7<small>%</small></span> | 14.6<small>%</small> | 1.56 | -15.1<small>%</small> | -3.7<small>%</small> |
| TIGER 미국S&P500 | <span style="color: tomato">23.3<small>%</small></span> | 14.8<small>%</small> | 1.57 | -15.2<small>%</small> | -3.7<small>%</small> |