| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SOL 미국S&P500](/433330-vs-379800/) | <span style="color: tomato">20.9<small>%</small></span> | 14.1<small>%</small> | 1.48 | -15.1<small>%</small> | -3.2<small>%</small> |
| KODEX 미국S&P500TR | <span style="color: tomato">21.7<small>%</small></span> | 14.1<small>%</small> | 1.54 | -15.0<small>%</small> | -3.1<small>%</small> |