| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 미국배당프리미엄액티브](/441640-vs-402970/) | <span style="color: tomato">12.6<small>%</small></span> | 11.6<small>%</small> | 1.09 | -12.4<small>%</small> | -3.9<small>%</small> |
| ACE 미국배당다우존스 | <span style="color: tomato">9.0<small>%</small></span> | 13.3<small>%</small> | 0.68 | -12.9<small>%</small> | -5.3<small>%</small> |