| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 미국배당프리미엄액티브](/441640-vs-402970/) | <span style="color: tomato">13.1<small>%</small></span> | 11.4<small>%</small> | 1.14 | -12.4<small>%</small> | -3.8<small>%</small> |
| ACE 미국배당다우존스 | <span style="color: tomato">9.3<small>%</small></span> | 13.1<small>%</small> | 0.71 | -12.9<small>%</small> | -5.2<small>%</small> |