| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 미국배당프리미엄액티브](/441640-vs-276970/) | <span style="color: tomato">13.3<small>%</small></span> | 11.3<small>%</small> | 1.18 | -12.4<small>%</small> | -3.7<small>%</small> |
| KODEX 미국S&P500배당귀족커버드콜(합성 H) | <span style="color: tomato">5.8<small>%</small></span> | 11.2<small>%</small> | 0.51 | -11.1<small>%</small> | -3.6<small>%</small> |