| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 미국배당프리미엄액티브](/441640-vs-429000/) | <span style="color: tomato">13.5<small>%</small></span> | 11.4<small>%</small> | 1.19 | -12.4<small>%</small> | -3.8<small>%</small> |
| TIGER 미국S&P500배당귀족 | <span style="color: tomato">8.7<small>%</small></span> | 12.9<small>%</small> | 0.68 | -11.5<small>%</small> | -3.7<small>%</small> |