| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 미국배당프리미엄액티브](/441640-vs-379800/) | <span style="color: tomato">13.6<small>%</small></span> | 11.5<small>%</small> | 1.19 | -12.4<small>%</small> | -3.9<small>%</small> |
| KODEX 미국S&P500TR | <span style="color: tomato">25.3<small>%</small></span> | 13.1<small>%</small> | 1.92 | -13.0<small>%</small> | -2.4<small>%</small> |