| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 미국배당프리미엄액티브](/441640-vs-458750/) | <span style="color: tomato">22.0<small>%</small></span> | 9.1<small>%</small> | 2.42 | -5.2<small>%</small> | -1.2<small>%</small> |
| TIGER 미국배당+3%프리미엄다우존스 | <span style="color: tomato">14.2<small>%</small></span> | 10.1<small>%</small> | 1.41 | -7.9<small>%</small> | -1.9<small>%</small> |