| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 미국배당프리미엄액티브](/441640-vs-458730/) | <span style="color: tomato">21.8<small>%</small></span> | 9.1<small>%</small> | 2.39 | -5.2<small>%</small> | -1.2<small>%</small> |
| TIGER 미국배당다우존스 | <span style="color: tomato">18.1<small>%</small></span> | 10.7<small>%</small> | 1.69 | -7.7<small>%</small> | -1.8<small>%</small> |