| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 미국배당프리미엄액티브](/441640-vs-446720/) | <span style="color: tomato">12.8<small>%</small></span> | 10.7<small>%</small> | 1.20 | -10.0<small>%</small> | -2.6<small>%</small> |
| SOL 미국배당다우존스 | <span style="color: tomato">6.6<small>%</small></span> | 12.0<small>%</small> | 0.55 | -13.3<small>%</small> | -5.8<small>%</small> |