| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 미국배당프리미엄액티브](/441640-vs-458750/) | <span style="color: tomato">18.3<small>%</small></span> | 9.5<small>%</small> | 1.92 | -6.2<small>%</small> | -1.4<small>%</small> |
| TIGER 미국배당+3%프리미엄다우존스 | <span style="color: tomato">17.2<small>%</small></span> | 10.6<small>%</small> | 1.62 | -7.9<small>%</small> | -1.9<small>%</small> |