| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국나스닥100커버드콜(합성)](/441680-vs-133690/) | <span style="color: tomato">16.4<small>%</small></span> | 11.2<small>%</small> | 1.47 | -12.0<small>%</small> | -2.1<small>%</small> |
| TIGER 미국나스닥100 | <span style="color: tomato">35.3<small>%</small></span> | 17.5<small>%</small> | 2.02 | -17.2<small>%</small> | -2.5<small>%</small> |