| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국나스닥100커버드콜(합성)](/441680-vs-133690/) | <span style="color: tomato">8.5<small>%</small></span> | 12.3<small>%</small> | 0.69 | -12.0<small>%</small> | -2.1<small>%</small> |
| TIGER 미국나스닥100 | <span style="color: tomato">22.7<small>%</small></span> | 18.4<small>%</small> | 1.23 | -17.2<small>%</small> | -2.6<small>%</small> |