| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 미국배당프리미엄액티브](/441640-vs-458730/) | <span style="color: tomato">18.3<small>%</small></span> | 9.5<small>%</small> | 1.92 | -6.2<small>%</small> | -1.4<small>%</small> |
| TIGER 미국배당다우존스 | <span style="color: tomato">20.0<small>%</small></span> | 11.4<small>%</small> | 1.76 | -7.7<small>%</small> | -1.9<small>%</small> |