| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 미국배당프리미엄액티브](/441640-vs-379800/) | <span style="color: tomato">12.2<small>%</small></span> | 11.5<small>%</small> | 1.06 | -12.4<small>%</small> | -3.9<small>%</small> |
| KODEX 미국S&P500TR | <span style="color: tomato">24.2<small>%</small></span> | 13.2<small>%</small> | 1.83 | -13.0<small>%</small> | -2.5<small>%</small> |