| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 미국배당프리미엄액티브](/441640-vs-458730/) | <span style="color: tomato">21.5<small>%</small></span> | 9.2<small>%</small> | 2.35 | -5.2<small>%</small> | -1.2<small>%</small> |
| TIGER 미국배당다우존스 | <span style="color: tomato">17.9<small>%</small></span> | 10.8<small>%</small> | 1.66 | -7.7<small>%</small> | -1.8<small>%</small> |