| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 미국배당프리미엄액티브](/441640-vs-161510/) | <span style="color: tomato">13.3<small>%</small></span> | 11.3<small>%</small> | 1.18 | -12.4<small>%</small> | -3.7<small>%</small> |
| PLUS 고배당주 | <span style="color: tomato">29.5<small>%</small></span> | 15.7<small>%</small> | 1.87 | -10.8<small>%</small> | -3.2<small>%</small> |