| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국나스닥100커버드콜(합성)](/441680-vs-133690/) | <span style="color: tomato">14.5<small>%</small></span> | 11.5<small>%</small> | 1.26 | -12.0<small>%</small> | -2.2<small>%</small> |
| TIGER 미국나스닥100 | <span style="color: tomato">31.2<small>%</small></span> | 17.9<small>%</small> | 1.74 | -17.2<small>%</small> | -2.7<small>%</small> |