| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 미국배당프리미엄액티브](/441640-vs-379800/) | <span style="color: tomato">12.8<small>%</small></span> | 11.4<small>%</small> | 1.12 | -12.4<small>%</small> | -3.8<small>%</small> |
| KODEX 미국S&P500TR | <span style="color: tomato">24.6<small>%</small></span> | 13.1<small>%</small> | 1.88 | -13.0<small>%</small> | -2.4<small>%</small> |