| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 미국배당프리미엄액티브](/441640-vs-402970/) | <span style="color: tomato">11.8<small>%</small></span> | 11.5<small>%</small> | 1.03 | -12.4<small>%</small> | -3.7<small>%</small> |
| ACE 미국배당다우존스 | <span style="color: tomato">9.9<small>%</small></span> | 13.2<small>%</small> | 0.75 | -12.9<small>%</small> | -5.0<small>%</small> |