| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIMEFOLIO Korea플러스배당액티브](/441800-vs-069500/) | <span style="color: tomato">30.3<small>%</small></span> | 18.2<small>%</small> | 1.67 | -13.3<small>%</small> | -2.8<small>%</small> |
| KODEX 200 | <span style="color: tomato">16.0<small>%</small></span> | 18.3<small>%</small> | 0.87 | -16.5<small>%</small> | -3.1<small>%</small> |