| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIMEFOLIO Korea플러스배당액티브](/441800-vs-161510/) | <span style="color: tomato">28.2<small>%</small></span> | 17.0<small>%</small> | 1.66 | -10.0<small>%</small> | -2.7<small>%</small> |
| PLUS 고배당주 | <span style="color: tomato">28.6<small>%</small></span> | 15.9<small>%</small> | 1.80 | -10.8<small>%</small> | -3.2<small>%</small> |