| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIMEFOLIO Korea플러스배당액티브](/441800-vs-315960/) | <span style="color: tomato">28.9<small>%</small></span> | 16.6<small>%</small> | 1.74 | -10.0<small>%</small> | -2.7<small>%</small> |
| RISE 대형고배당10TR | <span style="color: tomato">30.6<small>%</small></span> | 19.8<small>%</small> | 1.55 | -11.9<small>%</small> | -2.8<small>%</small> |