| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIMEFOLIO Korea플러스배당액티브](/441800-vs-069500/) | <span style="color: tomato">31.3<small>%</small></span> | 16.5<small>%</small> | 1.90 | -10.0<small>%</small> | -2.7<small>%</small> |
| KODEX 200 | <span style="color: tomato">18.9<small>%</small></span> | 16.6<small>%</small> | 1.14 | -12.6<small>%</small> | -2.9<small>%</small> |