| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIMEFOLIO Korea플러스배당액티브](/441800-vs-161510/) | <span style="color: tomato">26.8<small>%</small></span> | 18.3<small>%</small> | 1.47 | -13.3<small>%</small> | -2.9<small>%</small> |
| PLUS 고배당주 | <span style="color: tomato">27.7<small>%</small></span> | 16.7<small>%</small> | 1.66 | -10.8<small>%</small> | -3.2<small>%</small> |