| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIMEFOLIO Korea플러스배당액티브](/441800-vs-161510/) | <span style="color: tomato">26.0<small>%</small></span> | 18.5<small>%</small> | 1.41 | -13.3<small>%</small> | -2.9<small>%</small> |
| PLUS 고배당주 | <span style="color: tomato">25.3<small>%</small></span> | 16.8<small>%</small> | 1.50 | -10.8<small>%</small> | -3.3<small>%</small> |