| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIMEFOLIO Korea플러스배당액티브](/441800-vs-315960/) | <span style="color: tomato">28.6<small>%</small></span> | 18.1<small>%</small> | 1.58 | -13.3<small>%</small> | -2.8<small>%</small> |
| RISE 대형고배당10TR | <span style="color: tomato">26.3<small>%</small></span> | 21.6<small>%</small> | 1.22 | -21.5<small>%</small> | -3.4<small>%</small> |