| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIMEFOLIO Korea플러스배당액티브](/441800-vs-069500/) | <span style="color: tomato">25.0<small>%</small></span> | 18.4<small>%</small> | 1.36 | -13.3<small>%</small> | -2.9<small>%</small> |
| KODEX 200 | <span style="color: tomato">11.0<small>%</small></span> | 18.4<small>%</small> | 0.59 | -16.5<small>%</small> | -3.5<small>%</small> |