| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [마이티 다이나믹퀀트액티브](/442260-vs-069500/) | <span style="color: tomato">22.4<small>%</small></span> | 16.0<small>%</small> | 1.40 | -10.7<small>%</small> | -2.6<small>%</small> |
| KODEX 200 | <span style="color: tomato">20.3<small>%</small></span> | 16.5<small>%</small> | 1.23 | -12.6<small>%</small> | -3.0<small>%</small> |