| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [마이티 다이나믹퀀트액티브](/442260-vs-069500/) | <span style="color: tomato">22.7<small>%</small></span> | 15.9<small>%</small> | 1.43 | -10.7<small>%</small> | -2.5<small>%</small> |
| KODEX 200 | <span style="color: tomato">20.9<small>%</small></span> | 16.4<small>%</small> | 1.27 | -12.6<small>%</small> | -2.9<small>%</small> |