| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [마이티 다이나믹퀀트액티브](/442260-vs-069500/) | <span style="color: tomato">20.1<small>%</small></span> | 15.9<small>%</small> | 1.26 | -10.7<small>%</small> | -2.6<small>%</small> |
| KODEX 200 | <span style="color: tomato">17.6<small>%</small></span> | 16.6<small>%</small> | 1.06 | -12.6<small>%</small> | -3.1<small>%</small> |