| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [WOORI 미국S&P500](/444490-vs-379800/) | <span style="color: tomato">19.2<small>%</small></span> | 15.6<small>%</small> | 1.23 | -12.7<small>%</small> | -2.5<small>%</small> |
| KODEX 미국S&P500TR | <span style="color: tomato">19.7<small>%</small></span> | 13.5<small>%</small> | 1.46 | -13.0<small>%</small> | -2.6<small>%</small> |