| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [WOORI 미국S&P500](/444490-vs-379800/) | <span style="color: tomato">20.4<small>%</small></span> | 15.6<small>%</small> | 1.31 | -12.7<small>%</small> | -2.5<small>%</small> |
| KODEX 미국S&P500TR | <span style="color: tomato">20.9<small>%</small></span> | 13.4<small>%</small> | 1.55 | -13.0<small>%</small> | -2.5<small>%</small> |