| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [WON 미국S&P500](/444490-vs-360750/) | <span style="color: tomato">21.3<small>%</small></span> | 15.6<small>%</small> | 1.36 | -12.7<small>%</small> | -2.6<small>%</small> |
| TIGER 미국S&P500 | <span style="color: tomato">21.5<small>%</small></span> | 13.6<small>%</small> | 1.57 | -13.4<small>%</small> | -2.7<small>%</small> |