| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [WOORI 미국S&P500](/444490-vs-360750/) | <span style="color: tomato">18.8<small>%</small></span> | 15.7<small>%</small> | 1.20 | -12.7<small>%</small> | -2.5<small>%</small> |
| TIGER 미국S&P500 | <span style="color: tomato">19.1<small>%</small></span> | 13.7<small>%</small> | 1.40 | -13.4<small>%</small> | -2.6<small>%</small> |