| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [WOORI 미국S&P500](/444490-vs-379800/) | <span style="color: tomato">18.8<small>%</small></span> | 15.7<small>%</small> | 1.20 | -12.7<small>%</small> | -2.5<small>%</small> |
| KODEX 미국S&P500TR | <span style="color: tomato">19.3<small>%</small></span> | 13.5<small>%</small> | 1.43 | -13.0<small>%</small> | -2.5<small>%</small> |