| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SOL 미국배당다우존스](/446720-vs-402970/) | <span style="color: tomato">9.0<small>%</small></span> | 12.2<small>%</small> | 0.74 | -13.3<small>%</small> | -5.4<small>%</small> |
| ACE 미국배당다우존스 | <span style="color: tomato">9.6<small>%</small></span> | 12.6<small>%</small> | 0.76 | -12.9<small>%</small> | -5.1<small>%</small> |