| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SOL 미국배당다우존스](/446720-vs-402970/) | <span style="color: tomato">7.5<small>%</small></span> | 12.1<small>%</small> | 0.62 | -13.3<small>%</small> | -6.2<small>%</small> |
| ACE 미국배당다우존스 | <span style="color: tomato">7.7<small>%</small></span> | 12.6<small>%</small> | 0.61 | -12.9<small>%</small> | -5.8<small>%</small> |