| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SOL 미국배당다우존스](/446720-vs-458730/) | <span style="color: tomato">23.6<small>%</small></span> | 11.2<small>%</small> | 2.11 | -7.8<small>%</small> | -1.8<small>%</small> |
| TIGER 미국배당다우존스 | <span style="color: tomato">23.5<small>%</small></span> | 11.6<small>%</small> | 2.03 | -7.7<small>%</small> | -1.8<small>%</small> |