| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SOL 미국배당다우존스](/446720-vs-402970/) | <span style="color: tomato">8.5<small>%</small></span> | 12.0<small>%</small> | 0.71 | -13.3<small>%</small> | -5.8<small>%</small> |
| ACE 미국배당다우존스 | <span style="color: tomato">9.2<small>%</small></span> | 12.4<small>%</small> | 0.74 | -12.9<small>%</small> | -5.4<small>%</small> |