| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ACE 주주환원가치주액티브](/447430-vs-292190/) | <span style="color: tomato">14.0<small>%</small></span> | 12.3<small>%</small> | 1.14 | -6.5<small>%</small> | -2.2<small>%</small> |
| KODEX KRX300 | <span style="color: tomato">15.7<small>%</small></span> | 16.3<small>%</small> | 0.96 | -13.7<small>%</small> | -3.2<small>%</small> |