| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ACE 주주환원가치주액티브](/447430-vs-069500/) | <span style="color: tomato">15.9<small>%</small></span> | 12.7<small>%</small> | 1.25 | -6.5<small>%</small> | -2.3<small>%</small> |
| KODEX 200 | <span style="color: tomato">14.2<small>%</small></span> | 16.2<small>%</small> | 0.88 | -12.6<small>%</small> | -3.3<small>%</small> |