| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ACE 주주환원가치주액티브](/447430-vs-069500/) | <span style="color: tomato">9.8<small>%</small></span> | 13.2<small>%</small> | 0.75 | -12.0<small>%</small> | -2.4<small>%</small> |
| KODEX 200 | <span style="color: tomato">7.5<small>%</small></span> | 18.0<small>%</small> | 0.42 | -16.5<small>%</small> | -3.2<small>%</small> |