| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ACE 주주환원가치주액티브](/447430-vs-292190/) | <span style="color: tomato">13.4<small>%</small></span> | 12.1<small>%</small> | 1.11 | -6.5<small>%</small> | -2.3<small>%</small> |
| KODEX KRX300 | <span style="color: tomato">17.3<small>%</small></span> | 16.2<small>%</small> | 1.07 | -13.7<small>%</small> | -3.1<small>%</small> |