| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ACE 주주환원가치주액티브](/447430-vs-292190/) | <span style="color: tomato">14.3<small>%</small></span> | 12.6<small>%</small> | 1.14 | -6.5<small>%</small> | -2.2<small>%</small> |
| KODEX KRX300 | <span style="color: tomato">12.8<small>%</small></span> | 16.1<small>%</small> | 0.79 | -13.7<small>%</small> | -3.3<small>%</small> |