| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ACE 주주환원가치주액티브](/447430-vs-069500/) | <span style="color: tomato">14.5<small>%</small></span> | 12.2<small>%</small> | 1.19 | -6.5<small>%</small> | -2.2<small>%</small> |
| KODEX 200 | <span style="color: tomato">14.1<small>%</small></span> | 16.2<small>%</small> | 0.87 | -12.6<small>%</small> | -3.1<small>%</small> |