| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ACE 주주환원가치주액티브](/447430-vs-441800/) | <span style="color: tomato">14.4<small>%</small></span> | 13.3<small>%</small> | 1.08 | -12.0<small>%</small> | -2.6<small>%</small> |
| TIMEFOLIO Korea플러스배당액티브 | <span style="color: tomato">25.5<small>%</small></span> | 18.6<small>%</small> | 1.37 | -13.3<small>%</small> | -3.0<small>%</small> |