| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ACE 주주환원가치주액티브](/447430-vs-161510/) | <span style="color: tomato">14.2<small>%</small></span> | 13.3<small>%</small> | 1.07 | -12.0<small>%</small> | -2.6<small>%</small> |
| PLUS 고배당주 | <span style="color: tomato">24.5<small>%</small></span> | 16.9<small>%</small> | 1.45 | -10.8<small>%</small> | -3.5<small>%</small> |