| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국S&P500TR(H)](/448290-vs-269540/) | <span style="color: tomato">16.2<small>%</small></span> | 13.8<small>%</small> | 1.17 | -10.1<small>%</small> | -2.1<small>%</small> |
| PLUS 미국S&P500(H) | <span style="color: tomato">16.8<small>%</small></span> | 13.7<small>%</small> | 1.22 | -9.7<small>%</small> | -2.0<small>%</small> |