| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국나스닥100TR(H)](/448300-vs-qqq/) | <span style="color: tomato">32.3<small>%</small></span> | 19.2<small>%</small> | 1.68 | -11.2<small>%</small> | -2.5<small>%</small> |
| QQQ | <span style="color: tomato">34.4<small>%</small></span> | 18.3<small>%</small> | 1.88 | -11.2<small>%</small> | -2.3<small>%</small> |