| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국나스닥100TR(H)](/448300-vs-qqq/) | <span style="color: tomato">27.2<small>%</small></span> | 20.6<small>%</small> | 1.32 | -15.8<small>%</small> | -2.7<small>%</small> |
| QQQ | <span style="color: tomato">33.0<small>%</small></span> | 18.8<small>%</small> | 1.75 | -13.6<small>%</small> | -2.6<small>%</small> |