| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국나스닥100TR(H)](/448300-vs-304940/) | <span style="color: tomato">25.6<small>%</small></span> | 20.3<small>%</small> | 1.26 | -15.8<small>%</small> | -2.9<small>%</small> |
| KODEX 미국나스닥100선물(H) | <span style="color: tomato">23.9<small>%</small></span> | 19.6<small>%</small> | 1.22 | -15.9<small>%</small> | -3.0<small>%</small> |