| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국나스닥100TR(H)](/448300-vs-304940/) | <span style="color: tomato">22.8<small>%</small></span> | 19.8<small>%</small> | 1.15 | -15.8<small>%</small> | -2.6<small>%</small> |
| KODEX 미국나스닥100선물(H) | <span style="color: tomato">21.1<small>%</small></span> | 19.1<small>%</small> | 1.11 | -15.9<small>%</small> | -2.7<small>%</small> |