| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국나스닥100TR(H)](/448300-vs-304940/) | <span style="color: tomato">30.8<small>%</small></span> | 20.3<small>%</small> | 1.52 | -15.8<small>%</small> | -2.7<small>%</small> |
| KODEX 미국나스닥100선물(H) | <span style="color: tomato">29.1<small>%</small></span> | 19.6<small>%</small> | 1.49 | -15.9<small>%</small> | -2.8<small>%</small> |