| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국나스닥100TR(H)](/448300-vs-qqq/) | <span style="color: tomato">31.2<small>%</small></span> | 19.5<small>%</small> | 1.60 | -11.2<small>%</small> | -2.6<small>%</small> |
| QQQ | <span style="color: tomato">36.1<small>%</small></span> | 18.2<small>%</small> | 1.98 | -11.2<small>%</small> | -2.4<small>%</small> |