| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 미국나스닥100(H)](/449190-vs-448300/) | <span style="color: tomato">29.3<small>%</small></span> | 19.6<small>%</small> | 1.50 | -15.9<small>%</small> | -2.9<small>%</small> |
| TIGER 미국나스닥100TR(H) | <span style="color: tomato">29.5<small>%</small></span> | 20.0<small>%</small> | 1.48 | -15.8<small>%</small> | -2.9<small>%</small> |