| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 미국나스닥100(H)](/449190-vs-304940/) | <span style="color: tomato">26.2<small>%</small></span> | 19.5<small>%</small> | 1.35 | -15.9<small>%</small> | -2.6<small>%</small> |
| KODEX 미국나스닥100선물(H) | <span style="color: tomato">24.7<small>%</small></span> | 19.2<small>%</small> | 1.28 | -15.9<small>%</small> | -2.7<small>%</small> |