| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 미국S&P500(H)](/449180-vs-143850/) | <span style="color: tomato">17.2<small>%</small></span> | 15.4<small>%</small> | 1.12 | -10.8<small>%</small> | -2.3<small>%</small> |
| TIGER 미국S&P500선물(H) | <span style="color: tomato">14.6<small>%</small></span> | 13.7<small>%</small> | 1.07 | -10.6<small>%</small> | -2.2<small>%</small> |