| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 미국S&P500(H)](/449180-vs-448290/) | <span style="color: tomato">18.8<small>%</small></span> | 15.4<small>%</small> | 1.22 | -10.8<small>%</small> | -2.3<small>%</small> |
| TIGER 미국S&P500TR(H) | <span style="color: tomato">18.9<small>%</small></span> | 13.7<small>%</small> | 1.38 | -10.1<small>%</small> | -2.0<small>%</small> |