| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 미국나스닥100(H)](/449190-vs-304940/) | <span style="color: tomato">26.6<small>%</small></span> | 19.6<small>%</small> | 1.36 | -15.9<small>%</small> | -2.8<small>%</small> |
| KODEX 미국나스닥100선물(H) | <span style="color: tomato">25.1<small>%</small></span> | 19.3<small>%</small> | 1.30 | -15.9<small>%</small> | -2.9<small>%</small> |