| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 미국S&P500(H)](/449180-vs-269540/) | <span style="color: tomato">17.1<small>%</small></span> | 15.4<small>%</small> | 1.11 | -10.8<small>%</small> | -2.4<small>%</small> |
| PLUS 미국S&P500(H) | <span style="color: tomato">17.6<small>%</small></span> | 13.6<small>%</small> | 1.29 | -9.7<small>%</small> | -2.0<small>%</small> |