| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 미국S&P500(H)](/449180-vs-269540/) | <span style="color: tomato">18.3<small>%</small></span> | 15.5<small>%</small> | 1.18 | -10.8<small>%</small> | -2.4<small>%</small> |
| PLUS 미국S&P500(H) | <span style="color: tomato">18.8<small>%</small></span> | 13.7<small>%</small> | 1.37 | -9.7<small>%</small> | -2.0<small>%</small> |