| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 미국나스닥100(H)](/449190-vs-304940/) | <span style="color: tomato">29.1<small>%</small></span> | 18.1<small>%</small> | 1.61 | -11.0<small>%</small> | -2.5<small>%</small> |
| KODEX 미국나스닥100선물(H) | <span style="color: tomato">27.6<small>%</small></span> | 17.8<small>%</small> | 1.55 | -11.3<small>%</small> | -2.5<small>%</small> |