| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 미국S&P500(H)](/449180-vs-448290/) | <span style="color: tomato">15.9<small>%</small></span> | 15.4<small>%</small> | 1.03 | -10.8<small>%</small> | -2.4<small>%</small> |
| TIGER 미국S&P500TR(H) | <span style="color: tomato">16.1<small>%</small></span> | 13.7<small>%</small> | 1.18 | -10.1<small>%</small> | -2.0<small>%</small> |