| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KOSEF 미국S&P500](/449770-vs-379800/) | <span style="color: tomato">27.7<small>%</small></span> | 12.2<small>%</small> | 2.27 | -8.8<small>%</small> | -1.1<small>%</small> |
| KODEX 미국S&P500TR | <span style="color: tomato">27.4<small>%</small></span> | 12.0<small>%</small> | 2.28 | -8.9<small>%</small> | -1.1<small>%</small> |