| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KOSEF 미국S&P500](/449770-vs-360750/) | <span style="color: tomato">30.8<small>%</small></span> | 12.4<small>%</small> | 2.48 | -8.8<small>%</small> | -1.3<small>%</small> |
| TIGER 미국S&P500 | <span style="color: tomato">30.6<small>%</small></span> | 12.5<small>%</small> | 2.45 | -9.1<small>%</small> | -1.3<small>%</small> |