| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KOSEF 미국S&P500(H)](/449780-vs-143850/) | <span style="color: tomato">24.6<small>%</small></span> | 13.4<small>%</small> | 1.84 | -10.1<small>%</small> | -1.8<small>%</small> |
| TIGER 미국S&P500선물(H) | <span style="color: tomato">21.2<small>%</small></span> | 13.4<small>%</small> | 1.59 | -10.6<small>%</small> | -2.0<small>%</small> |