| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KOSEF 미국S&P500](/449770-vs-360750/) | <span style="color: tomato">28.8<small>%</small></span> | 12.2<small>%</small> | 2.36 | -8.8<small>%</small> | -1.2<small>%</small> |
| TIGER 미국S&P500 | <span style="color: tomato">28.8<small>%</small></span> | 12.3<small>%</small> | 2.34 | -9.1<small>%</small> | -1.2<small>%</small> |