| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KOSEF 미국S&P500(H)](/449780-vs-269540/) | <span style="color: tomato">22.5<small>%</small></span> | 13.4<small>%</small> | 1.68 | -10.1<small>%</small> | -1.8<small>%</small> |
| PLUS 미국S&P500(H) | <span style="color: tomato">22.3<small>%</small></span> | 13.3<small>%</small> | 1.67 | -9.7<small>%</small> | -1.7<small>%</small> |