| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KOSEF 미국S&P500(H)](/449780-vs-143850/) | <span style="color: tomato">25.8<small>%</small></span> | 13.5<small>%</small> | 1.91 | -10.1<small>%</small> | -1.8<small>%</small> |
| TIGER 미국S&P500선물(H) | <span style="color: tomato">22.2<small>%</small></span> | 13.5<small>%</small> | 1.65 | -10.6<small>%</small> | -2.0<small>%</small> |