| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KOSEF 미국S&P500](/449770-vs-379800/) | <span style="color: tomato">30.2<small>%</small></span> | 12.4<small>%</small> | 2.44 | -8.8<small>%</small> | -1.3<small>%</small> |
| KODEX 미국S&P500TR | <span style="color: tomato">30.1<small>%</small></span> | 12.2<small>%</small> | 2.47 | -8.9<small>%</small> | -1.3<small>%</small> |