| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KOSEF 미국S&P500(H)](/449780-vs-143850/) | <span style="color: tomato">25.5<small>%</small></span> | 13.4<small>%</small> | 1.90 | -10.1<small>%</small> | -1.8<small>%</small> |
| TIGER 미국S&P500선물(H) | <span style="color: tomato">22.1<small>%</small></span> | 13.4<small>%</small> | 1.66 | -10.6<small>%</small> | -1.9<small>%</small> |