| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KOSEF 미국S&P500(H)](/449780-vs-448290/) | <span style="color: tomato">23.9<small>%</small></span> | 13.5<small>%</small> | 1.77 | -10.1<small>%</small> | -1.8<small>%</small> |
| TIGER 미국S&P500TR(H) | <span style="color: tomato">23.3<small>%</small></span> | 13.4<small>%</small> | 1.73 | -10.1<small>%</small> | -1.8<small>%</small> |