| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [1Q K200액티브](/451060-vs-069500/) | <span style="color: tomato">7.3<small>%</small></span> | 18.0<small>%</small> | 0.41 | -16.4<small>%</small> | -3.9<small>%</small> |
| KODEX 200 | <span style="color: tomato">7.9<small>%</small></span> | 18.2<small>%</small> | 0.44 | -16.5<small>%</small> | -3.8<small>%</small> |