| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SOL 미국배당다우존스(H)](/452360-vs-446720/) | <span style="color: tomato">11.5<small>%</small></span> | 11.7<small>%</small> | 0.98 | -10.9<small>%</small> | -2.8<small>%</small> |
| SOL 미국배당다우존스 | <span style="color: tomato">15.8<small>%</small></span> | 11.7<small>%</small> | 1.36 | -7.9<small>%</small> | -2.2<small>%</small> |