| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KOSEF 미국나스닥100(H)](/453080-vs-304940/) | <span style="color: tomato">39.5<small>%</small></span> | 18.6<small>%</small> | 2.13 | -16.0<small>%</small> | -2.2<small>%</small> |
| KODEX 미국나스닥100선물(H) | <span style="color: tomato">35.1<small>%</small></span> | 18.2<small>%</small> | 1.93 | -15.9<small>%</small> | -2.4<small>%</small> |