| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KOSEF 미국나스닥100(H)](/453080-vs-448300/) | <span style="color: tomato">34.0<small>%</small></span> | 18.4<small>%</small> | 1.84 | -16.0<small>%</small> | -2.2<small>%</small> |
| TIGER 미국나스닥100TR(H) | <span style="color: tomato">33.4<small>%</small></span> | 19.0<small>%</small> | 1.76 | -15.8<small>%</small> | -2.3<small>%</small> |