| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KOSEF 미국나스닥100(H)](/453080-vs-448300/) | <span style="color: tomato">38.6<small>%</small></span> | 18.5<small>%</small> | 2.08 | -16.0<small>%</small> | -2.3<small>%</small> |
| TIGER 미국나스닥100TR(H) | <span style="color: tomato">38.0<small>%</small></span> | 19.0<small>%</small> | 2.00 | -15.8<small>%</small> | -2.4<small>%</small> |