| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KOSEF 미국나스닥100(H)](/453080-vs-304940/) | <span style="color: tomato">34.3<small>%</small></span> | 18.4<small>%</small> | 1.86 | -16.0<small>%</small> | -2.2<small>%</small> |
| KODEX 미국나스닥100선물(H) | <span style="color: tomato">29.8<small>%</small></span> | 18.0<small>%</small> | 1.65 | -15.9<small>%</small> | -2.4<small>%</small> |