| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KOSEF 미국나스닥100(H)](/453080-vs-304940/) | <span style="color: tomato">39.8<small>%</small></span> | 16.6<small>%</small> | 2.40 | -10.5<small>%</small> | -2.0<small>%</small> |
| KODEX 미국나스닥100선물(H) | <span style="color: tomato">35.3<small>%</small></span> | 16.2<small>%</small> | 2.17 | -11.3<small>%</small> | -2.2<small>%</small> |