| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [RISE 미국S&P500(H)](/453330-vs-143850/) | <span style="color: tomato">24.3<small>%</small></span> | 12.5<small>%</small> | 1.95 | -10.4<small>%</small> | -1.8<small>%</small> |
| TIGER 미국S&P500선물(H) | <span style="color: tomato">21.0<small>%</small></span> | 12.4<small>%</small> | 1.69 | -10.6<small>%</small> | -1.9<small>%</small> |