| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [RISE 미국S&P500(H)](/453330-vs-448290/) | <span style="color: tomato">22.6<small>%</small></span> | 12.3<small>%</small> | 1.84 | -10.4<small>%</small> | -1.8<small>%</small> |
| TIGER 미국S&P500TR(H) | <span style="color: tomato">22.3<small>%</small></span> | 12.2<small>%</small> | 1.83 | -10.1<small>%</small> | -1.7<small>%</small> |