| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 인도니프티50](/453870-vs-200250/) | <span style="color: tomato">29.0<small>%</small></span> | 13.2<small>%</small> | 2.21 | -6.5<small>%</small> | -1.4<small>%</small> |
| KOSEF 인도Nifty50(합성) | <span style="color: tomato">28.6<small>%</small></span> | 12.8<small>%</small> | 2.22 | -6.3<small>%</small> | -1.5<small>%</small> |