| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 인도니프티50](/453870-vs-453810/) | <span style="color: tomato">26.0<small>%</small></span> | 13.2<small>%</small> | 1.97 | -6.5<small>%</small> | -1.5<small>%</small> |
| KODEX 인도Nifty50 | <span style="color: tomato">26.4<small>%</small></span> | 13.5<small>%</small> | 1.95 | -6.3<small>%</small> | -1.5<small>%</small> |