| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 인도Nifty50](/453810-vs-200250/) | <span style="color: tomato">26.4<small>%</small></span> | 13.6<small>%</small> | 1.94 | -6.3<small>%</small> | -1.5<small>%</small> |
| KOSEF 인도Nifty50(합성) | <span style="color: tomato">25.2<small>%</small></span> | 13.0<small>%</small> | 1.94 | -6.3<small>%</small> | -1.5<small>%</small> |