| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 인도니프티50](/453870-vs-453810/) | <span style="color: tomato">27.3<small>%</small></span> | 13.4<small>%</small> | 2.04 | -6.5<small>%</small> | -1.4<small>%</small> |
| KODEX 인도Nifty50 | <span style="color: tomato">27.9<small>%</small></span> | 13.7<small>%</small> | 2.03 | -6.3<small>%</small> | -1.4<small>%</small> |