| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 인도니프티50](/453870-vs-200250/) | <span style="color: tomato">25.9<small>%</small></span> | 13.1<small>%</small> | 1.97 | -6.5<small>%</small> | -1.5<small>%</small> |
| KOSEF 인도Nifty50(합성) | <span style="color: tomato">25.3<small>%</small></span> | 12.9<small>%</small> | 1.97 | -6.3<small>%</small> | -1.5<small>%</small> |