| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 인도니프티50](/453870-vs-453810/) | <span style="color: tomato">26.6<small>%</small></span> | 13.3<small>%</small> | 2.00 | -6.5<small>%</small> | -1.5<small>%</small> |
| KODEX 인도Nifty50 | <span style="color: tomato">26.9<small>%</small></span> | 13.6<small>%</small> | 1.99 | -6.3<small>%</small> | -1.5<small>%</small> |