| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KBSTAR 머니마켓액티브](/455890-vs-357870/) | <span style="color: tomato">4.3<small>%</small></span> | 0.2<small>%</small> | 18.31 | -0.0<small>%</small> | -0.0<small>%</small> |
| TIGER CD금리투자KIS(합성) | <span style="color: tomato">3.7<small>%</small></span> | 0.2<small>%</small> | 19.39 | -0.0<small>%</small> | -0.0<small>%</small> |