| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PLUS 미국달러SOFR금리액티브(합성)](/456200-vs-456610/) | <span style="color: tomato">6.8<small>%</small></span> | 8.3<small>%</small> | 0.82 | -5.0<small>%</small> | -1.6<small>%</small> |
| TIGER 미국달러SOFR금리액티브(합성) | <span style="color: tomato">6.7<small>%</small></span> | 8.5<small>%</small> | 0.79 | -5.0<small>%</small> | -1.6<small>%</small> |