| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PLUS 미국달러SOFR금리액티브(합성)](/456200-vs-456610/) | <span style="color: tomato">7.6<small>%</small></span> | 8.0<small>%</small> | 0.95 | -5.0<small>%</small> | -1.4<small>%</small> |
| TIGER 미국달러SOFR금리액티브(합성) | <span style="color: tomato">7.4<small>%</small></span> | 8.3<small>%</small> | 0.88 | -5.0<small>%</small> | -1.5<small>%</small> |