| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국달러SOFR금리액티브(합성)](/456610-vs-138230/) | <span style="color: tomato">6.1<small>%</small></span> | 8.4<small>%</small> | 0.73 | -5.0<small>%</small> | -1.6<small>%</small> |
| KOSEF 미국달러선물 | <span style="color: tomato">5.8<small>%</small></span> | 8.4<small>%</small> | 0.69 | -5.0<small>%</small> | -1.5<small>%</small> |