| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국달러SOFR금리액티브(합성)](/456610-vs-138230/) | <span style="color: tomato">7.4<small>%</small></span> | 8.3<small>%</small> | 0.88 | -5.0<small>%</small> | -1.5<small>%</small> |
| KOSEF 미국달러선물 | <span style="color: tomato">7.0<small>%</small></span> | 8.4<small>%</small> | 0.84 | -5.0<small>%</small> | -1.4<small>%</small> |