| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국배당+7%프리미엄다우존스](/458760-vs-458730/) | <span style="color: tomato">16.2<small>%</small></span> | 9.7<small>%</small> | 1.68 | -8.1<small>%</small> | -2.1<small>%</small> |
| TIGER 미국배당다우존스 | <span style="color: tomato">22.8<small>%</small></span> | 10.8<small>%</small> | 2.10 | -7.7<small>%</small> | -1.8<small>%</small> |