| **종목** | **배율** | **1년** | **<small>변동성비용</small>** | **<small>금융비용</small>** | **<small>전체비용</small>** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| TIGER 미국배당다우존스 | 기초 | <span style="color: tomato">20.8<small>%</small></span> | - | - | - |
| [ACE 미국배당다우존스](/402970-vs-458730/) | 1<small>배</small> | <span style="color: tomato">19.6<small>%</small></span> | -0.0<small>%</small> | 0.6<small>%</small> | 0.6<small>%</small> |