| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국배당다우존스](/458730-vs-446720/) | <span style="color: tomato">22.2<small>%</small></span> | 10.9<small>%</small> | 2.03 | -7.7<small>%</small> | -1.7<small>%</small> |
| SOL 미국배당다우존스 | <span style="color: tomato">21.9<small>%</small></span> | 10.3<small>%</small> | 2.12 | -7.9<small>%</small> | -1.7<small>%</small> |