| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국배당다우존스](/458730-vs-360750/) | <span style="color: tomato">18.5<small>%</small></span> | 11.4<small>%</small> | 1.62 | -7.6<small>%</small> | -1.8<small>%</small> |
| TIGER 미국S&P500 | <span style="color: tomato">25.0<small>%</small></span> | 11.3<small>%</small> | 2.22 | -9.1<small>%</small> | -1.2<small>%</small> |