| **종목** | **배율** | **1년** | **<small>변동성비용</small>** | **<small>금융비용</small>** | **<small>전체비용</small>** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| TIGER 미국배당다우존스 | 기초 | <span style="color: tomato">20.5<small>%</small></span> | - | - | - |
| [TIGER 미국배당+7%프리미엄다우존스](/458760-458730/) | 1<small>배</small> | <span style="color: tomato">12.4<small>%</small></span> | -0.0<small>%</small> | 4.3<small>%</small> | 4.3<small>%</small> |