| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국배당다우존스](/458730-vs-402970/) | <span style="color: tomato">19.4<small>%</small></span> | 11.4<small>%</small> | 1.70 | -7.6<small>%</small> | -1.8<small>%</small> |
| ACE 미국배당다우존스 | <span style="color: tomato">19.5<small>%</small></span> | 11.0<small>%</small> | 1.78 | -7.8<small>%</small> | -1.8<small>%</small> |