| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국배당+7%프리미엄다우존스](/458760-vs-360750/) | <span style="color: tomato">11.2<small>%</small></span> | 9.7<small>%</small> | 1.15 | -8.1<small>%</small> | -2.1<small>%</small> |
| TIGER 미국S&P500 | <span style="color: tomato">37.0<small>%</small></span> | 10.1<small>%</small> | 3.66 | -6.8<small>%</small> | -1.1<small>%</small> |