| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국배당다우존스](/458730-vs-360750/) | <span style="color: tomato">18.9<small>%</small></span> | 10.8<small>%</small> | 1.74 | -7.7<small>%</small> | -1.8<small>%</small> |
| TIGER 미국S&P500 | <span style="color: tomato">32.6<small>%</small></span> | 10.4<small>%</small> | 3.13 | -6.8<small>%</small> | -1.1<small>%</small> |