| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국배당다우존스](/458730-vs-379800/) | <span style="color: tomato">19.9<small>%</small></span> | 11.4<small>%</small> | 1.75 | -7.7<small>%</small> | -1.9<small>%</small> |
| KODEX 미국S&P500TR | <span style="color: tomato">27.5<small>%</small></span> | 11.3<small>%</small> | 2.43 | -8.9<small>%</small> | -1.3<small>%</small> |