| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국배당+3%프리미엄다우존스](/458750-vs-458730/) | <span style="color: tomato">16.7<small>%</small></span> | 10.1<small>%</small> | 1.66 | -7.9<small>%</small> | -2.0<small>%</small> |
| TIGER 미국배당다우존스 | <span style="color: tomato">21.2<small>%</small></span> | 10.9<small>%</small> | 1.95 | -7.7<small>%</small> | -1.8<small>%</small> |