| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국배당+3%프리미엄다우존스](/458750-vs-458730/) | <span style="color: tomato">18.2<small>%</small></span> | 10.4<small>%</small> | 1.74 | -7.9<small>%</small> | -1.8<small>%</small> |
| TIGER 미국배당다우존스 | <span style="color: tomato">21.4<small>%</small></span> | 11.1<small>%</small> | 1.93 | -7.6<small>%</small> | -1.7<small>%</small> |