| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국배당다우존스](/458730-vs-379800/) | <span style="color: tomato">18.9<small>%</small></span> | 11.5<small>%</small> | 1.65 | -7.6<small>%</small> | -1.8<small>%</small> |
| KODEX 미국S&P500TR | <span style="color: tomato">28.8<small>%</small></span> | 11.3<small>%</small> | 2.54 | -8.9<small>%</small> | -1.3<small>%</small> |