| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국배당+3%프리미엄다우존스](/458750-vs-458730/) | <span style="color: tomato">16.4<small>%</small></span> | 10.0<small>%</small> | 1.63 | -7.9<small>%</small> | -1.9<small>%</small> |
| TIGER 미국배당다우존스 | <span style="color: tomato">20.0<small>%</small></span> | 10.9<small>%</small> | 1.82 | -7.7<small>%</small> | -1.8<small>%</small> |