| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국배당+3%프리미엄다우존스](/458750-vs-360750/) | <span style="color: tomato">15.1<small>%</small></span> | 10.7<small>%</small> | 1.42 | -7.9<small>%</small> | -1.9<small>%</small> |
| TIGER 미국S&P500 | <span style="color: tomato">25.0<small>%</small></span> | 11.7<small>%</small> | 2.13 | -9.1<small>%</small> | -1.4<small>%</small> |