| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국배당+7%프리미엄다우존스](/458760-vs-379800/) | <span style="color: tomato">14.9<small>%</small></span> | 10.4<small>%</small> | 1.43 | -8.1<small>%</small> | -2.1<small>%</small> |
| KODEX 미국S&P500TR | <span style="color: tomato">28.8<small>%</small></span> | 11.3<small>%</small> | 2.55 | -8.9<small>%</small> | -1.3<small>%</small> |