| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국배당+7%프리미엄다우존스](/458760-vs-458730/) | <span style="color: tomato">12.2<small>%</small></span> | 10.2<small>%</small> | 1.20 | -8.1<small>%</small> | -2.4<small>%</small> |
| TIGER 미국배당다우존스 | <span style="color: tomato">19.6<small>%</small></span> | 11.1<small>%</small> | 1.77 | -7.7<small>%</small> | -1.9<small>%</small> |