| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국배당다우존스](/458730-vs-379800/) | <span style="color: tomato">19.1<small>%</small></span> | 11.4<small>%</small> | 1.68 | -7.6<small>%</small> | -1.8<small>%</small> |
| KODEX 미국S&P500TR | <span style="color: tomato">28.0<small>%</small></span> | 11.1<small>%</small> | 2.53 | -8.9<small>%</small> | -1.2<small>%</small> |