| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국배당+7%프리미엄다우존스](/458760-vs-360750/) | <span style="color: tomato">16.2<small>%</small></span> | 10.1<small>%</small> | 1.60 | -8.1<small>%</small> | -2.0<small>%</small> |
| TIGER 미국S&P500 | <span style="color: tomato">31.9<small>%</small></span> | 10.2<small>%</small> | 3.13 | -6.8<small>%</small> | -1.1<small>%</small> |