| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국배당다우존스](/458730-vs-446720/) | <span style="color: tomato">17.0<small>%</small></span> | 10.7<small>%</small> | 1.58 | -7.7<small>%</small> | -1.8<small>%</small> |
| SOL 미국배당다우존스 | <span style="color: tomato">16.9<small>%</small></span> | 10.2<small>%</small> | 1.66 | -7.9<small>%</small> | -1.7<small>%</small> |