| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국배당+7%프리미엄다우존스](/458760-vs-360750/) | <span style="color: tomato">14.6<small>%</small></span> | 10.4<small>%</small> | 1.40 | -8.1<small>%</small> | -2.1<small>%</small> |
| TIGER 미국S&P500 | <span style="color: tomato">30.1<small>%</small></span> | 11.4<small>%</small> | 2.63 | -9.1<small>%</small> | -1.3<small>%</small> |