| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국배당다우존스](/458730-vs-402970/) | <span style="color: tomato">18.5<small>%</small></span> | 10.8<small>%</small> | 1.72 | -7.7<small>%</small> | -1.8<small>%</small> |
| ACE 미국배당다우존스 | <span style="color: tomato">18.2<small>%</small></span> | 10.4<small>%</small> | 1.75 | -7.8<small>%</small> | -1.7<small>%</small> |