| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국배당+7%프리미엄다우존스](/458760-vs-379800/) | <span style="color: tomato">14.5<small>%</small></span> | 10.4<small>%</small> | 1.40 | -8.1<small>%</small> | -2.1<small>%</small> |
| KODEX 미국S&P500TR | <span style="color: tomato">26.4<small>%</small></span> | 11.5<small>%</small> | 2.30 | -8.9<small>%</small> | -1.4<small>%</small> |