| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국배당다우존스](/458730-vs-402970/) | <span style="color: tomato">17.5<small>%</small></span> | 10.8<small>%</small> | 1.63 | -7.7<small>%</small> | -1.8<small>%</small> |
| ACE 미국배당다우존스 | <span style="color: tomato">17.3<small>%</small></span> | 10.4<small>%</small> | 1.67 | -7.8<small>%</small> | -1.7<small>%</small> |