| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국배당+3%프리미엄다우존스](/458750-vs-360750/) | <span style="color: tomato">16.8<small>%</small></span> | 10.6<small>%</small> | 1.58 | -7.9<small>%</small> | -1.9<small>%</small> |
| TIGER 미국S&P500 | <span style="color: tomato">27.6<small>%</small></span> | 11.5<small>%</small> | 2.39 | -9.1<small>%</small> | -1.4<small>%</small> |