| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [히어로즈 미국달러SOFR금리액티브(합성)](/460270-vs-456610/) | <span style="color: tomato">9.3<small>%</small></span> | 8.9<small>%</small> | 1.05 | -4.9<small>%</small> | -1.4<small>%</small> |
| TIGER 미국달러SOFR금리액티브(합성) | <span style="color: tomato">9.1<small>%</small></span> | 8.4<small>%</small> | 1.07 | -4.9<small>%</small> | -1.4<small>%</small> |