| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [히어로즈 미국달러SOFR금리액티브(합성)](/460270-vs-456610/) | <span style="color: tomato">8.6<small>%</small></span> | 9.0<small>%</small> | 0.95 | -5.1<small>%</small> | -1.4<small>%</small> |
| TIGER 미국달러SOFR금리액티브(합성) | <span style="color: tomato">8.5<small>%</small></span> | 8.5<small>%</small> | 1.00 | -4.9<small>%</small> | -1.5<small>%</small> |