| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PLUS 미국테크TOP10](/461900-vs-381170/) | <span style="color: tomato">41.8<small>%</small></span> | 22.0<small>%</small> | 1.90 | -20.5<small>%</small> | -3.2<small>%</small> |
| TIGER 미국테크TOP10 INDXX | <span style="color: tomato">41.9<small>%</small></span> | 24.0<small>%</small> | 1.75 | -22.6<small>%</small> | -3.1<small>%</small> |