| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PLUS 미국테크TOP10](/461900-vs-381170/) | <span style="color: tomato">34.1<small>%</small></span> | 21.9<small>%</small> | 1.56 | -20.5<small>%</small> | -2.8<small>%</small> |
| TIGER 미국테크TOP10 INDXX | <span style="color: tomato">34.1<small>%</small></span> | 24.1<small>%</small> | 1.42 | -22.6<small>%</small> | -2.7<small>%</small> |