| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PLUS 미국테크TOP10](/461900-vs-381170/) | <span style="color: tomato">45.5<small>%</small></span> | 21.6<small>%</small> | 2.10 | -20.5<small>%</small> | -2.2<small>%</small> |
| TIGER 미국테크TOP10 INDXX | <span style="color: tomato">46.5<small>%</small></span> | 24.0<small>%</small> | 1.94 | -22.6<small>%</small> | -2.1<small>%</small> |