| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ACE 미국빅테크TOP7 Plus](/465580-vs-381170/) | <span style="color: tomato">44.2<small>%</small></span> | 26.3<small>%</small> | 1.68 | -23.2<small>%</small> | -2.8<small>%</small> |
| TIGER 미국테크TOP10 INDXX | <span style="color: tomato">41.5<small>%</small></span> | 24.6<small>%</small> | 1.69 | -22.6<small>%</small> | -2.5<small>%</small> |