| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ACE 미국빅테크TOP7 Plus](/465580-vs-381170/) | <span style="color: tomato">46.8<small>%</small></span> | 25.8<small>%</small> | 1.81 | -23.2<small>%</small> | -3.8<small>%</small> |
| TIGER 미국테크TOP10 INDXX | <span style="color: tomato">44.7<small>%</small></span> | 24.4<small>%</small> | 1.84 | -22.6<small>%</small> | -3.5<small>%</small> |