| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ACE 미국빅테크TOP7 Plus](/465580-vs-381170/) | <span style="color: tomato">42.5<small>%</small></span> | 26.2<small>%</small> | 1.62 | -23.2<small>%</small> | -3.0<small>%</small> |
| TIGER 미국테크TOP10 INDXX | <span style="color: tomato">39.8<small>%</small></span> | 24.5<small>%</small> | 1.62 | -22.6<small>%</small> | -2.7<small>%</small> |