| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국테크TOP10 INDXX(H)](/472160-vs-381170/) | <span style="color: tomato">38.6<small>%</small></span> | 27.5<small>%</small> | 1.40 | -22.5<small>%</small> | -2.8<small>%</small> |
| TIGER 미국테크TOP10 INDXX | <span style="color: tomato">47.0<small>%</small></span> | 26.6<small>%</small> | 1.77 | -22.6<small>%</small> | -2.9<small>%</small> |