| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국테크TOP10 INDXX(H)](/472160-vs-381170/) | <span style="color: tomato">51.1<small>%</small></span> | 27.2<small>%</small> | 1.88 | -22.5<small>%</small> | -2.6<small>%</small> |
| TIGER 미국테크TOP10 INDXX | <span style="color: tomato">60.0<small>%</small></span> | 26.2<small>%</small> | 2.29 | -22.6<small>%</small> | -2.6<small>%</small> |