| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국테크TOP10 INDXX(H)](/472160-vs-381170/) | <span style="color: tomato">49.0<small>%</small></span> | 26.9<small>%</small> | 1.82 | -22.5<small>%</small> | -3.5<small>%</small> |
| TIGER 미국테크TOP10 INDXX | <span style="color: tomato">57.6<small>%</small></span> | 26.0<small>%</small> | 2.21 | -22.6<small>%</small> | -3.7<small>%</small> |