| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국테크TOP10+10%프리미엄](/474220-vs-461900/) | <span style="color: tomato">88.2<small>%</small></span> | 15.8<small>%</small> | 5.59 | -6.8<small>%</small> | -0.8<small>%</small> |
| ARIRANG 미국테크10iSelect | <span style="color: tomato">103.6<small>%</small></span> | 18.9<small>%</small> | 5.47 | -8.0<small>%</small> | -1.2<small>%</small> |