| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국테크TOP10+10%프리미엄](/474220-vs-461900/) | <span style="color: tomato">54.0<small>%</small></span> | 16.6<small>%</small> | 3.26 | -9.6<small>%</small> | -1.3<small>%</small> |
| PLUS 미국테크TOP10 | <span style="color: tomato">61.2<small>%</small></span> | 20.3<small>%</small> | 3.02 | -11.6<small>%</small> | -1.7<small>%</small> |