| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국테크TOP10+10%프리미엄](/474220-vs-381170/) | <span style="color: tomato">51.1<small>%</small></span> | 24.5<small>%</small> | 2.09 | -20.1<small>%</small> | -2.3<small>%</small> |
| TIGER 미국테크TOP10 INDXX | <span style="color: tomato">59.1<small>%</small></span> | 28.1<small>%</small> | 2.10 | -22.6<small>%</small> | -2.7<small>%</small> |