| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국테크TOP10+10%프리미엄](/474220-vs-381170/) | <span style="color: tomato">64.6<small>%</small></span> | 16.4<small>%</small> | 3.94 | -6.8<small>%</small> | -1.0<small>%</small> |
| TIGER 미국테크TOP10 INDXX | <span style="color: tomato">78.9<small>%</small></span> | 20.6<small>%</small> | 3.83 | -7.5<small>%</small> | -1.1<small>%</small> |