| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국테크TOP10+10%프리미엄](/474220-vs-461900/) | <span style="color: tomato">34.7<small>%</small></span> | 24.5<small>%</small> | 1.42 | -20.1<small>%</small> | -2.8<small>%</small> |
| PLUS 미국테크TOP10 | <span style="color: tomato">40.4<small>%</small></span> | 25.2<small>%</small> | 1.60 | -20.5<small>%</small> | -3.4<small>%</small> |