| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국테크TOP10+10%프리미엄](/474220-vs-381170/) | <span style="color: tomato">54.0<small>%</small></span> | 16.6<small>%</small> | 3.26 | -9.6<small>%</small> | -1.3<small>%</small> |
| TIGER 미국테크TOP10 INDXX | <span style="color: tomato">62.6<small>%</small></span> | 20.4<small>%</small> | 3.07 | -11.4<small>%</small> | -1.5<small>%</small> |