| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [RISE 버크셔포트폴리오TOP10](/475350-vs-360750/) | <span style="color: tomato">46.0<small>%</small></span> | 12.3<small>%</small> | 3.75 | -4.4<small>%</small> | -0.8<small>%</small> |
| TIGER 미국S&P500 | <span style="color: tomato">32.0<small>%</small></span> | 10.1<small>%</small> | 3.16 | -3.9<small>%</small> | -0.8<small>%</small> |