| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [RISE 버크셔포트폴리오TOP10](/475350-vs-379800/) | <span style="color: tomato">32.2<small>%</small></span> | 16.0<small>%</small> | 2.01 | -11.2<small>%</small> | -1.6<small>%</small> |
| KODEX 미국S&P500TR | <span style="color: tomato">25.9<small>%</small></span> | 12.9<small>%</small> | 2.02 | -8.9<small>%</small> | -1.4<small>%</small> |