| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [RISE 버크셔포트폴리오TOP10](/475350-vs-379800/) | <span style="color: tomato">32.1<small>%</small></span> | 16.1<small>%</small> | 1.99 | -11.2<small>%</small> | -1.4<small>%</small> |
| KODEX 미국S&P500TR | <span style="color: tomato">21.4<small>%</small></span> | 12.4<small>%</small> | 1.73 | -8.9<small>%</small> | -1.3<small>%</small> |