| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [RISE 버크셔포트폴리오TOP10](/475350-vs-360750/) | <span style="color: tomato">45.3<small>%</small></span> | 12.2<small>%</small> | 3.71 | -4.5<small>%</small> | -0.8<small>%</small> |
| TIGER 미국S&P500 | <span style="color: tomato">31.3<small>%</small></span> | 10.1<small>%</small> | 3.11 | -3.9<small>%</small> | -0.8<small>%</small> |