| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [RISE 버크셔포트폴리오TOP10](/475350-vs-379800/) | <span style="color: tomato">27.2<small>%</small></span> | 15.7<small>%</small> | 1.74 | -11.2<small>%</small> | -2.0<small>%</small> |
| KODEX 미국S&P500TR | <span style="color: tomato">21.2<small>%</small></span> | 13.1<small>%</small> | 1.62 | -8.9<small>%</small> | -1.8<small>%</small> |