| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [RISE 200위클리커버드콜](/475720-vs-166400/) | <span style="color: tomato">17.7<small>%</small></span> | 11.4<small>%</small> | 1.56 | -4.7<small>%</small> | -1.1<small>%</small> |
| TIGER 200커버드콜5%OTM | <span style="color: tomato">20.4<small>%</small></span> | 15.5<small>%</small> | 1.32 | -6.0<small>%</small> | -1.5<small>%</small> |