| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [RISE 200위클리커버드콜](/475720-vs-289480/) | <span style="color: tomato">0.8<small>%</small></span> | 18.7<small>%</small> | 0.04 | -14.5<small>%</small> | -1.8<small>%</small> |
| TIGER 200커버드콜ATM | <span style="color: cornflowerblue">-4.2<small>%</small></span> | 18.0<small>%</small> | -0.23 | -14.6<small>%</small> | -1.5<small>%</small> |