| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [RISE 200위클리커버드콜](/475720-vs-069500/) | <span style="color: cornflowerblue">-13.4<small>%</small></span> | 18.6<small>%</small> | -0.72 | -14.5<small>%</small> | -1.2<small>%</small> |
| KODEX 200 | <span style="color: cornflowerblue">-14.3<small>%</small></span> | 22.5<small>%</small> | -0.64 | -16.5<small>%</small> | -1.9<small>%</small> |