| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [RISE 200위클리커버드콜](/475720-vs-166400/) | <span style="color: cornflowerblue">-8.6<small>%</small></span> | 18.9<small>%</small> | -0.46 | -14.5<small>%</small> | -1.3<small>%</small> |
| TIGER 200커버드콜5%OTM | <span style="color: cornflowerblue">-7.8<small>%</small></span> | 22.4<small>%</small> | -0.35 | -16.4<small>%</small> | -1.9<small>%</small> |