| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [RISE 200위클리커버드콜](/475720-vs-069500/) | <span style="color: tomato">0.8<small>%</small></span> | 17.8<small>%</small> | 0.05 | -14.5<small>%</small> | -3.6<small>%</small> |
| KODEX 200 | <span style="color: cornflowerblue">-1.6<small>%</small></span> | 22.0<small>%</small> | -0.07 | -16.5<small>%</small> | -4.7<small>%</small> |