| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [RISE 200위클리커버드콜](/475720-vs-166400/) | <span style="color: cornflowerblue">-13.4<small>%</small></span> | 18.6<small>%</small> | -0.72 | -14.5<small>%</small> | -1.2<small>%</small> |
| TIGER 200커버드콜5%OTM | <span style="color: cornflowerblue">-14.0<small>%</small></span> | 22.0<small>%</small> | -0.63 | -16.4<small>%</small> | -1.7<small>%</small> |