| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [RISE 200위클리커버드콜](/475720-vs-289480/) | <span style="color: cornflowerblue">-1.5<small>%</small></span> | 18.0<small>%</small> | -0.09 | -14.5<small>%</small> | -3.1<small>%</small> |
| TIGER 200커버드콜ATM | <span style="color: cornflowerblue">-2.6<small>%</small></span> | 16.9<small>%</small> | -0.15 | -14.6<small>%</small> | -2.9<small>%</small> |