| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [RISE 200위클리커버드콜](/475720-vs-069500/) | <span style="color: tomato">3.1<small>%</small></span> | 17.9<small>%</small> | 0.18 | -14.5<small>%</small> | -2.4<small>%</small> |
| KODEX 200 | <span style="color: tomato">2.7<small>%</small></span> | 22.0<small>%</small> | 0.12 | -16.5<small>%</small> | -3.1<small>%</small> |