| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [RISE 200위클리커버드콜](/475720-vs-289480/) | <span style="color: cornflowerblue">-3.4<small>%</small></span> | 18.4<small>%</small> | -0.18 | -14.5<small>%</small> | -2.4<small>%</small> |
| TIGER 200커버드콜ATM | <span style="color: cornflowerblue">-5.5<small>%</small></span> | 17.1<small>%</small> | -0.32 | -14.6<small>%</small> | -2.4<small>%</small> |