| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SOL 미국나스닥100](/476030-vs-379810/) | <span style="color: tomato">23.9<small>%</small></span> | 20.4<small>%</small> | 1.17 | -15.9<small>%</small> | -3.7<small>%</small> |
| KODEX 미국나스닥100TR | <span style="color: tomato">24.2<small>%</small></span> | 20.4<small>%</small> | 1.18 | -15.9<small>%</small> | -3.7<small>%</small> |