| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SOL 미국나스닥100](/476030-vs-133690/) | <span style="color: tomato">3.5<small>%</small></span> | 19.0<small>%</small> | 0.19 | -15.9<small>%</small> | -1.9<small>%</small> |
| TIGER 미국나스닥100 | <span style="color: tomato">1.6<small>%</small></span> | 19.4<small>%</small> | 0.08 | -16.4<small>%</small> | -1.9<small>%</small> |