| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SOL 미국나스닥100](/476030-vs-133690/) | <span style="color: tomato">22.1<small>%</small></span> | 20.4<small>%</small> | 1.09 | -15.9<small>%</small> | -3.0<small>%</small> |
| TIGER 미국나스닥100 | <span style="color: tomato">21.9<small>%</small></span> | 21.0<small>%</small> | 1.04 | -16.4<small>%</small> | -3.0<small>%</small> |