| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SOL 미국나스닥100](/476030-vs-379810/) | <span style="color: tomato">28.2<small>%</small></span> | 20.6<small>%</small> | 1.37 | -15.9<small>%</small> | -2.7<small>%</small> |
| KODEX 미국나스닥100TR | <span style="color: tomato">28.2<small>%</small></span> | 20.6<small>%</small> | 1.37 | -15.9<small>%</small> | -2.7<small>%</small> |