| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SOL 미국나스닥100](/476030-vs-379810/) | <span style="color: tomato">32.4<small>%</small></span> | 20.0<small>%</small> | 1.62 | -15.9<small>%</small> | -3.8<small>%</small> |
| KODEX 미국나스닥100TR | <span style="color: tomato">32.6<small>%</small></span> | 20.0<small>%</small> | 1.63 | -15.9<small>%</small> | -3.8<small>%</small> |