| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SOL 미국나스닥100](/476030-vs-133690/) | <span style="color: tomato">15.5<small>%</small></span> | 20.2<small>%</small> | 0.77 | -15.9<small>%</small> | -2.1<small>%</small> |
| TIGER 미국나스닥100 | <span style="color: tomato">15.4<small>%</small></span> | 20.9<small>%</small> | 0.74 | -16.4<small>%</small> | -2.1<small>%</small> |