| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ACE 미국500 15%프리미엄분배(합성)](/480030-vs-379800/) | <span style="color: tomato">16.0<small>%</small></span> | 13.9<small>%</small> | 1.15 | -9.5<small>%</small> | -2.3<small>%</small> |
| KODEX 미국S&P500TR | <span style="color: tomato">22.6<small>%</small></span> | 13.8<small>%</small> | 1.63 | -8.9<small>%</small> | -2.0<small>%</small> |