| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ACE 미국빅테크7+ 15%프리미엄분배(합성)](/480020-vs-465580/) | <span style="color: tomato">87.5<small>%</small></span> | 23.8<small>%</small> | 3.68 | -11.8<small>%</small> | -2.1<small>%</small> |
| ACE 미국빅테크TOP7 Plus | <span style="color: tomato">100.5<small>%</small></span> | 24.9<small>%</small> | 4.03 | -12.0<small>%</small> | -2.0<small>%</small> |