| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ACE 미국500데일리타겟커버드콜(합성)](/480030-vs-379800/) | <span style="color: tomato">21.7<small>%</small></span> | 14.0<small>%</small> | 1.55 | -9.5<small>%</small> | -2.4<small>%</small> |
| KODEX 미국S&P500TR | <span style="color: tomato">27.8<small>%</small></span> | 13.8<small>%</small> | 2.01 | -8.9<small>%</small> | -2.1<small>%</small> |