| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ACE 미국빅테크7+ 15%프리미엄분배(합성)](/480020-vs-465580/) | <span style="color: tomato">54.6<small>%</small></span> | 25.7<small>%</small> | 2.13 | -14.0<small>%</small> | -2.3<small>%</small> |
| ACE 미국빅테크TOP7 Plus | <span style="color: tomato">59.1<small>%</small></span> | 27.5<small>%</small> | 2.15 | -14.4<small>%</small> | -2.2<small>%</small> |