| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ACE 미국500 15%프리미엄분배(합성)](/480030-vs-360200/) | <span style="color: tomato">16.4<small>%</small></span> | 14.2<small>%</small> | 1.16 | -9.5<small>%</small> | -1.0<small>%</small> |
| ACE 미국S&P500 | <span style="color: tomato">20.0<small>%</small></span> | 13.4<small>%</small> | 1.49 | -9.2<small>%</small> | -1.0<small>%</small> |