| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ACE 미국500 15%프리미엄분배(합성)](/480030-vs-360200/) | <span style="color: tomato">19.4<small>%</small></span> | 14.0<small>%</small> | 1.38 | -9.5<small>%</small> | -2.3<small>%</small> |
| ACE 미국S&P500 | <span style="color: tomato">25.8<small>%</small></span> | 14.2<small>%</small> | 1.81 | -9.2<small>%</small> | -2.0<small>%</small> |