| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ACE 미국빅테크7+ 15%프리미엄분배(합성)](/480020-vs-465580/) | <span style="color: tomato">82.7<small>%</small></span> | 24.0<small>%</small> | 3.45 | -11.8<small>%</small> | -1.8<small>%</small> |
| ACE 미국빅테크TOP7 Plus | <span style="color: tomato">91.6<small>%</small></span> | 24.5<small>%</small> | 3.75 | -11.3<small>%</small> | -1.6<small>%</small> |