| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ACE 미국500 15%프리미엄분배(합성)](/480030-vs-379800/) | <span style="color: tomato">18.7<small>%</small></span> | 14.1<small>%</small> | 1.33 | -9.5<small>%</small> | -1.2<small>%</small> |
| KODEX 미국S&P500TR | <span style="color: tomato">23.3<small>%</small></span> | 13.2<small>%</small> | 1.77 | -8.9<small>%</small> | -1.2<small>%</small> |