| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SOL 미국테크TOP10](/481190-vs-381170/) | <span style="color: tomato">24.5<small>%</small></span> | 32.2<small>%</small> | 0.76 | -21.7<small>%</small> | -5.4<small>%</small> |
| TIGER 미국테크TOP10 INDXX | <span style="color: tomato">23.6<small>%</small></span> | 34.1<small>%</small> | 0.69 | -22.6<small>%</small> | -5.4<small>%</small> |