| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SOL 미국테크TOP10](/481190-vs-381170/) | <span style="color: tomato">27.5<small>%</small></span> | 31.4<small>%</small> | 0.88 | -21.7<small>%</small> | -6.6<small>%</small> |
| TIGER 미국테크TOP10 INDXX | <span style="color: tomato">28.2<small>%</small></span> | 33.0<small>%</small> | 0.85 | -22.6<small>%</small> | -6.6<small>%</small> |