| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SOL 미국테크TOP10](/481190-vs-381170/) | <span style="color: tomato">37.8<small>%</small></span> | 33.5<small>%</small> | 1.13 | -21.7<small>%</small> | -4.7<small>%</small> |
| TIGER 미국테크TOP10 INDXX | <span style="color: tomato">37.8<small>%</small></span> | 35.3<small>%</small> | 1.07 | -22.6<small>%</small> | -4.7<small>%</small> |