| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국S&P500타겟데일리커버드콜](/482730-vs-480030/) | <span style="color: tomato">14.5<small>%</small></span> | 13.8<small>%</small> | 1.05 | -8.8<small>%</small> | -2.3<small>%</small> |
| ACE미국500데일리타겟커버드콜(합성) | <span style="color: tomato">10.5<small>%</small></span> | 14.1<small>%</small> | 0.75 | -9.5<small>%</small> | -2.7<small>%</small> |