| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국S&P500+10%프리미엄초단기](/482730-vs-360750/) | <span style="color: tomato">1.2<small>%</small></span> | 14.0<small>%</small> | 0.09 | -8.8<small>%</small> | -2.2<small>%</small> |
| TIGER 미국S&P500 | <span style="color: tomato">2.8<small>%</small></span> | 14.4<small>%</small> | 0.20 | -9.1<small>%</small> | -2.2<small>%</small> |