| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국S&P500+10%프리미엄초단기](/482730-vs-360750/) | <span style="color: tomato">11.8<small>%</small></span> | 13.7<small>%</small> | 0.86 | -8.8<small>%</small> | -2.0<small>%</small> |
| TIGER 미국S&P500 | <span style="color: tomato">14.3<small>%</small></span> | 14.1<small>%</small> | 1.01 | -9.1<small>%</small> | -2.0<small>%</small> |