| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국S&P500+10%프리미엄초단기](/482730-vs-360750/) | <span style="color: tomato">12.3<small>%</small></span> | 14.1<small>%</small> | 0.88 | -8.8<small>%</small> | -1.7<small>%</small> |
| TIGER 미국S&P500 | <span style="color: tomato">15.6<small>%</small></span> | 14.5<small>%</small> | 1.07 | -9.1<small>%</small> | -1.8<small>%</small> |