| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국S&P500+10%프리미엄초단기](/482730-vs-379800/) | <span style="color: tomato">15.4<small>%</small></span> | 13.9<small>%</small> | 1.11 | -8.8<small>%</small> | -2.3<small>%</small> |
| KODEX 미국S&P500TR | <span style="color: tomato">18.0<small>%</small></span> | 14.0<small>%</small> | 1.28 | -8.9<small>%</small> | -2.4<small>%</small> |