| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국S&P500+10%프리미엄초단기](/482730-vs-480030/) | <span style="color: tomato">8.2<small>%</small></span> | 13.9<small>%</small> | 0.59 | -8.8<small>%</small> | -2.3<small>%</small> |
| ACE 미국500 15%프리미엄분배(합성) | <span style="color: tomato">5.7<small>%</small></span> | 14.3<small>%</small> | 0.40 | -9.5<small>%</small> | -2.7<small>%</small> |