| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국S&P500+10%프리미엄초단기](/482730-vs-379800/) | <span style="color: tomato">8.9<small>%</small></span> | 13.7<small>%</small> | 0.65 | -8.8<small>%</small> | -1.9<small>%</small> |
| KODEX 미국S&P500TR | <span style="color: tomato">11.4<small>%</small></span> | 13.8<small>%</small> | 0.83 | -8.9<small>%</small> | -2.0<small>%</small> |