| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국S&P500타겟데일리커버드콜](/482730-vs-379800/) | <span style="color: tomato">26.8<small>%</small></span> | 13.8<small>%</small> | 1.95 | -8.8<small>%</small> | -2.1<small>%</small> |
| KODEX 미국S&P500TR | <span style="color: tomato">28.7<small>%</small></span> | 14.0<small>%</small> | 2.06 | -8.9<small>%</small> | -2.1<small>%</small> |