| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 미국AI테크TOP10타겟커버드콜](/483280-vs-485540/) | <span style="color: cornflowerblue">-8.7<small>%</small></span> | 37.7<small>%</small> | -0.23 | -22.9<small>%</small> | -9.1<small>%</small> |
| KODEX 미국AI테크TOP10 | <span style="color: cornflowerblue">-6.4<small>%</small></span> | 39.5<small>%</small> | -0.16 | -24.4<small>%</small> | -9.9<small>%</small> |