| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 미국배당+10%프리미엄다우존스](/483290-vs-458730/) | <span style="color: tomato">14.7<small>%</small></span> | 12.9<small>%</small> | 1.14 | -4.7<small>%</small> | -1.9<small>%</small> |
| TIGER 미국배당다우존스 | <span style="color: tomato">17.3<small>%</small></span> | 13.4<small>%</small> | 1.29 | -5.1<small>%</small> | -1.8<small>%</small> |