| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 미국배당다우존스타겟커버드콜](/483290-vs-458760/) | <span style="color: tomato">15.4<small>%</small></span> | 12.7<small>%</small> | 1.21 | -4.7<small>%</small> | -1.9<small>%</small> |
| TIGER 미국배당다우존스타겟커버드콜2호 | <span style="color: tomato">18.1<small>%</small></span> | 12.3<small>%</small> | 1.47 | -4.9<small>%</small> | -1.9<small>%</small> |