| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 미국AI테크TOP10타겟커버드콜](/483280-vs-485540/) | <span style="color: tomato">3.2<small>%</small></span> | 36.4<small>%</small> | 0.09 | -22.9<small>%</small> | -9.1<small>%</small> |
| KODEX 미국AI테크TOP10 | <span style="color: tomato">4.4<small>%</small></span> | 38.2<small>%</small> | 0.12 | -24.4<small>%</small> | -9.9<small>%</small> |