| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 미국AI테크TOP10타겟커버드콜](/483280-vs-485540/) | <span style="color: tomato">18.4<small>%</small></span> | 34.6<small>%</small> | 0.53 | -22.9<small>%</small> | -8.6<small>%</small> |
| KODEX 미국AI테크TOP10 | <span style="color: tomato">16.8<small>%</small></span> | 36.2<small>%</small> | 0.46 | -24.4<small>%</small> | -9.5<small>%</small> |