| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 미국배당다우존스타겟커버드콜](/483290-vs-458730/) | <span style="color: tomato">22.4<small>%</small></span> | 12.6<small>%</small> | 1.77 | -4.7<small>%</small> | -1.9<small>%</small> |
| TIGER 미국배당다우존스 | <span style="color: tomato">28.7<small>%</small></span> | 13.3<small>%</small> | 2.15 | -5.1<small>%</small> | -1.8<small>%</small> |