| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 미국배당+10%프리미엄다우존스](/483290-vs-458730/) | <span style="color: tomato">21.4<small>%</small></span> | 13.0<small>%</small> | 1.65 | -4.7<small>%</small> | -1.9<small>%</small> |
| TIGER 미국배당다우존스 | <span style="color: tomato">27.5<small>%</small></span> | 13.3<small>%</small> | 2.07 | -5.1<small>%</small> | -1.7<small>%</small> |