| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 미국배당+10%프리미엄다우존스](/483290-vs-360750/) | <span style="color: tomato">23.8<small>%</small></span> | 12.9<small>%</small> | 1.85 | -4.7<small>%</small> | -1.9<small>%</small> |
| TIGER 미국S&P500 | <span style="color: tomato">19.6<small>%</small></span> | 14.5<small>%</small> | 1.35 | -9.1<small>%</small> | -2.1<small>%</small> |