| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 미국배당+10%프리미엄다우존스](/483290-vs-360750/) | <span style="color: tomato">19.8<small>%</small></span> | 12.9<small>%</small> | 1.54 | -4.7<small>%</small> | -1.9<small>%</small> |
| TIGER 미국S&P500 | <span style="color: tomato">7.3<small>%</small></span> | 14.8<small>%</small> | 0.49 | -9.1<small>%</small> | -2.4<small>%</small> |