| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KODEX 미국배당+10%프리미엄다우존스](/483290-vs-360750/) | <span style="color: tomato">21.4<small>%</small></span> | 13.0<small>%</small> | 1.65 | -4.7<small>%</small> | -1.9<small>%</small> |
| TIGER 미국S&P500 | <span style="color: tomato">16.7<small>%</small></span> | 14.6<small>%</small> | 1.15 | -9.1<small>%</small> | -2.1<small>%</small> |