| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국나스닥100타겟데일리커버드콜](/486290-vs-379810/) | <span style="color: tomato">7.2<small>%</small></span> | 25.2<small>%</small> | 0.29 | -16.2<small>%</small> | -6.4<small>%</small> |
| KODEX 미국나스닥100TR | <span style="color: tomato">9.5<small>%</small></span> | 24.9<small>%</small> | 0.38 | -15.9<small>%</small> | -6.4<small>%</small> |