| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국나스닥100타겟데일리커버드콜](/486290-vs-379810/) | <span style="color: tomato">8.3<small>%</small></span> | 24.2<small>%</small> | 0.34 | -16.2<small>%</small> | -6.0<small>%</small> |
| KODEX 미국나스닥100TR | <span style="color: tomato">9.5<small>%</small></span> | 24.0<small>%</small> | 0.40 | -15.9<small>%</small> | -6.0<small>%</small> |