| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국나스닥100타겟데일리커버드콜](/486290-vs-379810/) | <span style="color: tomato">4.5<small>%</small></span> | 25.1<small>%</small> | 0.18 | -16.2<small>%</small> | -6.3<small>%</small> |
| KODEX 미국나스닥100TR | <span style="color: tomato">6.0<small>%</small></span> | 24.8<small>%</small> | 0.24 | -15.9<small>%</small> | -6.3<small>%</small> |