| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TIGER 미국S&P500동일가중](/488500-vs-379800/) | <span style="color: tomato">28.9<small>%</small></span> | 17.0<small>%</small> | 1.70 | -6.5<small>%</small> | -1.6<small>%</small> |
| KODEX 미국S&P500TR | <span style="color: tomato">22.2<small>%</small></span> | 17.3<small>%</small> | 1.28 | -7.5<small>%</small> | -2.3<small>%</small> |