| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [삼성 코스피 200 TR ETN](/530117-vs-069500/) | <span style="color: tomato">2.5<small>%</small></span> | 21.1<small>%</small> | 0.12 | -16.9<small>%</small> | -3.5<small>%</small> |
| KODEX 200 | <span style="color: tomato">2.0<small>%</small></span> | 21.2<small>%</small> | 0.09 | -16.5<small>%</small> | -3.4<small>%</small> |