| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [삼성 코스닥 150 TR ETN](/530118-vs-229200/) | <span style="color: cornflowerblue">-6.6<small>%</small></span> | 26.2<small>%</small> | -0.25 | -26.0<small>%</small> | -8.6<small>%</small> |
| KODEX 코스닥150 | <span style="color: cornflowerblue">-8.8<small>%</small></span> | 26.2<small>%</small> | -0.34 | -25.3<small>%</small> | -8.5<small>%</small> |