| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [삼성 코스피 200 TR ETN](/530117-vs-069500/) | <span style="color: tomato">3.7<small>%</small></span> | 21.0<small>%</small> | 0.17 | -16.9<small>%</small> | -4.4<small>%</small> |
| KODEX 200 | <span style="color: tomato">3.0<small>%</small></span> | 21.2<small>%</small> | 0.14 | -16.5<small>%</small> | -4.3<small>%</small> |