| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [삼성 나스닥 100 ETN](/530120-vs-379810/) | <span style="color: tomato">27.5<small>%</small></span> | 24.1<small>%</small> | 1.14 | -16.0<small>%</small> | -5.3<small>%</small> |
| KODEX 미국나스닥100TR | <span style="color: tomato">26.8<small>%</small></span> | 22.8<small>%</small> | 1.18 | -15.9<small>%</small> | -5.2<small>%</small> |