| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [삼성 코스피 200 TR ETN](/530117-vs-278530/) | <span style="color: tomato">3.6<small>%</small></span> | 20.8<small>%</small> | 0.17 | -16.9<small>%</small> | -4.6<small>%</small> |
| KODEX 200TR | <span style="color: tomato">3.4<small>%</small></span> | 20.6<small>%</small> | 0.16 | -16.1<small>%</small> | -4.5<small>%</small> |