| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [삼성 코스닥 150 TR ETN](/530118-vs-229200/) | <span style="color: cornflowerblue">-7.9<small>%</small></span> | 26.7<small>%</small> | -0.30 | -26.0<small>%</small> | -9.6<small>%</small> |
| KODEX 코스닥150 | <span style="color: cornflowerblue">-9.7<small>%</small></span> | 26.7<small>%</small> | -0.36 | -25.3<small>%</small> | -9.4<small>%</small> |