| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [삼성 코스피 200 TR ETN](/530117-vs-278530/) | <span style="color: tomato">2.0<small>%</small></span> | 21.1<small>%</small> | 0.10 | -16.9<small>%</small> | -4.2<small>%</small> |
| KODEX 200TR | <span style="color: tomato">1.6<small>%</small></span> | 20.9<small>%</small> | 0.08 | -16.1<small>%</small> | -4.1<small>%</small> |