| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [삼성 코스닥 150 TR ETN](/530118-vs-229200/) | <span style="color: cornflowerblue">-14.2<small>%</small></span> | 26.8<small>%</small> | -0.53 | -26.0<small>%</small> | -9.2<small>%</small> |
| KODEX 코스닥150 | <span style="color: cornflowerblue">-16.0<small>%</small></span> | 26.8<small>%</small> | -0.60 | -25.3<small>%</small> | -9.1<small>%</small> |