| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [삼성 나스닥 100 ETN](/530120-vs-379810/) | <span style="color: tomato">21.4<small>%</small></span> | 24.9<small>%</small> | 0.86 | -16.0<small>%</small> | -5.5<small>%</small> |
| KODEX 미국나스닥100TR | <span style="color: tomato">21.0<small>%</small></span> | 23.6<small>%</small> | 0.89 | -15.9<small>%</small> | -5.5<small>%</small> |