| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [삼성 나스닥 100 ETN](/530120-vs-379810/) | <span style="color: tomato">24.1<small>%</small></span> | 24.3<small>%</small> | 0.99 | -16.0<small>%</small> | -5.4<small>%</small> |
| KODEX 미국나스닥100TR | <span style="color: tomato">24.4<small>%</small></span> | 23.0<small>%</small> | 1.06 | -15.9<small>%</small> | -5.3<small>%</small> |