| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [삼성 S&P500 ETN](/530112-vs-379800/) | <span style="color: tomato">28.1<small>%</small></span> | 11.4<small>%</small> | 2.46 | -8.5<small>%</small> | -1.5<small>%</small> |
| KODEX 미국S&P500TR | <span style="color: tomato">27.7<small>%</small></span> | 11.5<small>%</small> | 2.41 | -8.9<small>%</small> | -1.5<small>%</small> |