| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [삼성 S&P500 ETN](/530112-vs-379800/) | <span style="color: tomato">28.2<small>%</small></span> | 11.2<small>%</small> | 2.51 | -8.5<small>%</small> | -1.3<small>%</small> |
| KODEX 미국S&P500TR | <span style="color: tomato">27.9<small>%</small></span> | 11.4<small>%</small> | 2.45 | -8.9<small>%</small> | -1.3<small>%</small> |