| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [키움 INDXX 미국테크탑10 ETN](/760005-vs-381170/) | <span style="color: tomato">61.1<small>%</small></span> | 21.7<small>%</small> | 2.82 | -17.8<small>%</small> | -2.4<small>%</small> |
| TIGER 미국테크TOP10 INDXX | <span style="color: tomato">59.5<small>%</small></span> | 23.3<small>%</small> | 2.56 | -22.6<small>%</small> | -2.2<small>%</small> |