| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [키움 INDXX 미국테크탑10 ETN](/760005-vs-381170/) | <span style="color: tomato">69.4<small>%</small></span> | 21.6<small>%</small> | 3.21 | -17.8<small>%</small> | -2.1<small>%</small> |
| TIGER 미국테크TOP10 INDXX | <span style="color: tomato">69.1<small>%</small></span> | 23.2<small>%</small> | 2.98 | -22.6<small>%</small> | -1.9<small>%</small> |