| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [키움 INDXX 미국테크탑10 ETN](/760005-vs-381170/) | <span style="color: tomato">65.7<small>%</small></span> | 21.7<small>%</small> | 3.03 | -17.8<small>%</small> | -2.6<small>%</small> |
| TIGER 미국테크TOP10 INDXX | <span style="color: tomato">64.9<small>%</small></span> | 23.2<small>%</small> | 2.79 | -22.6<small>%</small> | -2.4<small>%</small> |