| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ABNY](/abny-vs-abnb/) | <span style="color: cornflowerblue">-33.1<small>%</small></span> | 34.7<small>%</small> | -0.96 | -23.7<small>%</small> | -12.0<small>%</small> |
| ABNB | <span style="color: cornflowerblue">-36.4<small>%</small></span> | 38.1<small>%</small> | -0.96 | -26.8<small>%</small> | -15.2<small>%</small> |