| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ABNY](/abny-vs-abnb/) | <span style="color: cornflowerblue">-35.4<small>%</small></span> | 34.8<small>%</small> | -1.01 | -23.7<small>%</small> | -12.0<small>%</small> |
| ABNB | <span style="color: cornflowerblue">-40.4<small>%</small></span> | 38.2<small>%</small> | -1.06 | -26.8<small>%</small> | -15.2<small>%</small> |