| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ABNY](/abny-vs-abnb/) | <span style="color: cornflowerblue">-30.3<small>%</small></span> | 34.2<small>%</small> | -0.89 | -23.7<small>%</small> | -12.0<small>%</small> |
| ABNB | <span style="color: cornflowerblue">-32.4<small>%</small></span> | 37.8<small>%</small> | -0.86 | -26.8<small>%</small> | -15.1<small>%</small> |