| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [AIEQ](/aieq-vs-spy/) | <span style="color: tomato">7.4<small>%</small></span> | 23.2<small>%</small> | 0.32 | -39.0<small>%</small> | -12.7<small>%</small> |
| SPY | <span style="color: tomato">13.5<small>%</small></span> | 19.4<small>%</small> | 0.69 | -33.7<small>%</small> | -5.5<small>%</small> |