| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [AIEQ](/aieq-vs-spy/) | <span style="color: tomato">6.3<small>%</small></span> | 23.2<small>%</small> | 0.27 | -39.0<small>%</small> | -12.6<small>%</small> |
| SPY | <span style="color: tomato">12.8<small>%</small></span> | 19.4<small>%</small> | 0.66 | -33.7<small>%</small> | -5.6<small>%</small> |