| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [AIIQ](/aiiq-vs-spy/) | <span style="color: cornflowerblue">-0.7<small>%</small></span> | 20.4<small>%</small> | -0.04 | -36.7<small>%</small> | -7.5<small>%</small> |
| SPY | <span style="color: tomato">9.9<small>%</small></span> | 21.7<small>%</small> | 0.46 | -34.1<small>%</small> | -4.8<small>%</small> |