| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [AIVL](/aivl-vs-spy/) | <span style="color: tomato">7.5<small>%</small></span> | 19.8<small>%</small> | 0.38 | -62.5<small>%</small> | -8.7<small>%</small> |
| SPY | <span style="color: tomato">10.4<small>%</small></span> | 19.7<small>%</small> | 0.53 | -55.2<small>%</small> | -8.1<small>%</small> |