| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [AIYY](/aiyy-vs-ai/) | <span style="color: cornflowerblue">-61.4<small>%</small></span> | 44.3<small>%</small> | -1.39 | -32.8<small>%</small> | -11.8<small>%</small> |
| C3.ai Inc | <span style="color: cornflowerblue">-62.5<small>%</small></span> | 75.7<small>%</small> | -0.83 | -43.6<small>%</small> | -16.5<small>%</small> |