| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [AIYY](/aiyy-vs-ai/) | <span style="color: cornflowerblue">-32.1<small>%</small></span> | 42.9<small>%</small> | -0.75 | -33.7<small>%</small> | -16.5<small>%</small> |
| C3.ai Inc | <span style="color: cornflowerblue">-4.1<small>%</small></span> | 69.5<small>%</small> | -0.06 | -44.5<small>%</small> | -21.1<small>%</small> |