| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [AIYY](/aiyy-vs-ai/) | <span style="color: cornflowerblue">-28.3<small>%</small></span> | 44.4<small>%</small> | -0.64 | -33.7<small>%</small> | -15.9<small>%</small> |
| C3.ai Inc | <span style="color: cornflowerblue">-1.4<small>%</small></span> | 72.7<small>%</small> | -0.02 | -44.5<small>%</small> | -21.1<small>%</small> |