| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [AMDY](/amdy-vs-amd/) | <span style="color: tomato">22.6<small>%</small></span> | 38.6<small>%</small> | 0.59 | -32.0<small>%</small> | -10.2<small>%</small> |
| AMD | <span style="color: tomato">54.2<small>%</small></span> | 48.1<small>%</small> | 1.13 | -39.1<small>%</small> | -12.9<small>%</small> |