| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [AMDY](/amdy-vs-amd/) | <span style="color: tomato">26.2<small>%</small></span> | 37.6<small>%</small> | 0.70 | -26.2<small>%</small> | -8.5<small>%</small> |
| Advanced Micro Devices Inc | <span style="color: tomato">63.7<small>%</small></span> | 47.2<small>%</small> | 1.35 | -31.7<small>%</small> | -10.9<small>%</small> |