| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [AMDY](/amdy-vs-amd/) | <span style="color: tomato">14.1<small>%</small></span> | 38.6<small>%</small> | 0.36 | -32.0<small>%</small> | -10.7<small>%</small> |
| AMD | <span style="color: tomato">38.9<small>%</small></span> | 48.3<small>%</small> | 0.80 | -39.1<small>%</small> | -13.6<small>%</small> |