| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [AMOM](/amom-vs-spy/) | <span style="color: tomato">17.3<small>%</small></span> | 24.1<small>%</small> | 0.72 | -40.0<small>%</small> | -12.6<small>%</small> |
| SPY | <span style="color: tomato">15.5<small>%</small></span> | 20.6<small>%</small> | 0.75 | -33.7<small>%</small> | -6.1<small>%</small> |