| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [AMOM](/amom-vs-spy/) | <span style="color: tomato">16.0<small>%</small></span> | 24.4<small>%</small> | 0.66 | -40.0<small>%</small> | -13.2<small>%</small> |
| SPY | <span style="color: tomato">15.0<small>%</small></span> | 21.1<small>%</small> | 0.71 | -33.7<small>%</small> | -6.4<small>%</small> |