| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [AMOM](/amom-vs-spy/) | <span style="color: tomato">16.3<small>%</small></span> | 24.4<small>%</small> | 0.67 | -40.0<small>%</small> | -12.4<small>%</small> |
| SPY | <span style="color: tomato">15.5<small>%</small></span> | 20.5<small>%</small> | 0.76 | -33.7<small>%</small> | -6.0<small>%</small> |