| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [AMZY](/amzy-vs-amzn/) | <span style="color: tomato">66.5<small>%</small></span> | 25.3<small>%</small> | 2.62 | -12.3<small>%</small> | -2.3<small>%</small> |
| Amazon.com Inc | <span style="color: tomato">64.2<small>%</small></span> | 29.2<small>%</small> | 2.20 | -17.5<small>%</small> | -3.4<small>%</small> |