| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [AMZY](/amzy-vs-amzn/) | <span style="color: tomato">34.6<small>%</small></span> | 24.8<small>%</small> | 1.40 | -16.4<small>%</small> | -3.1<small>%</small> |
| AMZN | <span style="color: tomato">33.8<small>%</small></span> | 29.2<small>%</small> | 1.16 | -19.5<small>%</small> | -4.4<small>%</small> |