| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [AMZY](/amzy-vs-amzn/) | <span style="color: tomato">35.2<small>%</small></span> | 24.7<small>%</small> | 1.42 | -16.4<small>%</small> | -3.2<small>%</small> |
| AMZN | <span style="color: tomato">37.0<small>%</small></span> | 29.3<small>%</small> | 1.26 | -19.5<small>%</small> | -4.4<small>%</small> |