| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [APLY](/aply-vs-aapl/) | <span style="color: tomato">0.2<small>%</small></span> | 15.6<small>%</small> | 0.01 | -15.9<small>%</small> | -6.8<small>%</small> |
| Apple Inc | <span style="color: cornflowerblue">-0.5<small>%</small></span> | 19.5<small>%</small> | -0.03 | -16.6<small>%</small> | -6.0<small>%</small> |