| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [APLY](/aply-vs-aapl/) | <span style="color: tomato">13.4<small>%</small></span> | 16.2<small>%</small> | 0.83 | -15.9<small>%</small> | -6.3<small>%</small> |
| AAPL | <span style="color: tomato">24.1<small>%</small></span> | 21.4<small>%</small> | 1.12 | -16.6<small>%</small> | -5.7<small>%</small> |