| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [APLY](/aply-vs-aapl/) | <span style="color: tomato">2.8<small>%</small></span> | 15.7<small>%</small> | 0.18 | -15.9<small>%</small> | -6.4<small>%</small> |
| Apple Inc | <span style="color: tomato">2.6<small>%</small></span> | 19.2<small>%</small> | 0.14 | -14.9<small>%</small> | -5.4<small>%</small> |