| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ARKG](/arkg-vs-xbi/) | <span style="color: tomato">3.8<small>%</small></span> | 38.3<small>%</small> | 0.10 | -80.1<small>%</small> | -28.1<small>%</small> |
| XBI | <span style="color: tomato">6.1<small>%</small></span> | 33.7<small>%</small> | 0.18 | -63.9<small>%</small> | -25.6<small>%</small> |