| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ARKG](/arkg-vs-xbi/) | <span style="color: tomato">3.3<small>%</small></span> | 38.3<small>%</small> | 0.09 | -80.1<small>%</small> | -29.0<small>%</small> |
| XBI | <span style="color: tomato">5.9<small>%</small></span> | 33.5<small>%</small> | 0.18 | -63.9<small>%</small> | -25.9<small>%</small> |