| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ARKK](/arkk-vs-qld/) | <span style="color: tomato">9.9<small>%</small></span> | 37.4<small>%</small> | 0.26 | -80.9<small>%</small> | -24.6<small>%</small> |
| QLD | <span style="color: tomato">30.6<small>%</small></span> | 43.3<small>%</small> | 0.71 | -63.7<small>%</small> | -14.3<small>%</small> |