| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ARKK](/arkk-vs-qld/) | <span style="color: tomato">10.0<small>%</small></span> | 37.4<small>%</small> | 0.27 | -80.9<small>%</small> | -24.8<small>%</small> |
| QLD | <span style="color: tomato">29.4<small>%</small></span> | 43.3<small>%</small> | 0.68 | -63.7<small>%</small> | -14.2<small>%</small> |