| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ARKK](/arkk-vs-qld/) | <span style="color: tomato">9.5<small>%</small></span> | 37.6<small>%</small> | 0.25 | -80.9<small>%</small> | -24.2<small>%</small> |
| QLD | <span style="color: tomato">29.0<small>%</small></span> | 43.4<small>%</small> | 0.67 | -63.7<small>%</small> | -14.4<small>%</small> |