| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ARKK](/arkk-vs-qqq/) | <span style="color: tomato">10.9<small>%</small></span> | 37.7<small>%</small> | 0.29 | -80.9<small>%</small> | -23.2<small>%</small> |
| QQQ | <span style="color: tomato">17.8<small>%</small></span> | 21.9<small>%</small> | 0.82 | -35.1<small>%</small> | -6.4<small>%</small> |