| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ARKK](/arkk-vs-qqq/) | <span style="color: tomato">10.7<small>%</small></span> | 37.4<small>%</small> | 0.29 | -80.9<small>%</small> | -24.7<small>%</small> |
| QQQ | <span style="color: tomato">18.7<small>%</small></span> | 21.7<small>%</small> | 0.86 | -35.1<small>%</small> | -6.3<small>%</small> |