| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ARKK](/arkk-vs-qqq/) | <span style="color: tomato">9.4<small>%</small></span> | 37.7<small>%</small> | 0.25 | -80.9<small>%</small> | -23.6<small>%</small> |
| QQQ | <span style="color: tomato">17.2<small>%</small></span> | 21.8<small>%</small> | 0.79 | -35.1<small>%</small> | -6.4<small>%</small> |