| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [BALI](/bali-vs-jepq/) | <span style="color: tomato">31.3<small>%</small></span> | 10.2<small>%</small> | 3.07 | -7.7<small>%</small> | -1.0<small>%</small> |
| JEPQ | <span style="color: tomato">28.5<small>%</small></span> | 12.5<small>%</small> | 2.27 | -10.7<small>%</small> | -1.4<small>%</small> |