| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [BALI](/bali-vs-spy/) | <span style="color: tomato">23.7<small>%</small></span> | 10.1<small>%</small> | 2.34 | -7.7<small>%</small> | -0.9<small>%</small> |
| SPY | <span style="color: tomato">26.4<small>%</small></span> | 12.1<small>%</small> | 2.17 | -8.4<small>%</small> | -1.1<small>%</small> |