| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [BALI](/bali-vs-spyi/) | <span style="color: tomato">27.6<small>%</small></span> | 9.6<small>%</small> | 2.86 | -5.3<small>%</small> | -0.8<small>%</small> |
| SPYI | <span style="color: tomato">17.7<small>%</small></span> | 8.2<small>%</small> | 2.16 | -4.7<small>%</small> | -0.6<small>%</small> |