| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [BALI](/bali-vs-gpiq/) | <span style="color: tomato">41.1<small>%</small></span> | 9.0<small>%</small> | 4.57 | -4.8<small>%</small> | -0.6<small>%</small> |
| GPIQ | <span style="color: tomato">38.5<small>%</small></span> | 12.8<small>%</small> | 3.00 | -7.3<small>%</small> | -0.9<small>%</small> |