| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [BALI](/bali-vs-jepq/) | <span style="color: tomato">35.5<small>%</small></span> | 9.4<small>%</small> | 3.77 | -5.3<small>%</small> | -0.8<small>%</small> |
| JEPQ | <span style="color: tomato">37.6<small>%</small></span> | 10.9<small>%</small> | 3.43 | -6.0<small>%</small> | -0.7<small>%</small> |