| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [BALI](/bali-vs-qqq/) | <span style="color: tomato">35.2<small>%</small></span> | 9.1<small>%</small> | 3.86 | -5.3<small>%</small> | -0.7<small>%</small> |
| QQQ | <span style="color: tomato">44.7<small>%</small></span> | 15.5<small>%</small> | 2.88 | -7.4<small>%</small> | -1.2<small>%</small> |