| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [BALI](/bali-vs-gpix/) | <span style="color: tomato">39.2<small>%</small></span> | 10.0<small>%</small> | 3.91 | -7.7<small>%</small> | -0.9<small>%</small> |
| GPIX | <span style="color: tomato">38.5<small>%</small></span> | 10.5<small>%</small> | 3.66 | -7.0<small>%</small> | -0.8<small>%</small> |