| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [BALI](/bali-vs-spy/) | <span style="color: tomato">31.8<small>%</small></span> | 10.3<small>%</small> | 3.08 | -7.7<small>%</small> | -1.0<small>%</small> |
| SPY | <span style="color: tomato">36.4<small>%</small></span> | 12.4<small>%</small> | 2.94 | -8.4<small>%</small> | -1.2<small>%</small> |