| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [BALI](/bali-vs-jepy/) | <span style="color: tomato">31.0<small>%</small></span> | 10.3<small>%</small> | 3.02 | -7.7<small>%</small> | -1.0<small>%</small> |
| JEPY | <span style="color: tomato">672.6<small>%</small></span> | 201.9<small>%</small> | 3.33 | -4.3<small>%</small> | -0.6<small>%</small> |