| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [BALI](/bali-vs-spyi/) | <span style="color: tomato">30.2<small>%</small></span> | 10.3<small>%</small> | 2.95 | -7.7<small>%</small> | -1.0<small>%</small> |
| SPYI | <span style="color: tomato">22.4<small>%</small></span> | 9.3<small>%</small> | 2.40 | -6.6<small>%</small> | -0.7<small>%</small> |