| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [BALI](/bali-vs-spyi/) | <span style="color: tomato">36.6<small>%</small></span> | 9.1<small>%</small> | 4.02 | -5.3<small>%</small> | -0.7<small>%</small> |
| SPYI | <span style="color: tomato">23.7<small>%</small></span> | 7.6<small>%</small> | 3.13 | -4.7<small>%</small> | -0.6<small>%</small> |