| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [BALI](/bali-vs-qqq/) | <span style="color: tomato">30.8<small>%</small></span> | 9.4<small>%</small> | 3.28 | -5.3<small>%</small> | -0.7<small>%</small> |
| QQQ | <span style="color: tomato">37.8<small>%</small></span> | 16.0<small>%</small> | 2.36 | -7.9<small>%</small> | -1.3<small>%</small> |