| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [BALI](/bali-vs-spy/) | <span style="color: tomato">30.2<small>%</small></span> | 10.4<small>%</small> | 2.90 | -7.7<small>%</small> | -1.1<small>%</small> |
| SPY | <span style="color: tomato">34.0<small>%</small></span> | 12.5<small>%</small> | 2.72 | -8.4<small>%</small> | -1.2<small>%</small> |