| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [BALI](/bali-vs-jepy/) | <span style="color: tomato">35.4<small>%</small></span> | 9.1<small>%</small> | 3.89 | -5.3<small>%</small> | -0.7<small>%</small> |
| JEPY | <span style="color: tomato">24.5<small>%</small></span> | 7.0<small>%</small> | 3.52 | -3.9<small>%</small> | -0.6<small>%</small> |