| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [BALI](/bali-vs-qqq/) | <span style="color: tomato">37.0<small>%</small></span> | 9.1<small>%</small> | 4.07 | -5.3<small>%</small> | -0.7<small>%</small> |
| QQQ | <span style="color: tomato">51.8<small>%</small></span> | 15.3<small>%</small> | 3.39 | -7.4<small>%</small> | -1.2<small>%</small> |