| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [BALI](/bali-vs-jepy/) | <span style="color: tomato">29.0<small>%</small></span> | 9.6<small>%</small> | 3.01 | -5.3<small>%</small> | -0.8<small>%</small> |
| JEPY | <span style="color: tomato">333.3<small>%</small></span> | 212.5<small>%</small> | 1.57 | -4.3<small>%</small> | -0.7<small>%</small> |