| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [BALI](/bali-vs-gpiq/) | <span style="color: tomato">38.4<small>%</small></span> | 9.9<small>%</small> | 3.87 | -7.7<small>%</small> | -0.9<small>%</small> |
| GPIQ | <span style="color: tomato">37.5<small>%</small></span> | 14.5<small>%</small> | 2.58 | -11.7<small>%</small> | -1.7<small>%</small> |