| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [BALI](/bali-vs-jepq/) | <span style="color: tomato">30.6<small>%</small></span> | 10.4<small>%</small> | 2.95 | -7.7<small>%</small> | -1.0<small>%</small> |
| JEPQ | <span style="color: tomato">26.9<small>%</small></span> | 12.8<small>%</small> | 2.09 | -10.7<small>%</small> | -1.2<small>%</small> |