| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [BALI](/bali-vs-gpiq/) | <span style="color: tomato">35.4<small>%</small></span> | 10.0<small>%</small> | 3.55 | -7.7<small>%</small> | -0.9<small>%</small> |
| GPIQ | <span style="color: tomato">32.2<small>%</small></span> | 14.3<small>%</small> | 2.24 | -11.7<small>%</small> | -1.3<small>%</small> |