| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [BALI](/bali-vs-jepi/) | <span style="color: tomato">30.9<small>%</small></span> | 10.2<small>%</small> | 3.04 | -7.7<small>%</small> | -1.0<small>%</small> |
| JEPI | <span style="color: tomato">19.0<small>%</small></span> | 7.6<small>%</small> | 2.50 | -4.7<small>%</small> | -0.6<small>%</small> |