| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [BALI](/bali-vs-jepi/) | <span style="color: tomato">34.1<small>%</small></span> | 9.2<small>%</small> | 3.72 | -5.3<small>%</small> | -0.7<small>%</small> |
| JEPI | <span style="color: tomato">14.2<small>%</small></span> | 7.1<small>%</small> | 2.00 | -4.7<small>%</small> | -0.7<small>%</small> |