| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [BALI](/bali-vs-gpix/) | <span style="color: tomato">48.7<small>%</small></span> | 8.8<small>%</small> | 5.55 | -4.8<small>%</small> | -0.6<small>%</small> |
| GPIX | <span style="color: tomato">46.2<small>%</small></span> | 9.2<small>%</small> | 5.00 | -5.0<small>%</small> | -0.6<small>%</small> |