| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [BNDI](/bndi-vs-bnd/) | <span style="color: tomato">1.4<small>%</small></span> | 7.5<small>%</small> | 0.18 | -6.9<small>%</small> | -2.3<small>%</small> |
| BND | <span style="color: tomato">0.6<small>%</small></span> | 7.3<small>%</small> | 0.08 | -7.2<small>%</small> | -2.4<small>%</small> |