| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [BNDI](/bndi-vs-bnd/) | <span style="color: tomato">1.6<small>%</small></span> | 7.4<small>%</small> | 0.21 | -7.0<small>%</small> | -2.3<small>%</small> |
| BND | <span style="color: tomato">0.9<small>%</small></span> | 7.2<small>%</small> | 0.13 | -7.2<small>%</small> | -2.5<small>%</small> |