| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [BNDI](/bndi-vs-bnd/) | <span style="color: tomato">1.3<small>%</small></span> | 7.3<small>%</small> | 0.18 | -7.0<small>%</small> | -2.3<small>%</small> |
| BND | <span style="color: tomato">0.7<small>%</small></span> | 7.2<small>%</small> | 0.10 | -7.2<small>%</small> | -2.4<small>%</small> |