| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [BRK-A](/brk-a-vs-spy/) | <span style="color: tomato">13.3<small>%</small></span> | 22.5<small>%</small> | 0.59 | -51.5<small>%</small> | -10.6<small>%</small> |
| SPY | <span style="color: tomato">10.2<small>%</small></span> | 18.7<small>%</small> | 0.54 | -55.2<small>%</small> | -9.6<small>%</small> |