| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [BRK-A](/brk-a-vs-spy/) | <span style="color: tomato">13.4<small>%</small></span> | 22.4<small>%</small> | 0.60 | -51.5<small>%</small> | -10.5<small>%</small> |
| SPY | <span style="color: tomato">8.3<small>%</small></span> | 18.6<small>%</small> | 0.45 | -56.5<small>%</small> | -11.3<small>%</small> |