| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [BRK-A](/brk-a-vs-us500/) | <span style="color: tomato">19.0<small>%</small></span> | 22.6<small>%</small> | 0.84 | -51.5<small>%</small> | -9.7<small>%</small> |
| US500 | <span style="color: tomato">9.3<small>%</small></span> | 17.8<small>%</small> | 0.52 | -56.8<small>%</small> | -10.0<small>%</small> |