| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [BRK-B](/brk-b-vs-spy/) | <span style="color: tomato">10.7<small>%</small></span> | 22.4<small>%</small> | 0.48 | -53.9<small>%</small> | -11.4<small>%</small> |
| SPY | <span style="color: tomato">9.8<small>%</small></span> | 19.4<small>%</small> | 0.50 | -55.2<small>%</small> | -10.4<small>%</small> |