| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [CONY](/cony-vs-coin/) | <span style="color: tomato">61.6<small>%</small></span> | 54.5<small>%</small> | 1.13 | -37.7<small>%</small> | -10.6<small>%</small> |
| COIN | <span style="color: tomato">124.0<small>%</small></span> | 73.1<small>%</small> | 1.70 | -47.3<small>%</small> | -16.3<small>%</small> |