| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [CONY](/cony-vs-coin/) | <span style="color: tomato">202.4<small>%</small></span> | 50.2<small>%</small> | 4.03 | -29.1<small>%</small> | -7.5<small>%</small> |
| Coinbase Global Inc | <span style="color: tomato">484.7<small>%</small></span> | 71.4<small>%</small> | 6.79 | -37.1<small>%</small> | -10.1<small>%</small> |