| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [CONY](/cony-vs-coin/) | <span style="color: tomato">266.7<small>%</small></span> | 52.1<small>%</small> | 5.12 | -29.1<small>%</small> | -6.8<small>%</small> |
| Coinbase Global Inc | <span style="color: tomato">524.3<small>%</small></span> | 73.9<small>%</small> | 7.10 | -37.1<small>%</small> | -9.3<small>%</small> |