| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [CSHI](/cshi-vs-bil/) | <span style="color: tomato">5.1<small>%</small></span> | 1.1<small>%</small> | 4.78 | -0.5<small>%</small> | -0.0<small>%</small> |
| BIL | <span style="color: tomato">4.6<small>%</small></span> | 0.3<small>%</small> | 16.52 | -0.0<small>%</small> | -0.0<small>%</small> |