| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [CSHI](/cshi-vs-bil/) | <span style="color: tomato">5.4<small>%</small></span> | 1.0<small>%</small> | 5.67 | -0.4<small>%</small> | -0.0<small>%</small> |
| BIL | <span style="color: tomato">4.4<small>%</small></span> | 0.4<small>%</small> | 10.14 | -0.4<small>%</small> | -0.0<small>%</small> |