| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [CSHI](/cshi-vs-bil/) | <span style="color: tomato">5.4<small>%</small></span> | 0.9<small>%</small> | 5.76 | -0.4<small>%</small> | -0.0<small>%</small> |
| BIL | <span style="color: tomato">4.7<small>%</small></span> | 0.3<small>%</small> | 17.07 | -0.0<small>%</small> | -0.0<small>%</small> |