| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [DGRO](/dgro-vs-schd/) | <span style="color: tomato">8.9<small>%</small></span> | 16.7<small>%</small> | 0.53 | -35.1<small>%</small> | -4.5<small>%</small> |
| SCHD | <span style="color: tomato">7.6<small>%</small></span> | 16.6<small>%</small> | 0.46 | -33.4<small>%</small> | -5.0<small>%</small> |