| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [DGRO](/dgro-vs-schd/) | <span style="color: tomato">11.5<small>%</small></span> | 16.7<small>%</small> | 0.69 | -35.1<small>%</small> | -3.8<small>%</small> |
| SCHD | <span style="color: tomato">11.2<small>%</small></span> | 16.6<small>%</small> | 0.67 | -33.4<small>%</small> | -3.8<small>%</small> |