| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [DGRO](/dgro-vs-schd/) | <span style="color: tomato">11.4<small>%</small></span> | 16.7<small>%</small> | 0.68 | -35.1<small>%</small> | -3.8<small>%</small> |
| SCHD | <span style="color: tomato">10.9<small>%</small></span> | 16.5<small>%</small> | 0.66 | -33.4<small>%</small> | -3.8<small>%</small> |