| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [DISO](/diso-vs-dis/) | <span style="color: tomato">0.5<small>%</small></span> | 20.0<small>%</small> | 0.02 | -22.9<small>%</small> | -5.6<small>%</small> |
| DIS | <span style="color: tomato">4.4<small>%</small></span> | 26.9<small>%</small> | 0.16 | -29.7<small>%</small> | -7.7<small>%</small> |