| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [DISO](/diso-vs-dis/) | <span style="color: tomato">7.4<small>%</small></span> | 19.2<small>%</small> | 0.39 | -22.9<small>%</small> | -7.0<small>%</small> |
| DIS | <span style="color: tomato">12.1<small>%</small></span> | 26.0<small>%</small> | 0.46 | -30.0<small>%</small> | -9.6<small>%</small> |