| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [DISO](/diso-vs-dis/) | <span style="color: tomato">44.6<small>%</small></span> | 18.3<small>%</small> | 2.44 | -6.0<small>%</small> | -1.8<small>%</small> |
| Walt Disney Co | <span style="color: tomato">79.1<small>%</small></span> | 27.1<small>%</small> | 2.92 | -8.0<small>%</small> | -2.6<small>%</small> |