| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [DIVO](/divo-vs-schd/) | <span style="color: tomato">11.8<small>%</small></span> | 15.4<small>%</small> | 0.77 | -30.0<small>%</small> | -2.8<small>%</small> |
| SCHD | <span style="color: tomato">12.0<small>%</small></span> | 17.6<small>%</small> | 0.68 | -33.4<small>%</small> | -4.2<small>%</small> |