| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [DIVO](/divo-vs-schd/) | <span style="color: tomato">11.8<small>%</small></span> | 15.6<small>%</small> | 0.75 | -30.0<small>%</small> | -2.9<small>%</small> |
| SCHD | <span style="color: tomato">11.9<small>%</small></span> | 17.8<small>%</small> | 0.67 | -33.4<small>%</small> | -4.3<small>%</small> |