| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [DIVO](/divo-vs-idvo/) | <span style="color: tomato">13.1<small>%</small></span> | 10.7<small>%</small> | 1.22 | -8.9<small>%</small> | -2.1<small>%</small> |
| IDVO | <span style="color: tomato">16.6<small>%</small></span> | 15.6<small>%</small> | 1.06 | -11.0<small>%</small> | -2.8<small>%</small> |