| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [DJIA](/djia-vs-dia/) | <span style="color: tomato">4.4<small>%</small></span> | 10.9<small>%</small> | 0.40 | -16.9<small>%</small> | -4.9<small>%</small> |
| DIA | <span style="color: tomato">10.6<small>%</small></span> | 14.9<small>%</small> | 0.71 | -17.8<small>%</small> | -4.0<small>%</small> |