| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [DJIA](/djia-vs-dia/) | <span style="color: tomato">4.2<small>%</small></span> | 11.2<small>%</small> | 0.37 | -16.9<small>%</small> | -5.3<small>%</small> |
| DIA | <span style="color: tomato">8.0<small>%</small></span> | 15.4<small>%</small> | 0.52 | -17.8<small>%</small> | -4.2<small>%</small> |