| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [DJIA](/djia-vs-dia/) | <span style="color: tomato">6.5<small>%</small></span> | 10.8<small>%</small> | 0.60 | -16.9<small>%</small> | -4.5<small>%</small> |
| DIA | <span style="color: tomato">12.1<small>%</small></span> | 14.8<small>%</small> | 0.82 | -17.8<small>%</small> | -3.8<small>%</small> |