| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [EDOW](/edow-vs-dia/) | <span style="color: tomato">10.2<small>%</small></span> | 18.5<small>%</small> | 0.55 | -33.7<small>%</small> | -4.6<small>%</small> |
| DIA | <span style="color: tomato">11.3<small>%</small></span> | 19.1<small>%</small> | 0.59 | -36.7<small>%</small> | -4.7<small>%</small> |