| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [EDOW](/edow-vs-dia/) | <span style="color: tomato">10.5<small>%</small></span> | 18.8<small>%</small> | 0.56 | -33.7<small>%</small> | -4.7<small>%</small> |
| DIA | <span style="color: tomato">11.5<small>%</small></span> | 19.4<small>%</small> | 0.59 | -36.7<small>%</small> | -4.8<small>%</small> |