| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [EDOW](/edow-vs-dia/) | <span style="color: tomato">10.5<small>%</small></span> | 18.9<small>%</small> | 0.55 | -33.7<small>%</small> | -4.7<small>%</small> |
| DIA | <span style="color: tomato">11.4<small>%</small></span> | 19.5<small>%</small> | 0.58 | -36.7<small>%</small> | -4.9<small>%</small> |