| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [EWJ](/ewj-vs-idvo/) | <span style="color: tomato">18.4<small>%</small></span> | 17.0<small>%</small> | 1.09 | -12.2<small>%</small> | -3.0<small>%</small> |
| IDVO | <span style="color: tomato">17.7<small>%</small></span> | 15.7<small>%</small> | 1.13 | -11.0<small>%</small> | -2.7<small>%</small> |