| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [EWJ](/ewj-vs-idvo/) | <span style="color: tomato">17.8<small>%</small></span> | 17.2<small>%</small> | 1.04 | -12.2<small>%</small> | -3.0<small>%</small> |
| IDVO | <span style="color: tomato">16.4<small>%</small></span> | 15.7<small>%</small> | 1.05 | -11.0<small>%</small> | -2.8<small>%</small> |