| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [EWJ](/ewj-vs-idvo/) | <span style="color: tomato">21.0<small>%</small></span> | 16.0<small>%</small> | 1.31 | -10.1<small>%</small> | -2.9<small>%</small> |
| IDVO | <span style="color: tomato">20.0<small>%</small></span> | 15.4<small>%</small> | 1.30 | -11.0<small>%</small> | -2.7<small>%</small> |