| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [EWJV](/ewjv-vs-idvo/) | <span style="color: tomato">25.1<small>%</small></span> | 16.2<small>%</small> | 1.55 | -10.3<small>%</small> | -2.6<small>%</small> |
| IDVO | <span style="color: tomato">18.7<small>%</small></span> | 15.4<small>%</small> | 1.22 | -11.0<small>%</small> | -2.7<small>%</small> |