| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [EWJV](/ewjv-vs-idvo/) | <span style="color: tomato">23.0<small>%</small></span> | 17.2<small>%</small> | 1.34 | -12.0<small>%</small> | -2.7<small>%</small> |
| IDVO | <span style="color: tomato">17.9<small>%</small></span> | 15.7<small>%</small> | 1.14 | -11.0<small>%</small> | -2.7<small>%</small> |