| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [EWJV](/ewjv-vs-idvo/) | <span style="color: tomato">24.2<small>%</small></span> | 16.3<small>%</small> | 1.48 | -10.3<small>%</small> | -2.7<small>%</small> |
| IDVO | <span style="color: tomato">18.4<small>%</small></span> | 15.5<small>%</small> | 1.19 | -11.0<small>%</small> | -2.7<small>%</small> |