| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [FBY](/fby-vs-meta/) | <span style="color: tomato">60.5<small>%</small></span> | 24.5<small>%</small> | 2.47 | -11.1<small>%</small> | -2.4<small>%</small> |
| Meta Platforms Inc | <span style="color: tomato">85.1<small>%</small></span> | 36.0<small>%</small> | 2.36 | -12.2<small>%</small> | -3.4<small>%</small> |