| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [FBY](/fby-vs-meta/) | <span style="color: tomato">39.5<small>%</small></span> | 26.3<small>%</small> | 1.50 | -14.8<small>%</small> | -3.4<small>%</small> |
| Meta Platforms Inc | <span style="color: tomato">57.0<small>%</small></span> | 36.6<small>%</small> | 1.56 | -18.4<small>%</small> | -4.8<small>%</small> |