| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [FBY](/fby-vs-meta/) | <span style="color: tomato">45.0<small>%</small></span> | 27.0<small>%</small> | 1.67 | -14.8<small>%</small> | -2.9<small>%</small> |
| Meta Platforms Inc | <span style="color: tomato">65.2<small>%</small></span> | 37.7<small>%</small> | 1.73 | -18.4<small>%</small> | -4.0<small>%</small> |