| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [FDVV](/fdvv-vs-spy/) | <span style="color: tomato">11.7<small>%</small></span> | 18.0<small>%</small> | 0.65 | -40.3<small>%</small> | -4.4<small>%</small> |
| SPY | <span style="color: tomato">14.1<small>%</small></span> | 18.6<small>%</small> | 0.76 | -33.7<small>%</small> | -5.1<small>%</small> |