| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [FMAG](/fmag-vs-spy/) | <span style="color: tomato">12.7<small>%</small></span> | 19.8<small>%</small> | 0.64 | -32.9<small>%</small> | -11.4<small>%</small> |
| SPY | <span style="color: tomato">13.2<small>%</small></span> | 16.6<small>%</small> | 0.79 | -24.5<small>%</small> | -6.6<small>%</small> |