| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [FMAG](/fmag-vs-qqq/) | <span style="color: tomato">12.0<small>%</small></span> | 19.9<small>%</small> | 0.61 | -32.9<small>%</small> | -11.5<small>%</small> |
| QQQ | <span style="color: tomato">11.6<small>%</small></span> | 22.7<small>%</small> | 0.51 | -35.1<small>%</small> | -11.0<small>%</small> |