| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [FMAG](/fmag-vs-spy/) | <span style="color: tomato">12.2<small>%</small></span> | 20.0<small>%</small> | 0.61 | -32.9<small>%</small> | -11.8<small>%</small> |
| SPY | <span style="color: tomato">12.7<small>%</small></span> | 16.8<small>%</small> | 0.76 | -24.5<small>%</small> | -6.8<small>%</small> |