| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [FMAG](/fmag-vs-qqq/) | <span style="color: tomato">10.3<small>%</small></span> | 19.9<small>%</small> | 0.52 | -32.9<small>%</small> | -11.8<small>%</small> |
| QQQ | <span style="color: tomato">9.9<small>%</small></span> | 22.7<small>%</small> | 0.43 | -35.1<small>%</small> | -11.2<small>%</small> |