| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [FNGO](/fngo-vs-qld/) | <span style="color: tomato">37.0<small>%</small></span> | 63.8<small>%</small> | 0.58 | -78.4<small>%</small> | -27.0<small>%</small> |
| QLD | <span style="color: tomato">26.4<small>%</small></span> | 49.7<small>%</small> | 0.53 | -63.7<small>%</small> | -19.7<small>%</small> |