| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [FNGO](/fngo-vs-qld/) | <span style="color: tomato">35.3<small>%</small></span> | 63.9<small>%</small> | 0.55 | -78.4<small>%</small> | -27.0<small>%</small> |
| QLD | <span style="color: tomato">24.4<small>%</small></span> | 49.8<small>%</small> | 0.49 | -63.7<small>%</small> | -19.8<small>%</small> |