| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [FNGO](/fngo-vs-tqqq/) | <span style="color: tomato">38.1<small>%</small></span> | 63.4<small>%</small> | 0.60 | -78.4<small>%</small> | -26.7<small>%</small> |
| TQQQ | <span style="color: tomato">27.7<small>%</small></span> | 72.9<small>%</small> | 0.38 | -81.7<small>%</small> | -31.4<small>%</small> |