| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [FNGO](/fngo-vs-tqqq/) | <span style="color: tomato">38.7<small>%</small></span> | 63.9<small>%</small> | 0.61 | -78.4<small>%</small> | -27.0<small>%</small> |
| TQQQ | <span style="color: tomato">28.4<small>%</small></span> | 73.5<small>%</small> | 0.39 | -81.7<small>%</small> | -31.8<small>%</small> |