| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [FNGO](/fngo-vs-qld/) | <span style="color: tomato">36.6<small>%</small></span> | 63.8<small>%</small> | 0.57 | -78.4<small>%</small> | -26.9<small>%</small> |
| QLD | <span style="color: tomato">25.6<small>%</small></span> | 49.7<small>%</small> | 0.51 | -63.7<small>%</small> | -19.7<small>%</small> |