| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [FNGO](/fngo-vs-tqqq/) | <span style="color: tomato">34.0<small>%</small></span> | 63.9<small>%</small> | 0.53 | -78.4<small>%</small> | -27.0<small>%</small> |
| TQQQ | <span style="color: tomato">23.5<small>%</small></span> | 73.4<small>%</small> | 0.32 | -81.7<small>%</small> | -31.7<small>%</small> |