| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [FNGU](/fngu-vs-tqqq/) | <span style="color: tomato">30.8<small>%</small></span> | 92.7<small>%</small> | 0.33 | -92.3<small>%</small> | -43.0<small>%</small> |
| TQQQ | <span style="color: tomato">23.1<small>%</small></span> | 72.2<small>%</small> | 0.32 | -81.7<small>%</small> | -29.8<small>%</small> |