| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [FNGU](/fngu-vs-bulz/) | <span style="color: tomato">3.0<small>%</small></span> | 96.4<small>%</small> | 0.03 | -92.3<small>%</small> | -55.7<small>%</small> |
| BULZ | <span style="color: cornflowerblue">-21.5<small>%</small></span> | 92.8<small>%</small> | -0.23 | -94.4<small>%</small> | -67.5<small>%</small> |