| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [FNGU](/fngu-vs-qld/) | <span style="color: tomato">32.3<small>%</small></span> | 92.8<small>%</small> | 0.35 | -92.3<small>%</small> | -43.2<small>%</small> |
| QLD | <span style="color: tomato">23.7<small>%</small></span> | 48.9<small>%</small> | 0.48 | -63.7<small>%</small> | -18.6<small>%</small> |