| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [FNGU](/fngu-vs-tqqq/) | <span style="color: tomato">34.6<small>%</small></span> | 92.7<small>%</small> | 0.37 | -92.3<small>%</small> | -43.2<small>%</small> |
| TQQQ | <span style="color: tomato">25.5<small>%</small></span> | 72.2<small>%</small> | 0.35 | -81.7<small>%</small> | -29.9<small>%</small> |