| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [FNGU](/fngu-vs-bulz/) | <span style="color: tomato">9.2<small>%</small></span> | 96.1<small>%</small> | 0.10 | -92.3<small>%</small> | -55.2<small>%</small> |
| BULZ | <span style="color: cornflowerblue">-15.5<small>%</small></span> | 92.4<small>%</small> | -0.17 | -94.4<small>%</small> | -67.4<small>%</small> |