| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [FNGU](/fngu-vs-bulz/) | <span style="color: tomato">10.5<small>%</small></span> | 95.4<small>%</small> | 0.11 | -92.3<small>%</small> | -54.7<small>%</small> |
| BULZ | <span style="color: cornflowerblue">-15.5<small>%</small></span> | 91.8<small>%</small> | -0.17 | -94.4<small>%</small> | -67.2<small>%</small> |