| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [FNGU](/fngu-vs-tqqq/) | <span style="color: tomato">36.9<small>%</small></span> | 92.4<small>%</small> | 0.40 | -92.3<small>%</small> | -42.8<small>%</small> |
| TQQQ | <span style="color: tomato">27.8<small>%</small></span> | 71.9<small>%</small> | 0.39 | -81.7<small>%</small> | -29.7<small>%</small> |