| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [GDXY](/gdxy-vs-gdx/) | <span style="color: tomato">7.6<small>%</small></span> | 23.9<small>%</small> | 0.32 | -8.3<small>%</small> | -3.9<small>%</small> |
| GDX | <span style="color: tomato">27.8<small>%</small></span> | 32.9<small>%</small> | 0.85 | -11.6<small>%</small> | -5.3<small>%</small> |