| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [GDXY](/gdxy-vs-gdx/) | <span style="color: tomato">1.3<small>%</small></span> | 23.1<small>%</small> | 0.06 | -8.3<small>%</small> | -3.8<small>%</small> |
| GDX | <span style="color: tomato">24.6<small>%</small></span> | 32.4<small>%</small> | 0.76 | -11.6<small>%</small> | -4.9<small>%</small> |