| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [GDXY](/gdxy-vs-gdx/) | <span style="color: tomato">14.4<small>%</small></span> | 23.3<small>%</small> | 0.62 | -8.3<small>%</small> | -3.7<small>%</small> |
| GDX | <span style="color: tomato">39.4<small>%</small></span> | 32.3<small>%</small> | 1.22 | -11.6<small>%</small> | -4.8<small>%</small> |