| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [GOF](/gof-vs-spy/) | <span style="color: tomato">10.5<small>%</small></span> | 21.9<small>%</small> | 0.48 | -54.7<small>%</small> | -7.1<small>%</small> |
| SPY | <span style="color: tomato">10.4<small>%</small></span> | 20.0<small>%</small> | 0.52 | -55.2<small>%</small> | -8.4<small>%</small> |