| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [Guggenheim Strategic Opportunities Closed Fund](/gof-vs-hyt/) | <span style="color: tomato">10.2<small>%</small></span> | 21.9<small>%</small> | 0.47 | -54.7<small>%</small> | -7.1<small>%</small> |
| BlackRock Corporate High Yield Fund，Inc. | <span style="color: tomato">8.5<small>%</small></span> | 20.1<small>%</small> | 0.42 | -55.2<small>%</small> | -6.5<small>%</small> |