| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [GOF](/gof-vs-spy/) | <span style="color: tomato">10.3<small>%</small></span> | 21.9<small>%</small> | 0.47 | -54.7<small>%</small> | -7.1<small>%</small> |
| SPY | <span style="color: tomato">10.2<small>%</small></span> | 20.0<small>%</small> | 0.51 | -55.2<small>%</small> | -8.4<small>%</small> |