| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [Guggenheim Strategic Opportunities Closed Fund](/gof-vs-shy/) | <span style="color: tomato">10.2<small>%</small></span> | 21.9<small>%</small> | 0.47 | -54.7<small>%</small> | -7.1<small>%</small> |
| SHY | <span style="color: tomato">1.5<small>%</small></span> | 1.5<small>%</small> | 1.02 | -5.7<small>%</small> | -0.6<small>%</small> |