| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [GOOY](/gooy-vs-googl/) | <span style="color: cornflowerblue">-0.7<small>%</small></span> | 21.3<small>%</small> | -0.03 | -17.0<small>%</small> | -5.8<small>%</small> |
| Alphabet Inc Class A | <span style="color: tomato">36.1<small>%</small></span> | 28.8<small>%</small> | 1.25 | -14.4<small>%</small> | -3.7<small>%</small> |