| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [GOOY](/gooy-vs-googl/) | <span style="color: tomato">5.3<small>%</small></span> | 20.4<small>%</small> | 0.26 | -17.0<small>%</small> | -5.3<small>%</small> |
| Alphabet Inc Class A | <span style="color: tomato">39.1<small>%</small></span> | 27.5<small>%</small> | 1.42 | -14.4<small>%</small> | -3.4<small>%</small> |