| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [GOOY](/gooy-vs-googl/) | <span style="color: cornflowerblue">-7.9<small>%</small></span> | 21.3<small>%</small> | -0.37 | -17.0<small>%</small> | -5.9<small>%</small> |
| Alphabet Inc Class A | <span style="color: tomato">19.6<small>%</small></span> | 27.1<small>%</small> | 0.72 | -14.4<small>%</small> | -4.0<small>%</small> |