| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [GPIQ](/gpiq-vs-qqq/) | <span style="color: tomato">37.3<small>%</small></span> | 14.8<small>%</small> | 2.52 | -11.7<small>%</small> | -1.7<small>%</small> |
| QQQ | <span style="color: tomato">45.4<small>%</small></span> | 17.4<small>%</small> | 2.61 | -13.6<small>%</small> | -2.3<small>%</small> |