| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [GPIQ](/gpiq-vs-qqq/) | <span style="color: tomato">51.4<small>%</small></span> | 12.4<small>%</small> | 4.16 | -6.3<small>%</small> | -0.8<small>%</small> |
| QQQ | <span style="color: tomato">62.9<small>%</small></span> | 15.0<small>%</small> | 4.19 | -7.1<small>%</small> | -1.0<small>%</small> |