| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [GPIQ](/gpiq-vs-jepq/) | <span style="color: tomato">38.9<small>%</small></span> | 14.5<small>%</small> | 2.68 | -11.7<small>%</small> | -1.4<small>%</small> |
| JEPQ | <span style="color: tomato">33.9<small>%</small></span> | 12.5<small>%</small> | 2.71 | -10.7<small>%</small> | -1.1<small>%</small> |