| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [GPIQ](/gpiq-vs-qqq/) | <span style="color: tomato">47.7<small>%</small></span> | 12.4<small>%</small> | 3.84 | -6.3<small>%</small> | -0.8<small>%</small> |
| QQQ | <span style="color: tomato">57.6<small>%</small></span> | 15.0<small>%</small> | 3.83 | -7.1<small>%</small> | -1.1<small>%</small> |