| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [GPIQ](/gpiq-vs-jepq/) | <span style="color: tomato">51.8<small>%</small></span> | 12.5<small>%</small> | 4.16 | -6.3<small>%</small> | -0.8<small>%</small> |
| JEPQ | <span style="color: tomato">48.6<small>%</small></span> | 10.3<small>%</small> | 4.72 | -6.0<small>%</small> | -0.6<small>%</small> |