| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [GPIQ](/gpiq-vs-jepq/) | <span style="color: tomato">49.4<small>%</small></span> | 12.6<small>%</small> | 3.92 | -6.3<small>%</small> | -0.9<small>%</small> |
| JEPQ | <span style="color: tomato">47.1<small>%</small></span> | 10.4<small>%</small> | 4.52 | -6.0<small>%</small> | -0.6<small>%</small> |