| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [GPIX](/gpix-vs-spy/) | <span style="color: tomato">39.3<small>%</small></span> | 10.6<small>%</small> | 3.71 | -7.0<small>%</small> | -0.8<small>%</small> |
| SPY | <span style="color: tomato">47.7<small>%</small></span> | 12.2<small>%</small> | 3.91 | -8.4<small>%</small> | -1.0<small>%</small> |