| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [GPIX](/gpix-vs-jepi/) | <span style="color: tomato">39.0<small>%</small></span> | 10.5<small>%</small> | 3.70 | -7.0<small>%</small> | -0.8<small>%</small> |
| JEPI | <span style="color: tomato">25.0<small>%</small></span> | 7.4<small>%</small> | 3.37 | -3.9<small>%</small> | -0.6<small>%</small> |