| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [GPIX](/gpix-vs-spy/) | <span style="color: tomato">37.9<small>%</small></span> | 9.3<small>%</small> | 4.09 | -5.0<small>%</small> | -0.6<small>%</small> |
| SPY | <span style="color: tomato">46.2<small>%</small></span> | 11.0<small>%</small> | 4.19 | -5.4<small>%</small> | -0.8<small>%</small> |