| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [GPIX](/gpix-vs-jepi/) | <span style="color: tomato">42.2<small>%</small></span> | 8.9<small>%</small> | 4.71 | -5.0<small>%</small> | -0.5<small>%</small> |
| JEPI | <span style="color: tomato">23.5<small>%</small></span> | 6.3<small>%</small> | 3.71 | -3.6<small>%</small> | -0.6<small>%</small> |