| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [GPIX](/gpix-vs-jepi/) | <span style="color: tomato">38.6<small>%</small></span> | 9.2<small>%</small> | 4.20 | -5.0<small>%</small> | -0.5<small>%</small> |
| JEPI | <span style="color: tomato">21.8<small>%</small></span> | 6.4<small>%</small> | 3.38 | -3.6<small>%</small> | -0.6<small>%</small> |