| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [GPIX](/gpix-vs-spy/) | <span style="color: tomato">40.3<small>%</small></span> | 9.4<small>%</small> | 4.31 | -5.0<small>%</small> | -0.6<small>%</small> |
| SPY | <span style="color: tomato">49.1<small>%</small></span> | 11.1<small>%</small> | 4.41 | -5.4<small>%</small> | -0.8<small>%</small> |