| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [BlackRock Corporate High Yield Fund，Inc.](/hyt-vs-shy/) | <span style="color: tomato">7.7<small>%</small></span> | 18.5<small>%</small> | 0.41 | -56.9<small>%</small> | -6.4<small>%</small> |
| SHY | <span style="color: tomato">1.7<small>%</small></span> | 1.5<small>%</small> | 1.14 | -5.7<small>%</small> | -0.6<small>%</small> |