| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [HYT](/hyt-vs-spy/) | <span style="color: tomato">7.7<small>%</small></span> | 18.5<small>%</small> | 0.41 | -56.9<small>%</small> | -6.4<small>%</small> |
| SPY | <span style="color: tomato">10.6<small>%</small></span> | 18.6<small>%</small> | 0.57 | -55.2<small>%</small> | -7.1<small>%</small> |