| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [IEF](/ief-vs-tlt/) | <span style="color: tomato">3.7<small>%</small></span> | 6.9<small>%</small> | 0.54 | -23.9<small>%</small> | -4.7<small>%</small> |
| TLT | <span style="color: tomato">4.3<small>%</small></span> | 14.4<small>%</small> | 0.29 | -48.4<small>%</small> | -11.7<small>%</small> |