| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [IQQQ](/iqqq-vs-qqq/) | <span style="color: tomato">13.8<small>%</small></span> | 16.9<small>%</small> | 0.81 | -13.1<small>%</small> | -3.1<small>%</small> |
| QQQ | <span style="color: tomato">17.6<small>%</small></span> | 18.7<small>%</small> | 0.94 | -13.6<small>%</small> | -3.1<small>%</small> |