| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [IQQQ](/iqqq-vs-qqq/) | <span style="color: tomato">5.9<small>%</small></span> | 15.8<small>%</small> | 0.37 | -8.9<small>%</small> | -2.0<small>%</small> |
| QQQ | <span style="color: tomato">10.5<small>%</small></span> | 17.3<small>%</small> | 0.61 | -9.0<small>%</small> | -2.1<small>%</small> |