| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [IQQQ](/iqqq-vs-qqq/) | <span style="color: tomato">12.5<small>%</small></span> | 17.0<small>%</small> | 0.73 | -13.1<small>%</small> | -3.0<small>%</small> |
| QQQ | <span style="color: tomato">17.5<small>%</small></span> | 18.9<small>%</small> | 0.93 | -13.6<small>%</small> | -3.0<small>%</small> |