| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ISPY](/ispy-vs-xyld/) | <span style="color: tomato">20.2<small>%</small></span> | 11.1<small>%</small> | 1.82 | -7.9<small>%</small> | -1.1<small>%</small> |
| XYLD | <span style="color: tomato">11.4<small>%</small></span> | 7.0<small>%</small> | 1.63 | -5.2<small>%</small> | -0.4<small>%</small> |