| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ISPY](/ispy-vs-spyi/) | <span style="color: tomato">25.2<small>%</small></span> | 11.2<small>%</small> | 2.26 | -7.9<small>%</small> | -1.1<small>%</small> |
| SPYI | <span style="color: tomato">19.1<small>%</small></span> | 9.6<small>%</small> | 1.99 | -6.6<small>%</small> | -0.8<small>%</small> |