| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ISPY](/ispy-vs-gpix/) | <span style="color: tomato">27.4<small>%</small></span> | 11.2<small>%</small> | 2.46 | -7.9<small>%</small> | -1.1<small>%</small> |
| GPIX | <span style="color: tomato">26.0<small>%</small></span> | 10.7<small>%</small> | 2.44 | -7.0<small>%</small> | -0.9<small>%</small> |