| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ISPY](/ispy-vs-jepi/) | <span style="color: tomato">31.4<small>%</small></span> | 9.7<small>%</small> | 3.22 | -4.9<small>%</small> | -0.8<small>%</small> |
| JEPI | <span style="color: tomato">13.8<small>%</small></span> | 6.1<small>%</small> | 2.26 | -3.6<small>%</small> | -0.7<small>%</small> |