| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ISPY](/ispy-vs-xylg/) | <span style="color: tomato">30.0<small>%</small></span> | 9.6<small>%</small> | 3.13 | -4.9<small>%</small> | -0.8<small>%</small> |
| XYLG | <span style="color: tomato">25.5<small>%</small></span> | 6.8<small>%</small> | 3.73 | -4.3<small>%</small> | -0.6<small>%</small> |