| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ISPY](/ispy-vs-bali/) | <span style="color: tomato">25.1<small>%</small></span> | 10.0<small>%</small> | 2.52 | -4.9<small>%</small> | -0.8<small>%</small> |
| BALI | <span style="color: tomato">28.0<small>%</small></span> | 8.9<small>%</small> | 3.16 | -4.8<small>%</small> | -0.8<small>%</small> |