| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ISPY](/ispy-vs-jepi/) | <span style="color: tomato">32.3<small>%</small></span> | 9.4<small>%</small> | 3.43 | -4.9<small>%</small> | -0.7<small>%</small> |
| JEPI | <span style="color: tomato">14.4<small>%</small></span> | 6.0<small>%</small> | 2.41 | -3.6<small>%</small> | -0.7<small>%</small> |