| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ISPY](/ispy-vs-spy/) | <span style="color: tomato">31.7<small>%</small></span> | 9.4<small>%</small> | 3.36 | -4.9<small>%</small> | -0.7<small>%</small> |
| SPY | <span style="color: tomato">37.2<small>%</small></span> | 10.4<small>%</small> | 3.58 | -5.4<small>%</small> | -0.8<small>%</small> |