| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ISPY](/ispy-vs-jepy/) | <span style="color: tomato">34.4<small>%</small></span> | 9.3<small>%</small> | 3.68 | -4.9<small>%</small> | -0.7<small>%</small> |
| JEPY | <span style="color: tomato">23.7<small>%</small></span> | 6.5<small>%</small> | 3.65 | -3.3<small>%</small> | -0.5<small>%</small> |