| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ISPY](/ispy-vs-xylg/) | <span style="color: tomato">30.6<small>%</small></span> | 9.5<small>%</small> | 3.24 | -4.9<small>%</small> | -0.7<small>%</small> |
| XYLG | <span style="color: tomato">25.9<small>%</small></span> | 6.7<small>%</small> | 3.85 | -4.3<small>%</small> | -0.6<small>%</small> |