| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ISPY](/ispy-vs-xylg/) | <span style="color: tomato">28.2<small>%</small></span> | 11.4<small>%</small> | 2.48 | -7.9<small>%</small> | -1.1<small>%</small> |
| XYLG | <span style="color: tomato">24.6<small>%</small></span> | 9.4<small>%</small> | 2.62 | -7.2<small>%</small> | -0.8<small>%</small> |