| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ISPY](/ispy-vs-spy/) | <span style="color: tomato">20.9<small>%</small></span> | 11.9<small>%</small> | 1.75 | -7.9<small>%</small> | -1.1<small>%</small> |
| SPY | <span style="color: tomato">27.4<small>%</small></span> | 12.5<small>%</small> | 2.19 | -8.4<small>%</small> | -1.2<small>%</small> |