| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ISPY](/ispy-vs-bali/) | <span style="color: tomato">30.1<small>%</small></span> | 9.6<small>%</small> | 3.16 | -4.9<small>%</small> | -0.8<small>%</small> |
| BALI | <span style="color: tomato">34.3<small>%</small></span> | 8.5<small>%</small> | 4.05 | -4.8<small>%</small> | -0.7<small>%</small> |