| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ISPY](/ispy-vs-jepi/) | <span style="color: tomato">16.6<small>%</small></span> | 10.9<small>%</small> | 1.52 | -7.9<small>%</small> | -1.0<small>%</small> |
| JEPI | <span style="color: tomato">10.0<small>%</small></span> | 7.3<small>%</small> | 1.38 | -3.9<small>%</small> | -0.7<small>%</small> |