| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ISPY](/ispy-vs-xyld/) | <span style="color: tomato">20.2<small>%</small></span> | 10.4<small>%</small> | 1.95 | -5.4<small>%</small> | -0.9<small>%</small> |
| XYLD | <span style="color: tomato">11.5<small>%</small></span> | 5.2<small>%</small> | 2.22 | -2.7<small>%</small> | -0.3<small>%</small> |