| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ISPY](/ispy-vs-gpix/) | <span style="color: tomato">18.7<small>%</small></span> | 9.9<small>%</small> | 1.90 | -5.6<small>%</small> | -1.1<small>%</small> |
| GPIX | <span style="color: tomato">17.1<small>%</small></span> | 9.3<small>%</small> | 1.84 | -5.6<small>%</small> | -1.1<small>%</small> |