| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ISPY](/ispy-vs-spy/) | <span style="color: tomato">19.4<small>%</small></span> | 11.2<small>%</small> | 1.73 | -7.9<small>%</small> | -1.0<small>%</small> |
| SPY | <span style="color: tomato">23.0<small>%</small></span> | 12.3<small>%</small> | 1.86 | -8.4<small>%</small> | -1.1<small>%</small> |