| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ISPY](/ispy-vs-jepy/) | <span style="color: tomato">28.0<small>%</small></span> | 11.4<small>%</small> | 2.45 | -7.9<small>%</small> | -1.1<small>%</small> |
| JEPY | <span style="color: tomato">825.7<small>%</small></span> | 230.4<small>%</small> | 3.58 | -4.3<small>%</small> | -0.7<small>%</small> |