| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ISPY](/ispy-vs-jepy/) | <span style="color: tomato">25.1<small>%</small></span> | 11.2<small>%</small> | 2.24 | -7.9<small>%</small> | -1.1<small>%</small> |
| JEPY | <span style="color: tomato">14.3<small>%</small></span> | 7.9<small>%</small> | 1.81 | -6.7<small>%</small> | -1.0<small>%</small> |