| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ISPY](/ispy-vs-spyi/) | <span style="color: tomato">31.7<small>%</small></span> | 9.4<small>%</small> | 3.36 | -4.9<small>%</small> | -0.7<small>%</small> |
| SPYI | <span style="color: tomato">24.2<small>%</small></span> | 7.4<small>%</small> | 3.27 | -4.6<small>%</small> | -0.5<small>%</small> |