| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ISPY](/ispy-vs-xyld/) | <span style="color: tomato">21.3<small>%</small></span> | 11.5<small>%</small> | 1.84 | -7.9<small>%</small> | -1.2<small>%</small> |
| XYLD | <span style="color: tomato">16.0<small>%</small></span> | 7.4<small>%</small> | 2.17 | -5.2<small>%</small> | -0.4<small>%</small> |