| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ISPY](/ispy-vs-bali/) | <span style="color: tomato">25.3<small>%</small></span> | 11.2<small>%</small> | 2.26 | -7.9<small>%</small> | -1.1<small>%</small> |
| BALI | <span style="color: tomato">28.1<small>%</small></span> | 10.1<small>%</small> | 2.78 | -7.7<small>%</small> | -1.1<small>%</small> |