| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ISPY](/ispy-vs-gpix/) | <span style="color: tomato">23.1<small>%</small></span> | 10.0<small>%</small> | 2.32 | -4.9<small>%</small> | -0.8<small>%</small> |
| GPIX | <span style="color: tomato">21.4<small>%</small></span> | 9.1<small>%</small> | 2.35 | -5.0<small>%</small> | -0.7<small>%</small> |