| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [IWF](/iwf-vs-brk-b/) | <span style="color: tomato">7.6<small>%</small></span> | 20.7<small>%</small> | 0.36 | -64.2<small>%</small> | -23.3<small>%</small> |
| BRK-B | <span style="color: tomato">11.0<small>%</small></span> | 21.3<small>%</small> | 0.51 | -53.9<small>%</small> | -9.7<small>%</small> |