| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [IWF](/iwf-vs-brk-b/) | <span style="color: tomato">12.8<small>%</small></span> | 20.7<small>%</small> | 0.62 | -48.7<small>%</small> | -7.6<small>%</small> |
| BRK-B | <span style="color: tomato">9.8<small>%</small></span> | 22.4<small>%</small> | 0.44 | -52.0<small>%</small> | -10.4<small>%</small> |