| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [IWMY](/iwmy-vs-iwm/) | <span style="color: tomato">16.7<small>%</small></span> | 13.4<small>%</small> | 1.25 | -7.1<small>%</small> | -2.0<small>%</small> |
| IWM | <span style="color: tomato">37.1<small>%</small></span> | 21.2<small>%</small> | 1.75 | -10.1<small>%</small> | -3.0<small>%</small> |