| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [IWMY](/iwmy-vs-ryld/) | <span style="color: tomato">22.5<small>%</small></span> | 12.5<small>%</small> | 1.79 | -5.3<small>%</small> | -1.8<small>%</small> |
| RYLD | <span style="color: tomato">12.7<small>%</small></span> | 8.0<small>%</small> | 1.59 | -3.9<small>%</small> | -1.2<small>%</small> |