| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [IWMY](/iwmy-vs-iwm/) | <span style="color: tomato">21.3<small>%</small></span> | 13.7<small>%</small> | 1.55 | -7.1<small>%</small> | -2.0<small>%</small> |
| IWM | <span style="color: tomato">42.3<small>%</small></span> | 21.8<small>%</small> | 1.94 | -10.1<small>%</small> | -3.1<small>%</small> |