| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [IWMY](/iwmy-vs-iwm/) | <span style="color: tomato">15.7<small>%</small></span> | 13.0<small>%</small> | 1.21 | -5.3<small>%</small> | -1.9<small>%</small> |
| IWM | <span style="color: tomato">36.4<small>%</small></span> | 20.9<small>%</small> | 1.74 | -8.3<small>%</small> | -2.7<small>%</small> |