| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [IWMY](/iwmy-vs-ryld/) | <span style="color: tomato">18.1<small>%</small></span> | 13.5<small>%</small> | 1.33 | -7.1<small>%</small> | -2.0<small>%</small> |
| RYLD | <span style="color: tomato">11.8<small>%</small></span> | 9.8<small>%</small> | 1.21 | -6.3<small>%</small> | -1.2<small>%</small> |