| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [IWMY](/iwmy-vs-ryld/) | <span style="color: tomato">22.9<small>%</small></span> | 12.9<small>%</small> | 1.77 | -5.3<small>%</small> | -1.9<small>%</small> |
| RYLD | <span style="color: tomato">14.0<small>%</small></span> | 7.4<small>%</small> | 1.89 | -3.9<small>%</small> | -0.9<small>%</small> |