| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [JEPI](/jepi-vs-spy/) | <span style="color: tomato">13.3<small>%</small></span> | 10.7<small>%</small> | 1.25 | -13.7<small>%</small> | -2.3<small>%</small> |
| SPY | <span style="color: tomato">17.8<small>%</small></span> | 17.3<small>%</small> | 1.03 | -24.5<small>%</small> | -6.4<small>%</small> |