| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [JEPI](/jepi-vs-jepix/) | <span style="color: tomato">13.1<small>%</small></span> | 10.7<small>%</small> | 1.23 | -13.7<small>%</small> | -2.3<small>%</small> |
| JEPIX | <span style="color: tomato">12.9<small>%</small></span> | 11.1<small>%</small> | 1.16 | -13.7<small>%</small> | -2.4<small>%</small> |