| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [JEPI](/jepi-vs-spy/) | <span style="color: tomato">12.9<small>%</small></span> | 10.6<small>%</small> | 1.22 | -13.7<small>%</small> | -2.3<small>%</small> |
| SPY | <span style="color: tomato">17.5<small>%</small></span> | 17.2<small>%</small> | 1.02 | -24.5<small>%</small> | -6.3<small>%</small> |