| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [JEPI](/jepi-vs-idvo/) | <span style="color: tomato">11.9<small>%</small></span> | 9.7<small>%</small> | 1.23 | -9.2<small>%</small> | -1.4<small>%</small> |
| IDVO | <span style="color: tomato">16.6<small>%</small></span> | 15.6<small>%</small> | 1.06 | -11.0<small>%</small> | -2.8<small>%</small> |