| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [JEPIX](/jepix-vs-spy/) | <span style="color: tomato">10.2<small>%</small></span> | 15.5<small>%</small> | 0.66 | -32.6<small>%</small> | -3.2<small>%</small> |
| SPY | <span style="color: tomato">17.2<small>%</small></span> | 20.3<small>%</small> | 0.85 | -33.7<small>%</small> | -5.8<small>%</small> |