| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [JEPIX](/jepix-vs-schd/) | <span style="color: tomato">11.1<small>%</small></span> | 15.6<small>%</small> | 0.72 | -32.6<small>%</small> | -3.3<small>%</small> |
| SCHD | <span style="color: tomato">14.6<small>%</small></span> | 19.5<small>%</small> | 0.75 | -33.4<small>%</small> | -4.4<small>%</small> |