| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [JEPI](/jepi-vs-idvo/) | <span style="color: tomato">8.7<small>%</small></span> | 9.8<small>%</small> | 0.89 | -9.2<small>%</small> | -1.5<small>%</small> |
| IDVO | <span style="color: tomato">14.5<small>%</small></span> | 15.7<small>%</small> | 0.92 | -11.0<small>%</small> | -2.7<small>%</small> |