| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [JEPIX](/jepix-vs-schd/) | <span style="color: tomato">11.5<small>%</small></span> | 15.2<small>%</small> | 0.76 | -32.6<small>%</small> | -3.1<small>%</small> |
| SCHD | <span style="color: tomato">17.5<small>%</small></span> | 19.1<small>%</small> | 0.92 | -33.4<small>%</small> | -3.6<small>%</small> |