| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [JEPIX](/jepix-vs-spy/) | <span style="color: tomato">10.4<small>%</small></span> | 15.4<small>%</small> | 0.68 | -32.6<small>%</small> | -3.2<small>%</small> |
| SPY | <span style="color: tomato">16.7<small>%</small></span> | 20.1<small>%</small> | 0.83 | -33.7<small>%</small> | -5.7<small>%</small> |