| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [JEPI](/jepi-vs-spy/) | <span style="color: tomato">12.5<small>%</small></span> | 10.4<small>%</small> | 1.20 | -13.7<small>%</small> | -2.2<small>%</small> |
| SPY | <span style="color: tomato">17.9<small>%</small></span> | 16.9<small>%</small> | 1.06 | -24.5<small>%</small> | -6.0<small>%</small> |