| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [JEPIX](/jepix-vs-spy/) | <span style="color: tomato">10.0<small>%</small></span> | 15.8<small>%</small> | 0.63 | -32.6<small>%</small> | -3.5<small>%</small> |
| SPY | <span style="color: tomato">17.0<small>%</small></span> | 20.7<small>%</small> | 0.82 | -33.7<small>%</small> | -6.1<small>%</small> |