| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [JEPI](/jepi-vs-schd/) | <span style="color: tomato">13.1<small>%</small></span> | 10.5<small>%</small> | 1.25 | -13.7<small>%</small> | -2.2<small>%</small> |
| SCHD | <span style="color: tomato">16.3<small>%</small></span> | 15.7<small>%</small> | 1.04 | -16.8<small>%</small> | -4.0<small>%</small> |