| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [JEPI](/jepi-vs-divo/) | <span style="color: tomato">12.3<small>%</small></span> | 10.4<small>%</small> | 1.18 | -13.7<small>%</small> | -2.2<small>%</small> |
| DIVO | <span style="color: tomato">14.2<small>%</small></span> | 12.5<small>%</small> | 1.14 | -13.7<small>%</small> | -2.5<small>%</small> |