| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [JEPI](/jepi-vs-jepix/) | <span style="color: tomato">12.7<small>%</small></span> | 10.4<small>%</small> | 1.21 | -13.7<small>%</small> | -2.2<small>%</small> |
| JEPIX | <span style="color: tomato">12.5<small>%</small></span> | 10.8<small>%</small> | 1.16 | -13.7<small>%</small> | -2.3<small>%</small> |