| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [JEPI](/jepi-vs-schd/) | <span style="color: tomato">12.3<small>%</small></span> | 10.6<small>%</small> | 1.15 | -13.7<small>%</small> | -2.3<small>%</small> |
| SCHD | <span style="color: tomato">15.2<small>%</small></span> | 16.0<small>%</small> | 0.95 | -16.8<small>%</small> | -4.2<small>%</small> |