| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [JEPI](/jepi-vs-schd/) | <span style="color: tomato">13.1<small>%</small></span> | 10.7<small>%</small> | 1.22 | -13.7<small>%</small> | -2.3<small>%</small> |
| SCHD | <span style="color: tomato">16.0<small>%</small></span> | 16.1<small>%</small> | 1.00 | -16.8<small>%</small> | -4.2<small>%</small> |