| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [JEPIX](/jepix-vs-schd/) | <span style="color: tomato">12.9<small>%</small></span> | 7.5<small>%</small> | 1.71 | -7.0<small>%</small> | -1.0<small>%</small> |
| SCHD | <span style="color: tomato">13.9<small>%</small></span> | 11.6<small>%</small> | 1.20 | -10.8<small>%</small> | -2.6<small>%</small> |