| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [JEPI](/jepi-vs-divo/) | <span style="color: tomato">12.6<small>%</small></span> | 10.5<small>%</small> | 1.20 | -13.7<small>%</small> | -2.2<small>%</small> |
| DIVO | <span style="color: tomato">13.9<small>%</small></span> | 12.5<small>%</small> | 1.11 | -13.7<small>%</small> | -2.5<small>%</small> |