| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [JEPQ](/jepq-vs-spy/) | <span style="color: tomato">15.8<small>%</small></span> | 16.8<small>%</small> | 0.94 | -16.8<small>%</small> | -4.1<small>%</small> |
| SPY | <span style="color: tomato">14.4<small>%</small></span> | 17.7<small>%</small> | 0.81 | -16.7<small>%</small> | -4.4<small>%</small> |