| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [JEPQ](/jepq-vs-jepi/) | <span style="color: tomato">15.5<small>%</small></span> | 16.3<small>%</small> | 0.95 | -16.8<small>%</small> | -4.0<small>%</small> |
| JEPI | <span style="color: tomato">7.2<small>%</small></span> | 10.9<small>%</small> | 0.66 | -10.5<small>%</small> | -2.0<small>%</small> |