| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [JEPQ](/jepq-vs-qqq/) | <span style="color: tomato">15.4<small>%</small></span> | 16.5<small>%</small> | 0.93 | -16.8<small>%</small> | -4.1<small>%</small> |
| QQQ | <span style="color: tomato">20.2<small>%</small></span> | 22.9<small>%</small> | 0.88 | -21.6<small>%</small> | -6.4<small>%</small> |