| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [JEPQ](/jepq-vs-qqq/) | <span style="color: tomato">14.4<small>%</small></span> | 16.8<small>%</small> | 0.86 | -16.8<small>%</small> | -4.0<small>%</small> |
| QQQ | <span style="color: tomato">18.6<small>%</small></span> | 23.1<small>%</small> | 0.80 | -21.6<small>%</small> | -6.2<small>%</small> |