| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [JEPQ](/jepq-vs-jepi/) | <span style="color: tomato">12.5<small>%</small></span> | 16.6<small>%</small> | 0.75 | -16.8<small>%</small> | -4.0<small>%</small> |
| JEPI | <span style="color: tomato">7.6<small>%</small></span> | 10.9<small>%</small> | 0.69 | -10.5<small>%</small> | -1.9<small>%</small> |