| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [JEPQ](/jepq-vs-spy/) | <span style="color: tomato">14.4<small>%</small></span> | 16.8<small>%</small> | 0.86 | -16.8<small>%</small> | -4.0<small>%</small> |
| SPY | <span style="color: tomato">12.9<small>%</small></span> | 17.6<small>%</small> | 0.73 | -16.7<small>%</small> | -4.3<small>%</small> |