| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [JEPQ](/jepq-vs-spy/) | <span style="color: tomato">15.3<small>%</small></span> | 16.4<small>%</small> | 0.93 | -16.8<small>%</small> | -4.1<small>%</small> |
| SPY | <span style="color: tomato">13.7<small>%</small></span> | 17.3<small>%</small> | 0.79 | -16.7<small>%</small> | -4.4<small>%</small> |