| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [JEPQ](/jepq-vs-jepi/) | <span style="color: tomato">14.2<small>%</small></span> | 16.6<small>%</small> | 0.86 | -16.8<small>%</small> | -4.2<small>%</small> |
| JEPI | <span style="color: tomato">7.2<small>%</small></span> | 11.0<small>%</small> | 0.66 | -10.5<small>%</small> | -2.0<small>%</small> |