| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [JEPQ](/jepq-vs-qqq/) | <span style="color: tomato">13.9<small>%</small></span> | 17.1<small>%</small> | 0.81 | -16.8<small>%</small> | -4.3<small>%</small> |
| QQQ | <span style="color: tomato">19.5<small>%</small></span> | 23.7<small>%</small> | 0.82 | -21.6<small>%</small> | -6.7<small>%</small> |