| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [JEPY](/jepy-vs-spy/) | <span style="color: tomato">576.7<small>%</small></span> | 195.4<small>%</small> | 2.95 | -4.3<small>%</small> | -0.7<small>%</small> |
| SPY | <span style="color: tomato">30.2<small>%</small></span> | 12.4<small>%</small> | 2.43 | -8.4<small>%</small> | -1.4<small>%</small> |