| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [JEPY](/jepy-vs-xyld/) | <span style="color: tomato">19.7<small>%</small></span> | 7.4<small>%</small> | 2.65 | -3.9<small>%</small> | -0.7<small>%</small> |
| XYLD | <span style="color: tomato">11.6<small>%</small></span> | 6.0<small>%</small> | 1.94 | -4.6<small>%</small> | -0.7<small>%</small> |