| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [JEPY](/jepy-vs-xyld/) | <span style="color: tomato">13.9<small>%</small></span> | 7.9<small>%</small> | 1.75 | -3.9<small>%</small> | -0.8<small>%</small> |
| XYLD | <span style="color: tomato">11.7<small>%</small></span> | 6.4<small>%</small> | 1.83 | -4.4<small>%</small> | -0.6<small>%</small> |