| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [JEPY](/jepy-vs-xyld/) | <span style="color: tomato">16.2<small>%</small></span> | 8.1<small>%</small> | 2.01 | -6.7<small>%</small> | -1.0<small>%</small> |
| XYLD | <span style="color: tomato">13.6<small>%</small></span> | 7.7<small>%</small> | 1.76 | -5.2<small>%</small> | -0.7<small>%</small> |