| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [JEPY](/jepy-vs-spy/) | <span style="color: tomato">15.6<small>%</small></span> | 8.0<small>%</small> | 1.95 | -6.7<small>%</small> | -1.1<small>%</small> |
| SPY | <span style="color: tomato">29.3<small>%</small></span> | 12.4<small>%</small> | 2.36 | -8.4<small>%</small> | -1.4<small>%</small> |