| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [JEPY](/jepy-vs-spy/) | <span style="color: tomato">21.2<small>%</small></span> | 7.3<small>%</small> | 2.92 | -3.9<small>%</small> | -0.7<small>%</small> |
| SPY | <span style="color: tomato">35.2<small>%</small></span> | 11.2<small>%</small> | 3.14 | -7.2<small>%</small> | -1.1<small>%</small> |