| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [JPMO](/jpmo-vs-jpm/) | <span style="color: tomato">35.2<small>%</small></span> | 11.7<small>%</small> | 3.01 | -9.9<small>%</small> | -1.8<small>%</small> |
| JPMorgan Chase & Co | <span style="color: tomato">75.9<small>%</small></span> | 13.8<small>%</small> | 5.49 | -8.4<small>%</small> | -1.2<small>%</small> |