| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [JPMO](/jpmo-vs-jpm/) | <span style="color: tomato">14.7<small>%</small></span> | 15.6<small>%</small> | 0.94 | -10.6<small>%</small> | -3.4<small>%</small> |
| JPM | <span style="color: tomato">51.8<small>%</small></span> | 19.4<small>%</small> | 2.67 | -10.1<small>%</small> | -2.3<small>%</small> |