| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [JPMO](/jpmo-vs-jpm/) | <span style="color: tomato">10.7<small>%</small></span> | 15.9<small>%</small> | 0.67 | -10.6<small>%</small> | -3.0<small>%</small> |
| JPM | <span style="color: tomato">44.2<small>%</small></span> | 19.3<small>%</small> | 2.29 | -10.1<small>%</small> | -1.9<small>%</small> |