| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KNG](/kng-vs-nobl/) | <span style="color: tomato">9.5<small>%</small></span> | 18.2<small>%</small> | 0.52 | -35.1<small>%</small> | -4.3<small>%</small> |
| NOBL | <span style="color: tomato">10.5<small>%</small></span> | 18.5<small>%</small> | 0.57 | -35.4<small>%</small> | -4.2<small>%</small> |