| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KNG](/kng-vs-nobl/) | <span style="color: tomato">9.0<small>%</small></span> | 18.3<small>%</small> | 0.49 | -35.1<small>%</small> | -4.4<small>%</small> |
| NOBL | <span style="color: tomato">10.0<small>%</small></span> | 18.7<small>%</small> | 0.53 | -35.4<small>%</small> | -4.3<small>%</small> |