| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KOMP](/komp-vs-spy/) | <span style="color: tomato">9.8<small>%</small></span> | 27.9<small>%</small> | 0.35 | -50.1<small>%</small> | -21.2<small>%</small> |
| SPY | <span style="color: tomato">14.5<small>%</small></span> | 20.6<small>%</small> | 0.70 | -33.7<small>%</small> | -6.0<small>%</small> |