| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [KOMP](/komp-vs-spy/) | <span style="color: tomato">9.3<small>%</small></span> | 27.5<small>%</small> | 0.34 | -50.1<small>%</small> | -21.9<small>%</small> |
| SPY | <span style="color: tomato">14.5<small>%</small></span> | 20.3<small>%</small> | 0.71 | -33.7<small>%</small> | -5.8<small>%</small> |