| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [MAGS](/mags-vs-qqq/) | <span style="color: tomato">54.4<small>%</small></span> | 23.9<small>%</small> | 2.27 | -18.1<small>%</small> | -3.0<small>%</small> |
| QQQ | <span style="color: tomato">34.0<small>%</small></span> | 17.3<small>%</small> | 1.96 | -13.6<small>%</small> | -2.5<small>%</small> |