| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [MAGS](/mags-vs-qld/) | <span style="color: tomato">55.6<small>%</small></span> | 23.5<small>%</small> | 2.37 | -18.1<small>%</small> | -3.2<small>%</small> |
| QLD | <span style="color: tomato">65.9<small>%</small></span> | 34.2<small>%</small> | 1.93 | -26.2<small>%</small> | -5.8<small>%</small> |