| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [MAGS](/mags-vs-qld/) | <span style="color: tomato">56.2<small>%</small></span> | 23.8<small>%</small> | 2.37 | -18.1<small>%</small> | -3.1<small>%</small> |
| QLD | <span style="color: tomato">65.3<small>%</small></span> | 34.5<small>%</small> | 1.89 | -26.2<small>%</small> | -5.8<small>%</small> |