| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [MAGS](/mags-vs-qld/) | <span style="color: tomato">57.8<small>%</small></span> | 23.8<small>%</small> | 2.43 | -18.1<small>%</small> | -3.1<small>%</small> |
| QLD | <span style="color: tomato">66.2<small>%</small></span> | 34.5<small>%</small> | 1.92 | -26.2<small>%</small> | -5.7<small>%</small> |