| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [MAGS](/mags-vs-spy/) | <span style="color: tomato">48.1<small>%</small></span> | 23.5<small>%</small> | 2.05 | -18.0<small>%</small> | -2.2<small>%</small> |
| SPY | <span style="color: tomato">20.9<small>%</small></span> | 11.9<small>%</small> | 1.76 | -10.0<small>%</small> | -1.6<small>%</small> |