| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [MAGS](/mags-vs-tqqq/) | <span style="color: tomato">54.3<small>%</small></span> | 23.9<small>%</small> | 2.27 | -18.1<small>%</small> | -3.0<small>%</small> |
| TQQQ | <span style="color: tomato">91.6<small>%</small></span> | 51.8<small>%</small> | 1.77 | -37.4<small>%</small> | -8.6<small>%</small> |