| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [MAGS](/mags-vs-qqq/) | <span style="color: tomato">50.5<small>%</small></span> | 23.9<small>%</small> | 2.11 | -18.1<small>%</small> | -2.9<small>%</small> |
| QQQ | <span style="color: tomato">30.9<small>%</small></span> | 17.3<small>%</small> | 1.78 | -13.6<small>%</small> | -2.5<small>%</small> |