| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [MAGS](/mags-vs-tqqq/) | <span style="color: tomato">55.9<small>%</small></span> | 22.9<small>%</small> | 2.44 | -12.8<small>%</small> | -2.1<small>%</small> |
| TQQQ | <span style="color: tomato">94.7<small>%</small></span> | 48.4<small>%</small> | 1.96 | -33.1<small>%</small> | -7.1<small>%</small> |