| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [MAGS](/mags-vs-spy/) | <span style="color: tomato">47.6<small>%</small></span> | 23.5<small>%</small> | 2.03 | -18.1<small>%</small> | -2.3<small>%</small> |
| SPY | <span style="color: tomato">21.1<small>%</small></span> | 11.9<small>%</small> | 1.77 | -10.0<small>%</small> | -1.7<small>%</small> |