| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [MAGS](/mags-vs-qqq/) | <span style="color: tomato">54.7<small>%</small></span> | 23.6<small>%</small> | 2.32 | -18.1<small>%</small> | -2.7<small>%</small> |
| QQQ | <span style="color: tomato">35.2<small>%</small></span> | 17.0<small>%</small> | 2.07 | -13.6<small>%</small> | -2.4<small>%</small> |