| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [MAGS](/mags-vs-tqqq/) | <span style="color: tomato">50.6<small>%</small></span> | 23.7<small>%</small> | 2.13 | -18.1<small>%</small> | -2.8<small>%</small> |
| TQQQ | <span style="color: tomato">83.7<small>%</small></span> | 51.3<small>%</small> | 1.63 | -37.4<small>%</small> | -8.3<small>%</small> |