| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [MOAT](/moat-vs-schd/) | <span style="color: tomato">12.7<small>%</small></span> | 17.6<small>%</small> | 0.72 | -33.3<small>%</small> | -4.2<small>%</small> |
| SCHD | <span style="color: tomato">9.0<small>%</small></span> | 15.7<small>%</small> | 0.57 | -33.4<small>%</small> | -4.4<small>%</small> |