| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [MRNY](/mrny-vs-mrna/) | <span style="color: tomato">86.8<small>%</small></span> | 40.0<small>%</small> | 2.17 | -20.8<small>%</small> | -4.8<small>%</small> |
| Moderna Inc | <span style="color: tomato">102.3<small>%</small></span> | 54.7<small>%</small> | 1.87 | -26.0<small>%</small> | -8.2<small>%</small> |