| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [MRNY](/mrny-vs-mrna/) | <span style="color: cornflowerblue">-36.3<small>%</small></span> | 45.9<small>%</small> | -0.79 | -56.1<small>%</small> | -16.1<small>%</small> |
| MRNA | <span style="color: cornflowerblue">-25.7<small>%</small></span> | 60.3<small>%</small> | -0.43 | -63.9<small>%</small> | -19.3<small>%</small> |