| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [MRNY](/mrny-vs-mrna/) | <span style="color: tomato">90.3<small>%</small></span> | 39.8<small>%</small> | 2.27 | -20.8<small>%</small> | -4.8<small>%</small> |
| Moderna Inc | <span style="color: tomato">105.6<small>%</small></span> | 54.5<small>%</small> | 1.94 | -26.0<small>%</small> | -8.2<small>%</small> |