| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [MSFO](/msfo-vs-msft/) | <span style="color: tomato">28.5<small>%</small></span> | 16.3<small>%</small> | 1.75 | -13.2<small>%</small> | -1.8<small>%</small> |
| MSFT | <span style="color: tomato">27.7<small>%</small></span> | 19.9<small>%</small> | 1.39 | -15.5<small>%</small> | -2.7<small>%</small> |