| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [MSFO](/msfo-vs-msft/) | <span style="color: tomato">47.2<small>%</small></span> | 16.2<small>%</small> | 2.92 | -7.3<small>%</small> | -1.4<small>%</small> |
| Microsoft Corp | <span style="color: tomato">42.1<small>%</small></span> | 19.9<small>%</small> | 2.12 | -9.3<small>%</small> | -2.3<small>%</small> |