| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [MSFO](/msfo-vs-msft/) | <span style="color: tomato">48.6<small>%</small></span> | 16.0<small>%</small> | 3.03 | -7.3<small>%</small> | -1.4<small>%</small> |
| Microsoft Corp | <span style="color: tomato">45.4<small>%</small></span> | 19.8<small>%</small> | 2.29 | -9.3<small>%</small> | -2.3<small>%</small> |