| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [MSTY](/msty-vs-mstr/) | <span style="color: tomato">315.3<small>%</small></span> | 85.3<small>%</small> | 3.70 | -33.2<small>%</small> | -11.5<small>%</small> |
| Microstrategy Inc | <span style="color: tomato">390.0<small>%</small></span> | 121.1<small>%</small> | 3.22 | -46.4<small>%</small> | -20.0<small>%</small> |