| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [MSTY](/msty-vs-mstr/) | <span style="color: cornflowerblue">-0.7<small>%</small></span> | 99.7<small>%</small> | -0.01 | -43.1<small>%</small> | -28.9<small>%</small> |
| Microstrategy Inc | <span style="color: tomato">20.1<small>%</small></span> | 454.3<small>%</small> | 0.04 | -44.1<small>%</small> | -17.3<small>%</small> |