| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [MSTY](/msty-vs-mstr/) | <span style="color: tomato">167.3<small>%</small></span> | 77.7<small>%</small> | 2.15 | -33.2<small>%</small> | -12.6<small>%</small> |
| MSTR | <span style="color: tomato">197.7<small>%</small></span> | 112.5<small>%</small> | 1.76 | -46.4<small>%</small> | -21.7<small>%</small> |