| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [NFLY](/nfly-vs-nflx/) | <span style="color: tomato">25.2<small>%</small></span> | 28.5<small>%</small> | 0.88 | -21.4<small>%</small> | -3.9<small>%</small> |
| NFLX | <span style="color: tomato">39.5<small>%</small></span> | 32.9<small>%</small> | 1.20 | -22.8<small>%</small> | -4.6<small>%</small> |