| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [NFLY](/nfly-vs-nflx/) | <span style="color: tomato">47.9<small>%</small></span> | 31.7<small>%</small> | 1.51 | -21.4<small>%</small> | -4.1<small>%</small> |
| Netflix Inc | <span style="color: tomato">74.4<small>%</small></span> | 35.0<small>%</small> | 2.13 | -22.8<small>%</small> | -4.5<small>%</small> |