| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [NFLY](/nfly-vs-nflx/) | <span style="color: tomato">27.9<small>%</small></span> | 30.5<small>%</small> | 0.92 | -21.4<small>%</small> | -4.1<small>%</small> |
| Netflix Inc | <span style="color: tomato">60.4<small>%</small></span> | 34.9<small>%</small> | 1.73 | -22.8<small>%</small> | -4.6<small>%</small> |