| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [NOBL](/nobl-vs-spy/) | <span style="color: tomato">10.6<small>%</small></span> | 16.2<small>%</small> | 0.65 | -35.4<small>%</small> | -3.4<small>%</small> |
| SPY | <span style="color: tomato">12.9<small>%</small></span> | 17.2<small>%</small> | 0.75 | -33.7<small>%</small> | -4.2<small>%</small> |