| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [NOBL](/nobl-vs-spy/) | <span style="color: tomato">11.2<small>%</small></span> | 16.3<small>%</small> | 0.69 | -35.4<small>%</small> | -3.4<small>%</small> |
| SPY | <span style="color: tomato">13.4<small>%</small></span> | 17.2<small>%</small> | 0.78 | -33.7<small>%</small> | -4.2<small>%</small> |