| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [NOBL](/nobl-vs-idvo/) | <span style="color: tomato">7.5<small>%</small></span> | 14.1<small>%</small> | 0.53 | -12.9<small>%</small> | -3.6<small>%</small> |
| IDVO | <span style="color: tomato">16.4<small>%</small></span> | 15.7<small>%</small> | 1.04 | -11.0<small>%</small> | -2.7<small>%</small> |