| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [NOBL](/nobl-vs-schd/) | <span style="color: tomato">10.8<small>%</small></span> | 16.1<small>%</small> | 0.67 | -35.4<small>%</small> | -3.4<small>%</small> |
| SCHD | <span style="color: tomato">12.0<small>%</small></span> | 16.1<small>%</small> | 0.74 | -33.4<small>%</small> | -3.6<small>%</small> |