| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [NOBL](/nobl-vs-schd/) | <span style="color: tomato">11.3<small>%</small></span> | 16.0<small>%</small> | 0.71 | -35.4<small>%</small> | -3.4<small>%</small> |
| SCHD | <span style="color: tomato">15.8<small>%</small></span> | 16.2<small>%</small> | 0.98 | -33.4<small>%</small> | -3.1<small>%</small> |