| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [NOBL](/nobl-vs-schd/) | <span style="color: tomato">10.9<small>%</small></span> | 16.2<small>%</small> | 0.68 | -35.4<small>%</small> | -3.4<small>%</small> |
| SCHD | <span style="color: tomato">11.8<small>%</small></span> | 16.2<small>%</small> | 0.73 | -33.4<small>%</small> | -3.6<small>%</small> |