| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [NVDY](/nvdy-vs-nvda/) | <span style="color: tomato">128.8<small>%</small></span> | 36.1<small>%</small> | 3.57 | -16.4<small>%</small> | -3.6<small>%</small> |
| NVIDIA Corp | <span style="color: tomato">226.2<small>%</small></span> | 49.0<small>%</small> | 4.62 | -19.8<small>%</small> | -4.9<small>%</small> |