| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [NVDY](/nvdy-vs-nvda/) | <span style="color: tomato">134.1<small>%</small></span> | 34.8<small>%</small> | 3.86 | -13.9<small>%</small> | -3.4<small>%</small> |
| NVIDIA Corp | <span style="color: tomato">253.0<small>%</small></span> | 49.2<small>%</small> | 5.14 | -18.3<small>%</small> | -4.7<small>%</small> |