| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [NVDY](/nvdy-vs-nvda/) | <span style="color: tomato">150.2<small>%</small></span> | 35.8<small>%</small> | 4.19 | -16.4<small>%</small> | -3.4<small>%</small> |
| NVIDIA Corp | <span style="color: tomato">280.3<small>%</small></span> | 49.4<small>%</small> | 5.68 | -19.8<small>%</small> | -4.6<small>%</small> |