| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [OARK](/oark-vs-arkk/) | <span style="color: cornflowerblue">-2.0<small>%</small></span> | 30.0<small>%</small> | -0.07 | -27.2<small>%</small> | -11.2<small>%</small> |
| ARKK | <span style="color: tomato">15.8<small>%</small></span> | 39.9<small>%</small> | 0.40 | -32.1<small>%</small> | -11.5<small>%</small> |