| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [OARK](/oark-vs-arkk/) | <span style="color: tomato">1.1<small>%</small></span> | 29.9<small>%</small> | 0.04 | -27.2<small>%</small> | -11.3<small>%</small> |
| ARKK | <span style="color: tomato">18.0<small>%</small></span> | 39.7<small>%</small> | 0.45 | -32.1<small>%</small> | -11.8<small>%</small> |