| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [OARK](/oark-vs-arkk/) | <span style="color: tomato">3.3<small>%</small></span> | 30.6<small>%</small> | 0.11 | -27.2<small>%</small> | -11.5<small>%</small> |
| ARKK | <span style="color: tomato">30.9<small>%</small></span> | 41.0<small>%</small> | 0.75 | -32.1<small>%</small> | -11.6<small>%</small> |