| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ONEV](/onev-vs-iwb/) | <span style="color: tomato">11.2<small>%</small></span> | 17.5<small>%</small> | 0.64 | -39.7<small>%</small> | -4.1<small>%</small> |
| IWB | <span style="color: tomato">13.6<small>%</small></span> | 18.2<small>%</small> | 0.75 | -34.6<small>%</small> | -5.0<small>%</small> |