| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ONEV](/onev-vs-iwb/) | <span style="color: tomato">10.9<small>%</small></span> | 17.8<small>%</small> | 0.61 | -39.7<small>%</small> | -4.3<small>%</small> |
| IWB | <span style="color: tomato">12.8<small>%</small></span> | 18.5<small>%</small> | 0.69 | -34.6<small>%</small> | -5.2<small>%</small> |