| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [ONEV](/onev-vs-iwm/) | <span style="color: tomato">10.9<small>%</small></span> | 17.8<small>%</small> | 0.61 | -39.7<small>%</small> | -4.3<small>%</small> |
| IWM | <span style="color: tomato">8.2<small>%</small></span> | 23.2<small>%</small> | 0.35 | -41.1<small>%</small> | -10.3<small>%</small> |