| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PDI](/pdi-vs-hyt/) | <span style="color: tomato">10.6<small>%</small></span> | 17.6<small>%</small> | 0.60 | -46.5<small>%</small> | -6.6<small>%</small> |
| HYT | <span style="color: tomato">7.2<small>%</small></span> | 15.7<small>%</small> | 0.46 | -42.6<small>%</small> | -5.5<small>%</small> |