| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PDI](/pdi-vs-shy/) | <span style="color: tomato">10.5<small>%</small></span> | 17.6<small>%</small> | 0.60 | -46.5<small>%</small> | -6.6<small>%</small> |
| SHY | <span style="color: tomato">0.9<small>%</small></span> | 1.4<small>%</small> | 0.69 | -5.7<small>%</small> | -0.8<small>%</small> |