| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PDI](/pdi-vs-spy/) | <span style="color: tomato">10.5<small>%</small></span> | 17.6<small>%</small> | 0.60 | -46.5<small>%</small> | -6.6<small>%</small> |
| SPY | <span style="color: tomato">14.3<small>%</small></span> | 16.6<small>%</small> | 0.86 | -33.7<small>%</small> | -3.8<small>%</small> |