| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PEY](/pey-vs-spy/) | <span style="color: tomato">5.8<small>%</small></span> | 22.9<small>%</small> | 0.25 | -72.8<small>%</small> | -13.8<small>%</small> |
| SPY | <span style="color: tomato">10.0<small>%</small></span> | 19.2<small>%</small> | 0.52 | -55.2<small>%</small> | -7.7<small>%</small> |