| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PEY](/pey-vs-spy/) | <span style="color: tomato">5.9<small>%</small></span> | 22.8<small>%</small> | 0.26 | -72.8<small>%</small> | -13.7<small>%</small> |
| SPY | <span style="color: tomato">9.9<small>%</small></span> | 19.1<small>%</small> | 0.52 | -55.2<small>%</small> | -7.6<small>%</small> |