| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PEY](/pey-vs-spy/) | <span style="color: tomato">6.1<small>%</small></span> | 22.7<small>%</small> | 0.27 | -72.8<small>%</small> | -13.6<small>%</small> |
| SPY | <span style="color: tomato">10.2<small>%</small></span> | 19.0<small>%</small> | 0.54 | -55.2<small>%</small> | -7.5<small>%</small> |