| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PFF](/pff-vs-tlt/) | <span style="color: tomato">3.7<small>%</small></span> | 19.3<small>%</small> | 0.19 | -65.5<small>%</small> | -6.1<small>%</small> |
| TLT | <span style="color: tomato">3.5<small>%</small></span> | 15.4<small>%</small> | 0.23 | -48.4<small>%</small> | -13.6<small>%</small> |