| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PFF](/pff-vs-spy/) | <span style="color: tomato">3.6<small>%</small></span> | 19.5<small>%</small> | 0.18 | -65.5<small>%</small> | -6.1<small>%</small> |
| SPY | <span style="color: tomato">10.1<small>%</small></span> | 20.0<small>%</small> | 0.50 | -55.2<small>%</small> | -8.4<small>%</small> |