| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PFF](/pff-vs-aom/) | <span style="color: tomato">7.1<small>%</small></span> | 16.9<small>%</small> | 0.42 | -52.5<small>%</small> | -4.2<small>%</small> |
| AOM | <span style="color: tomato">6.4<small>%</small></span> | 9.9<small>%</small> | 0.65 | -20.0<small>%</small> | -2.9<small>%</small> |