| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PFF](/pff-vs-lqd/) | <span style="color: tomato">3.5<small>%</small></span> | 19.4<small>%</small> | 0.18 | -65.5<small>%</small> | -6.1<small>%</small> |
| LQD | <span style="color: tomato">4.1<small>%</small></span> | 9.0<small>%</small> | 0.46 | -25.0<small>%</small> | -4.2<small>%</small> |