| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PFF](/pff-vs-agg/) | <span style="color: tomato">3.6<small>%</small></span> | 19.4<small>%</small> | 0.19 | -65.5<small>%</small> | -6.1<small>%</small> |
| AGG | <span style="color: tomato">3.0<small>%</small></span> | 5.5<small>%</small> | 0.54 | -18.4<small>%</small> | -2.8<small>%</small> |