| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PFF](/pff-vs-spy/) | <span style="color: tomato">3.9<small>%</small></span> | 19.3<small>%</small> | 0.20 | -65.5<small>%</small> | -6.1<small>%</small> |
| SPY | <span style="color: tomato">10.2<small>%</small></span> | 19.9<small>%</small> | 0.52 | -55.2<small>%</small> | -8.3<small>%</small> |