| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PFF](/pff-vs-aok/) | <span style="color: tomato">8.4<small>%</small></span> | 16.6<small>%</small> | 0.51 | -52.5<small>%</small> | -4.1<small>%</small> |
| AOK | <span style="color: tomato">5.1<small>%</small></span> | 7.7<small>%</small> | 0.66 | -18.9<small>%</small> | -2.6<small>%</small> |