| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PFFD](/pffd-vs-aor/) | <span style="color: tomato">2.2<small>%</small></span> | 13.6<small>%</small> | 0.16 | -30.9<small>%</small> | -6.6<small>%</small> |
| AOR | <span style="color: tomato">5.8<small>%</small></span> | 11.4<small>%</small> | 0.51 | -22.9<small>%</small> | -4.9<small>%</small> |