| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PFFD](/pffd-vs-pff/) | <span style="color: tomato">2.1<small>%</small></span> | 13.6<small>%</small> | 0.15 | -30.9<small>%</small> | -6.6<small>%</small> |
| PFF | <span style="color: tomato">2.2<small>%</small></span> | 14.4<small>%</small> | 0.16 | -34.1<small>%</small> | -6.1<small>%</small> |