| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PFFD](/pffd-vs-spy/) | <span style="color: tomato">2.0<small>%</small></span> | 13.6<small>%</small> | 0.15 | -30.9<small>%</small> | -6.6<small>%</small> |
| SPY | <span style="color: tomato">13.0<small>%</small></span> | 19.3<small>%</small> | 0.67 | -33.7<small>%</small> | -5.5<small>%</small> |