| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PFFD](/pffd-vs-tlt/) | <span style="color: tomato">2.8<small>%</small></span> | 13.6<small>%</small> | 0.21 | -30.9<small>%</small> | -6.6<small>%</small> |
| TLT | <span style="color: cornflowerblue">-0.9<small>%</small></span> | 16.0<small>%</small> | -0.06 | -48.4<small>%</small> | -17.7<small>%</small> |