| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PFFD](/pffd-vs-lqd/) | <span style="color: tomato">2.3<small>%</small></span> | 13.6<small>%</small> | 0.17 | -30.9<small>%</small> | -6.6<small>%</small> |
| LQD | <span style="color: tomato">1.7<small>%</small></span> | 9.7<small>%</small> | 0.18 | -25.0<small>%</small> | -7.1<small>%</small> |