| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PFFD](/pffd-vs-aom/) | <span style="color: tomato">2.3<small>%</small></span> | 13.6<small>%</small> | 0.17 | -30.9<small>%</small> | -6.6<small>%</small> |
| AOM | <span style="color: tomato">4.7<small>%</small></span> | 8.4<small>%</small> | 0.55 | -20.0<small>%</small> | -4.4<small>%</small> |