| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PFFD](/pffd-vs-aom/) | <span style="color: tomato">2.2<small>%</small></span> | 13.6<small>%</small> | 0.16 | -30.9<small>%</small> | -6.6<small>%</small> |
| AOM | <span style="color: tomato">4.6<small>%</small></span> | 8.4<small>%</small> | 0.54 | -20.0<small>%</small> | -4.5<small>%</small> |