| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PFFD](/pffd-vs-tlt/) | <span style="color: tomato">2.2<small>%</small></span> | 13.6<small>%</small> | 0.16 | -30.9<small>%</small> | -6.6<small>%</small> |
| TLT | <span style="color: cornflowerblue">-2.0<small>%</small></span> | 16.0<small>%</small> | -0.13 | -48.4<small>%</small> | -17.4<small>%</small> |