| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PFFD](/pffd-vs-pff/) | <span style="color: tomato">3.2<small>%</small></span> | 13.5<small>%</small> | 0.24 | -30.9<small>%</small> | -6.6<small>%</small> |
| PFF | <span style="color: tomato">3.4<small>%</small></span> | 14.3<small>%</small> | 0.24 | -34.1<small>%</small> | -6.0<small>%</small> |