| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PFFD](/pffd-vs-aom/) | <span style="color: tomato">3.0<small>%</small></span> | 13.5<small>%</small> | 0.23 | -30.9<small>%</small> | -6.6<small>%</small> |
| AOM | <span style="color: tomato">4.9<small>%</small></span> | 8.4<small>%</small> | 0.59 | -20.0<small>%</small> | -4.3<small>%</small> |