| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PFFD](/pffd-vs-aok/) | <span style="color: tomato">2.2<small>%</small></span> | 13.6<small>%</small> | 0.17 | -30.9<small>%</small> | -6.6<small>%</small> |
| AOK | <span style="color: tomato">3.7<small>%</small></span> | 7.2<small>%</small> | 0.52 | -18.9<small>%</small> | -4.3<small>%</small> |