| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PFFD](/pffd-vs-aor/) | <span style="color: tomato">3.0<small>%</small></span> | 13.5<small>%</small> | 0.22 | -30.9<small>%</small> | -6.6<small>%</small> |
| AOR | <span style="color: tomato">6.7<small>%</small></span> | 11.3<small>%</small> | 0.59 | -22.9<small>%</small> | -4.8<small>%</small> |