| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PFFD](/pffd-vs-pgx/) | <span style="color: tomato">2.1<small>%</small></span> | 13.6<small>%</small> | 0.15 | -30.9<small>%</small> | -6.6<small>%</small> |
| PGX | <span style="color: tomato">1.6<small>%</small></span> | 14.9<small>%</small> | 0.11 | -34.1<small>%</small> | -6.6<small>%</small> |