| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PFFD](/pffd-vs-aok/) | <span style="color: tomato">2.4<small>%</small></span> | 13.6<small>%</small> | 0.17 | -30.9<small>%</small> | -6.6<small>%</small> |
| AOK | <span style="color: tomato">3.9<small>%</small></span> | 7.1<small>%</small> | 0.55 | -18.9<small>%</small> | -4.3<small>%</small> |