| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PFFD](/pffd-vs-pgx/) | <span style="color: tomato">3.0<small>%</small></span> | 13.5<small>%</small> | 0.23 | -30.9<small>%</small> | -6.6<small>%</small> |
| PGX | <span style="color: tomato">2.5<small>%</small></span> | 14.8<small>%</small> | 0.17 | -34.1<small>%</small> | -6.6<small>%</small> |