| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PGX](/pgx-vs-spy/) | <span style="color: tomato">2.9<small>%</small></span> | 21.3<small>%</small> | 0.13 | -66.4<small>%</small> | -8.3<small>%</small> |
| SPY | <span style="color: tomato">10.6<small>%</small></span> | 20.2<small>%</small> | 0.53 | -51.5<small>%</small> | -7.1<small>%</small> |