| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PGX](/pgx-vs-spy/) | <span style="color: tomato">2.8<small>%</small></span> | 21.2<small>%</small> | 0.13 | -66.4<small>%</small> | -8.4<small>%</small> |
| SPY | <span style="color: tomato">10.9<small>%</small></span> | 20.1<small>%</small> | 0.54 | -51.5<small>%</small> | -7.0<small>%</small> |