| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PGX](/pgx-vs-pff/) | <span style="color: tomato">3.1<small>%</small></span> | 21.1<small>%</small> | 0.14 | -66.4<small>%</small> | -8.4<small>%</small> |
| PFF | <span style="color: tomato">4.2<small>%</small></span> | 19.4<small>%</small> | 0.22 | -64.4<small>%</small> | -5.8<small>%</small> |