| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PGX](/pgx-vs-tlt/) | <span style="color: tomato">2.8<small>%</small></span> | 21.1<small>%</small> | 0.13 | -66.4<small>%</small> | -8.4<small>%</small> |
| TLT | <span style="color: tomato">3.2<small>%</small></span> | 15.6<small>%</small> | 0.20 | -48.4<small>%</small> | -14.1<small>%</small> |