| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PGX](/pgx-vs-lqd/) | <span style="color: tomato">3.3<small>%</small></span> | 21.1<small>%</small> | 0.16 | -66.4<small>%</small> | -8.4<small>%</small> |
| LQD | <span style="color: tomato">4.2<small>%</small></span> | 9.1<small>%</small> | 0.46 | -25.0<small>%</small> | -4.4<small>%</small> |