| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PGX](/pgx-vs-spy/) | <span style="color: cornflowerblue">-3.4<small>%</small></span> | 21.3<small>%</small> | -0.16 | -69.5<small>%</small> | -32.6<small>%</small> |
| SPY | <span style="color: tomato">8.8<small>%</small></span> | 20.1<small>%</small> | 0.44 | -52.4<small>%</small> | -8.1<small>%</small> |