| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PGX](/pgx-vs-agg/) | <span style="color: tomato">2.9<small>%</small></span> | 21.1<small>%</small> | 0.14 | -66.4<small>%</small> | -8.4<small>%</small> |
| AGG | <span style="color: tomato">2.7<small>%</small></span> | 5.5<small>%</small> | 0.49 | -18.4<small>%</small> | -2.9<small>%</small> |