| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PRNHX](/prnhx-vs-iwm/) | <span style="color: tomato">10.5<small>%</small></span> | 22.7<small>%</small> | 0.46 | -55.8<small>%</small> | -13.4<small>%</small> |
| IWM | <span style="color: tomato">8.1<small>%</small></span> | 24.0<small>%</small> | 0.34 | -58.6<small>%</small> | -11.0<small>%</small> |