| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PRNHX](/prnhx-vs-iwm/) | <span style="color: tomato">10.3<small>%</small></span> | 22.7<small>%</small> | 0.45 | -55.8<small>%</small> | -13.3<small>%</small> |
| IWM | <span style="color: tomato">7.8<small>%</small></span> | 24.0<small>%</small> | 0.32 | -58.6<small>%</small> | -11.0<small>%</small> |