| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PRNHX](/prnhx-vs-qqq/) | <span style="color: tomato">11.0<small>%</small></span> | 23.0<small>%</small> | 0.48 | -55.8<small>%</small> | -13.6<small>%</small> |
| QQQ | <span style="color: tomato">9.6<small>%</small></span> | 27.2<small>%</small> | 0.35 | -83.0<small>%</small> | -34.8<small>%</small> |