| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PRNHX](/prnhx-vs-spy/) | <span style="color: tomato">11.9<small>%</small></span> | 21.9<small>%</small> | 0.54 | -55.8<small>%</small> | -12.2<small>%</small> |
| SPY | <span style="color: tomato">10.3<small>%</small></span> | 18.6<small>%</small> | 0.55 | -55.2<small>%</small> | -9.4<small>%</small> |