| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PRNHX](/prnhx-vs-iwo/) | <span style="color: tomato">9.9<small>%</small></span> | 22.7<small>%</small> | 0.44 | -55.8<small>%</small> | -13.4<small>%</small> |
| IWO | <span style="color: tomato">6.2<small>%</small></span> | 25.1<small>%</small> | 0.24 | -60.1<small>%</small> | -17.2<small>%</small> |