| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PYPY](/pypy-vs-pypl/) | <span style="color: tomato">41.0<small>%</small></span> | 26.7<small>%</small> | 1.54 | -14.7<small>%</small> | -3.7<small>%</small> |
| PYPL | <span style="color: tomato">34.4<small>%</small></span> | 34.1<small>%</small> | 1.01 | -15.8<small>%</small> | -5.2<small>%</small> |