| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PYPY](/pypy-vs-pypl/) | <span style="color: tomato">33.7<small>%</small></span> | 27.6<small>%</small> | 1.22 | -12.4<small>%</small> | -2.9<small>%</small> |
| PayPal Holdings Inc | <span style="color: tomato">18.7<small>%</small></span> | 35.4<small>%</small> | 0.53 | -14.7<small>%</small> | -4.6<small>%</small> |