| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [PYPY](/pypy-vs-pypl/) | <span style="color: tomato">21.4<small>%</small></span> | 29.7<small>%</small> | 0.72 | -12.4<small>%</small> | -3.3<small>%</small> |
| PayPal Holdings Inc | <span style="color: tomato">20.4<small>%</small></span> | 38.6<small>%</small> | 0.53 | -14.7<small>%</small> | -5.1<small>%</small> |