| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [QDTE](/qdte-vs-iqqq/) | <span style="color: tomato">26.0<small>%</small></span> | 17.4<small>%</small> | 1.49 | -10.7<small>%</small> | -2.1<small>%</small> |
| IQQQ | <span style="color: tomato">18.6<small>%</small></span> | 17.3<small>%</small> | 1.07 | -13.1<small>%</small> | -3.5<small>%</small> |