| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [QDTE](/qdte-vs-qqq/) | <span style="color: tomato">10.2<small>%</small></span> | 15.0<small>%</small> | 0.68 | -6.7<small>%</small> | -1.6<small>%</small> |
| QQQ | <span style="color: tomato">11.7<small>%</small></span> | 16.2<small>%</small> | 0.72 | -8.9<small>%</small> | -1.8<small>%</small> |