| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [QDTE](/qdte-vs-iqqq/) | <span style="color: tomato">23.0<small>%</small></span> | 17.1<small>%</small> | 1.35 | -10.7<small>%</small> | -2.0<small>%</small> |
| IQQQ | <span style="color: tomato">15.3<small>%</small></span> | 17.0<small>%</small> | 0.90 | -13.1<small>%</small> | -3.4<small>%</small> |