| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [QDTE](/qdte-vs-qqq/) | <span style="color: tomato">23.6<small>%</small></span> | 17.0<small>%</small> | 1.39 | -10.7<small>%</small> | -2.0<small>%</small> |
| QQQ | <span style="color: tomato">19.4<small>%</small></span> | 18.3<small>%</small> | 1.06 | -13.6<small>%</small> | -3.3<small>%</small> |