| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [QDTE](/qdte-vs-iqqq/) | <span style="color: tomato">26.4<small>%</small></span> | 17.1<small>%</small> | 1.55 | -10.7<small>%</small> | -2.0<small>%</small> |
| IQQQ | <span style="color: tomato">18.6<small>%</small></span> | 17.0<small>%</small> | 1.10 | -13.1<small>%</small> | -3.4<small>%</small> |