| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [QDTE](/qdte-vs-qqq/) | <span style="color: tomato">5.1<small>%</small></span> | 17.4<small>%</small> | 0.29 | -10.7<small>%</small> | -2.1<small>%</small> |
| QQQ | <span style="color: tomato">3.3<small>%</small></span> | 18.4<small>%</small> | 0.18 | -13.6<small>%</small> | -2.5<small>%</small> |