| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [QLD](/qld-vs-qqq/) | <span style="color: tomato">23.3<small>%</small></span> | 43.8<small>%</small> | 0.53 | -84.0<small>%</small> | -20.0<small>%</small> |
| QQQ | <span style="color: tomato">14.9<small>%</small></span> | 22.0<small>%</small> | 0.68 | -53.6<small>%</small> | -8.3<small>%</small> |