| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [QLD](/qld-vs-qqq/) | <span style="color: tomato">35.5<small>%</small></span> | 41.3<small>%</small> | 0.86 | -63.7<small>%</small> | -11.4<small>%</small> |
| QQQ | <span style="color: tomato">20.4<small>%</small></span> | 20.7<small>%</small> | 0.98 | -35.1<small>%</small> | -5.1<small>%</small> |