| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [QQEW](/qqew-vs-qqq/) | <span style="color: tomato">16.4<small>%</small></span> | 20.5<small>%</small> | 0.80 | -32.1<small>%</small> | -5.5<small>%</small> |
| QQQ | <span style="color: tomato">20.0<small>%</small></span> | 20.8<small>%</small> | 0.96 | -35.1<small>%</small> | -5.2<small>%</small> |