| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [QQEW](/qqew-vs-qqq/) | <span style="color: tomato">12.0<small>%</small></span> | 22.1<small>%</small> | 0.54 | -53.9<small>%</small> | -7.9<small>%</small> |
| QQQ | <span style="color: tomato">15.3<small>%</small></span> | 22.5<small>%</small> | 0.68 | -49.4<small>%</small> | -7.5<small>%</small> |