| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [QQEW](/qqew-vs-qqq/) | <span style="color: tomato">11.5<small>%</small></span> | 21.8<small>%</small> | 0.53 | -58.2<small>%</small> | -8.9<small>%</small> |
| QQQ | <span style="color: tomato">15.2<small>%</small></span> | 22.1<small>%</small> | 0.69 | -53.4<small>%</small> | -8.2<small>%</small> |