| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [QQQ](/qqq-vs-spy/) | <span style="color: tomato">9.4<small>%</small></span> | 27.3<small>%</small> | 0.34 | -83.0<small>%</small> | -35.2<small>%</small> |
| SPY | <span style="color: tomato">7.4<small>%</small></span> | 19.4<small>%</small> | 0.38 | -55.2<small>%</small> | -11.3<small>%</small> |