| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [QQQ](/qqq-vs-spy/) | <span style="color: tomato">20.2<small>%</small></span> | 20.8<small>%</small> | 0.97 | -35.1<small>%</small> | -5.2<small>%</small> |
| SPY | <span style="color: tomato">14.2<small>%</small></span> | 17.9<small>%</small> | 0.79 | -33.7<small>%</small> | -4.1<small>%</small> |