| **종목** | **배율** | **1년** | **<small>변동성비용</small>** | **<small>금융비용</small>** | **<small>전체비용</small>** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| QQQ | 기초 | <span style="color: tomato">21.7<small>%</small></span> | - | - | - |
| [JEPQ](/jepq/) | 1<small>배</small> | <span style="color: tomato">14.9<small>%</small></span> | -0.0<small>%</small> | 9.7<small>%</small> | 9.7<small>%</small> |