| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [QQQM](/qqqm-vs-qqq/) | <span style="color: tomato">12.9<small>%</small></span> | 22.5<small>%</small> | 0.57 | -35.0<small>%</small> | -10.4<small>%</small> |
| QQQ | <span style="color: tomato">12.9<small>%</small></span> | 22.6<small>%</small> | 0.57 | -35.1<small>%</small> | -10.4<small>%</small> |