| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [QQQM](/qqqm-vs-qqq/) | <span style="color: tomato">14.5<small>%</small></span> | 22.4<small>%</small> | 0.65 | -35.0<small>%</small> | -10.2<small>%</small> |
| QQQ | <span style="color: tomato">14.5<small>%</small></span> | 22.5<small>%</small> | 0.64 | -35.1<small>%</small> | -10.2<small>%</small> |