| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [QQQY](/qqqy-vs-qyld/) | <span style="color: tomato">13.2<small>%</small></span> | 10.7<small>%</small> | 1.24 | -5.5<small>%</small> | -1.1<small>%</small> |
| QYLD | <span style="color: tomato">15.0<small>%</small></span> | 8.5<small>%</small> | 1.78 | -4.8<small>%</small> | -0.7<small>%</small> |