| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [QQQY](/qqqy-vs-qqq/) | <span style="color: tomato">299.7<small>%</small></span> | 206.9<small>%</small> | 1.45 | -6.4<small>%</small> | -1.3<small>%</small> |
| QQQ | <span style="color: tomato">26.1<small>%</small></span> | 16.6<small>%</small> | 1.57 | -9.0<small>%</small> | -1.9<small>%</small> |