| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [QQQY](/qqqy-vs-qyld/) | <span style="color: tomato">13.5<small>%</small></span> | 12.3<small>%</small> | 1.10 | -10.1<small>%</small> | -1.9<small>%</small> |
| QYLD | <span style="color: tomato">15.3<small>%</small></span> | 10.9<small>%</small> | 1.40 | -7.8<small>%</small> | -1.0<small>%</small> |