| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [QQQY](/qqqy-vs-qyld/) | <span style="color: tomato">19.0<small>%</small></span> | 10.4<small>%</small> | 1.83 | -5.5<small>%</small> | -1.2<small>%</small> |
| QYLD | <span style="color: tomato">13.7<small>%</small></span> | 8.2<small>%</small> | 1.66 | -5.0<small>%</small> | -0.9<small>%</small> |