| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [QQQY](/qqqy-vs-qqq/) | <span style="color: tomato">24.7<small>%</small></span> | 10.0<small>%</small> | 2.46 | -5.5<small>%</small> | -1.1<small>%</small> |
| QQQ | <span style="color: tomato">41.6<small>%</small></span> | 15.4<small>%</small> | 2.71 | -8.8<small>%</small> | -1.6<small>%</small> |