| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [QQQY](/qqqy-vs-qqq/) | <span style="color: tomato">22.2<small>%</small></span> | 10.2<small>%</small> | 2.18 | -5.5<small>%</small> | -1.2<small>%</small> |
| QQQ | <span style="color: tomato">37.1<small>%</small></span> | 15.5<small>%</small> | 2.39 | -8.8<small>%</small> | -1.7<small>%</small> |