| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [QRFT](/qrft-vs-spy/) | <span style="color: tomato">16.8<small>%</small></span> | 21.1<small>%</small> | 0.80 | -30.2<small>%</small> | -8.3<small>%</small> |
| SPY | <span style="color: tomato">15.3<small>%</small></span> | 20.7<small>%</small> | 0.74 | -33.7<small>%</small> | -6.1<small>%</small> |