| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [QRFT](/qrft-vs-spy/) | <span style="color: tomato">16.5<small>%</small></span> | 20.9<small>%</small> | 0.79 | -30.2<small>%</small> | -8.1<small>%</small> |
| SPY | <span style="color: tomato">15.3<small>%</small></span> | 20.5<small>%</small> | 0.75 | -33.7<small>%</small> | -6.0<small>%</small> |