| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [QRFT](/qrft-vs-spy/) | <span style="color: tomato">15.9<small>%</small></span> | 21.0<small>%</small> | 0.76 | -30.2<small>%</small> | -8.2<small>%</small> |
| SPY | <span style="color: tomato">14.5<small>%</small></span> | 20.5<small>%</small> | 0.71 | -33.7<small>%</small> | -6.0<small>%</small> |