| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [QYLD](/qyld-vs-xyld/) | <span style="color: tomato">6.9<small>%</small></span> | 14.8<small>%</small> | 0.47 | -24.8<small>%</small> | -4.2<small>%</small> |
| XYLD | <span style="color: tomato">4.6<small>%</small></span> | 14.2<small>%</small> | 0.32 | -34.7<small>%</small> | -4.9<small>%</small> |