| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [QYLD](/qyld-vs-xyld/) | <span style="color: tomato">7.4<small>%</small></span> | 14.7<small>%</small> | 0.50 | -24.8<small>%</small> | -4.1<small>%</small> |
| XYLD | <span style="color: tomato">5.1<small>%</small></span> | 14.1<small>%</small> | 0.37 | -34.7<small>%</small> | -4.8<small>%</small> |