| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [QYLD](/qyld-vs-xyld/) | <span style="color: tomato">7.2<small>%</small></span> | 14.7<small>%</small> | 0.49 | -24.8<small>%</small> | -4.2<small>%</small> |
| XYLD | <span style="color: tomato">4.8<small>%</small></span> | 14.1<small>%</small> | 0.34 | -34.7<small>%</small> | -4.9<small>%</small> |