| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [QYLD](/qyld-vs-qqq/) | <span style="color: tomato">7.1<small>%</small></span> | 14.8<small>%</small> | 0.48 | -24.8<small>%</small> | -4.3<small>%</small> |
| QQQ | <span style="color: tomato">18.3<small>%</small></span> | 21.3<small>%</small> | 0.86 | -35.1<small>%</small> | -6.1<small>%</small> |