| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [RSP](/rsp-vs-spy/) | <span style="color: tomato">9.3<small>%</small></span> | 20.1<small>%</small> | 0.46 | -60.9<small>%</small> | -7.8<small>%</small> |
| SPY | <span style="color: tomato">8.8<small>%</small></span> | 18.7<small>%</small> | 0.47 | -56.5<small>%</small> | -8.5<small>%</small> |