| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [RSP](/rsp-vs-spy/) | <span style="color: tomato">11.0<small>%</small></span> | 20.1<small>%</small> | 0.54 | -59.9<small>%</small> | -7.0<small>%</small> |
| SPY | <span style="color: tomato">10.7<small>%</small></span> | 18.6<small>%</small> | 0.57 | -55.2<small>%</small> | -7.2<small>%</small> |