| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [RYLD](/ryld-vs-iwm/) | <span style="color: tomato">3.3<small>%</small></span> | 17.9<small>%</small> | 0.18 | -41.5<small>%</small> | -9.9<small>%</small> |
| IWM | <span style="color: tomato">7.9<small>%</small></span> | 26.4<small>%</small> | 0.30 | -41.1<small>%</small> | -13.5<small>%</small> |