| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [RYLD](/ryld-vs-iwm/) | <span style="color: tomato">3.0<small>%</small></span> | 18.1<small>%</small> | 0.17 | -41.5<small>%</small> | -9.6<small>%</small> |
| IWM | <span style="color: tomato">6.9<small>%</small></span> | 26.6<small>%</small> | 0.26 | -41.1<small>%</small> | -13.6<small>%</small> |