| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SCHD](/schd-vs-divo/) | <span style="color: tomato">8.1<small>%</small></span> | 17.8<small>%</small> | 0.45 | -33.4<small>%</small> | -5.6<small>%</small> |
| DIVO | <span style="color: tomato">6.1<small>%</small></span> | 15.6<small>%</small> | 0.39 | -31.7<small>%</small> | -4.5<small>%</small> |