| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SCHD](/schd-vs-spy/) | <span style="color: tomato">12.6<small>%</small></span> | 15.6<small>%</small> | 0.81 | -33.4<small>%</small> | -3.2<small>%</small> |
| SPY | <span style="color: tomato">14.4<small>%</small></span> | 16.7<small>%</small> | 0.86 | -33.7<small>%</small> | -3.8<small>%</small> |