| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SCHD](/schd-vs-brk-b/) | <span style="color: tomato">13.4<small>%</small></span> | 15.5<small>%</small> | 0.86 | -33.4<small>%</small> | -3.2<small>%</small> |
| BRK-B | <span style="color: tomato">15.3<small>%</small></span> | 18.3<small>%</small> | 0.84 | -29.6<small>%</small> | -5.7<small>%</small> |