| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SCHD](/schd-vs-idvo/) | <span style="color: tomato">11.0<small>%</small></span> | 14.0<small>%</small> | 0.79 | -12.3<small>%</small> | -3.9<small>%</small> |
| IDVO | <span style="color: tomato">17.4<small>%</small></span> | 15.6<small>%</small> | 1.11 | -11.0<small>%</small> | -2.7<small>%</small> |