| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SCHD](/schd-vs-idvo/) | <span style="color: tomato">7.2<small>%</small></span> | 14.0<small>%</small> | 0.52 | -12.3<small>%</small> | -4.2<small>%</small> |
| IDVO | <span style="color: tomato">18.4<small>%</small></span> | 15.5<small>%</small> | 1.19 | -11.0<small>%</small> | -2.7<small>%</small> |