| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SCHD](/schd-vs-divo/) | <span style="color: tomato">12.2<small>%</small></span> | 17.6<small>%</small> | 0.70 | -33.4<small>%</small> | -4.2<small>%</small> |
| DIVO | <span style="color: tomato">11.9<small>%</small></span> | 15.4<small>%</small> | 0.77 | -30.0<small>%</small> | -2.8<small>%</small> |