| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SCHD](/schd-vs-divo/) | <span style="color: tomato">11.2<small>%</small></span> | 17.7<small>%</small> | 0.63 | -33.4<small>%</small> | -4.3<small>%</small> |
| DIVO | <span style="color: tomato">11.5<small>%</small></span> | 15.5<small>%</small> | 0.74 | -30.0<small>%</small> | -2.9<small>%</small> |