| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SCHD](/schd-vs-idvo/) | <span style="color: tomato">6.9<small>%</small></span> | 14.0<small>%</small> | 0.49 | -12.3<small>%</small> | -4.1<small>%</small> |
| IDVO | <span style="color: tomato">19.1<small>%</small></span> | 15.4<small>%</small> | 1.24 | -11.0<small>%</small> | -2.7<small>%</small> |