| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SCHG](/schg-vs-spy/) | <span style="color: tomato">15.0<small>%</small></span> | 19.5<small>%</small> | 0.77 | -35.0<small>%</small> | -5.5<small>%</small> |
| SPY | <span style="color: tomato">11.5<small>%</small></span> | 17.1<small>%</small> | 0.67 | -34.1<small>%</small> | -4.5<small>%</small> |