| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SCHG](/schg-vs-qqq/) | <span style="color: tomato">15.1<small>%</small></span> | 19.6<small>%</small> | 0.77 | -34.6<small>%</small> | -5.4<small>%</small> |
| QQQ | <span style="color: tomato">17.6<small>%</small></span> | 20.4<small>%</small> | 0.86 | -35.1<small>%</small> | -5.4<small>%</small> |