| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SCHG](/schg-vs-spy/) | <span style="color: tomato">15.6<small>%</small></span> | 19.6<small>%</small> | 0.79 | -34.6<small>%</small> | -5.4<small>%</small> |
| SPY | <span style="color: tomato">13.3<small>%</small></span> | 17.2<small>%</small> | 0.77 | -33.7<small>%</small> | -4.1<small>%</small> |