| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SCHG](/schg-vs-spy/) | <span style="color: tomato">15.9<small>%</small></span> | 19.5<small>%</small> | 0.81 | -34.6<small>%</small> | -5.4<small>%</small> |
| SPY | <span style="color: tomato">13.4<small>%</small></span> | 17.1<small>%</small> | 0.78 | -33.7<small>%</small> | -4.0<small>%</small> |