| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SDY](/sdy-vs-schd/) | <span style="color: tomato">12.0<small>%</small></span> | 16.0<small>%</small> | 0.75 | -36.7<small>%</small> | -3.3<small>%</small> |
| SCHD | <span style="color: tomato">13.3<small>%</small></span> | 15.5<small>%</small> | 0.86 | -33.4<small>%</small> | -3.2<small>%</small> |