| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SHY](/shy-vs-tlt/) | <span style="color: tomato">1.9<small>%</small></span> | 1.5<small>%</small> | 1.24 | -5.7<small>%</small> | -0.5<small>%</small> |
| TLT | <span style="color: tomato">4.2<small>%</small></span> | 14.4<small>%</small> | 0.29 | -48.4<small>%</small> | -11.8<small>%</small> |