| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SNOY](/snoy-vs-snow/) | <span style="color: cornflowerblue">-14.7<small>%</small></span> | 36.7<small>%</small> | -0.40 | -17.4<small>%</small> | -7.2<small>%</small> |
| SNOW | <span style="color: cornflowerblue">-37.0<small>%</small></span> | 46.2<small>%</small> | -0.80 | -24.1<small>%</small> | -11.5<small>%</small> |