| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SNOY](/snoy-vs-snow/) | <span style="color: tomato">4.1<small>%</small></span> | 35.1<small>%</small> | 0.12 | -17.4<small>%</small> | -7.6<small>%</small> |
| SNOW | <span style="color: cornflowerblue">-12.4<small>%</small></span> | 44.6<small>%</small> | -0.28 | -24.1<small>%</small> | -12.7<small>%</small> |