| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SNOY](/snoy-vs-snow/) | <span style="color: cornflowerblue">-19.7<small>%</small></span> | 35.8<small>%</small> | -0.55 | -17.4<small>%</small> | -7.5<small>%</small> |
| SNOW | <span style="color: cornflowerblue">-40.1<small>%</small></span> | 45.0<small>%</small> | -0.89 | -24.1<small>%</small> | -12.2<small>%</small> |