| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SPHD](/sphd-vs-splv/) | <span style="color: tomato">9.0<small>%</small></span> | 16.7<small>%</small> | 0.54 | -41.4<small>%</small> | -5.0<small>%</small> |
| SPLV | <span style="color: tomato">9.8<small>%</small></span> | 15.0<small>%</small> | 0.66 | -36.3<small>%</small> | -4.0<small>%</small> |