| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SPHD](/sphd-vs-spy/) | <span style="color: tomato">5.2<small>%</small></span> | 16.7<small>%</small> | 0.31 | -42.1<small>%</small> | -6.4<small>%</small> |
| SPY | <span style="color: tomato">12.3<small>%</small></span> | 16.8<small>%</small> | 0.73 | -34.1<small>%</small> | -4.3<small>%</small> |