| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SPHD](/sphd-vs-schd/) | <span style="color: tomato">9.2<small>%</small></span> | 16.8<small>%</small> | 0.55 | -41.4<small>%</small> | -5.0<small>%</small> |
| SCHD | <span style="color: tomato">12.8<small>%</small></span> | 15.9<small>%</small> | 0.81 | -33.4<small>%</small> | -3.4<small>%</small> |