| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SPHD](/sphd-vs-spy/) | <span style="color: tomato">8.8<small>%</small></span> | 16.7<small>%</small> | 0.52 | -41.4<small>%</small> | -5.0<small>%</small> |
| SPY | <span style="color: tomato">13.8<small>%</small></span> | 16.8<small>%</small> | 0.82 | -33.7<small>%</small> | -3.9<small>%</small> |