| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SPHD](/sphd-vs-spy/) | <span style="color: tomato">9.2<small>%</small></span> | 16.7<small>%</small> | 0.55 | -41.4<small>%</small> | -5.0<small>%</small> |
| SPY | <span style="color: tomato">14.0<small>%</small></span> | 16.8<small>%</small> | 0.83 | -33.7<small>%</small> | -3.9<small>%</small> |