| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SPHD](/sphd-vs-splv/) | <span style="color: tomato">9.1<small>%</small></span> | 16.7<small>%</small> | 0.55 | -41.4<small>%</small> | -4.9<small>%</small> |
| SPLV | <span style="color: tomato">9.9<small>%</small></span> | 14.9<small>%</small> | 0.67 | -36.3<small>%</small> | -3.9<small>%</small> |