| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SPLV](/splv-vs-spy/) | <span style="color: tomato">10.2<small>%</small></span> | 14.9<small>%</small> | 0.69 | -36.3<small>%</small> | -3.7<small>%</small> |
| SPY | <span style="color: tomato">13.1<small>%</small></span> | 17.3<small>%</small> | 0.76 | -33.7<small>%</small> | -4.1<small>%</small> |