| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SPLV](/splv-vs-spy/) | <span style="color: tomato">7.8<small>%</small></span> | 14.8<small>%</small> | 0.52 | -36.6<small>%</small> | -4.4<small>%</small> |
| SPY | <span style="color: tomato">11.3<small>%</small></span> | 17.2<small>%</small> | 0.66 | -34.1<small>%</small> | -4.5<small>%</small> |