| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SPY](/spy-vs-schd/) | <span style="color: tomato">14.5<small>%</small></span> | 16.6<small>%</small> | 0.87 | -33.7<small>%</small> | -3.8<small>%</small> |
| SCHD | <span style="color: tomato">13.1<small>%</small></span> | 15.5<small>%</small> | 0.84 | -33.4<small>%</small> | -3.2<small>%</small> |