| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SPY](/spy-vs-divo/) | <span style="color: tomato">13.8<small>%</small></span> | 18.6<small>%</small> | 0.74 | -33.7<small>%</small> | -5.1<small>%</small> |
| DIVO | <span style="color: tomato">11.4<small>%</small></span> | 15.5<small>%</small> | 0.74 | -30.0<small>%</small> | -2.9<small>%</small> |