| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SPY](/spy-vs-schd/) | <span style="color: tomato">12.5<small>%</small></span> | 16.7<small>%</small> | 0.75 | -34.1<small>%</small> | -4.2<small>%</small> |
| SCHD | <span style="color: tomato">9.5<small>%</small></span> | 15.7<small>%</small> | 0.61 | -33.4<small>%</small> | -4.2<small>%</small> |