| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SPY](/spy-vs-idvo/) | <span style="color: tomato">20.6<small>%</small></span> | 15.3<small>%</small> | 1.34 | -12.9<small>%</small> | -2.7<small>%</small> |
| IDVO | <span style="color: tomato">18.2<small>%</small></span> | 15.5<small>%</small> | 1.17 | -11.0<small>%</small> | -2.7<small>%</small> |