| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SPY](/spy-vs-divo/) | <span style="color: tomato">13.3<small>%</small></span> | 18.5<small>%</small> | 0.72 | -33.7<small>%</small> | -5.0<small>%</small> |
| DIVO | <span style="color: tomato">11.3<small>%</small></span> | 15.4<small>%</small> | 0.73 | -30.0<small>%</small> | -2.8<small>%</small> |