| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SPY](/spy-vs-idvo/) | <span style="color: tomato">17.9<small>%</small></span> | 15.5<small>%</small> | 1.15 | -12.9<small>%</small> | -2.7<small>%</small> |
| IDVO | <span style="color: tomato">16.3<small>%</small></span> | 15.8<small>%</small> | 1.04 | -11.0<small>%</small> | -2.7<small>%</small> |