| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SPY](/spy-vs-idvo/) | <span style="color: tomato">20.5<small>%</small></span> | 15.5<small>%</small> | 1.32 | -12.9<small>%</small> | -2.7<small>%</small> |
| IDVO | <span style="color: tomato">19.5<small>%</small></span> | 15.6<small>%</small> | 1.25 | -11.0<small>%</small> | -2.6<small>%</small> |