| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SPY](/spy-vs-^sp500tr/) | <span style="color: tomato">10.3<small>%</small></span> | 18.6<small>%</small> | 0.56 | -55.2<small>%</small> | -9.4<small>%</small> |
| ^SP500TR | <span style="color: tomato">10.5<small>%</small></span> | 18.4<small>%</small> | 0.57 | -55.3<small>%</small> | -9.3<small>%</small> |