| **종목** | **배율** | **1년** | **<small>변동성비용</small>** | **<small>금융비용</small>** | **<small>전체비용</small>** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| SPY | 기초 | <span style="color: tomato">7.5<small>%</small></span> | - | - | - |
| [QQQ](/qqq-vs-spy/) | 1<small>배</small> | <span style="color: tomato">9.6<small>%</small></span> | 0.0<small>%</small> | -65.4<small>%</small> | -65.4<small>%</small> |