| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SPYD](/spyd-vs-spy/) | <span style="color: tomato">8.1<small>%</small></span> | 20.8<small>%</small> | 0.39 | -46.4<small>%</small> | -6.9<small>%</small> |
| SPY | <span style="color: tomato">13.4<small>%</small></span> | 18.1<small>%</small> | 0.74 | -33.7<small>%</small> | -4.8<small>%</small> |