| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SPYD](/spyd-vs-spy/) | <span style="color: tomato">8.0<small>%</small></span> | 20.6<small>%</small> | 0.39 | -46.4<small>%</small> | -6.8<small>%</small> |
| SPY | <span style="color: tomato">14.0<small>%</small></span> | 17.9<small>%</small> | 0.78 | -33.7<small>%</small> | -4.7<small>%</small> |