| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SPYG](/spyg-vs-spy/) | <span style="color: tomato">6.4<small>%</small></span> | 21.6<small>%</small> | 0.30 | -67.6<small>%</small> | -25.8<small>%</small> |
| SPY | <span style="color: tomato">7.9<small>%</small></span> | 19.2<small>%</small> | 0.41 | -55.2<small>%</small> | -10.5<small>%</small> |