| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SPYG](/spyg-vs-schd/) | <span style="color: tomato">15.8<small>%</small></span> | 18.3<small>%</small> | 0.87 | -32.7<small>%</small> | -5.2<small>%</small> |
| SCHD | <span style="color: tomato">13.2<small>%</small></span> | 15.5<small>%</small> | 0.85 | -33.4<small>%</small> | -3.2<small>%</small> |