| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SPYG](/spyg-vs-spy/) | <span style="color: tomato">6.2<small>%</small></span> | 21.6<small>%</small> | 0.29 | -67.6<small>%</small> | -26.0<small>%</small> |
| SPY | <span style="color: tomato">7.7<small>%</small></span> | 19.3<small>%</small> | 0.40 | -55.2<small>%</small> | -10.5<small>%</small> |