| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SPYI](/spyi-vs-xyld/) | <span style="color: tomato">13.9<small>%</small></span> | 11.3<small>%</small> | 1.23 | -10.2<small>%</small> | -2.0<small>%</small> |
| XYLD | <span style="color: tomato">9.1<small>%</small></span> | 9.0<small>%</small> | 1.01 | -10.2<small>%</small> | -1.8<small>%</small> |