| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SPYI](/spyi-vs-spy/) | <span style="color: tomato">13.6<small>%</small></span> | 11.4<small>%</small> | 1.19 | -10.2<small>%</small> | -2.0<small>%</small> |
| SPY | <span style="color: tomato">20.6<small>%</small></span> | 15.3<small>%</small> | 1.35 | -12.9<small>%</small> | -2.6<small>%</small> |