| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SPYI](/spyi-vs-spy/) | <span style="color: tomato">11.8<small>%</small></span> | 11.9<small>%</small> | 0.99 | -10.2<small>%</small> | -2.2<small>%</small> |
| SPY | <span style="color: tomato">18.1<small>%</small></span> | 15.9<small>%</small> | 1.14 | -12.9<small>%</small> | -2.8<small>%</small> |