| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SPYI](/spyi-vs-spy/) | <span style="color: tomato">13.7<small>%</small></span> | 11.8<small>%</small> | 1.16 | -10.2<small>%</small> | -2.2<small>%</small> |
| SPY | <span style="color: tomato">20.7<small>%</small></span> | 16.0<small>%</small> | 1.30 | -12.9<small>%</small> | -2.8<small>%</small> |