| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SPYI](/spyi-vs-xyld/) | <span style="color: tomato">12.3<small>%</small></span> | 11.4<small>%</small> | 1.07 | -10.2<small>%</small> | -2.0<small>%</small> |
| XYLD | <span style="color: tomato">8.6<small>%</small></span> | 9.1<small>%</small> | 0.95 | -10.2<small>%</small> | -1.8<small>%</small> |