| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SPYI](/spyi-vs-xyld/) | <span style="color: tomato">12.1<small>%</small></span> | 11.9<small>%</small> | 1.02 | -10.2<small>%</small> | -2.2<small>%</small> |
| XYLD | <span style="color: tomato">9.5<small>%</small></span> | 9.5<small>%</small> | 1.00 | -10.2<small>%</small> | -2.0<small>%</small> |