| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SQY](/sqy-vs-sq/) | <span style="color: tomato">91.1<small>%</small></span> | 42.7<small>%</small> | 2.13 | -18.4<small>%</small> | -6.5<small>%</small> |
| Block Inc | <span style="color: tomato">114.4<small>%</small></span> | 54.2<small>%</small> | 2.11 | -22.0<small>%</small> | -8.1<small>%</small> |