| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SQY](/sqy-vs-sq/) | <span style="color: tomato">131.4<small>%</small></span> | 46.0<small>%</small> | 2.86 | -18.4<small>%</small> | -6.7<small>%</small> |
| Block Inc | <span style="color: tomato">275.6<small>%</small></span> | 57.1<small>%</small> | 4.83 | -21.4<small>%</small> | -7.4<small>%</small> |