| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [SQY](/sqy-vs-sq/) | <span style="color: tomato">152.8<small>%</small></span> | 43.9<small>%</small> | 3.48 | -18.4<small>%</small> | -6.1<small>%</small> |
| Block Inc | <span style="color: tomato">259.4<small>%</small></span> | 55.3<small>%</small> | 4.69 | -21.4<small>%</small> | -6.8<small>%</small> |