| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TLTW](/tltw-vs-tlt/) | <span style="color: cornflowerblue">-1.9<small>%</small></span> | 13.0<small>%</small> | -0.15 | -18.6<small>%</small> | -9.5<small>%</small> |
| TLT | <span style="color: cornflowerblue">-2.0<small>%</small></span> | 17.8<small>%</small> | -0.11 | -24.5<small>%</small> | -11.1<small>%</small> |