| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TLTW](/tltw-vs-tlt/) | <span style="color: cornflowerblue">-3.1<small>%</small></span> | 13.2<small>%</small> | -0.24 | -18.6<small>%</small> | -9.6<small>%</small> |
| TLT | <span style="color: cornflowerblue">-3.3<small>%</small></span> | 17.9<small>%</small> | -0.18 | -24.5<small>%</small> | -11.2<small>%</small> |