| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TLTW](/tltw-vs-tlt/) | <span style="color: cornflowerblue">-6.0<small>%</small></span> | 13.3<small>%</small> | -0.45 | -18.6<small>%</small> | -9.5<small>%</small> |
| TLT | <span style="color: cornflowerblue">-6.4<small>%</small></span> | 18.0<small>%</small> | -0.36 | -24.5<small>%</small> | -11.2<small>%</small> |