| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TQQQ](/tqqq-vs-qqq/) | <span style="color: tomato">40.0<small>%</small></span> | 60.4<small>%</small> | 0.66 | -81.7<small>%</small> | -19.0<small>%</small> |
| QQQ | <span style="color: tomato">18.4<small>%</small></span> | 20.4<small>%</small> | 0.90 | -35.1<small>%</small> | -5.3<small>%</small> |