| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TQQQ](/tqqq-vs-qqq/) | <span style="color: tomato">42.8<small>%</small></span> | 60.3<small>%</small> | 0.71 | -81.8<small>%</small> | -19.1<small>%</small> |
| QQQ | <span style="color: tomato">18.1<small>%</small></span> | 20.4<small>%</small> | 0.89 | -35.6<small>%</small> | -5.5<small>%</small> |