| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TSLY](/tsly-vs-tsla/) | <span style="color: cornflowerblue">-9.8<small>%</small></span> | 42.4<small>%</small> | -0.23 | -45.6<small>%</small> | -20.2<small>%</small> |
| Tesla Inc | <span style="color: cornflowerblue">-2.0<small>%</small></span> | 56.1<small>%</small> | -0.04 | -51.6<small>%</small> | -20.6<small>%</small> |