| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TSLY](/tsly-vs-tsla/) | <span style="color: cornflowerblue">-3.1<small>%</small></span> | 42.8<small>%</small> | -0.07 | -45.6<small>%</small> | -21.4<small>%</small> |
| TSLA | <span style="color: tomato">8.1<small>%</small></span> | 56.7<small>%</small> | 0.14 | -51.6<small>%</small> | -22.0<small>%</small> |