| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [TSLY](/tsly-vs-tsla/) | <span style="color: cornflowerblue">-11.5<small>%</small></span> | 41.7<small>%</small> | -0.28 | -40.5<small>%</small> | -19.0<small>%</small> |
| Tesla Inc | <span style="color: cornflowerblue">-3.3<small>%</small></span> | 54.6<small>%</small> | -0.06 | -44.6<small>%</small> | -19.0<small>%</small> |