| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [USMV](/usmv-vs-vti/) | <span style="color: tomato">11.8<small>%</small></span> | 13.8<small>%</small> | 0.86 | -33.1<small>%</small> | -3.1<small>%</small> |
| VTI | <span style="color: tomato">13.8<small>%</small></span> | 17.2<small>%</small> | 0.80 | -35.0<small>%</small> | -4.3<small>%</small> |