| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [VIG](/vig-vs-schd/) | <span style="color: tomato">12.6<small>%</small></span> | 15.3<small>%</small> | 0.82 | -31.7<small>%</small> | -3.3<small>%</small> |
| SCHD | <span style="color: tomato">12.9<small>%</small></span> | 15.7<small>%</small> | 0.83 | -33.4<small>%</small> | -3.3<small>%</small> |