| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [VIG](/vig-vs-brk-b/) | <span style="color: tomato">10.0<small>%</small></span> | 17.7<small>%</small> | 0.56 | -43.8<small>%</small> | -5.4<small>%</small> |
| BRK-B | <span style="color: tomato">9.8<small>%</small></span> | 22.4<small>%</small> | 0.44 | -52.0<small>%</small> | -10.4<small>%</small> |