| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [VIG](/vig-vs-spy/) | <span style="color: tomato">9.9<small>%</small></span> | 17.7<small>%</small> | 0.56 | -43.8<small>%</small> | -5.4<small>%</small> |
| SPY | <span style="color: tomato">10.5<small>%</small></span> | 20.0<small>%</small> | 0.52 | -51.9<small>%</small> | -7.2<small>%</small> |