| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [VIG](/vig-vs-spy/) | <span style="color: tomato">7.5<small>%</small></span> | 17.3<small>%</small> | 0.43 | -48.2<small>%</small> | -7.0<small>%</small> |
| SPY | <span style="color: tomato">8.1<small>%</small></span> | 19.6<small>%</small> | 0.42 | -56.5<small>%</small> | -9.6<small>%</small> |