| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [VIG](/vig-vs-brk-b/) | <span style="color: tomato">9.6<small>%</small></span> | 17.3<small>%</small> | 0.56 | -46.8<small>%</small> | -5.9<small>%</small> |
| BRK-B | <span style="color: tomato">11.5<small>%</small></span> | 21.7<small>%</small> | 0.53 | -53.9<small>%</small> | -10.5<small>%</small> |