| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [VIG](/vig-vs-spy/) | <span style="color: tomato">9.7<small>%</small></span> | 17.4<small>%</small> | 0.56 | -46.8<small>%</small> | -6.0<small>%</small> |
| SPY | <span style="color: tomato">10.1<small>%</small></span> | 19.7<small>%</small> | 0.51 | -55.2<small>%</small> | -8.1<small>%</small> |