| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [VIG](/vig-vs-brk-b/) | <span style="color: tomato">9.8<small>%</small></span> | 17.2<small>%</small> | 0.57 | -46.8<small>%</small> | -5.9<small>%</small> |
| BRK-B | <span style="color: tomato">12.0<small>%</small></span> | 21.7<small>%</small> | 0.56 | -53.9<small>%</small> | -10.5<small>%</small> |