| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [VIG](/vig-vs-schd/) | <span style="color: tomato">10.5<small>%</small></span> | 15.2<small>%</small> | 0.69 | -31.7<small>%</small> | -3.8<small>%</small> |
| SCHD | <span style="color: tomato">9.5<small>%</small></span> | 15.7<small>%</small> | 0.61 | -33.4<small>%</small> | -4.2<small>%</small> |