| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [VOO](/voo-vs-spy/) | <span style="color: tomato">14.3<small>%</small></span> | 17.1<small>%</small> | 0.84 | -34.0<small>%</small> | -3.9<small>%</small> |
| SPY | <span style="color: tomato">14.2<small>%</small></span> | 16.9<small>%</small> | 0.84 | -33.7<small>%</small> | -3.9<small>%</small> |