| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [VOO](/voo-vs-^sp500tr/) | <span style="color: tomato">14.3<small>%</small></span> | 17.0<small>%</small> | 0.84 | -34.0<small>%</small> | -3.9<small>%</small> |
| ^SP500TR | <span style="color: tomato">14.4<small>%</small></span> | 17.1<small>%</small> | 0.84 | -33.8<small>%</small> | -3.9<small>%</small> |