| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [VT](/vt-vs-vti/) | <span style="color: tomato">7.6<small>%</small></span> | 21.0<small>%</small> | 0.36 | -50.3<small>%</small> | -7.6<small>%</small> |
| VTI | <span style="color: tomato">11.4<small>%</small></span> | 20.2<small>%</small> | 0.57 | -48.0<small>%</small> | -6.3<small>%</small> |