| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [VT](/vt-vs-vti/) | <span style="color: tomato">7.5<small>%</small></span> | 21.1<small>%</small> | 0.36 | -50.2<small>%</small> | -7.7<small>%</small> |
| VTI | <span style="color: tomato">11.3<small>%</small></span> | 20.4<small>%</small> | 0.56 | -48.0<small>%</small> | -6.4<small>%</small> |