| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [VTI](/vti-vs-spy/) | <span style="color: tomato">8.8<small>%</small></span> | 19.2<small>%</small> | 0.46 | -55.5<small>%</small> | -8.2<small>%</small> |
| SPY | <span style="color: tomato">8.4<small>%</small></span> | 19.1<small>%</small> | 0.44 | -55.2<small>%</small> | -8.5<small>%</small> |