| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [VTV](/vtv-vs-brk-b/) | <span style="color: tomato">8.7<small>%</small></span> | 18.9<small>%</small> | 0.46 | -59.3<small>%</small> | -8.4<small>%</small> |
| BRK-B | <span style="color: tomato">9.9<small>%</small></span> | 21.0<small>%</small> | 0.47 | -53.9<small>%</small> | -10.3<small>%</small> |