| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [VTV](/vtv-vs-brk-b/) | <span style="color: tomato">9.0<small>%</small></span> | 18.9<small>%</small> | 0.48 | -59.3<small>%</small> | -8.4<small>%</small> |
| BRK-B | <span style="color: tomato">10.2<small>%</small></span> | 21.0<small>%</small> | 0.49 | -53.9<small>%</small> | -10.4<small>%</small> |