| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [VTV](/vtv-vs-spy/) | <span style="color: tomato">9.0<small>%</small></span> | 18.9<small>%</small> | 0.48 | -59.3<small>%</small> | -8.4<small>%</small> |
| SPY | <span style="color: tomato">10.0<small>%</small></span> | 18.8<small>%</small> | 0.53 | -55.2<small>%</small> | -7.3<small>%</small> |