| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [VUG](/vug-vs-brk-b/) | <span style="color: tomato">11.1<small>%</small></span> | 19.8<small>%</small> | 0.56 | -50.7<small>%</small> | -7.4<small>%</small> |
| BRK-B | <span style="color: tomato">9.9<small>%</small></span> | 21.0<small>%</small> | 0.47 | -53.9<small>%</small> | -10.3<small>%</small> |