| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [VUG](/vug-vs-spy/) | <span style="color: tomato">11.1<small>%</small></span> | 19.8<small>%</small> | 0.56 | -50.7<small>%</small> | -7.4<small>%</small> |
| SPY | <span style="color: tomato">9.8<small>%</small></span> | 18.8<small>%</small> | 0.52 | -55.2<small>%</small> | -7.3<small>%</small> |