| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [VYM](/vym-vs-schd/) | <span style="color: tomato">12.1<small>%</small></span> | 15.4<small>%</small> | 0.79 | -35.2<small>%</small> | -3.1<small>%</small> |
| SCHD | <span style="color: tomato">13.2<small>%</small></span> | 15.5<small>%</small> | 0.85 | -33.4<small>%</small> | -3.2<small>%</small> |