| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [VYM](/vym-vs-schd/) | <span style="color: tomato">12.4<small>%</small></span> | 15.3<small>%</small> | 0.81 | -35.2<small>%</small> | -3.1<small>%</small> |
| SCHD | <span style="color: tomato">20.8<small>%</small></span> | 15.7<small>%</small> | 1.32 | -33.4<small>%</small> | -2.4<small>%</small> |