| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [XDTE](/xdte-vs-spy/) | <span style="color: tomato">18.3<small>%</small></span> | 10.1<small>%</small> | 1.82 | -5.0<small>%</small> | -1.1<small>%</small> |
| SPY | <span style="color: tomato">20.3<small>%</small></span> | 11.1<small>%</small> | 1.83 | -5.4<small>%</small> | -1.2<small>%</small> |