| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [XDTE](/xdte-vs-ispy/) | <span style="color: tomato">26.2<small>%</small></span> | 12.1<small>%</small> | 2.16 | -6.9<small>%</small> | -1.2<small>%</small> |
| ISPY | <span style="color: tomato">24.3<small>%</small></span> | 11.9<small>%</small> | 2.05 | -7.9<small>%</small> | -1.3<small>%</small> |