| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [XDTE](/xdte-vs-spy/) | <span style="color: tomato">25.9<small>%</small></span> | 12.3<small>%</small> | 2.11 | -6.9<small>%</small> | -1.2<small>%</small> |
| SPY | <span style="color: tomato">22.3<small>%</small></span> | 13.0<small>%</small> | 1.72 | -8.4<small>%</small> | -1.5<small>%</small> |