| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [XDTE](/xdte-vs-ispy/) | <span style="color: tomato">25.9<small>%</small></span> | 11.8<small>%</small> | 2.19 | -6.9<small>%</small> | -1.1<small>%</small> |
| ISPY | <span style="color: tomato">25.0<small>%</small></span> | 11.7<small>%</small> | 2.14 | -7.9<small>%</small> | -1.3<small>%</small> |