| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [XDTE](/xdte-vs-spy/) | <span style="color: tomato">5.3<small>%</small></span> | 11.5<small>%</small> | 0.46 | -6.9<small>%</small> | -1.3<small>%</small> |
| SPY | <span style="color: tomato">3.3<small>%</small></span> | 12.4<small>%</small> | 0.27 | -8.4<small>%</small> | -1.5<small>%</small> |