| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [XDTE](/xdte-vs-ispy/) | <span style="color: tomato">26.1<small>%</small></span> | 12.0<small>%</small> | 2.17 | -6.9<small>%</small> | -1.1<small>%</small> |
| ISPY | <span style="color: tomato">25.0<small>%</small></span> | 11.8<small>%</small> | 2.11 | -7.9<small>%</small> | -1.3<small>%</small> |