| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [XLK](/xlk-vs-spy/) | <span style="color: tomato">8.7<small>%</small></span> | 25.8<small>%</small> | 0.34 | -82.0<small>%</small> | -37.6<small>%</small> |
| SPY | <span style="color: tomato">7.7<small>%</small></span> | 19.4<small>%</small> | 0.40 | -55.2<small>%</small> | -11.2<small>%</small> |