| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [XLK](/xlk-vs-qqq/) | <span style="color: tomato">8.8<small>%</small></span> | 25.8<small>%</small> | 0.34 | -82.0<small>%</small> | -37.3<small>%</small> |
| QQQ | <span style="color: tomato">9.9<small>%</small></span> | 27.1<small>%</small> | 0.37 | -83.0<small>%</small> | -34.7<small>%</small> |