| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [XLK](/xlk-vs-qqq/) | <span style="color: tomato">8.4<small>%</small></span> | 25.8<small>%</small> | 0.33 | -82.0<small>%</small> | -38.1<small>%</small> |
| QQQ | <span style="color: tomato">9.6<small>%</small></span> | 27.3<small>%</small> | 0.35 | -83.0<small>%</small> | -35.4<small>%</small> |