| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [XLK](/xlk-vs-spy/) | <span style="color: tomato">15.3<small>%</small></span> | 23.1<small>%</small> | 0.66 | -49.2<small>%</small> | -7.5<small>%</small> |
| SPY | <span style="color: tomato">10.3<small>%</small></span> | 20.2<small>%</small> | 0.51 | -51.9<small>%</small> | -7.3<small>%</small> |