| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [XLK](/xlk-vs-spy/) | <span style="color: tomato">9.4<small>%</small></span> | 25.8<small>%</small> | 0.36 | -82.0<small>%</small> | -37.3<small>%</small> |
| SPY | <span style="color: tomato">8.1<small>%</small></span> | 19.3<small>%</small> | 0.42 | -55.2<small>%</small> | -11.1<small>%</small> |