| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [XLK](/xlk-vs-qqq/) | <span style="color: tomato">7.5<small>%</small></span> | 25.7<small>%</small> | 0.29 | -82.0<small>%</small> | -40.6<small>%</small> |
| QQQ | <span style="color: tomato">9.2<small>%</small></span> | 27.2<small>%</small> | 0.34 | -83.0<small>%</small> | -36.1<small>%</small> |