| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [XMLV](/xmlv-vs-ijh/) | <span style="color: tomato">9.1<small>%</small></span> | 16.4<small>%</small> | 0.56 | -39.9<small>%</small> | -4.6<small>%</small> |
| IJH | <span style="color: tomato">10.3<small>%</small></span> | 19.9<small>%</small> | 0.52 | -42.2<small>%</small> | -5.5<small>%</small> |