| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [XMLV](/xmlv-vs-ijh/) | <span style="color: tomato">9.5<small>%</small></span> | 16.2<small>%</small> | 0.58 | -39.9<small>%</small> | -4.5<small>%</small> |
| IJH | <span style="color: tomato">10.9<small>%</small></span> | 19.7<small>%</small> | 0.55 | -42.2<small>%</small> | -5.4<small>%</small> |