| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [XOMO](/xomo-vs-xom/) | <span style="color: cornflowerblue">-0.0<small>%</small></span> | 15.3<small>%</small> | -0.00 | -13.5<small>%</small> | -6.6<small>%</small> |
| Exxon Mobil Corp | <span style="color: tomato">8.4<small>%</small></span> | 20.2<small>%</small> | 0.41 | -18.7<small>%</small> | -9.0<small>%</small> |