| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [XOMO](/xomo-vs-xom/) | <span style="color: tomato">1.7<small>%</small></span> | 14.9<small>%</small> | 0.11 | -13.5<small>%</small> | -6.2<small>%</small> |
| XOM | <span style="color: tomato">10.4<small>%</small></span> | 20.2<small>%</small> | 0.52 | -18.7<small>%</small> | -8.1<small>%</small> |