| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [XOMO](/xomo-vs-xom/) | <span style="color: cornflowerblue">-6.7<small>%</small></span> | 15.1<small>%</small> | -0.45 | -13.5<small>%</small> | -6.6<small>%</small> |
| Exxon Mobil Corp | <span style="color: tomato">0.2<small>%</small></span> | 20.2<small>%</small> | 0.01 | -18.7<small>%</small> | -8.6<small>%</small> |