| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [XSLV](/xslv-vs-ijr/) | <span style="color: tomato">8.0<small>%</small></span> | 18.8<small>%</small> | 0.43 | -44.3<small>%</small> | -7.5<small>%</small> |
| IJR | <span style="color: tomato">10.8<small>%</small></span> | 21.3<small>%</small> | 0.51 | -44.4<small>%</small> | -7.9<small>%</small> |