| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [XSLV](/xslv-vs-ijr/) | <span style="color: tomato">4.9<small>%</small></span> | 18.9<small>%</small> | 0.26 | -45.3<small>%</small> | -8.7<small>%</small> |
| IJR | <span style="color: tomato">8.4<small>%</small></span> | 21.3<small>%</small> | 0.40 | -45.6<small>%</small> | -8.8<small>%</small> |