| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [XYLD](/xyld-vs-spy/) | <span style="color: tomato">5.6<small>%</small></span> | 14.1<small>%</small> | 0.40 | -34.7<small>%</small> | -4.8<small>%</small> |
| SPY | <span style="color: tomato">13.7<small>%</small></span> | 17.1<small>%</small> | 0.81 | -33.7<small>%</small> | -4.1<small>%</small> |