| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [XYLD](/xyld-vs-spy/) | <span style="color: tomato">5.3<small>%</small></span> | 14.1<small>%</small> | 0.38 | -34.7<small>%</small> | -4.8<small>%</small> |
| SPY | <span style="color: tomato">13.4<small>%</small></span> | 17.1<small>%</small> | 0.79 | -33.7<small>%</small> | -4.2<small>%</small> |