| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [XYLD](/xyld-vs-spy/) | <span style="color: tomato">5.2<small>%</small></span> | 13.9<small>%</small> | 0.37 | -34.7<small>%</small> | -4.7<small>%</small> |
| SPY | <span style="color: tomato">13.3<small>%</small></span> | 16.9<small>%</small> | 0.79 | -33.7<small>%</small> | -4.0<small>%</small> |