| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [YMAG](/ymag-vs-jepq/) | <span style="color: tomato">34.2<small>%</small></span> | 19.0<small>%</small> | 1.80 | -14.3<small>%</small> | -3.3<small>%</small> |
| JEPQ | <span style="color: tomato">20.3<small>%</small></span> | 13.2<small>%</small> | 1.54 | -10.7<small>%</small> | -1.7<small>%</small> |