| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [YMAG](/ymag-vs-qqq/) | <span style="color: tomato">30.6<small>%</small></span> | 18.9<small>%</small> | 1.62 | -14.3<small>%</small> | -3.3<small>%</small> |
| QQQ | <span style="color: tomato">21.5<small>%</small></span> | 18.2<small>%</small> | 1.18 | -13.6<small>%</small> | -2.9<small>%</small> |