| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [YMAG](/ymag-vs-mags/) | <span style="color: tomato">35.8<small>%</small></span> | 19.0<small>%</small> | 1.88 | -14.3<small>%</small> | -3.3<small>%</small> |
| MAGS | <span style="color: tomato">56.5<small>%</small></span> | 26.2<small>%</small> | 2.15 | -18.1<small>%</small> | -4.4<small>%</small> |