| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [YMAG](/ymag-vs-jepq/) | <span style="color: tomato">31.6<small>%</small></span> | 20.0<small>%</small> | 1.58 | -14.3<small>%</small> | -2.3<small>%</small> |
| JEPQ | <span style="color: tomato">12.7<small>%</small></span> | 13.9<small>%</small> | 0.92 | -10.7<small>%</small> | -1.5<small>%</small> |