| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [YMAG](/ymag-vs-mags/) | <span style="color: tomato">39.4<small>%</small></span> | 18.7<small>%</small> | 2.10 | -8.3<small>%</small> | -1.2<small>%</small> |
| MAGS | <span style="color: tomato">80.7<small>%</small></span> | 24.4<small>%</small> | 3.30 | -9.4<small>%</small> | -1.5<small>%</small> |