| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [YMAG](/ymag-vs-qqq/) | <span style="color: tomato">21.1<small>%</small></span> | 20.1<small>%</small> | 1.05 | -14.3<small>%</small> | -2.9<small>%</small> |
| QQQ | <span style="color: tomato">9.8<small>%</small></span> | 18.9<small>%</small> | 0.52 | -13.6<small>%</small> | -2.7<small>%</small> |