| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [YMAG](/ymag-vs-jepq/) | <span style="color: tomato">30.6<small>%</small></span> | 18.9<small>%</small> | 1.62 | -14.3<small>%</small> | -3.3<small>%</small> |
| JEPQ | <span style="color: tomato">19.4<small>%</small></span> | 13.2<small>%</small> | 1.47 | -10.7<small>%</small> | -1.7<small>%</small> |