| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [YMAG](/ymag-vs-jepi/) | <span style="color: tomato">54.1<small>%</small></span> | 18.1<small>%</small> | 2.98 | -7.5<small>%</small> | -1.5<small>%</small> |
| JEPI | <span style="color: tomato">16.1<small>%</small></span> | 6.6<small>%</small> | 2.42 | -3.6<small>%</small> | -0.8<small>%</small> |