| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [YMAG](/ymag-vs-mags/) | <span style="color: tomato">34.2<small>%</small></span> | 19.0<small>%</small> | 1.80 | -14.3<small>%</small> | -3.3<small>%</small> |
| MAGS | <span style="color: tomato">54.2<small>%</small></span> | 26.3<small>%</small> | 2.06 | -18.1<small>%</small> | -4.4<small>%</small> |