| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [YMAG](/ymag-vs-qqq/) | <span style="color: tomato">33.1<small>%</small></span> | 19.6<small>%</small> | 1.69 | -14.3<small>%</small> | -2.7<small>%</small> |
| QQQ | <span style="color: tomato">22.0<small>%</small></span> | 18.4<small>%</small> | 1.20 | -13.6<small>%</small> | -2.6<small>%</small> |