| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [YMAG](/ymag-vs-jepi/) | <span style="color: tomato">39.4<small>%</small></span> | 18.7<small>%</small> | 2.10 | -8.3<small>%</small> | -1.2<small>%</small> |
| JEPI | <span style="color: tomato">12.2<small>%</small></span> | 6.2<small>%</small> | 1.97 | -3.6<small>%</small> | -0.8<small>%</small> |