| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [YMAG](/ymag-vs-jepi/) | <span style="color: tomato">21.1<small>%</small></span> | 20.1<small>%</small> | 1.05 | -14.3<small>%</small> | -2.9<small>%</small> |
| JEPI | <span style="color: tomato">12.1<small>%</small></span> | 7.8<small>%</small> | 1.54 | -3.9<small>%</small> | -0.8<small>%</small> |