| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [YMAX](/ymax-vs-jepi/) | <span style="color: tomato">18.8<small>%</small></span> | 18.2<small>%</small> | 1.04 | -12.8<small>%</small> | -2.3<small>%</small> |
| JEPI | <span style="color: tomato">19.1<small>%</small></span> | 7.7<small>%</small> | 2.48 | -3.9<small>%</small> | -0.7<small>%</small> |