| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [YMAX](/ymax-vs-qqq/) | <span style="color: tomato">22.7<small>%</small></span> | 16.2<small>%</small> | 1.40 | -7.8<small>%</small> | -1.4<small>%</small> |
| QQQ | <span style="color: tomato">26.2<small>%</small></span> | 16.5<small>%</small> | 1.59 | -8.9<small>%</small> | -1.4<small>%</small> |