| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [YMAX](/ymax-vs-qqq/) | <span style="color: tomato">22.9<small>%</small></span> | 18.0<small>%</small> | 1.27 | -12.8<small>%</small> | -2.8<small>%</small> |
| QQQ | <span style="color: tomato">31.7<small>%</small></span> | 18.2<small>%</small> | 1.74 | -13.6<small>%</small> | -2.8<small>%</small> |