| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [YMAX](/ymax-vs-jepq/) | <span style="color: tomato">20.0<small>%</small></span> | 18.2<small>%</small> | 1.10 | -12.8<small>%</small> | -2.8<small>%</small> |
| JEPQ | <span style="color: tomato">22.4<small>%</small></span> | 13.3<small>%</small> | 1.68 | -10.7<small>%</small> | -1.7<small>%</small> |