| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [YMAX](/ymax-vs-jepi/) | <span style="color: tomato">22.4<small>%</small></span> | 18.1<small>%</small> | 1.24 | -12.8<small>%</small> | -2.8<small>%</small> |
| JEPI | <span style="color: tomato">19.7<small>%</small></span> | 7.5<small>%</small> | 2.64 | -3.9<small>%</small> | -0.7<small>%</small> |