| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [YMAX](/ymax-vs-jepq/) | <span style="color: tomato">20.6<small>%</small></span> | 18.2<small>%</small> | 1.13 | -12.8<small>%</small> | -2.8<small>%</small> |
| JEPQ | <span style="color: tomato">23.6<small>%</small></span> | 13.3<small>%</small> | 1.77 | -10.7<small>%</small> | -1.7<small>%</small> |