| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [YMAX](/ymax-vs-jepi/) | <span style="color: tomato">10.4<small>%</small></span> | 18.0<small>%</small> | 0.58 | -12.8<small>%</small> | -1.7<small>%</small> |
| JEPI | <span style="color: tomato">9.5<small>%</small></span> | 7.6<small>%</small> | 1.25 | -3.9<small>%</small> | -0.8<small>%</small> |