| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [YMAX](/ymax-vs-qqq/) | <span style="color: tomato">25.8<small>%</small></span> | 16.3<small>%</small> | 1.58 | -7.8<small>%</small> | -1.4<small>%</small> |
| QQQ | <span style="color: tomato">28.5<small>%</small></span> | 16.5<small>%</small> | 1.73 | -8.9<small>%</small> | -1.5<small>%</small> |