| **종목** | **CAGR** | **편차** | **샤프** | **MDD** | **AvDD** |
| :------- | -------: | ------: | --------------: | ------------: | ------------: |
| [YMAX](/ymax-vs-jepq/) | <span style="color: tomato">35.3<small>%</small></span> | 15.6<small>%</small> | 2.27 | -7.8<small>%</small> | -1.3<small>%</small> |
| JEPQ | <span style="color: tomato">29.7<small>%</small></span> | 10.5<small>%</small> | 2.83 | -6.0<small>%</small> | -0.7<small>%</small> |