<br>
## 국내 지수

<br>
### KOSPI 200 지수<a id="069500"></a>

{% include lev/069500_md.inc %}

### KOSDAQ 150 지수<a id="229200"></a>

{% include lev/229200_md.inc %}

### 달러 환율<a id="261240"></a>

{% include lev/261240_md.inc %}

<br>
## 미국 지수

<br>
### 다우 존스 산업평균 지수<a id="DIA"></a>

{% include lev/dia_md.inc %}

### S&P 500 지수<a id="SPY"></a>

{% include lev/spy_md.inc %}


{% include /commons/ads/adsense.html %}

### 나스닥 100 지수<a id="QQQ"></a>

{% include lev/qqq_md.inc %}

### 러셀 2000 지수<a id="IWM"></a>

{% include lev/iwm_md.inc %}

### 미국 20+년 장기채<a id="TLT"></a>

{% include lev/tlt_md.inc %}

<br>
## 미국 섹터 지수

<br>
### 필라델피아 반도체 지수<a id="SOXQ"></a>

{% include lev/soxq_md.inc %}

### 기술 섹터 지수<a id="XLK"></a>

{% include lev/xlk_md.inc %}


{% include /commons/ads/adsense.html %}

### S&P 바이오기술 지수<a id="XBI"></a>

{% include lev/xbi_md.inc %}

<br>
## 해외 지수

<br>
### MSCI Japan 지수<a id="EWJ"></a>

{% include lev/ewj_md.inc %}

### FTSE China A50 지수<a id="FXI"></a>

{% include lev/fxi_md.inc %}

### MSCI India 지수<a id="INDA"></a>

{% include lev/inda_md.inc %}

### CSI 중국 인터넷 지수<a id="KWEB"></a>

{% include lev/kweb_md.inc %}


{% include /commons/ads/adsense.html %}

<br>
## 해외 개별 종목

<br>
### 테슬라<a id="TSLA"></a>

{% include lev/tsla_md.inc %}

### 엔비디아<a id="NVDA"></a>

{% include lev/nvda_md.inc %}